### ISSUE TITLE
[Annotations] Hide score for annotated labels in text classification

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1039]
Annotated labels should hide info about prediction score (%). Some cases could be confusing to the annotators.

**Comment by frascuchon** [comment]
what about this issue ?

cc @dvsrepo @Amelie-V @leiyre @dcfidalgo

**Comment by dcfidalgo** [comment]
I remember we had a discussion about this when the score changed to 100% when selecting the label. Now it always stays the same reflecting the prediction score, which to me seems ok.

**Comment by dvsrepo** [comment]
Yes, let's close this I think
