### ISSUE TITLE
[Text Class] Optimize Long records view *Prioritary*

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1054]
- [x] Show labels buttons area above the fold.
- [x] Create Action to open/close on click the full record in the same view
- [x] Copy "Show full record" "Show less"

- [ ] I would grap the opportunity to update the "View more" "view less" on Metrics modal to "Show more" "Show less" and apply the same style there

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-01-28 a las 11 44 23](https://user-images.githubusercontent.com/84135211/151533465-ee75ce03-45c7-49f1-ba6f-40951f55ba23.png)
![Captura de pantalla 2022-01-28 a las 11 44 04](https://user-images.githubusercontent.com/84135211/151533481-fe4dc586-6a57-4eba-94fb-b83144c08ee1.png)

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-01-28 a las 11 46 35](https://user-images.githubusercontent.com/84135211/151533765-98f2ec74-dcb0-4ba4-ae69-603654081b06.png)
![Captura de pantalla 2022-01-28 a las 11 45 56](https://user-images.githubusercontent.com/84135211/151533794-1e050bb7-1475-4004-a120-0e8aab65f865.png)

**Comment by Amelie-V** [comment]
@dvsrepo  feedback on the copy pliz

**Comment by Amelie-V** [comment]
@leiyre We should see the entire card between header and footer. 
Leave 10 px space more on card top and bottom

**Comment by Amelie-V** [comment]
@leiyre @frascuchon It has been applied en XL screen and it's nice. I would recommend do the same on laptop 1440x900

**Comment by leiyre** [comment]
@Amelie-V some screenshots with the new changes

laptop
![Captura de pantalla 2022-02-04 a las 11 48 17](https://user-images.githubusercontent.com/20307370/152516293-f730ca12-c6b6-4ce9-806c-4395baddf30c.png)

1920 x 1080

![Captura de pantalla 2022-02-04 a las 11 56 58](https://user-images.githubusercontent.com/20307370/152517386-53e1632c-ba38-4dbc-b8f4-0c8048c01f44.png)

@Amelie-V could you confirm that are ok?

**Comment by Amelie-V** [comment]
I confirm it's ok.

Add:
- [x] Text class + Text2text : Align on top : checkbox + records + state button + menu ...

**Comment by Amelie-V** [comment]
- [x] Error limit Model (view screenshot) in /release Annotation /single label: while i'm pushing on an label to annotate it appears the error toasr
- [x] Lower the button "show full records" /More height to the record extract
- [x] Maintain same left padding on explore and annotation mode. (dont maintain checkbox column space on explore)

**Comment by Amelie-V** [comment]
<img width="645" alt="Captura de pantalla 2022-02-08 a las 12 05 35" src="https://user-images.githubusercontent.com/84135211/152979304-ce776c7d-d439-48f4-914d-294f084c000f.png">

**Comment by Amelie-V** [comment]
I've just uncheked the fourth task because style seems not updated. (SS)

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-02-10 a las 15 13 31](https://user-images.githubusercontent.com/84135211/153425266-5d891066-5c36-407b-9454-2efd8cead83b.png)

**Comment by Amelie-V** [comment]
@leiyre @frascuchon As this component exists only in NER I dont have pb to move it for the next release with NER stuff
