### ISSUE TITLE
[Unify records results ] Style

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1061]
- [x] Unify style of :  records (xxx) : Use as ref. style of Records in Rules mode
- [x] Unify style of :  records (xxx) : Show it on top of records list in Explore and Annotation Mode
- [x] Explore and Annotation mode : Align records on left size (under checkbox)

See also #970

**Comment by Amelie-V** [comment]
<img width="1325" alt="Captura de pantalla 2022-01-31 a las 12 05 36" src="https://user-images.githubusercontent.com/84135211/151783203-13d587f4-7b56-448a-82e5-d0bc0095409e.png">

**Comment by frascuchon** [comment]
About "Records..." copy. It will be adapted regarding the filters (not the query search) ONLY for "Define Rules" mode. For Annotate and Explore modes will be remains the same.
