### ISSUE TITLE
[NER Fine tuning] content selection

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1063]
### Multi word

Actual state : (VIEW SS)
1- I select various words, highlight is grey and in a solid block (Highlight/words).
2- When selection is done, highlight selection is splited and label selector appears.

- [x] Should be:

1- I select various words, highlight is grey and splited (highlight/word)
2- When selection is done, highlight selection is a solid block label selector appears.

### Delete labelling

- [x] Make clicable the whole tooltip to delete

### Selection on a searched word

- [x] Selection highlight should not be cut (SS)
- [x] When selection is containing a search word the label selector does not appear (how it works only on right>left sense)
- [x] In general : change appearance of results : in place of Orange highlight show text in *bold*

### Cursor 

- [x] Active "hand" cursor (pointer) on piece of text already annotated/Predicted
- [x] Active "Text Select" cursor on the rest of record
- [x] Enlarge the hover state to the whole area : (record + annotated tooltip + empty space between them) (record + predicted tooltip + empty space between us)

### New Select label modal

- [x] Integrate new UI modal
- [x] In case of unique label, dont show modal, and just affect label after selecting text
- [x] Add logic to show first and preselected the last label used
- [x] Add following Keyboard shortcut: Enter to valid preselected label, and vertical arrow keyboard or Number to valid other labels

**Comment by Amelie-V** [comment]
<img width="245" alt="Captura de pantalla 2022-01-31 a las 14 32 38" src="https://user-images.githubusercontent.com/84135211/151805800-3e633888-8026-4bb8-8b21-c781063e7adb.png">
<img width="270" alt="Captura de pantalla 2022-01-31 a las 14 32 20" src="https://user-images.githubusercontent.com/84135211/151805804-d79c5abe-2771-4a2b-ab16-29f582c862d6.png">

**Comment by Amelie-V** [comment]
<img width="177" alt="Captura de pantalla 2022-01-31 a las 14 52 30" src="https://user-images.githubusercontent.com/84135211/151806854-09f8a229-c03c-4f9c-bdc1-775107c5006f.png">

**Comment by frascuchon** [comment]
Regarding interactions in app, I think it would be nice a way to easily validate a single annotation (entity label in record)

<img width="189" alt="Screenshot 2022-02-07 at 16 58 15" src="https://user-images.githubusercontent.com/2518789/152824049-e36d0b2e-606f-4229-ae03-11afdedae1ad.png">

<img width="243" alt="Screenshot 2022-02-07 at 16 58 35" src="https://user-images.githubusercontent.com/2518789/152824103-678f4fb0-1152-411d-b062-8df32dfbb72a.png">

The example below shows a predicted PERSON, where we must navigate over all entities finding predicted one. Even more, by clicking the tooltip, we loose the single annotation, that is a bit confusing. 

What do you think @Amelie-V ?

**Comment by Amelie-V** [comment]
QA 1

General
- [x] "Last label selected" shortcut is always [space]
- [x] [Enter] is the hover state when user is scrolling
- [x] "First label in alphabetic order is [1]
- [ ] Continue to number label 9, 10, 11, 12 etc.
- [ ] I would recommend to mark numbers label in the legend on top 
- [x] Improve hover (see video)
- [x] Extend selector width 
- [x] Extend padding around label buttons
- [x] Write shortcut [space];[1]  in regular weight (not thin)
- [ ] Center sector on highlighted selection

About Predicted text
- [x] On click on text with prediction text should be highlighted in grey 

Proposal to speed up annotation on predicted text:

- Activate selector at the same time, and show as dropdown first option the predicted label. Ej: Jerry is predicted as NAME, show NAME as first option.

- Use the "pred. tooltip" to add a validation action. (UI required)

**Comment by Amelie-V** [comment]
Uploading NER_hover.mov…

**Comment by frascuchon** [comment]
- Once last label is selected to be presented as the first one, sholdn't be duplicated. 

<img width="291" alt="Screenshot 2022-02-08 at 15 52 15" src="https://user-images.githubusercontent.com/2518789/153011975-0af745da-7246-4aa5-b216-85109e24f81f.png">
<img width="226" alt="Screenshot 2022-02-08 at 15 53 22" src="https://user-images.githubusercontent.com/2518789/153012201-c8b7d4ef-6843-4464-b4b9-84610337da83.png">

- Introduced highlighting design for text search does not highlight too much. Even more in other tasks:
<img width="1537" alt="Screenshot 2022-02-08 at 16 30 38" src="https://user-images.githubusercontent.com/2518789/153019835-69b852b1-e801-4a04-a86a-5e88820ae8f6.png">

could we use another highlighting pattern ? maybe filling text with a higher contrast color ?

**Comment by dcfidalgo** [comment]
@Amelie-V  

- To me, it seems a bit confusing that you can remove predictions:
    - a record with predictions in explore mode
    - go to annotation mode, validate only a few predictions in this record
    - go back to explore mode, the predictions are gone
  
   To me, predictions should be something static that you cannot change from within in web app. Use case: I have predictions from a model, and ask the client to annotate a few records to see how my model is performing. Right now, I cannot visually check this after the client annotated the dataset.

- Like @frascuchon said, I also find it a bit counterintuitive that by clicking the prediction tooltip in the annotate mode, you remove the prediction (or is it the annotation in the end?). 

- annotate mode: when clicking on the mention predicted by the model, I would not display the dropdown but automatically choose the label predicted by the model. If you want to change the label, you can simply click again on the mention and choose the right label. As an alternative, I would put the predicted label first in the dropdown. 

- right now the workflow works nicely for models that are more or less working, but predictions from a model that makes a lot of mistakes, can get in your way quickly (you first have to remove all the wrong predictions, make your annotations and then press the save button). Then I would rather log the records again without the predictions to the web app. Not sure if two buttons could be a solution:
  - validate: validates the annotations that you explicitly made (by either making new annotations or validating single predictions)
  - validate all: validates all untouched predictions and your explicit annotations

- general comment: when a record is pending, I really miss some "cancel" button next to the "save" button, but my understanding is that right now this is impossible to implement, right @leiyre?

**Comment by Amelie-V** [comment]
Annotation mode : 

- [ ] Maintain prediction state when label is annotated
- [ ] Add delete all/clean button at record level in all states.
- [ ] Add a Pre-annotation state in transparency by default.
- [ ] Don't allow delete prediction.
- [ ] Review Highlight

**Comment by Amelie-V** [comment]
Conclusion post Friday review:

Next release MVP:

- [x] Maintain prediction state (don't delete them)
- [x] Pre-annotation (can be deleted on clic)
- [x] Results searched: bold + color 4C4EA3
- [x] Dropdown: Add space between the label sugerency and the full list
- [x] Dropdown: color border is the darker label color 
- [x] Maintain numeric until 9
- [x] DSont show num on legend (for now)
- [x] Label sugerency: when there is a prediction: the prediction, when no prediction the last used

V2:
- [ ] Add Clear annotations bt
- [ ] Add dropdown config.
- [ ] Integrate new header (cross tasks)
- [ ] prevent shortcut pagination when dropdown is active

**Comment by Amelie-V** [comment]
- [x] Background dropdown : use hover grey (in place of BG app color)
- [x] Lighter the color border
- [x] I would add the label number on the legend right now 
- [x] scroll with arrow doesn't work Versión 98.0.4758.80 (Build oficial) (x86_64)
- [x] Legend : change "show all" for "+3"

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-02-15 a las 14 21 48](https://user-images.githubusercontent.com/84135211/154072587-f4c6822c-3179-452e-9a9f-7bbbc495c1a5.png)
![Captura de pantalla 2022-02-15 a las 14 21 09](https://user-images.githubusercontent.com/84135211/154072592-9a6210c3-b403-4e76-92a0-9a0312f0e35f.png)

**Comment by frascuchon** [comment]
The "Cancel" button action, but we can tackle in v2.

**Comment by Amelie-V** [comment]
QA OK
