### ISSUE TITLE
The client noticed that the server is not a supported distribution of Elasticsearch

### ISSUE THREAD

**Issue by stephenleo** [recognai/rubrix#1089]
Hi All, Was trying to install today on a Macbook (Intel) and hitting this error
Version: 0.9.0

```
raise UnsupportedProductError(message)
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch
```

Here are the details of the setup process
```
# Create a directory for notebooks and another to download data 
mkdir -p rubrix/notebooks rubrix/data 

# CD into the directory
cd rubrix

# Create and activate a conda environment
conda create -n rubrix python=3.8 -y
conda activate rubrix

# Pip install the necessary libraries
pip install -U jupyterlab pandas matplotlib tqdm ipywidgets 
pip install -U "rubrix[server]" snorkel datasets

# Run the ES Docker container
docker run -d \
 --name elasticsearch-for-rubrix \
 -p 9200:9200 -p 9300:9300 \
 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
 -e "discovery.type=single-node" \
 docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2

# Run the Rubrix server
python -m rubrix
```

Please let me know if there's any other information needed from me to troubleshoot this issue. Appreciate the help!

**Comment by frascuchon** [comment]
Hi @stephenleo 

you need to downgrade or install version before 7.14.0 of elasticsearch client.

pip install 'elasticsearch<7.14.0'

Clients from 7.14.0 do not work with es open source distros

**Comment by stephenleo** [comment]
Perfect it works! Is it possible to add this into the README?

Also, any plan to migrate to Opensearch instead of ElasticSearch given the issues around licensing?

**Comment by frascuchon** [comment]
Great!

We would like to keep compatibility for both services elasticsearch and OpenSearch, but definitely we must simplify default installation setup with opensearch service.

Thanks!
