### ISSUE TITLE
[Workspaces] Users without personal datasets

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1119]
Users without personal datasets but that belongs to one or more workspaces which have datasets, should automatically change to one of those workspace?

Better to show all datasets from all workspaces in datasets list allowing to filter by workspace?

**Comment by dcfidalgo** [comment]
+1 For showing all datasets with the option to filter by workspace

**Comment by frascuchon** [comment]
See also #984

**Comment by Amelie-V** [comment]
Specifications related to the proposal (WIP)

- If NO dataset in any workspace: show the piece of code
- Workspace is filtrable
- A workspace belongs to a User or a Group and it's attached to an email. example: Alice workspace, IBM workspace, Linguists team workspace
- A user/group can be invited to other workspaces based threw the email address
- Filter: Automatic table refreshing on a check, need to uncheck one by one to remove filters
- Define Filtered column and Sort column (in the first version I would recommend activating filters only for Workspace)
- New feature: "add to top list" to keep accessible the main datasets user is working on

BIG pain point:

- A workspace doesn't exist at the URL level, _Datasets > Pirates_  so we can´t share a batch of datasets belonging to a workspace for example
- If we add the workspace to the breadcrumb: _Datasets > Goonies > Pirates_  it does not match with the workspace filter feature. or at least it's weird behaviour

**Comment by Amelie-V** [comment]
![DSlist2](https://user-images.githubusercontent.com/84135211/154489385-af18d7af-9dfe-488f-a48b-936676c016e6.png)
![DSlist1](https://user-images.githubusercontent.com/84135211/154489390-d7f9afee-ef8d-4337-8800-4ceecefd576a.png)

**Comment by frascuchon** [comment]
I think that keeping workspace as part of url is critical. As you mentioned, sharing datasets in different workspaces is one of them, but also, be able to distinguish datasets with same name allocated in different workspaces.

We need to discuss about workflow with workspace filters and the weird behaviour about breadcrumb + workspace filters

**Comment by Amelie-V** [comment]
### Summary 

- [x] Breadcrumb. _Datasets> Goonies>Dataset name_
- [x] Filter is activated on Goonies dataset List when I click on Goonies
- [ ] Add top list feature on default list (but filters stays the priority)

**Comment by Amelie-V** [comment]
QA 

- [x] Add Grey BG hover on filters 
- [x] Invert order to: Workspace, Task, Tags
- [x] Correct "glitch" on click on filters (button is moving)
- [x] Correct corner radius on Hover and active state header + on selector (should be 5)
- [ ] Let's see together how to polish completely the shadow effect. (view SS)

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-03-22 a las 15 16 30](https://user-images.githubusercontent.com/84135211/159502801-80ecea38-c4b5-445d-bb04-6c63c8584d6d.png)

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-03-22 a las 15 36 58](https://user-images.githubusercontent.com/84135211/159510689-d1370baa-adaf-4a47-8ef2-4e5f7f0a4461.png)

**Comment by Amelie-V** [comment]
- [ ] Modal shadow: 
x: 0 px
Y: 8 px
Blur: 20px
Alpha: 20%
Color: #5D6997 

- [ ] Increase size of user modal (aprox 300px/200px) and give more space between account circle and modal

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-03-23 a las 11 55 41](https://user-images.githubusercontent.com/84135211/159683971-e8312940-00fe-4761-b4a6-da87984e06b5.png)
