### ISSUE TITLE
[Search bar] Adjust search bar size based on device

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1121]
Large screen:

![Screenshot 2022-02-10 at 10 07 16](https://user-images.githubusercontent.com/2518789/153374697-5c3fc73a-d336-47ee-9529-4fbd61181153.png)

Laptop: 
<img width="1437" alt="Captura de pantalla 2022-02-10 a las 10 04 17" src="https://user-images.githubusercontent.com/2518789/153374803-44abcd1c-3e6a-4e0a-996a-615021f2ab0f.png">

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-02-10 a las 10 05 52](https://user-images.githubusercontent.com/84135211/153377357-16821461-25ed-45f4-b968-5ea2361aff1a.png)

**Comment by Amelie-V** [comment]
- [ ] Search area size should be adapted to size screen.

The fifth modal should always fit on left size, we need to text
- [ ] On XL Extend it a bit (around 80px?)
- [ ] On Laptop Reduce it (around 80px?)
