### ISSUE TITLE
[Monitoring] Introduce a more general async log

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1132]
Some users find `rb.monitor` very useful because it's async and they wonder if it would be possible to have a more general-purpose `rb.log` which is async too for dealing with custom cases and pipelines.

A specific use case where rb.monitor is not flexible enough (which might raise some enhancement ideas too):

User has a single pipeline/model which receives data from different "customers" and wants to log the predictions into different datasets something like `nlp(data, rubrix_dataset=f"{customer_name}_dataset")` 

In any case if feasible I think an async version of log makes total sense 

What do you think @frascuchon ?

**Comment by frascuchon** [comment]
yes, totally agree with async/lazy version of `log`

**Comment by dvsrepo** [comment]
Hi @davidberenstein1957, 

We're tackling this for the upcoming release. I recall you were interested in this, and you are using BentoML, we'd love to know more details about your use cases and even do some tests if you are interested in contributing.
