### ISSUE TITLE
[Text2Text] Correct card styles

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1138]
### Button 

- [x] Move the button area to the right side (to be unified with the rest of the tasks)
- [x] Unify order: 1.Block, 2.Outline 

### Text and links
- [x] Move the score on the prediction right side. like this : Prediction: 17.731% (15pt source)
- [x] Apply _card link style_  to "view annotation"  (refer to "show full record" behavior)
- [x] Add the separate line between Record area and Annotation (and/or) Prediction area

**Comment by frascuchon** [comment]
what about this @Amelie-V ?

**Comment by Amelie-V** [comment]
Moved to backlog

**Comment by Amelie-V** [comment]
<img width="1294" alt="Captura de pantalla 2022-07-20 a las 11 14 51" src="https://user-images.githubusercontent.com/84135211/179948366-1444677d-834f-44cb-9df2-e679a5129a82.png">
<img width="1280" alt="Captura de pantalla 2022-07-20 a las 11 11 22" src="https://user-images.githubusercontent.com/84135211/179948406-1e45c0ee-97a6-43fd-b45b-c736e5b6b9e5.png">
