### ISSUE TITLE
[Webapp] Show Rubrix version in  the webapp

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1180]
**Is your feature request related to a problem? Please describe.**
This was once discussed and there was an issue. The goal is to avoid confusion when we users (or ourselves) don't know which version we're running.

**Describe the solution you'd like**
I think it makes a lot of sense to have the rubrix version number somewhere in the UI (footer, or maybe in the top-right corner)

**Describe alternatives you've considered**
-

**Additional context**

**Comment by frascuchon** [comment]
We definitely need a way to present rubrix server version from app. We can start with a simple footer for now but it's critical since we need identify reported errors to version where occurs.

**Comment by Amelie-V** [comment]
Add version number into the  account menu : 0.12.0

Source pro regular 11

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-03-10 a las 10 20 20](https://user-images.githubusercontent.com/84135211/157630733-197bc252-564d-4268-a5f8-a2b0d09b7b2e.png)
