### ISSUE TITLE
[Tutorials] Update videos and screenshots for Token classification

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1182]
All tutorials and guides showing token classification task UI, should be updated with new UI

**Comment by dcfidalgo** [comment]
### References

- https://rubrix.readthedocs.io/en/master/reference/webapp/annotate_records.html#token-classification
- https://rubrix.readthedocs.io/en/master/reference/webapp/annotate_records.html#annotate-records
- https://rubrix.readthedocs.io/en/master/reference/webapp/explore_records.html#search-and-filter
- https://rubrix.readthedocs.io/en/master/reference/webapp/explore_records.html#token-classification
- https://rubrix.readthedocs.io/en/master/reference/webapp/dataset.html#search-bar
- https://rubrix.readthedocs.io/en/master/reference/webapp/dataset.html#status-filter
- https://rubrix.readthedocs.io/en/master/reference/webapp/dataset.html#token-classification
- https://rubrix.readthedocs.io/en/master/reference/webapp/filter_records.html#filtering-records-in-the-annotation-mode

### Tutorials
- https://rubrix.readthedocs.io/en/master/tutorials/02-spacy.html
- https://rubrix.readthedocs.io/en/master/tutorials/07-zeroshot_ner.html
- https://rubrix.readthedocs.io/en/master/tutorials/skweak.html (david)
