### ISSUE TITLE
[ClientRecords] Record id's not decisive

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1188]
This will log only the second record
```python
records = [
    rb.TextClassificationRecord(inputs="mock", id=1),
    rb.TextClassificationRecord(inputs="mock", id="1")
]
rb.log(records, "test")
```

Not sure what to do here, or if it is even an issue. One solution could be to restrict the id type to str as we had before, but then we will lose the functionality of ordering the records with `enumerate`.

cc @dvsrepo @frascuchon

**Comment by frascuchon** [comment]
`id`'s are stored in elasticsearch using keyword field types (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-field-type))

All considerations about this type should be applied to id. In your case, the id 1 and "1" results in the same keyword value, so are the same id.

Anyway, It's not a good practice use several id types in the same datasets

**Comment by dcfidalgo** [comment]
:+1: i will include this field type in the field glossary of the search guide.
