### ISSUE TITLE
httpx 422 error when using wrong characters in 'name' during 'rb.log()' within FastAPI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1200]
**Describe the bug**
httpx 422 error when using wrong characters in 'name' during 'rb.log()' within FastAPI

**To Reproduce**
I came across a bug(?) when trying to set-up logging from within FastAPI with backgroundtasks. When calling the rb.log(), the name variable containing certain characters, it results in a HTTP/1.1 422 Unprocessable Entity  error. It turn out, it was caused by using cased letters and some other characters like "." and "_". When outside FastAPI, I didn't have these issues.
`
rb.log(
    rb.TextClassificationRecord(inputs="My first Rubrix example"),
        name="Research--spacy-en-research",
        verbose=False
)
`

**Expected behavior**
Outside of FastAPI I do get to use the naming I want.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Windows 11
 - Browser [e.g. chrome, safari]: N.A. 
 - Rubrix Version [e.g. 0.10.0]: 0.11
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:  N.A.
 - httpx = {version = "0.15.0", extras = ["http2"]}
- fastapi = "^0.70.0"
- uvicorn = "^0.15.0"

**Additional context**
HTTP Request: POST http://localhost:6900/api/datasets/Research--spacy-en-research/TextClassification:bulk "HTTP/1.1 422 Unprocessable Entity"
HTTP Request: POST http://localhost:6900/api/datasets/research_spacy-en-research/TextClassification:bulk "HTTP/1.1 422 Unprocessable Entity"
HTTP Request: POST http://localhost:6900/api/datasets/research.spacy-en-research/TextClassification:bulk "HTTP/1.1 422 Unprocessable Entity"

**Comment by frascuchon** [comment]
Hello @davidberenstein1957 Thanks for reaching out.

The dataset name has a strong limitation about allowed characters and position. Regarding your example, the provided name `Research--spacy-en-research` should failed when logging records.

Could you share a pseudo code snippet where your is failing vs another where is not failing ?

Thanks !

**Comment by frascuchon** [comment]
Closed by #1312
