### ISSUE TITLE
[Tutorials][Documentation] updating videos and images for reference + tutorials docs

### ISSUE THREAD

**Issue by leireropl** [recognai/rubrix#1229]
All tutorials and guides showing text classification should be updated with new UI

**DOCS TO BE UPDATED:**
TUTORIALS:
- https://rubrix.readthedocs.io/en/stable/tutorials/01-labeling-finetuning.html
- https://rubrix.readthedocs.io/en/stable/tutorials/05-active_learning.html
- https://rubrix.readthedocs.io/en/stable/tutorials/find_label_errors.html
- https://rubrix.readthedocs.io/en/stable/tutorials/08-error_analysis_using_loss.html

REFERENCE DOCS:
- https://rubrix.readthedocs.io/en/stable/reference/webapp/dataset.html
- https://rubrix.readthedocs.io/en/stable/reference/webapp/explore_records.html
- https://rubrix.readthedocs.io/en/stable/reference/webapp/annotate_records.html
- https://rubrix.readthedocs.io/en/stable/reference/webapp/search_records.html
- https://rubrix.readthedocs.io/en/stable/reference/webapp/view_dataset_metrics.html

**Comment by leireropl** [comment]
I am wondering whether to update the **"Find label errors" tutorial video** or just wait, because you made a good edition and maybe you want to keep it for now.

**Comment by dcfidalgo** [comment]
I think you can update it as well, replicating just the last part of it, the one with the web app. No need to show the notebook part. Should be a fairly quick video, 20s max.

**Comment by leireropl** [comment]
Closed with #1232
