### ISSUE TITLE
Add a FAQ section

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1270]
All these past months we've been receiving highly recurrent questions. 

I think is important to provide a FAQ section.  I would vote for adding this to the README so it's easier to maintain and extend quickly with new questions and answers.

I have started drafting this. I'd propose we start drafting this here and then do a PR with a first version:

## What is Rubrix?
Rubrix is an open-source MLOps tool for building and managing training data for Natural Language Processing. 

## What can I use Rubrix for?
Rubrix is useful if you want to:

- create a training set for training a model.
- evaluate and improve an existing model.
- monitor an existing model in order to improve it over time and gather more training data.

## What do I need to start using Rubrix?
You need to have a running instance of Elasticsearch and install Rubrix Python library. 

The Python library is used to read and write data into Rubrix. To get started we highly recommend to use Jupyter Notebooks so you might want to install Jupyter Lab, or use jupyter support for VS Code for example.

## How can I "upload" data into Rubrix?
Currently, the only way to upload data into Rubrix is by using the Python library. This is based on the assumption that there's rarely a perfectly prepared dataset in the format expected by the data annotation tool. 

Rubrix is designed to enable fast iteration for users that are closer to data and models, namely data scientists and NLP/ML/Data engineers. If you are familiar with libraries like Weights & Biases or MLFlow, you'll find Rubrix `log` and `load` methods intuitive. That said, Rubrix gives you different shortcuts and utils to make loading data into Rubrix a breed, such as for example the ability to read datasets directly from the Hugging Face Hub.

In summary, the recommend process for uploading data into Rubrix would be following: 

(1) Install Rubrix Python library, 

(2) Open a Jupyter Notebook, 

(3) Make sure you have a Rubrix server instance up and running, 

(4) Read your source dataset using Pandas, Hugging Face datasets, or any other library, 

(5) Do any data preparation, pre-processing, or pre-annotation with a pretrained model, and 

(6) Transform your dataset rows/records into Rubrix records and log them into a Rubrix dataset using `rb.log`. If your dataset is already loaded as a Hugging Face dataset, checks the `read_datasets` method to make this process even simpler.

## Can I use my own Elasticsearch Instance/cluster?
Yes, you can use your own Elasticsearch installation. You only need to perform some configuration, check the Advanced installation guide in the [docs](https://docs.rubrix.ml/).

## How can I train a model
...

**Comment by dcfidalgo** [comment]
I copied the FAQ to google docs for you to easier comment/add stuff:
https://docs.google.com/document/d/1gNGxMR_5StXDnXRXydepzOqLuzMr_CxioPWNt3Qqvu0/edit?usp=sharing

@dvsrepo @frascuchon Let me know if you want to add more stuff, or if I can go ahead and create a PR with this first complete version.
