### ISSUE TITLE
[Record card] Giving some extra space (air) for TextClassification (maybe Token too)

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1274]
**Is your feature request related to a problem? Please describe.**
See
<img width="1561" alt="Screenshot 2022-03-18 at 14 21 52" src="https://user-images.githubusercontent.com/1107111/159010564-3c980fd0-b9c6-452b-add5-b19e6403407b.png">

**Describe the solution you'd like**
I think we should have more space between at least the labels and the text inputs. And in general I think that having a larger min-height for record cards is a good idea.

**Comment by Amelie-V** [comment]
<img width="1284" alt="Captura de pantalla 2022-03-22 a las 14 02 25" src="https://user-images.githubusercontent.com/84135211/159504073-60e86534-42ff-4a66-916a-06122baf92d6.png">
<img width="1294" alt="Captura de pantalla 2022-03-22 a las 14 02 08" src="https://user-images.githubusercontent.com/84135211/159504082-4548aaff-9213-4a03-9250-556300cad438.png">

**Comment by Amelie-V** [comment]
### Record Card padding Explore/annotation/WS mode

- [x] increase padding around record (50/50/50/50) for Text and token Class
- [x] increase padding around record (50/50/20/50) for Text2 text (because of the slider line)

### Spaces between records and buttons Text and token Class, Text2text

- [x] Apply in annotation mode the space existing in explore.

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-03-22 a las 15 35 18](https://user-images.githubusercontent.com/84135211/159507939-35696e77-dad5-42d5-a455-9440c9b9d32c.png)

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-03-22 a las 15 38 20](https://user-images.githubusercontent.com/84135211/159508007-10cff081-008c-4927-9cbb-bdeefd5594c7.png)
![Captura de pantalla 2022-03-22 a las 15 37 10](https://user-images.githubusercontent.com/84135211/159508025-c08b96a1-1dbf-4951-ab16-8a15ce34bdf0.png)
