### ISSUE TITLE
Fields in my metadata go beyond 128 chars (e.g.: URLS from web archived pages)

### ISSUE THREAD

**Issue by davidsbatista** [recognai/rubrix#1276]
```
class _Validators(BaseModel):
    """Base class for our record models that takes care of general validations"""

    @validator("metadata", check_fields=False)
    def _check_value_length(cls, v):
        """Checks metadata values length and apply value truncation for large values"""
        new_metadata = limit_value_length(v, max_length=MAX_KEYWORD_LENGTH)
        if new_metadata != v:
            warnings.warn(
                "Some metadata values exceed the max length. "
                f"Those values will be truncated by keeping only the last {MAX_KEYWORD_LENGTH} characters."
            )

        return new_metadata
```

Seems to be that there's no way to define the `MAX_KEYWORD_LENGHT`, and one has to live with the 128 char limit, is there any workaround?

**Comment by frascuchon** [comment]
Hello @davidsbatista ! Thanks for reaching out. 

It's not possible to modify change metadata length for textual fields for now.  We will make available a configuration using environment variables in future releases.

As workaround, maybe you can parse the url and use several metadata fields, for example `url_hostname` and `url_path`.  
I hope I have been helpful

**Comment by davidsbatista** [comment]
Hi @frascuchon, thanks for the reply, I just changed the source to a higher value, but thanks for your suggestion

**Comment by dvsrepo** [comment]
Hi @davidsbatista, we've created an issue with your suggestion. Thanks for pointing this out!

**Comment by frascuchon** [comment]
Closing this issue. Moving discussion to https://github.com/argilla-io/argilla/issues/1761
