### ISSUE TITLE
[TextClassificationRecord] Copy inputs values to text?

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1287]
When making a query for `TextClassificationRecord`s, the `text` field contains all the values of the `inputs` dictionary.
Shall we follow the same logic in the client?

Now we have this:
```python
rec = rb.TextClassificationRecord(inputs={"text": "mock"})
rec.text == "mock"

rec = rb.TextClassificationRecord(inputs={"not_text": "mock"})
rec.text is None

rec = rb.TextClassificationRecord(inputs={"text": "mock", "second_text": "mock2})
rec.text is None
```
cc @dvsrepo @frascuchon

**Comment by frascuchon** [comment]
Mmmmm, maybe should be the default behavior to be consistent when the number of inputs is one. In those cases, the text is filled with a single value.

**Comment by frascuchon** [comment]
Closing. We could normalize the inputs in a cross-task way. Let's think about it then
