### ISSUE TITLE
Unable to install rubrix with own elastic search

### ISSUE THREAD

**Issue by radhakrishr36** [recognai/rubrix#1299]
This command doesn't work and throws this error

**docker run -p 80:80 -e "ELASTICSEARCH=http(s)://elastic:pwd@IP" --name rubrix3 recognai/rubrix**	
 
**Error:**
opensearchpy.exceptions.AuthenticationException: AuthenticationException(401, 'security_exception', 'unable to authenticate user [elastic] for REST request [/_template/.rubrix.dataset.%7B%7D.records-v0]')

But the same time it's working without password elastic search

docker run -p 80:80 -e "ELASTICSEARCH=IP:Port" --name rubrix3 recognai/rubrix	

Help me to resolve this isseus.

**Comment by frascuchon** [comment]
Hi @radhakrishr36  and thanks for reaching out.

Did you try to access to your elasticsearch instance with configured credentials ? Try in your browser the url http(s)://elastic:pwd@IP and check if credencials al required. 

You can also try with a simple pass. Sometimes password should be escaped when include as part of a url. Finally, maybe some roles should be configured to your user. Take a look to [this guide](https://rubrix.readthedocs.io/en/stable/getting_started/advanced_setup_guides.html#configure-elasticsearch-role-users) for more info about that

**Comment by frascuchon** [comment]
Hi, @radhakrishr36 

Did you manage to solve the problem?

**Comment by radhakrishr36** [comment]
Hi @frascuchon,

This problem not solved yet, If you have any proper documentation kindly share with me.

**Comment by frascuchon** [comment]
Thanks, @radhakrishr36 

What was the result of opening in a browser the elasticsearch info URL? Were the credentials required?

Has the password some special characters that you [should escape](https://stackoverflow.com/questions/10050877/url-username-with)?

**Comment by pooja-solaikannu** [comment]
I faced with the same issue and after changing the format to "http(s)://elastic:pwd@IP", I'm able to view the info of elastic in the browser.

After confirming the connectivity, I tried changing the docker-compose.yml file as such to use the existing elastic as rubrix's persistance layer,

################################################################
docker-compose.ym
version: "3"

services:
  rubrix:
    image: recognai/rubrix:latest
    restart: unless-stopped
    ports:
      - "6900:80"
    environment:
      ELASTICSEARCH: http://username:pwd@IP
      # RUBRIX_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
    # volumes:
      #- ${PWD}/.users.yaml:/config/.users.yaml
    networks:
      - rubrix

networks:
  rubrix:
    driver: bridge
######################################################################
Note: I created a new role called "rubrix" in the specified elastic service.

I could not up my elastic and I'm facing with an error following

(base) username@172:~/rubrix$ docker-compose up
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (4.0.0) doesn't match a supported version!
warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
ERROR: Invalid interpolation format for "environment" option in service "rubrix": "http://username:pwd@IP"

Please help me with a clear guide to use any existing elastic service as rubrix's persistence layer without pulling new elastic from docker. 

Thanks, 
Pooja

**Comment by frascuchon** [comment]
Hi @pooja-solaikannu 

Sorry for the late response. Regarding your error, I figure out that some special character is included as part of the `ELASTICSEARCH` env var. Did you test using an unsecured elasticsearch instance? Did it work?

See this StackOverflow [topic](https://stackoverflow.com/questions/49897503/docker-compose-invalid-interpolation-format-for-environment-option-in-service)

**Comment by radhakrishr36** [comment]
@frascuchon Now it's working. I escape the special character in the elastic search password and made some changes in the docker-compose.yml file.

Thanks for your support

**Comment by frascuchon** [comment]
Thanks, @radhakrishr36. Glad to read this. I will close the issue. Please, feel free to reopen it if you consider.
