### ISSUE TITLE
[Tags] Improve integration Dataset list

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1303]

**Comment by Amelie-V** [comment]
Tags can't be sorted, so it does not make sense to present them as header column.

- [ ] Show "tags" close to the dataset title (on the right side) and leave Header title "Tags".

**Comment by frascuchon** [comment]
which work close this issue @Amelie-V @leiyre ?

**Comment by Amelie-V** [comment]
I closed this issue because this topic has been discarded. No work done

**Comment by frascuchon** [comment]
Great! I've removed it from the Release project too.
