### ISSUE TITLE
Prevent logging auto-setup

### ISSUE THREAD

**Issue by vigenere23** [recognai/rubrix#1305]
**Is your feature request related to a problem? Please describe.**

When importing anything from Rubrik, it automatically setups the Python logging, which surpress any configuration I might have done. This is currently done at line 70 of `__init__.py` with the command `configure_logging()`.

**Describe the solution you'd like**

I would like to be able to manually setup the logging *if needed*, instead of having it be done automatically on import. For example, calling `rubrix.configure_logging()` manually in my script.

**Describe alternatives you've considered**

I've tried configuring my logging after the import of Rubrix, but it still doesn't work. I've also tried importing the classes directly (like `Text2TextRecord`) without using the singleton from the `__init__,py`, but it still doesn't work.

**Comment by frascuchon** [comment]
Hi @vigenere23 and thanks for reaching out.

If  you are not using `logoru` for your logging configuration, you could uninstall it. Then rubrix won't do the auto-loggin configuration. 

See [here](https://github.com/recognai/rubrix/blob/master/src/rubrix/logging.py#L111)

**Comment by vigenere23** [comment]
Thanks for the info :) That does work, but I think it's still not ideal to prevent the logging (requires a manual step after each installation).

**Comment by frascuchon** [comment]
Totally true! `loguru` should be an optional dependency.

Thanks for your feedback. I've created an issue for that #1331
