### ISSUE TITLE
Utilize GPT3 embedding / classification API for more automated bulk labelling

### ISSUE THREAD

**Issue by whaowhao** [recognai/rubrix#1309]
Keyword-based bulk labeling using Rubrix Rules is still too slow if I were to label thousands of texts for classification - at maximum, I can label 20 at a time since keyword match is noisy with regard to ground-truth label. 

I have played with GPT3 embeddings, where applying UMAP on texts results in clear clusters with semantically similar texts in clusters. If one can create Rubrix Rules instead based on a selected area on a scatterplot of text embeddings, then one can label hundreds of texts at once, and can easily finish labeling 50,000 data points in a day with high quality. And that'd be a game-changer.

Adding on to that, I also played with GPT3 classification API, where it gives pretty accurate few-shot classifications. And if that is added to the pipeline, it'd expedite labeling even further. Making it possible to label thousands of texts at once.

I have the GPT3 embedding + classification pipeline done in a notebook, is there plan on Rubrix's side to look into utilizing GPT3?

**Comment by dcfidalgo** [comment]
Hey @whaowhao Thank you for bringing this up! We are [working on a tutorial](https://github.com/recognai/rubrix/pull/1135) in which we show how you can use [Epoxy](https://github.com/HazyResearch/epoxy) to achieve the same goal you are mentioning. The workflow would be something like this:
- Come up with a few rules trying to cover semantically diverse records
- Provide the weak label matrix and your embeddings of choice to Epoxy (with some thresholds)
- Get back an enhanced weak label matrix

Hopefully, we can share it with you soon, we would love to get your feedback.

**Comment by dvsrepo** [comment]
Thanks @whaowhao ! Adding to what @dcfidalgo mentions, we've also been discussing the ability of "labelling-by-drawing" based on a 2-D embedding-based representation (UMAP or otherwise). This will be in the roadmap but not immediately. 

Meanwhile I'd be really interested on collaboration/supporting you with experiments with GPT3, would you be interested?

**Comment by whaowhao** [comment]
Hi @dvsrepo yeah let's chat

**Comment by dcfidalgo** [comment]
@whaowhao We just added the feature of extending the weak label matrix via embeddings. You can find a comprehensive tutorial on this feature [here](https://rubrix.readthedocs.io/en/master/tutorials/extend_weak_labels_with_embeddings.html). We would love to receive some feedback from your side, and if this feature results useful for your use case.  Let us know if we can be of any further help!
