### ISSUE TITLE
[login] Change message in login page

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1330]
Change the text to:

Build, improve, and monitor data for NLP

<img width="429" alt="Screenshot 2022-03-28 at 22 15 46" src="https://user-images.githubusercontent.com/1107111/160479651-e6cffb21-d261-44cf-892f-25edb9c3e3ab.png">

**Comment by Amelie-V** [comment]
<img width="439" alt="Captura de pantalla 2022-03-29 a las 9 54 20" src="https://user-images.githubusercontent.com/84135211/160561855-0a6aaba1-b675-4af0-8bd3-f6ab2142e0ed.png">

**Comment by Amelie-V** [comment]
- [ ] Border field radius 5 
- [ ] Padding 50 px (all around)
- [ ] Font Futura medium 26,  #010250
- [ ] size modal around 350*460
