### ISSUE TITLE
[Client] Move to 'rb.DatasetFor*' by default

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1360]
- Remove `as_pandas` argument in the `rb.load` method, return a `rb.DatasetFor*` by default
- Return `rb.DatasetFor*` objects instead of records `list`s in the `labeling` module

**Comment by spetrescu** [comment]
Hey! Can I tackle this issue?

**Comment by dvsrepo** [comment]
Of course @spetrescu ! Thanks, let us know if you need anything
