### ISSUE TITLE
Using regex for defining a rule fails 

### ISSUE THREAD

**Issue by saraesteveznewtral** [recognai/rubrix#1365]
When trying to define a rule using regex format the _save rule_ button does not work and the rule is not saved.

1. Go to any dataset already uploaded to Rubrix
2. Click on _Define rules_ and press enter to see the results filtered
3. Then click on the corresponding label
4. The last step, clicking on  _save rule_ button, does not work so therefore it does not save the rule in the _Manage rules_ dashboard.

The following description is an example of a query and the error it throws.  
![image](https://user-images.githubusercontent.com/102751804/161099925-b2aa796f-f30d-4753-8e48-95b63ec29d3a.png)

I'm using the last version of Rubrix **(v.0.13.0)**.

**Comment by frascuchon** [comment]
Hi @saraesteveznewtral and thanks for reaching out.

Yes, It indeed looks like a regular expression query processing error. We're working on a fix and we will publish it as soon as possible.

**Comment by dvsrepo** [comment]
Hi Sara, we've just published 0.13.1 solving this issue. If you could upgrade using pip install -U rubrix[server] and let us know it'd be great! Also we have a slack community channel in case you want to ask questions over there
