### ISSUE TITLE
Can't view metadata when text is too large for TokenClassificationRecord

### ISSUE THREAD

**Issue by coreyelowsky** [recognai/rubrix#1367]
**Describe the bug**

For a TokenClassificationRecord, when I upload metadata with the record, and then click the three vertical dots to view the metadata associated with that record, the text is also shown with the metadata. When there isn't much text this is not an issue. But when the text is large, one cannot see the metadata. I included 2 images below demonstrating both scenarios. In the second image  the metadata is not visible.

**To Reproduce**
1. Upload a TokenClassification Record with large amounts of text and metadata
2. Click the three vertical dots to try and view the metadata

**Expected behavior**

Would it be possible to not include the text when viewing the metadata, as the text itself is not metadata? Or possibly just be able to scroll down within the metadata pop up so one can see the metadata.

**Screenshots**
![Screen Shot 2022-03-31 at 2 07 41 PM](https://user-images.githubusercontent.com/15001058/161122290-76c5ca90-9c1d-4f72-805d-f7c3c0cb2896.png)

![Screen Shot 2022-03-31 at 2 07 57 PM](https://user-images.githubusercontent.com/15001058/161122311-85de7cf5-d690-4b4f-9f92-521ad3994488.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Linux/Mac
 - Browser [e.g. chrome, safari]: Chrome
 - Rubrix Version [e.g. 0.10.0]: 0.13.0
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:

**Comment by Amelie-V** [comment]
Hi @coreyelowsky 

You are right the text should not be repeated into the metadata pop up. We'll solve it :)

**Comment by Amelie-V** [comment]
- [ ] remove text record from metadata popup
