### ISSUE TITLE
Odd behavior for some labels in TokenClassificationRecord

### ISSUE THREAD

**Issue by coreyelowsky** [recognai/rubrix#1368]
**Describe the bug**

For a TokenClassificationRecord, some of the predictions don't show up correctly. As shown in the image below, the word 'Snoring' isn't underlined like the word 'Fatigue' is. And when I hover over 'Snoring' the expected pop up is displayed without color. For context, we have many labels (~100).

**To Reproduce**
1. Upload many TokenClassifcationRecords with many labels and predictions.

**Expected behavior**

All tokens that correspond to predictions are displayed in the same manner. Underlined with a color, etc...

**Screenshots**

![Screen Shot 2022-03-31 at 2 22 00 PM](https://user-images.githubusercontent.com/15001058/161124136-4f8da4a2-4e1c-403d-9e9e-737f3420f745.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Linux / Mac
 - Browser [e.g. chrome, safari]: Chrome
 - Rubrix Version [e.g. 0.10.0]: 0.13.0
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:

**Comment by Amelie-V** [comment]
Quick fix

- [ ] Rotate the color every 50 labels endlessly
