### ISSUE TITLE
TokenClassification scoring filtering doe not work within UI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1373]
**Describe the bug**
When filtering on prediction score within TokenClassification, I do not get TokenClassificaiton scores within the filter.

**To Reproduce**
run [this code](https://github.com/Pandora-Intelligence/rubrix-blogs/blob/main/concise-concepts.ipynb). 

**Expected behavior**
I would expect that all classified token and sentences are filtered based on their scoring. Resulting in only showing sentences that contain one or more entities within the filter, without showing entities outside the filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/25269220/161485221-d115c46b-b745-4b5e-8970-f53b83eb80d6.png)
![image](https://user-images.githubusercontent.com/25269220/161485257-43ce9fa5-baa5-46d9-9e98-0d7e6c520c38.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]: Firefox
 - Rubrix Version [e.g. 0.10.0]: 0.13.0
 - ElasticSearch Version [e.g. 7.10.2]: 7.11.1

**Additional context**

**Comment by Amelie-V** [comment]
Hi @davidberenstein1957
We are working on it!

**Comment by frascuchon** [comment]
This issue is already resolved in version 0.14
