### ISSUE TITLE
[Score info] In NER

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1379]

**Comment by Amelie-V** [comment]
### update Filter score style

- [x] Update modal style (Grey BG, shadow, No border, Change "results" color to blue #0508d9 and score line to purple #4c4ea3.
- [x] Open score modal just under selector (as all filters), should fit into selector width

### Prediction tooltip

- [x] Show prediction % in Prediction tooltip (explore and annotate mode)
- [x] In general add a pixel line darker on predicted token tooltip darker

**Comment by Amelie-V** [comment]
<img width="439" alt="Captura de pantalla 2022-04-05 a las 15 25 39" src="https://user-images.githubusercontent.com/84135211/161765796-2630686f-f196-42e6-b77d-90f7aa84827d.png">

**Comment by dcfidalgo** [comment]
Just a comment, more for a second iteration: I think it would be useful to see the scores without having to hover over the predictions. This can be useful when one has longer records with a lot of predictions, and you use the score filter. Now you have to hover over all the predictions to figure out, which of the predictions matched the filter (usually the predictions with a low score).

**Comment by frascuchon** [comment]
> Just a comment, more for a second iteration: I think it would be useful to see the scores without having to hover over the predictions. This can be useful when one has longer records with a lot of predictions, and you use the score filter. Now you have to hover over all the predictions to figure out, which of the predictions matched the filter (usually the predictions with a low score).

Do make sense allow to see only predictions matching the score used in filters? I mean, for records with a lot of labels, maybe make sense show only affected entities instead of all. Including an score for all entities could overload info shown to user, even more if the records have a lot of labels.

**Comment by dvsrepo** [comment]
> > Just a comment, more for a second iteration: I think it would be useful to see the scores without having to hover over the predictions. This can be useful when one has longer records with a lot of predictions, and you use the score filter. Now you have to hover over all the predictions to figure out, which of the predictions matched the filter (usually the predictions with a low score).
> 
> Do make sense allow to see only predictions matching the score used in filters? I mean, for records with a lot of labels, maybe make sense show only affected entities instead of all. Including an score for all entities could overload info shown to user, even more if the records have a lot of labels.

Yes, I agree with both. As David mentions, I'd leave this for a second iteration and open a design issue to analyze the different options (showing only affected entities, etc.) cc @Amelie-V

**Comment by Amelie-V** [comment]
as @dcfidalgo mentioned it's a useful info with low score pred: Do you think it's correct showing the % without decimal? ex: 1% or 0%?

**Comment by dcfidalgo** [comment]
> Do make sense allow to see only predictions matching the score used in filters? I mean, for records with a lot of labels, maybe make sense show only affected entities instead of all. Including an score for all entities could overload info shown to user, even more if the records have a lot of labels.

This could be another option, I think we really have to see it ... maybe hiding predictions can be confusing, maybe showing all scores can be overwhelming.

 > as @dcfidalgo mentioned it's a useful info with low score pred: Do you think it's correct showing the % without decimal? ex: 1% or 0%?
 
 I think most of the time, the percentage without decimals is more than sufficient. Maybe it would still be nice if the user could somehow consult the full number if requiered.

**Comment by Amelie-V** [comment]
<img width="529" alt="Captura de pantalla 2022-04-06 a las 11 29 49" src="https://user-images.githubusercontent.com/84135211/161944228-9f335fee-ed3c-47b5-81f2-ba45aaa00295.png">

**Comment by Amelie-V** [comment]
After doing a last review, I also found confusing to show entities that do not match with the score filter just because they are making part of the record.

### Reduce opacity to entities that doesn't match with filters

I would recommend to implement from now to show all entities out of the filter with a light opacity to distinguish them from the other.
e.g. Score filter = 0% to 10%.  Entity > 10% = Show entity (underlined + tooltip) into the record with opacity to 70% .

This behavior should be generalized to all filters. 
e.g. "predicted_as : ORG" in both mode: Explore and Annotate

### Leave 2 decimals to score as a max in score dropdown

e.g. 0% to 14.00000000002% -> 0% to 14% ,  0% to 14.05%

**Comment by Amelie-V** [comment]
<img width="645" alt="Captura de pantalla 2022-04-13 a las 11 46 48" src="https://user-images.githubusercontent.com/84135211/163158244-2d915059-e37b-4789-aa17-91e3b017e1a0.png">

**Comment by Amelie-V** [comment]
@leiyre The layout is broken in annotation mode. (view SS)
DS: mock_tokenclass_scores_for_leire

Also, I would recommend in annotation mode to show annotation highlight in the same tone as the prediction which means: if the prediction is different from the score range, apply transparency to both: the prediction underlines and annotation highlight. what do you think @frascuchon @dcfidalgo @leiyre @dvsrepo

**Comment by Amelie-V** [comment]
<img width="1339" alt="Captura de pantalla 2022-04-25 a las 21 30 36" src="https://user-images.githubusercontent.com/84135211/165240022-06c25d80-f31f-4967-9f57-aa697d6ad294.png">

**Comment by dcfidalgo** [comment]
Not sure if the score filter (which is a filter for the predictions) should affect the annotations. But in general, I like the idea of somehow "hiding" the predictions that are not in the score range, by making them more transparent. I think we need to test this.

**Comment by Amelie-V** [comment]
Yes I understand that the score is affecting only the prediction. In any case It's better to wait for the fix and test it all together.

**Comment by frascuchon** [comment]
Like @dcfidalgo says, is a bit confusing for me to hide annotations based on the score filter that is based on prediction scores.

**Comment by Amelie-V** [comment]
### Prediction visualisation suggestion
When the prediction is inside of the score range: strong 1 px underline color line + color underline
When the prediction is outside of the score range: only color underline
