### ISSUE TITLE
When uploading text for TokenClassificationRecord if a word whose suffix matched the following word, the two words will be shown concatenated without a space in between

### ISSUE THREAD

**Issue by coreyelowsky** [recognai/rubrix#1383]
See below how when an example like "This is" is in the text, where the suffix of the previous word matches the following word, then the two words are not shown with a space in between. Below this, I show the original text and the tokens.

<img width="470" alt="Screen Shot 2022-04-05 at 11 43 28 PM" src="https://user-images.githubusercontent.com/15001058/161891763-2141ca55-a17a-4236-bc46-9d97ffad6adc.png">
<img width="493" alt="Screen Shot 2022-04-05 at 11 44 00 PM" src="https://user-images.githubusercontent.com/15001058/161891768-52e5e45f-b3e0-4e65-bebe-1d817e9f9076.png">

**Comment by Amelie-V** [comment]
let's check that together @leiyre
