### ISSUE TITLE
When TokenClassificationRecrod has a lot of labels, if I expand the labels to view them all, the screen doesnt allow me to scroll down to view all the labels

### ISSUE THREAD

**Issue by coreyelowsky** [recognai/rubrix#1393]
When TokenClassificationRecrod has a lot of labels, if I expand the labels to view them all, the screen doesnt allow me to scroll down to view all the labels. When this happens there is no way to view the records either since the screen is essentiallly stuck.

<img width="1416" alt="Screen Shot 2022-04-07 at 9 36 33 AM" src="https://user-images.githubusercontent.com/15001058/162212189-8092a521-8ca4-45ec-b9b1-0dd225bf5b30.png">

**Comment by Amelie-V** [comment]
- [x] On click on "+n" expand the labels on 5 lines max. keeping the "show less" button at the end of the list.
- [x] Allow scroll to view the full list

**Comment by Amelie-V** [comment]
@leiyre 

- [x] Review "Show less" position and style
- [x] Active hand hover cursor on +N and Show less
