### ISSUE TITLE
Broken UI element Viewport 1024

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1407]
**Describe the bug**

- A. STATUS/METADATA/SORT modal are cut
- B. Sort and records (101) overlaps with each other
- C. Sort and records (101) overlaps with the metrics panel
- D. Long Prediction tags doesn't respect margin-right

**To Reproduce**
1. Go to [a_lot_of_labels_multi-label]
2. viewport 1024

**Expected behavior**

- A. 
Suggestion?

- B. 

**Option to analyse:**

In general:
 (all screen size) : Reduce margin on right side (SS?) could be a way to win space + same space between Search field and first filter that between filter 1 and filter 2

In 1024:
Reduce spaces between filters: 15 to 10
Possibility to remove "Records" and show only (101)

- C. Sort and records (101) are overlap with metrcis panel
Change component order

- D. Long Prediction tags doesn't respect margin-right
Suggestion

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]: mac
 - Browser [e.g. chrome, safari]: chrome
 - Rubrix Version [e.g. 0.10.0]: dev
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:

**Comment by Amelie-V** [comment]
<img width="1403" alt="Captura de pantalla 2022-04-12 a las 13 53 37" src="https://user-images.githubusercontent.com/84135211/162956166-5f267775-bead-45de-a3c0-1960eebeaa33.png">
<img width="990" alt="Captura de pantalla 2022-04-12 a las 13 41 22" src="https://user-images.githubusercontent.com/84135211/162956257-4459c539-5089-44ea-8a86-44012af8cb01.png">

**Comment by Amelie-V** [comment]
<img width="599" alt="Captura de pantalla 2022-04-12 a las 14 00 13" src="https://user-images.githubusercontent.com/84135211/162958072-2a1877f1-3475-4805-801e-e9c6c63012e7.png">

**Comment by Amelie-V** [comment]
<img width="254" alt="Captura de pantalla 2022-04-12 a las 14 56 27" src="https://user-images.githubusercontent.com/84135211/162967733-0c9896a8-e361-43cc-86bc-11a4b1e1f4d3.png">

**Comment by leiyre** [comment]
A. STATUS/METADATA/SORT modal are cut 

for this point I would open the drop-down more to the left in max-width 1024px

**Comment by Amelie-V** [comment]
QA:

Describe the bug

A. STATUS/METADATA/SORT modal are cut : OK
B. Sort and records (101) overlaps with each other : OK
C. Sort and records (101) overlaps with the metrics panel : OK
D. Long Prediction tags doesn't respect margin-right : OK

I was not be able to find [a_lot_of_labels_multi-label] to review.

2 things discovered:

- [x] 1024: Header dataset list should be optimized like the rules table (SS) + "Workspace" is moving on hover (video)
- [x] General: Spaces between title and related modal is not standard, should be 10 px. (SS) Review it on dataset list template + all mode



<img width="945" alt="Captura de pantalla 2022-04-25 a las 22 29 10" src="https://user-images.githubusercontent.com/84135211/165171934-d85c3f3e-43b2-4498-96a1-e30a034d2d51.png">

**Comment by Amelie-V** [comment]
https://user-images.githubusercontent.com/84135211/165172812-4abe74e6-c0b8-4a44-9bfc-42ce858f08ed.mov

**Comment by Amelie-V** [comment]
<img width="871" alt="Captura de pantalla 2022-04-25 a las 22 56 56" src="https://user-images.githubusercontent.com/84135211/165174164-7c431c83-d58f-4078-bc28-528cc2300295.png">
