### ISSUE TITLE
[docs] Replace majority vote example with our own implementation

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1421]
We need to use our MajorityVote model here https://rubrix.readthedocs.io/en/stable/guides/weak-supervision.html#4.-Using-the-weak-labels and likely simplify this part a little bit (metrics computation, etc.)

**Comment by dcfidalgo** [comment]
I remember we added this Majority vote section mainly to show how to use the `WeakLabels` object with "vanilla Snorkel". If we replace this with our own implementation, should we add another example? There is a short example in the `WeakLabels` docstring, not sure if this is enough.

**Comment by dvsrepo** [comment]
Yes, you are right. I'd prefer to use our majority vote anyway and lose that "vanilla Snorkel" example
