### ISSUE TITLE
[Datasets] Allow configuring datasets with a predefined label schema

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1432]
The idea here is to create datasets with a labels schema.

With this new feature, users can create or update datasets with a set of labels to simplify the annotation process.

**Comment by frascuchon** [comment]
_My proposal:_

The labels schema management will be addressed in the python client library for the very first version, as part of general dataset settings management.

```python
import rubrix as rb
from rubrix.settings import TextClassificationSettings as Settings

settings = Settings(labels_schema=["A","B","C"]) 
# If dataset does not exists yet, the following line will create an empty
# dataset with provided settings.
rb.settings.save_settings(name="my-dataset", settings=settings)
```

The same function `rb.settings.save_settings` will be used for updating the schema.

When the labels schema is updated, some checks will be applied (for example, dropping a label that already exists as annotation) in order to preserve the dataset integrity

This schema will provide an initial set of labels for annotation, but labels on existing records (prediction/annotation) will be also available for that purpose.

**Comment by dvsrepo** [comment]
> _My proposal:_
> 
> The labels schema management will be addressed in the python client library for the very first version, as part of general dataset settings management.
> 
> ```python
> import rubrix as rb
> from rubrix.settings import TextClassificationSettings as Settings
> 
> settings = Settings(labels_schema=["A","B","C"]) 
> # If dataset does not exists yet, the following line will create an empty
> # dataset with provided settings.
> rb.settings.save_settings(name="my-dataset", settings=settings)
> ```
> 
> The same function `rb.settings.save_settings` will be used for updating the schema.
> 
> When the labels schema is updated, some checks will be applied (for example, dropping a label that already exists as annotation) in order to preserve the dataset integrity
> 
> This schema will provide an initial set of labels for annotation, but labels on existing records (prediction/annotation) will be also available for that purpose.

It's looking good. We should inform the user that a dataset has been created if that's the case, to avoid confusion if there are misspellings in the name.

**Comment by dcfidalgo** [comment]
Not sure if you discussed this issue/feature in more detail, but I thought maybe it would be convenient to connect these settings with the `rb.Dataset*` classes? At the moment they only accept one argument (the records), but they could accept also some arguments regarding the settings, something like this:
```python
dataset_rb = rb.DatasetForTextClassification(
    my_records,
    label_schema=["A", "B", "C"]
)
rb.log(dataset_rb, "my_dataset")
``` 
One could also create an empty dataset:
```python
dataset_rb = rb.DatasetForTextClassification(
    label_schema=["A", "B", "C"]
)
rb.log(dataset_rb, "my_dataset")
``` 
Not sure about updating the settings of an existing dataset through this API, though. Maybe a dedicated method for this would be nicer.

**Comment by frascuchon** [comment]
We think about the definition of a more general settings configuration. 

Those settings could include other dataset aspects such as, which users can annotate, or if labels can be extended from UI. 

As a shortcut could be nice to include some of the settings directly to the `rb.DatasetFor*` classes on dataset creation, but maybe should be done in future work, when settings and workflows use the `rb.DatasetFor*` are better defined.

I do not fully agree to log an empty dataset just to create the settings, but  I'm not too convinced either with the `rb.save_settings` alternative

**Comment by frascuchon** [comment]
thinking a bit more about the client API, I think we should separate data-related and management-related functions.

For me, `rb.log` and `rb.load` are two clear data-related actions.

The dataset creation, configuration, list, and even `rb.delete` should be related to dataset management, and maybe should be considered as a different set of functions.

In that way, the `rb.DatasetFor*` are abstractions for data-related operations and, from my point of view, should not include management operations.

What a `rb.list_datasets` should return? a list of `rb.DatasetFor*`? what if the consumer of `rb.list_dataset` just want to fine-tune some settings? Should download the datasets with their data?

I think we should discuss that and find a better integration for this new feature.

cc @dvsrepo @dcfidalgo

**Comment by frascuchon** [comment]
Open questions about the labels schema implications:

- What happens with prediction/annotation labels and the labels schema? Should be reflected in the schema if is not yet defined?  Or the labels schema should be used to validate the prediction/annotation integrity?
- Dropping a label from the labels schema, should raise any validation error if the dataset already contains annotated records with the label?
- After a `rb.log` including records with predictions/annotations, the labels schema should be updated?

cc @dcfidalgo @dvsrepo

**Comment by dcfidalgo** [comment]
I think from the server-side it would be fine to only accept labels that are defined in the schema.
In the client I would do some hybrid for the `rb.log` method:
- If `rb.log` creates a new dataset, figure out the label schema automatically by looking at the provided records and send it to the server first, then the records.
- If `rb.log` tries to add data to a dataset, raise an Exception if the provided annotations/predictions do not match the schema, and tell the user to update the schema first.

> Dropping a label from the labels schema, should raise any validation error if the dataset already contains annotated records with the label?

I would print a warning instead of raising an exception. I think sometimes you know that you have annotations of a specific label but still want to get rid of it. Or maybe have two ways, a "safe" way, and a "amok" way.
