### ISSUE TITLE
[Dropdown height limitation] - Improve access to actions : Filter/Sort/Cancel/remove

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1435]
**Describe the bug**
Sometimes, especially with metadata dropdown list are very long and it's complicated to access to button action.

**To Reproduce**
1. Go to 'metadata filter'
2. Click on 'Select option into a metadata' at the bottom of your screen
3. Scroll down to access to Filter/cancel ....
4. See how it's long to access

**Expected behavior**
Avoid very long scroll to access to main actions.

- Dropdown level 2 Limit value number to 6 at first sight and then active scroll. 
- Dropdown level 1 Limit height to 70% screen size (approx)

eg:
First level: Metadata list
Second level: Option list for each metadata

- Fix action at the modal bottom: Filter/Sort/Cancel/remove all filters/_Only records not covered by rules_ checkbox

**Screenshots**
Video and SS

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Rubrix Version [e.g. 0.10.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:  

**Additional context**

**Comment by Amelie-V** [comment]
related to #1409

**Comment by Amelie-V** [comment]
https://user-images.githubusercontent.com/84135211/168238869-66331b01-4c1b-4160-b1f7-03354b57f816.mov

**Comment by Amelie-V** [comment]
QA 

- [x] Fix action at the modal bottom: Filter/Sort/Cancel/remove all filters/Only records not covered by rules checkbox
This point should also include modal with scroll. In metadata "remove all filters" bt. should be visible without scrolling.

- [x] Modal with scroll: when the user scroll up and down with an open dropdown, It should close itself as a cancel action.

- [ ] Asking for an enhancement: How much it could be interesting to show sort values selected in a "disabled" state to avoid duplicate sort selection?

**Comment by Amelie-V** [comment]
<img width="522" alt="Captura de pantalla 2022-05-19 a las 19 35 32" src="https://user-images.githubusercontent.com/84135211/169362670-2d94ac80-71cc-43fb-a125-4b4f4ee781b2.png">

**Comment by leiyre** [comment]
> * [ ]  Asking for an enhancement: How much it could be interesting to show sort values selected in a "disabled" state to avoid duplicate sort selection?

except for the metadata fields the rest are removed from the list of options when selected, I have applied the same behavior for metadata. We can discuss if it is better to remove or disable it.
