### ISSUE TITLE
Basics In Docs

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1445]

**Comment by Amelie-V** [comment]
Quick notes:
Getting started/ V1.0

How to upload ds
How to annotate
How to train model

Treat main Actions separately
eg:
1. Upload data

- Classifier
- NER
Add records (use Pandas, Use Dataset...)

Dani Notebook:
https://github.com/recognai/pln_con_rubrix/blob/main/somospln_hackathon/etiquetado_pln.ipynb

**Comment by dcfidalgo** [comment]
TOC:

1.  How to upload datasets
Fill in the structure

2.  How to annotate datasets

-    Text classification

     - Manual annotation
     - Rules in UI
     - Weak supervision with Python

-    Token classification

     - Manual annotation

-    Text2text

     - Manual annotation




3.  How to add model predictions


To continue
  - For text classification
- How to generate training data
- How to train a model
- How to review a training datasets/upload data with annotation
    - Via the client when uploading a dataset 

Things to think about:

- How to transform offsets to tags for token classification datasets)

**Comment by Amelie-V** [comment]
### General feedback

- Do not use majuscule in the doc
- Describe each step in detail: the aim is to explain how to start with Rubrix to beginners.
- In general try to do not multiply the examples of dataset. 
- Explain clearly the two methods to interact with DS from Python: Log and load

**Comment by dcfidalgo** [comment]
I wrote a proposal for the "How to annotate datasets" section, that tries to present the different approaches with their pros and cons, and defers the step-by-step part to our feature references. I feel this adds much more value to the docs and surfaces information that is already available. It is still a work in progress, y como siempre, comments are highly appreciated.

https://docs.google.com/document/d/1dUqaFE-eML_myzOHVvDaR8U4WugWU7kVMpxZsRWNgxE/edit?usp=sharing
