### ISSUE TITLE
[Tutorial gallery] Put tutorials in a gallery

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1456]
The main idea here is to create sections for our tutorials and maybe use the sphinx-gallery plugin for that.

**Comment by Amelie-V** [comment]
- [ ] Find a tutorial illustration concept

 Inspiration
  -  https://streamlit.io/gallery
  - https://stripe.com/docs/payments

- [ ] Adapt CSS styles

**Comment by Amelie-V** [comment]
This is the information architecture that I suggest implementing in the tutorials' gallery.

### General
- A page per category eg: "Pre annotate" with a color code (this option will allow in the future to add more filters to tutorials (technicity, popularity...)
- An extract per tutorial containing: UI Screenshot (discuss the possibility to automatically crop the first screenshot), tutorial title, emoji, and short Intro (the intro should be the very beginning tutorial)

### Menu
- Show only 2 contents levels: tuto category and tuto title

List of categories to discuss:
- Introductory
- Pre annotate
- Weak supervision
- Active learning
- Label errors
- Monitoring

**Comment by Amelie-V** [comment]
![DOCU TUTO](https://user-images.githubusercontent.com/84135211/169019719-623db884-323d-40aa-b4b1-8592f948880e.png)

**Comment by dcfidalgo** [comment]
I can tackle:
- [x] page per category layout
- [ ] provide tooltip with a short intro to the tutorial

Not sure how to use the screenshot as thumbnail, I need to have a closer look into this.

**Comment by dcfidalgo** [comment]
Arg, this plugin together wth nbsphinx is really not flexible ... I cannot create thumbnails from markdown cells, if i do not use the cell metadata to define a thumbnail, i cannot create the tooltip, if I hide the cell from the build, i cannot use it as thumbnail ... 
Not sure how to proceed here, maybe we should look into the possibility of adding some custom javascript to create the gallery.

**Comment by Amelie-V** [comment]
I was thinking to invite @leiyre to evaluate the work to do to custom the plugin but definitely, there is a UI job to do. And I'm quite sure we'll need javascript to generate the thumbnail. 
@dcfidalgo What do you mean by "tooltip"?

**Comment by dcfidalgo** [comment]
When using the plugin, you can configure a tooltip for the thumbnails, and I thought that maybe one could use those tooltips to turn them into the short abstracts that you see in your proposal.

**Comment by Amelie-V** [comment]
QA:

General
- [x] Review padding in the right menu between navigation levels
- [x] Extend central colum
- [x] reduce right menu column


Gallery
- [x] Include 12 colors set
- [x] Change bullet style
- [x] Increase intro tutorial font size
- [x] Increase thumbnail size
