### ISSUE TITLE
Table word splitting 

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1460]
Justified text* with hyphenation. (weak supervi-sion) to improve words breaking onto a new line:

- In the table's columns
- In metrics
- In filters dropdown (in/outside of tables)

* Labels, Tags, Tokens

**Comment by Amelie-V** [comment]
<img width="558" alt="Captura de pantalla 2022-05-05 a las 10 43 57" src="https://user-images.githubusercontent.com/84135211/166890121-04419539-2096-4e13-8367-241c258ab83b.png">

**Comment by Amelie-V** [comment]
<img width="1031" alt="Captura de pantalla 2022-05-05 a las 10 46 40" src="https://user-images.githubusercontent.com/84135211/166890231-d840d716-b897-4ec9-8def-89b23e9dbefb.png">

**Comment by Amelie-V** [comment]
<img width="987" alt="Captura de pantalla 2022-05-05 a las 10 47 47" src="https://user-images.githubusercontent.com/84135211/166890400-59d182b6-5eea-4d8e-876c-c257f47ef70b.png">

**Comment by Amelie-V** [comment]
Another option @dcfidalgo @frascuchon @dvsrepo could be: do not allow word breaking and jump the full word to the next line. In that option the negative thing is to increase too much the height of the table line.

**Comment by Amelie-V** [comment]
<img width="298" alt="Captura de pantalla 2022-05-05 a las 10 56 55" src="https://user-images.githubusercontent.com/84135211/166893995-70ea562b-5b5b-43f1-8122-57174ea70345.png">
<img width="290" alt="Captura de pantalla 2022-05-05 a las 10 55 38" src="https://user-images.githubusercontent.com/84135211/166894013-67f0e742-d7cc-4913-9429-04e0956ca30e.png">

**Comment by Amelie-V** [comment]
QA:

It miss the "-" on word breaking in rules table : ksdckdsj.Watertechnolo-gy

In the dropdown the "-" is visible. It should be visible in any places

**Comment by Amelie-V** [comment]
<img width="266" alt="Captura de pantalla 2022-05-18 a las 15 54 35" src="https://user-images.githubusercontent.com/84135211/169058612-167e374e-eddf-4bcd-9461-8115c0cb73fd.png">
<img width="505" alt="Captura de pantalla 2022-05-18 a las 15 53 52" src="https://user-images.githubusercontent.com/84135211/169058651-66ad291c-8dbb-48c9-9a69-0f07ccecc5bb.png">

**Comment by leiyre** [comment]
> QA:
> 
> It miss the "-" on word breaking in rules table : ksdckdsj.Watertechnolo-gy
> 
> In the dropdown the "-" is visible. It should be visible in any places
> 

In this case the css hyphen property doesn't interpret that the word can be split, the "-" has an automatic logic and it is not possible to force it for some cases.
