### ISSUE TITLE
ValidationError When Logging Data

### ISSUE THREAD

**Issue by firqaaa** [recognai/rubrix#1481]
When i try to run this code : 

```
import rubrix as rb

rb.log(
    rb.TextClassificationRecord(text="My first Rubrix example"),
    name="weak_supervision_job_titles"
)

```
I face the following error. It says : 

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17152/3159988794.py in <module>
      2 
      3 rb.log(
----> 4     rb.TextClassificationRecord(text="My first Rubrix example"),
      5     name="weak_supervision_job_titles"
      6 )

D:\Anaconda\envs\torchflow\lib\site-packages\pydantic\main.cp37-win_amd64.pyd in pydantic.main.BaseModel.__init__()

ValidationError: 2 validation errors for TextClassificationRecord
inputs
  field required (type=value_error.missing)
text
  extra fields not permitted (type=value_error.extra)

What should i do?

**Comment by dcfidalgo** [comment]
Hi @firqaaa , thanks for reporting. I suspect you are using an older version of Rubrix. Could you try to install a newer version with `pip install -U "rubrix[server]"` or, if you are using docker-compose, with `docker-compose pull`?

**Comment by frascuchon** [comment]
I will close the issue. Please, feel free to reopen it if you need to include some extra info
