### ISSUE TITLE
Select path for opensearch ca

### ISSUE THREAD

**Issue by zelanastasia** [recognai/rubrix#1494]
I'm trying to deploy rubrix in k8s and connect with external ES instance. Connection should be secure, but i got error

`opensearchpy.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091))`

This is because with opensearchpy you should select path in parametr `ca_certs` with `OpenSearch` function. Reference: https://opensearch.org/docs/latest/clients/python/#sample-code

It would be great if you add `ca_cert_path` variable to rubrix. #1495

**Comment by frascuchon** [comment]
Hi @zelanastasia and thanks for using Rubrix.

I've seen also your PR, thanks a lot! But, first of all, I would like to better understand why you're getting that error. 

If you have a valid certificate configured to connect to your elasticsearch instance, this extra configuration should not be needed. If I'm not wrong, you're trying to connect to an es instance using the secured `HTTPS` protocol, but the certificate is not valid for the domain you're using. It's that right?

Did you try to disable the client SSL verification? You can use the `RUBRIX_ELASTICSEARCH_SSL_VERIFY=False` configuration for that.

Anyway, I will review your PR.

Thanks!
