### ISSUE TITLE
Active learning with Hugging Face Neural Networks  tutorial

### ISSUE THREAD

**Issue by PrasanthiDesiraju** [recognai/rubrix#1496]
Can you please help with available options apart from integrating with Scikit learn for Active Learning? Please point to any documentation for model options to achieve active learning and check how can we integrate HuggingFace or Tensor models for the training.

#Active Learning #HuggingFace #documentation #helpwanted

**Comment by frascuchon** [comment]
Hi, @PrasanthiDesiraju, and thanks for reaching out

You can follow [this discussion](https://github.com/recognai/rubrix/discussions/1398). @chschroeder is working on a tutorial using Rubrix with [small-text](https://github.com/webis-de/small-text) python lib.

Also, you could take a look at the [WIP demo app](https://github.com/chschroeder/active-learning-with-rubrix-test) and the [small-text examples](https://github.com/webis-de/small-text/tree/master/examples)

**Comment by PrasanthiDesiraju** [comment]
Thanks for the response.. It's helpful ! Hopefully, the feature comes out in the latest versions of Rubrix, kudos to all the amazing work and creating such an easy environment!
