### ISSUE TITLE
Error: The number of nested documents has exceeded the allowed limit of [10000]

### ISSUE THREAD

**Issue by coreyelowsky** [recognai/rubrix#1499]
Below is the error I get when trying to log a TokenClassificationRecord with a fairly large piece of text (>30000 characters) and some predictions. I have tried sending a PUT request to the elasticsearch docker container to update the index.mapping.nested_objects.limit, and It seems that Im able to successfully send the request. However, when trying to log the record I receive the same error that the limit is 10000, as opposed to the new limit that I sent in the put request.

**ERROR**

opensearchpy.helpers.errors.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': '.rubrix.dataset.coreyelowsky.test.records-v0', '_type': '_doc', '_id': '2091e6a3-2daa-4f5b-8677-1adbe2254fd6', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'The number of nested documents has exceeded the allowed limit of [10000]. This limit can be set by changing the [index.mapping.nested_objects.limit] index level setting.'},

**Comment by frascuchon** [comment]
Hi @coreyelowsky and thanks for your feedback

Did you check if the index settings were updated? 

````bash
GET .rubrix.dataset.coreyelowsky.test.records-v0/_settings
````

Did you launch the update as follows?:
````bash
PUT .rubrix.dataset.coreyelowsky.test.records-v0/_settings
{
  "index": {
    "mapping": {
      "nested_objects": {
        "limit": "30000"
      }
    }
  }
}
````

Which versions of elasticsearch and Rubrix are you using?

Thanks!

**Comment by frascuchon** [comment]
Hi, @coreyelowsky

Were you able to check this?

I've done several tests and cannot reproduce your problem. I always allow keeping the customized configuration when logging the records.

**Comment by frascuchon** [comment]
Closing this issue since cannot reproduce. Please, @coreyelowsky, feel free to reopen if you consider.

**Comment by frascuchon** [comment]
This problem is related to token-level metrics. We should let users warn about these metrics and allow them to enable/disable them.

**Comment by walter-hernandez** [comment]
For anyone experiencing the issue, the solution that I found for the Docker Compose version of Argilla was to execute:

```bash
curl -X PUT "http://localhost:9200/_all/_settings?preserve_existing=true" -H "Content-Type: application/json" -d '
{
  "index": {
    "mapping": {
      "nested_objects": {
        "limit": "500000"
      }
    }
  }
}'
```

where you just update the limit to your needs

**Comment by nataliaElv** [comment]
@frascuchon Is this issue relevant for 2.0?

**Comment by frascuchon** [comment]
We should review elasticsearch fine-tuning setup but as a separate work. So we can close it for now.
