### ISSUE TITLE
Password encryption method

### ISSUE THREAD

**Issue by zelanastasia** [recognai/rubrix#1501]
I've noticed that in your documentation not indicated that password should be encrypted in bcrypt.

In your doc indicated this command:
https://github.com/recognai/rubrix/blob/master/docs/getting_started/user-management.ipynb?short_path=8a69e9b#L112

Despite the fact that you double use small `b` flag, in fact it should be `B` ( that means bcrypt encryption flag)
```
➜  ~ htpasswd --help
...
 -b  Use the password from the command line rather than prompting for it.
 -B  Force bcrypt encryption of the password (very secure).
```

At first time, i just copied command for htpasswd and i catch error `hash could not be identified`

It would be great if you specify in docs encryption method. Thanks.

**Comment by frascuchon** [comment]
Hi @zelanastasia 

Yes, you're right. At some point in time, the docs were changed by mistake.

**Comment by frascuchon** [comment]
@dcfidalgo could you tackle this?

There are quite changes on this commit applying a random lowercase and it should be nice to review them in more detail.
