### ISSUE TITLE
"Predicted as" filter activates highlighting of words

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1533]
**Describe the bug**
When activating the *Predicted as* filter, words that match the predicted as value, seem to be highlighted.

**To Reproduce**
1. Go to the `score_filter_bug` dataset in our dev env
2. Select `palestine`, for example, in the "Predictions -> Predicted as" filter

**Expected behavior**
Only search terms should be highlighted in my understanding.

**Screenshots**
![Screenshot from 2022-06-02 17-45-27](https://user-images.githubusercontent.com/15979778/171670500-792f2090-30c9-40dc-9a5b-262a292db3a0.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: ubuntu 20.04
 - Browser [e.g. chrome, safari]: firefox/chrome
 - Rubrix Version [e.g. 0.10.0]: dev env
 - ElasticSearch Version [e.g. 7.10.2]: dev env
 - Docker Image (optional) [e.g. rubrix:v0.10.0]: dev env

**Additional context**

**Comment by dcfidalgo** [comment]
CC @leiyre @frascuchon

**Comment by Amelie-V** [comment]
@leiyre 
I filtered by "Palestine", then I did a search for "Palestine", so it shows me the word in pink (its okay). Then I removed the search "Palestine", and changed it for "third" and it still underlined "Palestine".

**Comment by Amelie-V** [comment]
<img width="1130" alt="Captura de pantalla 2022-06-07 a las 12 27 29" src="https://user-images.githubusercontent.com/84135211/172358862-918df107-cbba-4f27-89fd-73265d5744ce.png">

**Comment by dcfidalgo** [comment]
+1 I can reproduce it in our release env
