### ISSUE TITLE
[Bulk Annotations] Apply bulk annotation to more than 20 records (max page size)

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1578]
**Is your feature request related to a problem? Please describe.**
[Cpoied from Slack] When annotating examples in a dataset, if you find a pattern bringing a lot of data (say 1000 results) and you want to annotate for all of those in batch mode a particular label, you need to proceed page by page. The max page size is 20 records, it would mean repeating the action 50 times. Users said that they would be happy to have something higher like 100.

**Describe the solution you'd like**
Users said that they would be happy to have something higher like 100.

**Describe alternatives you've considered**
Maybe add an option for applying the bulk action to all the records of the query.

**Additional context**

**Comment by dcfidalgo** [comment]
Feedback by José from datamaran.
CC @frascuchon @leiyre @Amelie-V

**Comment by Amelie-V** [comment]
Record per pages options:
1, 10, 20, 50, 100
