### ISSUE TITLE
Annotation, pagination, and status default actived inconsistency

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1597]
**Describe the bug**

When changing the page (by clicking on pagination) after doing a bulk annotation with the status filter activated, the next page does not load records.

**To Reproduce**

1. Go to 'Annotation mode'
2. Active status filter
3. Annotate a record batch 
4. Change to the next page (from pagination: page number or Next)

" If I am selecting all the articles by running a query, I can annotate the first page but on the second page there will be 0 articles and again I have to refresh the page in order to get all the articles annotated."

**Expected behavior**

Should be able to visualize the next records

**Screenshots**

View video link

**Environment (please complete the following information):**

 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Rubrix Version [e.g. 0.14.2.]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:  

**Additional context**

**Comment by Amelie-V** [comment]
https://rubrixworkspace.slack.com/files/U02UFKPB4GN/F03MW8CAWSY/13-31-55.mp4

**Comment by frascuchon** [comment]
Duplicated in #1621
