### ISSUE TITLE
[rubrix.log] Deprecate 'metadata' argument

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1605]
Our server dataset model has a `metadata` field that we do not use in the client or the UI. It is exposed in the `rubrix.log` method which does not make sense, we will deprecate it for now.

**Comment by frascuchon** [comment]
Not sure if this issue is really a bug. For me, has more sense as a maintenance or client API refactoring action, since does not solve any broken functionality. Just avoid exposing fields that we're not showing yet.

However, the HTTP API consumers could retrieve the info sent in metadata.
