### ISSUE TITLE
Spacing friendships - Improve record card visibility

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1624]
**Is your feature request related to a problem? Please describe.**

We are currently improving our space system in Figma and we'll implement it in various batches. 
This issue aim to adapt spaces to improve the records cards visualisation

**Describe the solution you'd like**

https://uxdesign.cc/ui-cheat-sheet-spacing-friendships-e37a6fccc407

Apply the 8 magic number and spacing friendship concept
8px: between cards
16px: between global action bar and record card
32px: around search box

**Describe alternatives you've considered**
-

**Additional context**

**Comment by Amelie-V** [comment]
<img width="1427" alt="Captura de pantalla 2022-07-20 a las 12 06 57" src="https://user-images.githubusercontent.com/84135211/179958011-87b7b80a-4dbf-4803-9c3b-73b43b8f60a1.png">
<img width="696" alt="Captura de pantalla 2022-07-20 a las 11 55 58" src="https://user-images.githubusercontent.com/84135211/179958035-56bfa19c-90ce-4828-9688-1935dd1f1458.png">

**Comment by frascuchon** [comment]
We must take into account the number of visible records after the spacing. It should be nice to find a trade-off between record visibility and batch revision/annotation.

Anyway, this is just a comment.
