### ISSUE TITLE
[Conda] `listener` not available

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1634]
I wanted to include the listener dependencies to the conda "rubrix" package, but the new dependency `prodict` is unavailable at conda-forge. So either we help the maintainer of prodict to publish the package in conda-forge, or we could try to replace this dependency (maybe a `NamedTuple`?). @frascuchon

**Comment by frascuchon** [comment]
Could work NamedTuple for nested objects? 

The metrics object can contain nested values. We should parse and convert it into NamedTuples objects the whole metrics info. Let's see the code
