### ISSUE TITLE
Updating docs using prepare_for_training with transformers to include the framework parameter

### ISSUE THREAD

**Issue by ignacioct** [recognai/rubrix#1641]
Should we update the `prepare_for_training` method in the cookbook (and potentially in other places, I don't know if it's used in any other guide or tutorial) to specify the parameter `framework="transformers"`, even if it's the default option? It could be interesting to promote this explicit declaration to show that they are other frameworks?

I can take care of it if you give me green light :)

**Comment by dvsrepo** [comment]
Sorry that I missed this! This is definitely a good idea!

**Comment by ignacioct** [comment]
Hi there! I think we forgot to close this issue, because I remember taking it into consideration. However, I cannot find the cookbook anymore, maybe you changed its name or structure when migrating from Rubrix to Argilla. If that piece of text is in any other documentation file I can have a look and confirm that I include it :)

Good morning to all, friends!
