### ISSUE TITLE
Allow disabling the Word Cloud Metric

### ISSUE THREAD

**Issue by maxserras** [recognai/rubrix#1644]
When dealing with large datasets, the elasticsearch shards often fail to compute the word_cloud metric:

rubrix-1  | Cannot compute metric [words_cloud]. Error: TransportError(500, 'search_phase_execution_exception', 'cancelled')

As I might understand that in small datasets these frequent tokens might be somehow related to keywords, when having big datasets (+300k samples) these tokens are no longer related to keywords and the computational effort to extract this word_cloud metric causes ES to fail, degrading the performance of the solution.

Proposed solution:

Allow enabling/disabling these default metrics in the Dataset settings class

Discarded Alternatives:
- Use environmental variables (Discarded because it is not scalable to other metrics, single setup for all the databases)
- Set a limit of samples to automatically disable this metric (Against python conventions, explicit is better than implicit)

**Comment by frascuchon** [comment]
Thanks for reporting, @maxserras. Yes. We need to integrate the UI with the metrics API to improve the flow. But enabling/disabling the dataset metrics by configuration is a great idea.

**Comment by frascuchon** [comment]
Issue moved to [recognai/rubrix-roadmap #82](https://github.com/recognai/rubrix-roadmap/issues/82) via [**ZenHub**](https://www.zenhub.com/)
