### ISSUE TITLE
add specific host and port to launch ui when use rb.log

### ISSUE THREAD

**Issue by batman-do** [recognai/rubrix#1676]
`import rubrix as rb`
`rb.init(api_url="http://172.26.33.174:5555",)`

- When i create rb.init above appear erorr : [Errno 111] Connection refused
how to rb,init with specific host and port 
- I can't run rubix on google colab

**Comment by frascuchon** [comment]
Hi @Dean98AI and thanks for reporting.

Is there a rubrix instance running on that location? Before you connect the server using the `rb.init`, you should run the server instance using the `python -m rubrix` command.  You can follow the setup documentation https://rubrix.readthedocs.io/en/stable/getting_started/setup%26installation.html
