### ISSUE TITLE
`prepare_for_training` method should fail if no training data is available

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1697]
**Describe the bug**

**To Reproduce**
1. Log some records without annotation info into Rubrix
2. Load and apply a training transformation using `prepare_for_training`.

An empty dataset is created.

**Expected behavior**
An error should be raised when no training data is available since nothing can be done for those cases.

**Screenshots**
![Screenshot from 2022-08-24 09-36-45](https://user-images.githubusercontent.com/2518789/186620108-03fec577-7b02-49ba-81fe-b8774da8ebcd.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Rubrix Version [e.g. 0.10.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:  

**Additional context**

**Comment by iakhil** [comment]
I'd like to work on this.

**Comment by dvsrepo** [comment]
Hi @iakhil that's great to hear!

Feel free to ask questions!

**Comment by davidberenstein1957** [comment]
@ufukhurriyetoglu maybe this aligns with this https://github.com/argilla-io/argilla/issues/1821?

**Comment by ufukhurriyetoglu** [comment]
yes, similar case to handle. @davidberenstein1957

**Comment by davidberenstein1957** [comment]
@frascuchon Shall I add this to the 1.2.0 too? And @ufukhurriyetoglu will you be able to do it in terms of time allocation?

**Comment by frascuchon** [comment]
We will keep it in the 1.2.0 backlog. If we have time, we will tackle it for the next release.

The idea should align both messages since they have similar nature.
