### ISSUE TITLE
Collaborate and user management on azure instance

### ISSUE THREAD

**Issue by amulyahwr** [recognai/rubrix#1730]
Thank you for the excellent library. I was wondering if there are any steps to follow where I can share the data annotation project (deployed on azure instance) with my team members for collaboration?
I have:
1. Azure instance.
2. Deployed Rubrix on the azure instance.
3. Following [User management](https://docs.rubrix.ml/en/stable/getting_started/user-management.html), I have: .users.yaml and docker-compose.yaml.
4. I use command: "docker compose up" to start the services: rubrix, elasticsearch and kibana
5. After debugging, I figured out that I am receiving the following error when rubrix service starts: ConnectionRefusedError: [Errno 111] Connection refused.
6. Below is the docker-compose.yaml file, I am using:

version: "3"
services:
  rubrix:
    image: recognai/rubrix:latest
    restart: unless-stopped
    ports:
      - "6900:80"
    environment:
      ELASTICSEARCH: http://elasticsearch:9200
      RUBRIX_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
    volumes:
      - ${PWD}/.users.yaml:/config/.users.yaml
    networks:
      - rubrix
      
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-rubrix-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - rubrix
    volumes:
      - elasticdata:<azure_dir_path>

kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - rubrix

networks:
  rubrix:
    driver: bridge

volumes:
  elasticdata:

**Questions:**

1. Do I have to configure my azure instance to resolve the connection error?
2. I do port forwarding to access rubrix app on the browser on my local machine. I can access kibana (port 5601) and rubrix (port: 6900). But when I try to login with user details defined in .users.yaml, I receive invalid authentication error. How to resolve this error?

Thank you.

**Comment by frascuchon** [comment]
Hi @amulyahwr and really sorry for the late response.

Not sure about the problem in (1): Do you mean that the Rubrix service is running but you cannot access it from the browser or it's failing on start because of a ConnectionError issue?

For (2) Can you check login with the default credentials? If you can log in it mean that the `users.yaml` configuration is not used. In that case, you must be sure to mount the file from the azure machine instance where you're running the docker-compose command. The `${PWD}/.users.yaml` path should be valid in your azure instance.
