### ISSUE TITLE
[UI] Update theme

### ISSUE THREAD

**Issue by leiyre** [recognai/rubrix#1732]
- [x] Include "Inter" font
- [x] Logo and icon
- [x] Greyscale fonts
- [x] replace colors
- [x] Open explanation help info in modal
- [x] Place the records loading animation bar at the bottom of topbar

**Comment by leiyre** [comment]
- [x] blue shadow to grey
- [x] Attribute "secondary light"button style d ti "show less" in entity legend block
- [x] Attribute "Primary light" bt style to "Manage rules" button

Text2text
- [x]  Change small slider color arrow style 1of 2 (remove "prediction")
- [x] Maintain right and left arrow with disabled state when there is no results

Filters

- [x] Sort by button: Add hover style
- [x] X to close filters: add opacity on hover

- [x] Disable correct/incorrect icon  in predicted records

Font size:

Into metrics panel (weak supervision) and in the right sidebar there are too much font variety.

- [x]  Reduce number of weight 

- [x] - Simplify list (weight/size font)

**Comment by Amelie-V** [comment]
QA/fine tuning

- [x] Use crayola color for the first line loader (still in black)
Weak labeling:
- [x] Manage rules layout : Leave the light BG 
- [x] Remove bold weight on "Introduce a query" to define a rule. (To keep it simple)
- [x] We should completely remove "new query" text. Now we had the labels visible, this text bring more confusion than help since my opinion.

**Comment by Amelie-V** [comment]
<img width="967" alt="Captura de pantalla 2022-09-30 a las 12 24 32" src="https://user-images.githubusercontent.com/84135211/193251777-ce37cd5f-0c2b-41e9-bb26-4439db81bd06.png">
<img width="1439" alt="Captura de pantalla 2022-09-30 a las 12 24 02" src="https://user-images.githubusercontent.com/84135211/193251780-6a1092ac-6255-4b20-bb38-e3551ad0b9c6.png">

**Comment by Amelie-V** [comment]
- [x] Correct space between mains button in NER record cards (it's double now)
- [x] Invert order button in Text2text button in records card
- [x] Decide the right rule to place primary and secondary button
- [x] Review login BG (I'll pass you material)

**Comment by frascuchon** [comment]
When could be finished this task? Tomorrow was planned to create a functional public branch in the rubrix repo with all this content.



cc @leiyre @Amelie-V?

**Comment by leiyre** [comment]
@frascuchon I will finish today morning

**Comment by Amelie-V** [comment]
QA Login

- [x] Correct position of the white text (should not be centered on the shape)
- [x] Review new copy from Figma 
- [x] Add mention to Slack on the right side to don't disturb the login process
- [x] Error gestion: change copy to :  Wrong username or password. Try again. in red
- [x] Reduce 40 px the input field and bt
