### ISSUE TITLE
Client: WeakList in Text Classification

### ISSUE THREAD

**Issue by keithCuniah** [recognai/rubrix#1758]
**Describe the bug**
Sometimes, a chevron ">" is insert after the highlight query result

**To Reproduce**
1. Go to the a dataset with task as TextClassificaiton :  Dataset>sst2_with_explanations 
2. Select in the search query "a*"
3. Scroll down to result
4. See error as  sometimes you can see a highlight resul as "a' or ">a".

**Expected behavior**
The result should be without chevron 

**Screenshots**
![image](https://user-images.githubusercontent.com/88380932/194878082-52857dd7-a908-4b09-ac79-d472e9acf67d.png)
or 
![image](https://user-images.githubusercontent.com/88380932/194879863-8458ffd0-8f96-48aa-8a21-970d350606fc.png)

**Environment (please complete the following information):**
 - Windows:
 - Browser Chrome:
 - Rubrix Version Dev:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:

**Additional context**
The problem is maybe in the component RecordExplain.vue at method explainFormatted()

**Comment by frascuchon** [comment]
Thanks, @keithCuniah  for reporting,

@leiyre I've checked the search response output and it's ok. I can imagine xthat is a problem with the UI highlighting.

<img width="280" alt="Screenshot 2022-10-10 at 18 33 28" src="https://user-images.githubusercontent.com/2518789/194913625-d0961a2b-b445-4f67-86d0-c765ab611269.png">
