### ISSUE TITLE
[Configuration] Allow configure max length for metadata fields 

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1761]
Instead of fixed 128 value, it would be nice to provide a max value (for server) by environment var. See also recognai/rubrix#1276

**Comment by frascuchon** [comment]
See recognai/rubrix#1276

**Comment by frascuchon** [comment]
@davidberenstein1957 @dvsrepo I think this could be this a good first issue...

**Comment by davidberenstein1957** [comment]
I agree.

**Comment by frascuchon** [comment]
The `MAX_KEYWORD_LENGTH` is used by the client to inform users when fields will be truncated. (see [here](https://github.com/argilla-io/argilla/blob/develop/src/argilla/client/models.py#L40))

If we plan to configure this parameter as a server environment variable, this client check will be dependent on the connected server and won't be applied

**Comment by shahjaidev** [comment]
Suggestion:
 let the user input any length fields for uploading to the UI (so he can view it during manual labeling) but choose which fields Elastic Search indexes

**Comment by frascuchon** [comment]
That is a great feature that we plan to include as part od the datasets setting one, but is a mid term feature.

Thank for the suggestion. Really appreciate it!!!
