### ISSUE TITLE
Textualize/rich support: rich text and beautiful formatting in the terminal.

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1772]
**Is your feature request related to a problem? Please describe.**
Not directly. 

**Describe the solution you'd like**
I would like to see some good-looking terminal feedback.

**Describe alternatives you've considered**
N.A.

**Additional context**
A think more visual cues in the terminal would improve the readability.
https://github.com/Textualize/rich

**Comment by dvsrepo** [comment]
Closing this in favor of https://github.com/argilla-io/argilla/issues/1843
