### ISSUE TITLE
Difficult to read explanations in UI

### ISSUE THREAD

**Issue by saraesteveznewtral** [recognai/rubrix#1774]
When using shap to understand in which parts of the text the model its putting attention on, the following happens:

![image](https://user-images.githubusercontent.com/102751804/196447625-95298ef1-e79c-4264-8be4-187ba129493a.png)

 As the probabilities of some transformers are heavily located on the extremes (or really close to 0 or to 1), the colours on the shap representation are very dark and it's difficult to read the words inside to make an analysis. Just by changing the intensity of this colours would be enough.

**Comment by leiyre** [comment]
Hi @saraesteveznewtral, there is definitely a reading and usability problem, we will improve it as soon as possible. thank you for reporting
