### ISSUE TITLE
Rename Text2Text to TextGeneration

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1775]
**Is your feature request related to a problem? Please describe.**
Misalignment with docs for Text2Text.

**Describe the solution you'd like**
Create a class TextGeneration that import everything from Text2Text.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by nikhil73533** [comment]
I would like to work on this can you assign me this.

**Comment by davidberenstein1957** [comment]
Hey @nikhil73533 awesome you want to contribute. However, since we want to include this in the release of the coming weekend, I will work on this myself. Would you be willing to contribute a tutorial on TextGeneration instead💪🏽? 
A good example of a tutorial on our website can be found [here](https://rubrix.readthedocs.io/en/stable/tutorials/01-labeling-finetuning.html). And [this](https://github.com/infinitylogesh/mutate) paraphrase generation package could be a cool topic. What do you think?

**Comment by nikhil73533** [comment]
This sound awesome yes i will surely do that

**Comment by davidberenstein1957** [comment]
@nikhil73533  https://github.com/recognai/rubrix/issues/1787

**Comment by frascuchon** [comment]
Fixed in #1783

**Comment by davidberenstein1957** [comment]
@nikhil73533 Do you still want to work on the tutorial? From our side we would really appreciate it😃
