### ISSUE TITLE
More extensive dataset search (sorting, reset filters etc.)

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1776]
**Is your feature request related to a problem? Please describe.**
I selected a lot filters in the search area but only was able to find them when scrolling down the extensive list. 

**Describe the solution you'd like**
Some additional search options like resetting the filters and/or sorts for all column types.

**Describe alternatives you've considered**
Manual scrolling and searching.

**Additional context**
N.A.

**Comment by Amelie-V** [comment]
Uploading Grabación de pantalla 2022-10-28 a las 14.30.01.mov…

**Comment by Amelie-V** [comment]
I'm not able to reproduce it. (view video)

**Comment by Amelie-V** [comment]
https://user-images.githubusercontent.com/84135211/198587559-49ec5d35-ea4a-407e-a363-1a0d63c1a1ac.mov

**Comment by Amelie-V** [comment]
https://user-images.githubusercontent.com/84135211/201958194-3870face-ecc6-4a34-a086-72d3029804e1.mov

**Comment by Amelie-V** [comment]
Improve the interaction to save time and avoid searching in sort/filter lists to reset columns. Bring a solution close to the existent one in the dataset view.

**Comment by Amelie-V** [comment]
https://user-images.githubusercontent.com/84135211/201959346-7d1d20b4-38e0-4173-8f80-01a6b83fded1.mov

**Comment by Amelie-V** [comment]
The video shows how it works on the dataset view. We should apply something similar to the dataset list view.

**Comment by nataliaElv** [comment]
@davidberenstein1957 Would you say this is still an issue in Feedback datasets?

**Comment by davidberenstein1957** [comment]
@nataliaElv, this can be closed.
