### ISSUE TITLE
Tutorial on TextGeneration using mutate paraphrasing package

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1787]
**Is your feature request related to a problem? Please describe.**
We need a tutorial example of TextGeneration.

**Describe the solution you'd like**
Write a tutorial.
Like https://rubrix.readthedocs.io/en/stable/tutorials/01-labeling-finetuning.html
Based on https://github.com/infinitylogesh/mutate

**Describe alternatives you've considered**
N.A.

**Additional context**
#1775

**Comment by iakhil** [comment]
I am willing to work on this.

**Comment by davidberenstein1957** [comment]
@iakhil awesome! Do you need help getting started? You can schedule a meeting with me via the docs.💪

**Comment by iakhil** [comment]
Hi,

Yes, some help would be appreciated. Are there any docs I should go through
before scheduling the meeting? I have been through the sample doc mentioned
in the issue that is ultimately expected.

Thanks

**Comment by davidberenstein1957** [comment]
Awesome! there aren´t that many Docs. 

Could you contact me via [our Slack](https://join.slack.com/t/rubrixworkspace/shared_invite/zt-whigkyjn-a3IUJLD7gDbTZ0rKlvcJ5g)? 

You can have a look at the following things before scheduling a meeting, but we can also have a look together if you want.
- https://github.com/infinitylogesh/mutate (I think it would be cool to use this package)
- https://docs.argilla.io/en/latest/guides/tasks/text_generation.html (I hope to add a short example here)
- https://docs.argilla.io/en/latest/tutorials/tasks/text_generation.html (I hope to add a tutorial here)

**Comment by davidberenstein1957** [comment]
Hi,

You could also try using a smaller generative model or loading the model
without GPU and limiting the number of examples for now. Later on, I can
re-run the notebook for a better model or with more examples. Feel free to
schedule a meeting with me if I need to walk you through anything.

I believe
https://huggingface.co/EleutherAI/gpt-neo-125M
https://huggingface.co/EleutherAI/gpt-neo-1.3B
https://huggingface.co/EleutherAI/pythia-13b-deduped

Enjoy the holidays.

Regards,
David


Regards,
David
