### ISSUE TITLE
add quickstart example to application start-up

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1801]
**Is your feature request related to a problem? Please describe.**
The example is a bit meaningless.

**Describe the solution you'd like**
An example that actually allows to use the UI in multiple ways like the quickstart.

**Describe alternatives you've considered**
N.A.

**Additional context**
![image](https://user-images.githubusercontent.com/25269220/198070076-06ced8df-5f8f-4444-8419-fc5467d3ae0f.png)

**Comment by dvsrepo** [comment]
it will be fixed in #1811
