### ISSUE TITLE
UI: Text Classification - Record card: improve access to labels list 

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1804]
**Describe the bug**
When label list is long, there is no way to show all the available labels without having to click the + sign on each records

**To Reproduce**
1. Go to my dataset  in annotation mode
2. Click on "+ sign" to view the full label list
3. Have to click again on the + sign on each records

**Expected behavior**
"it’s that +4 that I wanted to get rid of and instead just show the 4 labels missing".
View directly the full list

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**
"We have around 25~30 labels"

"we reduced it to around 15 but still we can’t see all the options, and the annotators always have to click the + to see the extra labels"

**Comment by Amelie-V** [comment]
<img width="874" alt="Screenshot 2022-10-27 at 16 07 23" src="https://user-images.githubusercontent.com/84135211/198343519-116d0460-95ef-42ca-993e-3352782f9c9b.png">

**Comment by Amelie-V** [comment]
Hi @davidsbatista,

We would like to check with you if that solution, quickly designed, could resolve the limitation you mentioned: https://www.figma.com/proto/0tm1Cs3ru6nEdF5ddBaXuf/Argilla-UI?node-id=809%3A10822&scaling=min-zoom&page-id=586%3A9553

The idea is to use the "one record/page view" to provide the complete labels list, with no click added. 
You could use the arrow keys to move quickly to the next record.

**Comment by davidsbatista** [comment]
Hi @Amelie-V looks good - thanks for taking the time to look into it.

just another suggestion, would it be possible to assign 0 - 1 keys shortcut to the first 10 labels? as in the named-entities.

**Comment by Amelie-V** [comment]
@davidsbatista  It's indeed an interesting other suggestion. We will provide the shortcut interaction in the focus mode. The focus mode is on our roadmap and hopefully ready in Q1 2023.  It's an optimized view to able to annotate fastly in every task covered by Argilla. For now we'll implement the improvement we designed.

**Comment by Amelie-V** [comment]
Update docs for v.1.1 @davidberenstein1957 

https://docs.argilla.io/en/latest/reference/webapp/features.html#text-classification

Add a blue Note and explain the following behavior:
When the dataset contains a large list of labels (10 +) we encourage viewing the record one by one (from the footer) and using the arrow keys to move quickly to the next record.
