### ISSUE TITLE
Link key features

### ISSUE THREAD

**Issue by chschroeder** [recognai/rubrix#1805]
Hey, I have a small but maybe useful suggestion: In the README.md file, of all things your "Key Features" do not link to the respective concepts in the docs. Maybe there is a reason against this, then consider this withdrawn. Otherwise, this is easy to do and much nicer to navigate, especially for new users.

I can provide a PR with suggestions if you like.

**Is your feature request related to a problem? Please describe.**

For example, this...
![Auswahl_397](https://user-images.githubusercontent.com/6340318/198347715-fded9303-23bc-4a02-93ed-f7e7424994d4.png)

**Describe the solution you'd like**

...could look like this:
![Auswahl_396](https://user-images.githubusercontent.com/6340318/198347681-e153ad41-6f23-4fb9-a2f5-c2aa1cbff365.png)

I was not sure which documentation page to link in the middle, otherwise each line would have had at least one link.

**Comment by dvsrepo** [comment]
@chschroeder This is such a great suggestion! We would be glad to receive a PR!
