### ISSUE TITLE
UI: Remove "Help explain button" in Manage rule view

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1807]
**Describe the bug**
view screenshot

**Comment by Amelie-V** [comment]
<img width="1432" alt="Captura de pantalla 2022-10-27 a las 16 05 26" src="https://user-images.githubusercontent.com/84135211/198575176-b46553cf-791a-4b79-bd1f-230abed059b8.png">

**Comment by Amelie-V** [comment]
@leiyre We need to create another issue to cover the info modal

**Comment by leiyre** [comment]
> @leiyre We need to create another issue to cover the info modal

@Amelie-V see (https://github.com/argilla-io/argilla/issues/1877)
