### ISSUE TITLE
Server: Improve message and docs for telemetry opt-out when using docker-compose

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1808]
**Is your feature request related to a problem? Please describe.**
When running Argilla server using Docker compose, I'd like to have a more clear documentation on how to opt-out

**Describe the solution you'd like**
I'd like to see a section/paragraph describing the steps to opt-out (what changes do I need on the docker-compose yml)

**Describe alternatives you've considered**
N/A

**Comment by frascuchon** [comment]
We should :

- Adapt the docker-based install guides adding more info about telemetry
- Include commented env vars required to disable telemetry in the `docker-compose.yaml` file

Anything else @dvsrepo, or should be enough with these 2 points?

**Comment by dvsrepo** [comment]
That should be enough
