### ISSUE TITLE
JSONDecodeError when doing weak_labels = WeakLabels(dataset="news") 

### ISSUE THREAD

**Issue by shahjaidev** [recognai/rubrix#1810]
**Describe the bug**
JSONDecodeError when doing weak_labels = WeakLabels(dataset="news") 

**To Reproduce**
weak_labels = WeakLabels(dataset="news")

Following News Classificiation with Weak Supervision Tutorial: 
https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-snorkel-weaksupervision.html

**Environment (please complete the following information):**
 Standard Conda Env on Mac with M1

**Comment by davidberenstein1957** [comment]
@shahjaidev I'll take a look tomorrow.

**Comment by davidberenstein1957** [comment]
Hello, I cannot seem to reproduce this behaviour. Could you send me an overview of the rules you defined. It could be that the `JSONDecodeError` is rule specific.

**Comment by davidberenstein1957** [comment]
I will close this issue for now and and work in the more explicit feature request.
