### ISSUE TITLE
docs: typo in the README video filename

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#1824]
Hello!

I noticed that the 3 minute walkthrough on the `README.md` has a typo: `walthrough` rather than `walkthrough`:

![image](https://user-images.githubusercontent.com/37621491/200115908-f113795f-b686-4cc2-8b3f-2d17d78b232f.png)

Again congratulations on the rebrand!

- Tom Aarsen

**Comment by davidberenstein1957** [comment]
@tomaarsen Thanks for the contribution ❤️ I even had a typo in my new job announcement on LinkedIn🫠, luckily my twin brother notified me in time.

**Comment by tomaarsen** [comment]
I've made a typo in a critical table header on a large project I worked on in the past ☠️ Had to write a whole script to auto-fix that for all users when I found out haha. Luckily this is less of a problem.
