### ISSUE TITLE
feat: update instead of overwriting annotations from scrach for previous (multi-label) bulk-annotations 

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1825]
**Is your feature request related to a problem? Please describe.**
With the `bulk_annotate` option in the UI, each of the previously annotated examples gets overwritten instead of updating the record, which does not allow me to layer annotations.

**Describe the solution you'd like**
if a record is already annotated I would like to get the option to update instead completely overwriting annotations.

**Describe alternatives you've considered**
N.A.

**Additional context**
"Hi, we are trying to use bulk annotation for a Multi-label dataset. We search for a word and we want to add a label to the pre-existing set of labels for each of the selected examples. Now with the current implementation of annotate_as, you can select multiple labels and apply them to all the examples which will automatically update any pre-existing labels. Is this possible in any other way?"

**Comment by issam9** [comment]
Would like to mention that I believe this only makes sense in the context of Multi-label classification

**Comment by davidberenstein1957** [comment]
I was thinking bulk annotation might be a bit clumsy/trigger-happy in some cases and people might accidentally overwrite already annotated records during this process. I saw an additional check with GitHub-like merge review might be relevant. @issam9 not sure what you think about this?

**Comment by issam9** [comment]
I think under annotate_as we can have two buttons for overwrite/update or a checkbox next to annotate_as that would determine its behavior. Sorry I'm not sure i got your example of github like merge review

**Comment by davidberenstein1957** [comment]
No problem. I thought we might potentially go over each (merge-conflict) entry one by one to resolve to overwrite issues manually, however, your solution is probably much easier and straightforward to implement.

**Comment by frascuchon** [comment]
Ref: #1621
