### ISSUE TITLE
Dataset snapshots and versioning (DVC, S3, HF ...)

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1831]
As a user (e.g., data/ML engineer) I want to be able to persist a snapshot of my data so that I can have better reproducibility. 
As a user I want to be able to easily read and recover a snapshot.

The simplest case is having a `to_disk()` method which stores all necesary info (including rules, tags, etc.). Other ideas are to leverage hf `Dataset` to delegate this.

Question: how is this related to DVC, Pachyderm and others?

Related: https://www.pachyderm.com/blog/pachyderm-label-studio-versioned-data-labeling/

See also argilla-io/roadmap#10

**Comment by frascuchon** [comment]
Refs #1903
