### ISSUE TITLE
[Token Classification metrics] Review entity consistency and mentions histograms

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1834]
The first version of `entity_consistency` adds a threshold param and forces it to be greater than 2 (see https://github.com/recognai/rubrix/blob/7e806ad8b9d3b2abf54b14c87c335022c60633ff/src/rubrix/metrics/token_classification/metrics.py#L378). I'd like to get rid of this logic as I think counterintuitive.

Related to this, we briefly discussed this but having a list of the top N mentions (and their types) in the metrics module would be really useful. I say this because this would be solved by threshold=1 but maybe the name `entity_consistency` is not the best naming. One might argue that is not the best in any case, but I could live with both options:

1. Changing the name `entity_consistency` to something more meaningful and keeping the threshold parameter (without enforcing >=2, but still have the default=2)
2.  Have a separate metric top_k_mentions for the mentions and keep entity_consistency as is (although I still think forcing >=2 is not the best option).
3. Keep the name `entity_consistency` and keep the threshold parameter (without enforcing >=2, but ). This is probably the fastest way to do this (without enforcing >=2, but still have the default=2)

What do you think @frascuchon @dcfidalgo ?

**Comment by dcfidalgo** [comment]
I would vote for 2. but without enforcing >=2, simply leave the default at 2. The main problem I see with one method covering both use cases is that the default value of `mentions` should be quite different. For top_k_mentions you want something like ~10, but for entity consistency, you often don't want any limit at all.

**Comment by frascuchon** [comment]
The trick here is the entity consistency should show relevant mentions without tunning thresholds or k-mentions. So, I vote for option 2. The current implementation is nearest of `top_k_mentions` than `entities_consistence`. Also, you could always find or explore the the entity consistency by usint the top_k_mentiions methods.

We keep `entity_mentions` as is but regarding a better metric that show relevant mentions regarding the label consistency (get less consistent mentions or whatever).

**Comment by dvsrepo** [comment]
There are two issues:

1. `entity_consistency` with default = 2 but not enforcing >= 2
2. Add `top_k_mentions`
