### ISSUE TITLE
Dataset cards and metadata generation for Hub

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1841]
## Resources

- The HF dataset card creator app: https://huggingface.co/datasets/card-creator/
- The HF dataset card template: https://raw.githubusercontent.com/huggingface/datasets/master/templates/README.md

## Description

The HF dataset card contains a set of fields we will easily expose when publishing an RB dataset into the HF hub. 

<img width="1566" alt="Screenshot 2022-06-21 at 11 41 41" src="https://user-images.githubusercontent.com/2518789/174769659-514bb06e-0783-48ae-b468-27861a72e732.png">

As a starting point, we can provide tools for:
- manual configuring some dataset tags (task, task category, language,...) 
- automatic configuring tag like size
- manual a dataset summary/description
- automatically generate a basic dataset structure - all RB datasets should keep the same general schema.

please @dvsrepo @dcfidalgo confirm the issue spec.

**Comment by dvsrepo** [comment]
I confirm!

**Comment by frascuchon** [comment]
Can we depriorize this one, @dvsrepo ?

**Comment by dvsrepo** [comment]
Now it's easier to handle and push metadata and cards, see: 

https://huggingface.co/docs/huggingface_hub/how-to-model-cards

**Comment by davidberenstein1957** [comment]
I´ve created an example here.
https://huggingface.co/datasets/argilla/uber-reviews/blob/main/README.md

**Comment by davidberenstein1957** [comment]
Also, train-test splits are not taken into account based on metadata. our release `twitter-coronavirus` vs `argilla/twitter-coronavirus` on the hub.

**Comment by nataliaElv** [comment]
This is already covered in the new `FeedbackDataset`s. Is this something we want to expand to other datasets or are we ok closing this issue @dvsrepo ?

**Comment by dvsrepo** [comment]
Well spotted, we can close this 🎆
