### ISSUE TITLE
Use Rich for logging, stack traces, and progress bars

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#1843]
I propose to substitute tqdm and loguru with the rich library:
- use rich to format the stack traces
- use rich for the progress bars
- use rich to format our logging
- (optional) add a specific logging handler for notebooks
- (optional) hide certain stack traces in the notebook

**Comment by tomaarsen** [comment]
Some sample outputs when Rich is used:
### Loading and logging `gutenberg_spacy-ner`
#### Rich:
![image](https://user-images.githubusercontent.com/37621491/218731397-1d90099d-440d-46ff-ac30-d214cadaf5c9.png)
#### Current (with Loguru & tqdm):
![image](https://user-images.githubusercontent.com/37621491/218732160-6db8a097-5366-4877-b304-3936e490c1ce.png)


### Providing an incorrect value for initialising a Record
#### Rich:
![image](https://user-images.githubusercontent.com/37621491/218731844-ffff5802-f1ca-466a-9165-7804916e0bb3.png)
#### Current:
![image](https://user-images.githubusercontent.com/37621491/218732279-f810d3bb-d3b6-4ca7-817b-ac2d4b0659f9.png)

I'd love to hear your thoughts on the before and after.

**Comment by davidberenstein1957** [comment]
For me, rich is more readable in both cases.

**Comment by dvsrepo** [comment]
Same for me!

**Comment by tomaarsen** [comment]
Alright, wonderful. I'll prepare a PR.
