### ISSUE TITLE
Improve search pagination using the `search_after` parameter

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1848]
The current pagination mechanism has a (configurable) hard limit to 10k records. You cannot request more records after that.

In those cases, you can use the `[search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after)` parameter. 

- We need to validate how many versions include this parameter 
- `rb.load` could be benefited from this change. You could load the whole dataset by paginating into the records.

**Comment by dvsrepo** [comment]
Is this still relevant @frascuchon ?

**Comment by frascuchon** [comment]
This could improve the backend performance since the use of the `scroll` action is discouraged. 

But we need to re-think the pagination flow, since, with this approach, we need to provide a record ID for pagination, so the feature "go to page 120" could be affected.

**Comment by frascuchon** [comment]
TODO:
- [ ] Review current pagination workflow VS <Previous | Next>

**Comment by davidberenstein1957** [comment]
closed in favor of https://github.com/argilla-io/argilla/issues/2484
