### ISSUE TITLE
Add record fields into record card

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1849]
For now, we cannot access to record ids from UI. We could want use id for some specific filter query and it would be nice show this info to UI users

**Comment by dcfidalgo** [comment]
Slightly related: It would be nice to be able to see the `event timestamp` somewhere in the UI as well.

**Comment by frascuchon** [comment]
Also, sorting for those values could be interesting (and the `last_updated` one)

**Comment by dvsrepo** [comment]
This is a small but relevant feature

**Comment by Amelie-V** [comment]
@frascuchon I would like we start defining it. Can we have a quick call this week with @leiyre and anyone else we consider important

**Comment by frascuchon** [comment]
:+1:

**Comment by Amelie-V** [comment]
@ufukhurriyetoglu @davidberenstein1957 @dvsrepo @frascuchon 

We are considering adding to the record card the following info:
(1) ID record
(2) Last updated
(3) Event time stamps

(1) will have the copy action. For now, this is the main need we've detected. Do you think any other things we could do during the global user flow with this ID?

(2) and (3) could be added to the main sort filter. Do you think it's still useful to view it from the record card?

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/1911

**Comment by ufukhurriyetoglu** [comment]
@Amelie-V I will check this

**Comment by Amelie-V** [comment]
Some inputs:

- We should add (1) (2) (3) inside the record falafel menu
- We should align in with metadata view
- We should disabled "metadata filter by" from the record

**Comment by Amelie-V** [comment]
@leiyre Spec. are ready in Notion.
