### ISSUE TITLE
Dataset settings

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1854]
## Description

Allow configure dataset level settings for several purposes:

- Edit the labels (add, edit, remove) ( refs #1887 )
- Define metadata fields schema. This could include hidden fields, for example
- Customize the inner elaticsearch index settings/mappings (for advanced users)
- Configure the users that can operate over the dataset (annotators, administrators, reviewers,...). Here, a previous design for user roles should be defined.
- Some task could define their own settings (the `multi_label` parameter could be a setting for the text classification task)

### From issue #1853 
Edit the tags and workspace for the dataset, but only was able to do so via deletion and re-creation.

**Describe the solution you'd like**
The possibility to have a button next o the delete and copy that allows for editting.

**Comment by frascuchon** [comment]
This suggestion could match with some config that could be included as part of the dataset settings.

https://github.com/argilla-io/argilla/issues/1761#issuecomment-1316455118
