### ISSUE TITLE
Normalize user notifications in the UI

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1858]
- Notifications after delete a dataset or a dataset rule
- Notifications after annotate from global actions
- Notification aftet create a label o a new rule
- ...

Related issue: recognai/rubrix#874

**Comment by Amelie-V** [comment]
- [ ] Adress an exhaustive list of:
- All actions that need to be notified
- All notifications types we dispose (Error Toast, Success toast, info message...)
- Notification coming from back or client?
