### ISSUE TITLE
Dataset entity abstraction

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1859]
The python client has been working mainly with two simple functions: `rb.log` and `rb.load`. 

Then, extra functionality - such as automatic labeling, monitor, metrics computation, or dataset settings -  was included. And different base modules were created. 

The flows become more and more complex, and the interactions cross-module are more and more frequent. The main reason is that the core data entity in rubrix, the `Dataset`, has no entity category in the client part. So, operations over datasets are disgregated over several modules.

The idea here is to define a client component that aggregates the actions over a dataset in the same context. We can configure a dataset, log some records, create some labeling rules and compute the weak label matrix, but for that, we need to import and use sI propose.

My proposal is to create an abstraction with those features. A pseudo-code could be:

```python
dataset = rb.new_dataset("name", settings=...) # the task could be also a parameter

# Then, we operate over the dataset without importing the modules
dataset.add_rule(...)

dataset.log(records)
dataset.load(query=....) # the result of this method returns a `DatasetFor...`, A name that crashes with the new Dataset concept. We should review the naming and hierarchy here.

dataset.compute_weak_label(...)
# or
dataset.update_settings(....)
```

This is an open discussion, and all kind of proposal and feedback is welcome!

**Comment by dvsrepo** [comment]
I agree and like the proposed design
