### ISSUE TITLE
Docs: Replace one old UI screenshot

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1862]
**Describe the bug**
A screenshot from Rubrix UI persists on docs .

**To Reproduce**

(weak labeling mode view)
https://docs.argilla.io/en/latest/reference/webapp/features.html

**Expected behavior**
Update it with a screenshot from the new UI

**Screenshots**

**Environment (please complete the following information):**
-

**Additional context**
-

**Comment by frascuchon** [comment]
@davidberenstein1957 could you please include the  PR resolving this?

Normally, when you create a PR you should include the closing or related issues with Closes #... or Refs #...
