### ISSUE TITLE
Docs: Maintain menu position on click

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1864]
**Describe the bug**
When I select a content from the right menu, I get lost because menu refresh and focus on top.

**To Reproduce**
1. Go to main menu
2. Click on a section close to the bottom
3. See error: Menu is on the top

**Expected behavior**
Would like to maintain the position, to see the active section in the menu

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by davidberenstein1957** [comment]
@leiyre 

I think I am going to need some help here because both the Furo theme and the default sphinx website show the same behaviour. And the Furo theme explicitly mentions it shouldn´t be used with too much content in the sidebar.

**Comment by leiyre** [comment]
@davidberenstein1957  I don't know if reducing the content in the sidebar is feasible for us so I'll check some options like save in the local storage the scroll position or something similar, I need to explore and think about
