### ISSUE TITLE
UI: Score filter closes when you drag the slider

### ISSUE THREAD

**Issue by leiyre** [recognai/rubrix#1876]
**Describe the bug**
Score filter closes when you drag the slider outside the select screen

**To Reproduce**
1. Go to dataset
2. Click on prediction / Score
3. Drag the slider outside of the dropdown
4. Filter closes

**Expected behavior**
Mantain opened the filter

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Comment by frascuchon** [comment]
Fixed in #1822
