### ISSUE TITLE
UI: Create an "info" button to support the user in the different views

### ISSUE THREAD

**Issue by leiyre** [recognai/rubrix#1877]
Create a button that gives access to a modal with complementary information for a specific view.
At the moment we will show the information of the explanation records but in the future we can expand to other views.

**Comment by leiyre** [comment]
Modal content:
Title: Info
Subtitle: Highlight colors in token attributions.

**Comment by Amelie-V** [comment]
@davidberenstein1957 
Add content to the doc. below the Filter section: https://docs.argilla.io/en/latest/reference/webapp/pages.html#filters

Text proposal:

Adaptative help 

On the right side of the filters, the help button is opening a small overlay help window. The aim is to anticipate the user need and offer a shortcut to related information specific to the current view. This button appears each time extra help is considered useful. (e.g model explanation, weal labeling...)
