### ISSUE TITLE
Kernel Dies when following the WeakSupervision ag news tutorial and using Snorkel's LabelModel()

### ISSUE THREAD

**Issue by shahjaidev** [recognai/rubrix#1878]
**Describe the bug**

JupyterKernel Dies instantly when following ag news tutorial and using Snorkel's LabelModel()

**To Reproduce**
In the Weak Supervision ag news tutorial, 

label_model = Snorkel(weak_labels)

# fit the model
label_model.fit()

^Dies

I believe the error is with Snorkel's SnorkelLabelModel

When passing a much smaller l_train matrix, snorkel still segfaults. 

Have you folks been able to run any example successfully with snorkel labelmodel() without segfault-ing? 

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/22052444/200769272-ef4db99c-ee64-4eb7-a8f4-4b271d97adc3.png">

**Environment (please complete the following information):**
 Jupyter-lab notebook running on MacOS
Also tested on terminal

**Comment by davidberenstein1957** [comment]
@shahjaidev duly noted! Thanks for your input lately, it really helps use to fine-tune the product 💪🏽. I will take a look early next week, perhaps we could also go over it during our office hour? Did you already have some talking points for me?

**Comment by dvsrepo** [comment]
@ufukhurriyetoglu while you add the new add rules usage to this tutorial, could you verify if you also get this error when running Snorkel?

**Comment by ufukhurriyetoglu** [comment]
this tutorial works at my local, windows 11, msi notebook. I am using Anaconda for notebook creation. however in our tutorial the Snorkel related part is as follows: 

```
from argilla.labeling.text_classification import Snorkel

# create the label model
label_model = Snorkel(weak_labels)

# fit the model
label_model.fit()
```

@shahjaidev does this part working?

**Comment by shahjaidev** [comment]
The .fit() is what segfaults and fails

**Comment by frascuchon** [comment]
Thanks, @shahjaidev. which version of snorkel are you using?
