### ISSUE TITLE
feat: remove label button

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1887]
**Is your feature request related to a problem? Please describe.**
I just spoke with the a user and they told me they were not able to delete a label from within the UI. Especially, after creating a wrong label.

**Describe the solution you'd like**
hey would like to have a "remove label" button, besides the "create label" button.

**Describe alternatives you've considered**
Re-creating the dataset or leaving wrong/un-used labels

**Additional context**
do keep in mind that deleting labels might remove them from previously annotated records.

**Comment by dvsrepo** [comment]
+1.

We first need something for #1854 and #1857. Deleting a label side effects as you mention so we need to be careful with permission. Permissions are relevant to add labels too.

Having said that, in the current version, once the label set is defined, we recommend to use dataset settings from the Python client to set the labels. If labels are predefined from the cli the annotators cant create new labels (a more consistent experience will be provided once we have roles and dataset settings in the UI)

**Comment by shahjaidev** [comment]
Having a label class delete/ edit button would be a feature I'd love to see as well

**Comment by frascuchon** [comment]
Closing, will be resolved in #1854
