### ISSUE TITLE
feat: Set a default value to the `event_timestamp` field

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1892]
**Describe the bug**
After going through the quickstart. The Kibana records don't contain time information, besides, `last_updated`. 

**To Reproduce**
1. Initialize your Argilla with Kibana
2. Upload the [quickstart](https://docs.argilla.io/en/latest/getting_started/quickstart.html#). 
3. Create a Kibana index pattern based on `event_timestamp`
4. No record show due to empty field.

**Expected behavior**
I would expect to have this set to the same date as `event_timestamp`, until someone has annotated the data and therefore updated.

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.0.1
 - ElasticSearch Version [e.g. 7.10.2]: 7.10.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla:v1.0.1

**Additional context**
Maybe we can align this with other kibana issues #1803.

**Comment by frascuchon** [comment]
Thanks @davidberenstein1957 

Regarding the data from the quickstart, the datasets don't contain that field. You must provide a value for the `event_timestamp` field. It's a field used when your data is time-based.

Maybe [the python client reference docs](https://docs.argilla.io/en/latest/reference/python/python_client.html?highlight=event_timestamp#argilla.client.models.TextClassificationRecord) should be improved :-)

**Comment by davidberenstein1957** [comment]
Yes, maybe it would, but I would expect it to be equal to the creation_time by default.

**Comment by frascuchon** [comment]
So, I think we can move as a feature request and place it in the roadmap. Adding this default behavior could conflict with the way Argilla indexes the data, and we need to think about how to handle it.

**Comment by davidberenstein1957** [comment]
related to https://github.com/argilla-io/argilla/issues/1911

**Comment by frascuchon** [comment]
maybe an explicit argument in the `rg.log` function to create records with creation time?

Something like:

```python
rg.log(name="my-new-dataset", records=records, with_event_timestamp=True)
```

This should be easy to tackle and could give the users an easy way to add historical data to the dataset.

**Comment by davidberenstein1957** [comment]
I was thinking of adding this on a record-level `init` . 

```
if timestamp is None:
    timestamp = datetime.now()
```

Most production-using users that I have spoken to explicitly mentioned using DateTime to filter the data, giving preference over the records to annotate. And this will likely also be needed by default if we want to create [default Kibana Dashboards](https://github.com/argilla-io/argilla/issues/1803).

**Comment by frascuchon** [comment]
In that case, we must be sure that the client will send this info for record updates, otherwise, the creation time will be updated with a new timestamp.

For example:
```python
records = ... # build some text classification records. The timestamp will be generated

rg.log(name=...,records=records,...)

# at some point

record_33 = TextClassificationRecord(id=33,....) # this record is already created


rg.log(name..., records=record_33) # This will override the whole record. If we don't setup the record properly, the event_timestamp will be overridden.  

```
Just note that this is already happening with annotations and predictions since Argilla does not support partial updates.

So, we assume and resolve it once we have a client dataset abstraction to handle record manipulation.

**Comment by davidberenstein1957** [comment]
`event_timestamp` -> `creation_time`
deprecate `event_timestamp`
and `creation_time` should always be included
