### ISSUE TITLE
feat: render HTML within UI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1897]
**Is your feature request related to a problem? Please describe.**
I was working on an integration for entity linking and wanted to get nicely rendered HTML in the UI. 

**Describe the solution you'd like**
I would like to see HTML formatted in both cases.

**Describe alternatives you've considered**
I´ve considered not using HTML.

**Additional context**
![image](https://user-images.githubusercontent.com/25269220/201719930-d22aefe9-8550-46d1-9422-b3c7a58f8b12.png)

**Comment by dvsrepo** [comment]
We've allowed custom, arbitrary HTML rendering inside record cards in previous versions (before OSS launch) and it can get really problematic. We will tackle this need in a controlled manner when we build #1837
