### ISSUE TITLE
feat: container image server configuration (to enable HTTPS proxy over HTTP)

### ISSUE THREAD

**Issue by EsraaMadi** [recognai/rubrix#1899]
**Describe the bug**
I am trying to integrate Argilla with [Orchest](https://github.com/orchest/orchest) , the Argilla sever have launched successfully (screenshot from logs below), but the web page of argilla kept loading. When I investigated the network section, found a blocking error (the error is attached below). It seems like there is a conflict between HTTPS and HTTP protocols and need to request the domain owner to add HTTPS as well. I have contacted technical support for orchest and they responded as attached

**Screenshots**
![2D284D81-529D-4357-A900-DE0B12B2FF6E](https://user-images.githubusercontent.com/33832903/201741573-be8e3ce0-9bf8-47f7-b2f6-500a56868644.jpeg)
![BA700ABB-B445-4139-A531-C602486179FE](https://user-images.githubusercontent.com/33832903/201741583-4b33e787-236d-42e4-84f6-be5ecfed7245.jpeg)
![606775FE-01CF-405A-8BDB-DA9330F27442](https://user-images.githubusercontent.com/33832903/201741585-a31e855d-278a-4e30-96bf-77c83c408131.jpeg)
![0F65856F-0135-439F-B88E-16996BB4D25A](https://user-images.githubusercontent.com/33832903/201741587-984ae5ad-bd2c-440d-98ae-0e966edd2076.jpeg)

**Environment (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome, firefox
 - ElasticSearch Version: 7.10.2
 - Docker Image: argilla: lastest

**Comment by ricklamers** [comment]
Chipping in here, I think it's the lack of a `base_url` or similar option and not using relative resource paths causing the issue.

Orchest runs services on a subpath to proxy requests to the correct underlying container service. We can either pass the path component `http://orchest.app.com/service-abc-path/Z -> (internal) -> http://<container host>/service-abc-path/Z` or hide it from the application (usually best when the application uses relative resource pointers) `http://orchest.app.com/service-abc-path/Z -> (internal) -> http://<container host>/Z`

<img width="744" alt="Screen Shot 2022-11-15 at 10 37 08" src="https://user-images.githubusercontent.com/1309307/201884653-682a109b-2486-48c1-8fab-ca016cc1c3db.png">

**Comment by dvsrepo** [comment]
Thanks for reporting @EsraaMadi and @ricklamers for your insights. We're very keen to make Argilla work for Orchest.

@leiyre, @keithCuniah could you check this to assess what could be done?

**Comment by frascuchon** [comment]
Hi @EsraaMadi and thanks for reaching out.

Could you verify that you can access to `https://<your-service-endponit>/login` without problems?

I think the HTTPS -> HTTP problem is related to the login redirection.

**Comment by EsraaMadi** [comment]
![image](https://user-images.githubusercontent.com/33832903/201963202-5b53989f-6f81-4787-90dd-bb88a8e7dcaf.png)
the same issue

**Comment by frascuchon** [comment]
Thanks.

I've been doing some tests. Could you try with this docker image `argilla/argilla-server:pr-1907`? If everything is ok we could release a new patch this week.

**Comment by EsraaMadi** [comment]
with the new docker image
![image](https://user-images.githubusercontent.com/33832903/202097034-943f538b-f934-49a9-a890-0ee580acbeb8.png)

**Comment by frascuchon** [comment]
As @ricklamers  comments above, we need to support configurable `base_url` to enable serving argilla in a subpath. 

I will open an issue for that. 

Thanks for your feedback, guys!!

cc: @dvsrepo @leiyre @keithCuniah

**Comment by dhruvsakalley** [comment]
I can confirm IIS reverse proxy has a similar issue described here. I see the spinner but I do not see the javascript libraries loaded on the remote machine. Something (maybe the redirect or the firewall) is creating a problem with the argilla client to load remotely. I've been able to load some of the common libraries such as fastapi endpoints and streamlit apps but the issue seems to only happen with argilla. I'm following the topic as well.
