### ISSUE TITLE
feat: monospaced fonts to allow for better text alignment

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1900]
**Is your feature request related to a problem? Please describe.**
When adding text that is longer, characters are not aligned.

**Describe the solution you'd like**
A fancy monospaced.

**Describe alternatives you've considered**
I´ve considered aligning by adding underscore but that doesn´t look very good.

**Additional context**
![image](https://user-images.githubusercontent.com/25269220/201742530-94e25c8d-f67f-440d-acef-cade320511b8.png)

**Comment by dvsrepo** [comment]
I'll let @Amelie-V and @leiyre better discuss this one but as a general practice is not recommended to use a monospace font for text bodies as it generally decreases readability (see https://www.quora.com/Typography-Monospaced-fonts-what-are-the-pros-and-cons-for-the-reader?ch=10&oid=1236328&share=15cff568&srid=hha0g3&target_type=question).

I have the impression that you are trying to get a visual alignment of a table, which a rare case and might be better solved with custom templates. For most use cases, we have chunks of texts inside records so we need readability. But again, I could be wrong as I'm not a typography expert so I'll let Leire and Amélie comment on this.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/1837

**Comment by Amelie-V** [comment]
Yes, if I understand correctly the use case, It could be relevant to have a view of the record in columns when it contains fields but I would not tackle it from the type of font.
