### ISSUE TITLE
bug: query disappears after hitting refresh in the `/datasets` view

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1902]
**Describe the bug**
Dataset query field is empty after the refresh but the query is still executed.

**To Reproduce**
https://user-images.githubusercontent.com/25269220/201851108-ae49e863-4024-4fc9-8de3-6c587d77f9d7.mp4

**Expected behavior**
I would expect it to still be there.

**Screenshots**
Look at the cool video. 

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: FireFox
 - Argilla Version [e.g. 1.0.0]: 1.0.1
 - ElasticSearch Version [e.g. 7.10.2]: 7.10.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.0.1

**Additional context**
N.A.

**Comment by Amelie-V** [comment]
Merci for the bonito video @davidberenstein1957 
Why are you refreshing the list at that moment? 
if I do it, I would expect a reset of the content: View the complete dataset list and the query field clearly.

**Comment by davidberenstein1957** [comment]
@Amelie-V I will try to do every bug-report like this if you like it. 

I was expecting a dataset to show up, given the filter but it didn´t show yet, so I refreshed the page. 
I would expect a reset of the content of but of the filter, just like the behaviour when querying records. (which is correct IMO)
Now the content is still filtered after the refresh but the actual filter disappears from the search bar, which is wrong for sure.

**Comment by Amelie-V** [comment]
Yes, the behavior is definitely wrong. 

The refresh button was initially temporary that why I ask you @frascuchon @leiyre @davidberenstein1957  which solution would be wiser from your point of view:
- Remove the reset button in the dataset list template (if we still need to maintain it in other views)and add shortcuts to reset quickly activated Query/filters/sort info.
- Maintain the reset button and correct the behavior: show the complete dataset list and reset activated Query/filters/sort info.

**Comment by Amelie-V** [comment]
#https://github.com/argilla-io/argilla/issues/1776
we could kill two birds, with one "Pan!"

**Comment by davidberenstein1957** [comment]
I think it makes sense to align this with the behaviour in the records view. Especially because we want to work towards having multiple users work on the same problems. But I think either reset or refresh can work in the same way.

**Comment by davidberenstein1957** [comment]
Yes, maybe aligning them is also good.

**Comment by frascuchon** [comment]
Alignment is good for me too. If we remove the refresh button, when page is refreshed, filters still should be there after refresh

**Comment by frascuchon** [comment]
Réf #1621

**Comment by damianpumar** [comment]
Hi Team, with our new architecture this problem will be solved.
Here #3301

**Comment by nataliaElv** [comment]
Solved with #3301
