### ISSUE TITLE
docs: Guidelines on backing up Argilla ES

### ISSUE THREAD

**Issue by bengsoon** [recognai/rubrix#1903]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I almost lost all my annotations when I migrated from Rubrix to Argilla, thankfully it was retained. It gave me a sense of urgency to create persistent back up workflow on my server.

**Describe the solution you'd like**
Best practices / workflow / tutorial on backing up Argilla annotations or creating ES snapshots.

**Describe alternatives you've considered**
Several potential workflows
 - Creating ES snapshots
 - Automated Python scripts using Argilla's Python API to load the datasets in the workspace and serialize them (Pickle)

**Additional context**
I'll be more than happy to contribute to this under guidance.

**Comment by davidberenstein1957** [comment]
https://docs.argilla.io/en/latest/getting_started/installation/elasticsearch.html
I think it would fit in nicely over here.

@frascuchon Do you have some best practices here?

**Comment by davidberenstein1957** [comment]
![image](https://user-images.githubusercontent.com/25269220/201869013-38096f6b-d76e-40d1-a059-2db2e0ac93e3.png)

**Comment by frascuchon** [comment]
Not really. We could start defining the es snapshots process/guide

**Comment by davidberenstein1957** [comment]
@frascuchon @dvsrepo FYI, I will create some docs for this using default `Dataset.to_pandas()` and [DVC](https://dvc.org/doc/start/data-management/data-versioning), and a basic reference to the Elastic docs for snapshot because @bengsoon and I will also discuss this during our office hour 🤓

**Comment by frascuchon** [comment]
Fixed in #2169

**Comment by davidberenstein1957** [comment]
Thanks @frascuchon
