### ISSUE TITLE
feat: show record log time in UI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1911]
**Is your feature request related to a problem? Please describe.**
I was annotating some data and wanted to get some insight about when the data was logged, however, this isn´t possible unless we add this to the metadata field explicitly.

**Describe the solution you'd like**
I would like to see and for example sort records based on when they were created.

**Describe alternatives you've considered**
Adding this manually to the metadata field.

**Additional context**
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/25269220/202190883-ed099811-59fb-42bb-aef1-b5ad419415e6.png">

**Comment by davidberenstein1957** [comment]
#1892

**Comment by frascuchon** [comment]
This should be resolved with #2079, right?

cc @leiyre @Amelie-V
