### ISSUE TITLE
Hide empty menu dropdown

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1912]
**Describe the bug**
Between bug and enhancement. This is not something broken, but it's not the correct behavior.

When I open my dataset view (cross mode) with no annotation, I can click on annotation menu and view a piece of empty dropdown. 

**To Reproduce**
1. Go to a dataset without annotation e.g "dataset-with-dates"
2. Click on 'Annotation into filter menu
3. See error

**Expected behavior**
I would like to avoid this unuseful action.

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

If there is no annotation in my dataset, I would not see Annotation filter in the filter menu.
If there is no prediction (when I'm creating a dataset to start annotate some data) I would say the same: No prediction

**Comment by Amelie-V** [comment]
<img width="533" alt="Captura de pantalla 2022-11-16 a las 15 35 54" src="https://user-images.githubusercontent.com/84135211/202210880-66f23097-2c47-418c-9d04-a32c9d251402.png">

**Comment by frascuchon** [comment]
What is the behavior of the other filter group in same conditions? E.g. datasets with no predictions or no metadata. 

I think the expected behavior should be the same for all of them

**Comment by dvsrepo** [comment]
At least with predictions this doesn't happen and the prediction drop-down option is not shown so that one works as expected, that's the thing. 

I agree that all should have the same behaviour, so this enhancement should make sure all filter options behave the same.

**Comment by frascuchon** [comment]
👍
