### ISSUE TITLE
Upper case letters are not allowed in dataset name

### ISSUE THREAD

**Issue by jamnicki** [recognai/rubrix#1918]
**Describe the bug**
Dataset's name is invalid, because of upper letters. I assume it was not intended.

**To Reproduce**

```python
record = rg.TextClassificationRecord(text="Some text")
rg.log(record, "DS_NAME")
```

> ```powershell
> argilla.client.api.InputValueError: Provided dataset name ALtempdataset does not match
> the pattern ^(?!-|_)[a-z0-9-_]+$. Please, use a valid name for your dataset
> ```

**Comment by davidberenstein1957** [comment]
Hey, this is a Elastic configuration thingy. They don't allow for this and it is a heavily debated topic 
- https://discuss.elastic.co/t/why-cant-an-index-start-with-an-uppercase-letter/72435
- https://github.com/elastic/elasticsearch/issues/29420

**Comment by davidberenstein1957** [comment]
@frascuchon Maybe we can make this message a bit more human-readable?

**Comment by davidberenstein1957** [comment]
@jamnicki Could you potentially add the suggested fix above to your PR?

**Comment by frascuchon** [comment]
> @frascuchon Maybe we can make this message a bit more human-readable?

👍 Could you please create a specific issue for that, @davidberenstein1957?

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/1931
