### ISSUE TITLE
Show Full Record

### ISSUE THREAD

**Issue by splevine** [recognai/rubrix#1920]
Long messages that have "Show Full Record" when Clicking show full record, the message pops up but then does not load. 

**Expected behavior**
Expected the rest of the text to load

**Environment**
 - OS: iOS
 - Browser: Chrome
 - Argilla Version: 1.0.1

**Comment by davidberenstein1957** [comment]
@splevine thank you for the feedback! Could you share any screenshot or video recording?

**Comment by splevine** [comment]
https://user-images.githubusercontent.com/4715331/202925955-aa6ede07-981d-488d-82ed-ecdf2b99bf4c.mov

**Comment by leiyre** [comment]
Hi @splevine, thank you, we are doing some tests to simulate the behavior and it will be useful to have this extra information. 

- Does this erroneous behavior always happens on all records or only sometimes? 
- If pagination is changed to a single record per page, does this still happen? 
- Is there an error in Chrome's Debug console or weird console log?

Thank you again for your feedback

**Comment by leiyre** [comment]
Hi @splevine, have you had a look and get a little more information? Thanks!
