### ISSUE TITLE
Remove "metadata filter by" from the record

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1927]
**Is your feature request related to a problem? Please describe.**
Filter by metadata from records is not really useful now it's available from the main filter bar.

**Describe the solution you'd like**

Remove the filter action:
- Checkbox
- Apply/cancel button
- Aligned metadata presentation to metadata info
- Maintain separated metadata info and record info as two items in the falafel menu

**Describe alternatives you've considered**

**Additional context**
#1911

**Comment by Amelie-V** [comment]
This issue will be tackled when we'll implement the "info records". What do you think @leiyre ? we don't save time doing this one first?

**Comment by leiyre** [comment]
@Amelie-V I think both issues can be tackled at the same time, because they are closely related.
