### ISSUE TITLE
Show scroll bar into dropdown

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#1928]
**Is your feature request related to a problem? Please describe.**
Adding two new items in the sort dropdown, we detect the lack of evidence we need to scroll to view the whole list.
(view screenshot)

**Describe the solution you'd like**
Show scroll bar in all dropdowns from the filter bar: With/without checkbox
Don't active scroll when there are until 6 items (to avoid behavior viewed in video)

**Describe alternatives you've considered**

**Additional context**
6 items are showing before the scroll, active scrollbar from seven items

**Comment by Amelie-V** [comment]
<img width="433" alt="Captura de pantalla 2022-11-21 a las 12 05 42" src="https://user-images.githubusercontent.com/84135211/203035869-da79a8f7-15ab-4f5f-aeaf-12545e479341.png">

**Comment by Amelie-V** [comment]
https://user-images.githubusercontent.com/84135211/203036464-a3ffb7a5-b6f8-469a-87eb-51e8baf61fa6.mov

**Comment by Amelie-V** [comment]
@leiyre, please give to @keithCuniah  UI material in figma

**Comment by frascuchon** [comment]
Closed by #2000
