### ISSUE TITLE
Allow for additional markup on data while annotating / hand labeling

### ISSUE THREAD

**Issue by dhruvsakalley** [recognai/rubrix#1939]
**Is your feature request related to a problem? Please describe.**
When labeling a large corpus, it becomes important to take notes about an interesting data point or add additional metadata like a set of tags or flags to a data point to come back to it quickly. The current data model does not support such flags or custom notes.

**Describe the solution you'd like**
Extend the data model with additional tags and notes attributes which can be queried or filtered by, and are editable during hand annotation mode. Optionally, making certain fields of metadata editable during the hand labeling exercise could also fulfil the intention.

**Describe alternatives you've considered**
One might need to keep track of the interesting / confusing data points manually, or just not validate them till the very end, which causes friction.

**Additional context**
This is a productivity booster and helps you annotate faster, also helps in validating your annotations later by another annotator if they exchange data specific notes or fixes.

**Comment by davidberenstein1957** [comment]
@dhruvsakalley Thanks for your great input. This might also align with this feature request I created a while ago.
https://github.com/argilla-io/argilla/issues/1800

**Comment by davidberenstein1957** [comment]
closed this one in favor of #1800
