### ISSUE TITLE
[Installation] Argilla server is not published in conda repositories

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1942]
The setup installation guide in the documentation shows how to install argilla-server from conda, but the package is not published in conda repositories anymore.

We should remove the conda section until we make it available again.

**Comment by dvsrepo** [comment]
Maybe @sugatoray can guide us with the conda package publication 🙌

**Comment by sugatoray** [comment]
@dvsrepo Of course, I can help. But it would be nice to know who from the repository core team will be mostly maintaining it as newer versions are released on PyPI. There are almost over 70 libraries that I am associated with. So, a dedicated resource from your end will help ensure the conda-forge recipe doesn't fall behind.

**Comment by dvsrepo** [comment]
Thanks, @sugatoray, of course! Let us discuss this internally and make a decision. Thanks for your help!

**Comment by frascuchon** [comment]
Hi, @sugatoray I will manage newer versions. Do you need to give me some kind of access? I think I already have access to the old rubrix conda repository, but not sure.

**Comment by sugatoray** [comment]
@frascuchon Great. We will need a new conda-forge package for argila (the old rubrix package remains as is). 

Let's talk about this after this weekend.

**Comment by frascuchon** [comment]
Hi @sugatoray. How can we proceed with this? What do you need from my side for the setup?

**Comment by sugatoray** [comment]
@frascuchon Is there anyone from the core team who has had some experience with conda-forge packaging?

**Comment by davidberenstein1957** [comment]
@davidberenstein1957 remove conda references from the docs for now

**Comment by frascuchon** [comment]
Hi @sugatoray! 

Not really. I already have access to the old [feedstock repository](https://github.com/conda-forge/rubrix-feedstock), but I have no experience setting up a new one from scratch.

**Comment by davidberenstein1957** [comment]
@frascuchon I assigned the ticket to you for the overview.

**Comment by frascuchon** [comment]
Great! Thanks @davidberenstein1957

**Comment by sugatoray** [comment]
@frascuchon Could you please identify someone from the core Argilla team who will be a co-maintainer of the new feedstock repository for conda-forge presence of Argilla?

**Comment by frascuchon** [comment]
Hi @sugatoray!

Do you mean besides me? Could you also include @davidberenstein1957 

Let me know if you need something else

**Comment by sugatoray** [comment]
Hi @davidberenstein1957,

I will add you a co-maintainer as well. But, as I am pretty tight on my schedule nowadays, it will be preferable if both of you could create a conda-forge recipe, once am done creating the package. I am the maintainer of 70+ packages. And collaborating with upstream repositories is the only way to scale and maintain these packages. 

Please don't remove the conda related install instructions. Just comment them out. Once the package is released, all you would need is uncommenting.

**Comment by sugatoray** [comment]
@frascuchon Does argilla need argilla-server or it's the other way around?

@dvsrepo I have a good news for you... Yesterday I added `arguilla` and `distilabel` to conda-forge. 

- https://github.com/conda-forge/staged-recipes/pull/25552
- https://github.com/conda-forge/staged-recipes/pull/25553

I will soon make an announcement of the packages' availabilities on LinkedIn and X. However, it would be comforting if someone from the core team could test these packages by installing from conda-forge first.

```sh
# install argilla
conda install -c conda-forge argilla
# install distilabel
conda install -c conda-forge distilabel
```

:bulb: I will send two PRs to `argilla` and `distilabel` to update the docs and README.

**Comment by davidberenstein1957** [comment]
@gabrielmbmb @alvarobartt

**Comment by nataliaElv** [comment]
@frascuchon @davidberenstein1957 Was this issue solved or is there still work to do here?

**Comment by davidberenstein1957** [comment]
It was not, but I think we can close the issue for now, and re-evaluate based on the need from the community for a publishment in the conda repos to reduce overhead in maintenance.
