### ISSUE TITLE
docs: missing reference to record card: improve access to labels list for TextClassification

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1949]
Describe the bug
https://github.com/argilla-io/argilla/issues/1877

To Reproduce
N.A.

Expected behavior
N.A.

Screenshots
N.A.

Environment (please complete the following information):
N.A.

Additional context
N.A.

**Comment by dvsrepo** [comment]
I would remove the bug tag from this issue as it's more an enhancement to the docs

**Comment by Amelie-V** [comment]
@davidberenstein1957 related to #1804
