### ISSUE TITLE
docs: First code example in docstring for rg.load not showing correctly

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1951]
**Describe the bug**
The first example for https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.load is not correctly rendered, likely a newline, whitespace or indentation problem

**To Reproduce**
Go to https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.load and check the first example. It should show. a highlighted code block

**Expected behavior**
Render the code snippet as with other examples

**Additional context**
This should be fixed in the docstring of the load method and check the rest of the methods and models in https://docs.argilla.io/en/latest/reference/python/python_client.html to make sure this is not happening in other places

**Comment by ufukhurriyetoglu** [comment]
I see, ok :+1:
