### ISSUE TITLE
question: prepare_for_training reference doc not showing framework param in latest docs

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1952]
AFAIK we have the prepare_for_training with the framework param since a few releases. However I cannot see the correct docstring in the docs: https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.client.datasets.DatasetForTextClassification.prepare_for_training

The docstring is correct here: https://github.com/argilla-io/argilla/blob/6264983ca4c42338c010bf72e862e5ccbaf18c60/src/argilla/client/datasets.py#L793

Any ideas? or is this expected and will be shown in the upcoming release?

**Comment by frascuchon** [comment]
The `prepare_for_training` method with parameters is only defined for token classification datasets, and it is shown in docs:

https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.client.datasets.DatasetForTokenClassification.prepare_for_training

**Comment by dvsrepo** [comment]
Now I see! Thanks!
