### ISSUE TITLE
Predicted filter not working for token classification

### ISSUE THREAD

**Issue by feddevanderlijn** [recognai/rubrix#1955]
**Describe the bug**
When querying for `ko` on a token classification set, the client returns many records for which all tokens have been correctly tagged. 
 
**To Reproduce**
1. Compile a dataset for a tokenclassification task, including annotations and predictions and log it to argilla. Make sure to  also include a score for the predictions.  
2. Load all records with query="predicted:ko" 
3. Verify that this will include records for which all tokens have been correctly predicted. 
4. Verify that the ko records only include those records without any prediction or annotation.

**Expected behavior**
I would expect to see only records with at least one wrongly predicted token.

**Screenshots**
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/3964971/203800834-1f1fe0bb-a53b-4abb-855e-826fd56031a0.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: 
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]: 1.0.1
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by davidberenstein1957** [comment]
@feddevanderlijn Thanks for the feedback!

**Comment by dvsrepo** [comment]
@feddevanderlijn thanks! 

I believe this is caused by the clause `==` with predicted entities with scores which become different tuples to those in the annotation (which don't have a score): 

https://github.com/argilla-io/argilla/blob/a3bc55480400455a22dbb3b329d0329623342a72/src/argilla/server/services/tasks/token_classification/model.py#L146

**Comment by davidberenstein1957** [comment]
@frascuchon I updated the docs about reindexing #2076

**Comment by frascuchon** [comment]
Great! Very helpful!!! Thanks a lot @davidberenstein1957
