### ISSUE TITLE
Weak supervision for token classification metrics

### ISSUE THREAD

**Issue by keithCuniah** [recognai/rubrix#1959]
refs #1767 

I have a suggestion to validate : 

When there is no query, the component Rules Metric doesn't have the total number of coverage and total annotated coverage. 
So to keep an atomic design,  is it possible to show at the initialization the Rules Metric like this : 

![image](https://user-images.githubusercontent.com/88380932/203836306-81e93f65-9791-490a-b871-02e79d016de5.png)

It's different from the **TextClassification**, since the totals are already showned 
![image](https://user-images.githubusercontent.com/88380932/203836512-ef28e110-388b-4b10-bc5c-f0f6e490e4a3.png)

**Comment by dvsrepo** [comment]
I like your suggestion! and I would apply it also to the TextClassification view, let's see what the others think

**Comment by Amelie-V** [comment]
Agree!

**Comment by frascuchon** [comment]
This is related to the weak label changes for the Text classification task, right?

**Comment by keithCuniah** [comment]
This behavior was only in Token Classification but it will be put in text classification too

**Comment by frascuchon** [comment]
Refs #1749
