### ISSUE TITLE
feat: show multi-label classification labels together in exploration mode

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1963]
**Is your feature request related to a problem? Please describe.**
one label is shown in the bottom left corner, and the rest of the labels are shown in the upper right corner. To me, this comes across as a bit confusing and takes a additional effort to thee and assess the assigned labels.

**Describe the solution you'd like**
I would expect all labels to show in the bottom left corner.

**Describe alternatives you've considered**
N.A.

**Additional context**
![image](https://user-images.githubusercontent.com/25269220/204033129-307abab9-1272-48e7-8968-919aacb753f7.png)

**Comment by Amelie-V** [comment]
In explore view, on the right side, this is the annotation "GOOD AND SERVICES", below the record text, in the screenshot "SHELTER" is the prediction.
