### ISSUE TITLE
Extra query search requests using the cursor to move in query text characters

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#1976]
**Describe the bug**
Moving through the search input box using the keyboard cursor applies a query request, even if the query text didn't change

**To Reproduce**

https://user-images.githubusercontent.com/2518789/204311490-873f036d-da13-4dd3-a6ee-478fb796d41d.mov

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]: mac OS
 - Browser [e.g. chrome, safari]: chorme
 - Argilla Version [e.g. 1.0.0]: 1.1.0
 - ElasticSearch Version [e.g. 7.10.2]: -
 - Docker Image (optional) [e.g. argilla:v1.0.0]: -

**Additional context**

**Comment by leiyre** [comment]
@frascuchon this is because the pagination, we can disable it when we are in a textarea or input
