### ISSUE TITLE
feat: revert changes renaming text2text to textgeneration

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#1979]
**Is your feature request related to a problem? Please describe.**
Renaming Text2Text to TextGeneration will take a bit more work than is worth the effort for a subjective benefit. Therefore the partial changes will be re-verted.

**Describe the solution you'd like**
N.A.

**Describe alternatives you've considered**
N.A.

**Additional context**
#1819 #1775

**Comment by frascuchon** [comment]
Fixed by #1980
