### ISSUE TITLE
Tag relations between spans of tokens

### ISSUE THREAD

**Issue by rdaniel** [recognai/rubrix#1987]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
@rdaniel I think this is a copy of https://github.com/argilla-io/argilla/issues/1839. Correct? If so, could you provide some context and input within that issue?

**Comment by davidberenstein1957** [comment]
@closed in favor of #1839
