### ISSUE TITLE
[Dataset settings] New section in UI

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2003]
We need to change the front-end part to create new labels by using the labeling schema already defined as part of the dataset settings.

Including these changes, we need to think about how to restrict the use of label creation to users.

cc @dvsrepo 

# Updated

This view cannot be visible for ALL users. For example, for now, the "Create label" button is only shown when no settings resource is found (from an API call), or deleting a dataset is only possible for dataset creators.

The condition will be (until argilla has no user role assignment):

Show dataset settings view only for users that have created the dataset (cc @dvsrepo)

Also, we should unify the current labels schema to the settings resource (cc @keithCuniah @leiyre )

# Tasks
- [x] #2210  
- [x] #2368
- [x] #2369
- [x] #2370
- [x] #2371
- [x] #2372

**Comment by Amelie-V** [comment]
We will create a proper area for dataset settings. The two main sets accessible to users from the UI are:

- Label creation
- Delete dataset

These two features already exist on the UI.

It consists of relocating them into a dedicated page.

**Comment by frascuchon** [comment]
Refs [#1854](https://github.com/argilla-io/argilla/issues/1854)

**Comment by frascuchon** [comment]
@keithCuniah  see https://github.com/argilla-io/argilla/blob/develop/frontend/models/Dataset.js#L22 references for the action migration
