### ISSUE TITLE
too verbose failure logging during failed `rg.log()` (with too large chunk_size)

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2005]
**Describe the bug**
The terminal gets bombarded with the complete records after failed logging attempts. When logging a lot of records or larger records, this is problematic because it freezes the IDE and doesn´t really stop.

Also the `rg.log` generally failed a lot with larger chunk_sizes, however, instead of failing so easily, I would initially expect this to just influence speed and only fail after a relatively large timeout (60s?).

**To Reproduce**
1. Go to Any arbitrary large dataset with larger records for example `news-fakenews`within our pre-release.
2. upload data via `rg.log()`with a chunk size larger than 100
3. it starts failing after a while

**Expected behavior**
I would expect to get a message `# records with IDs x,y,z have failed` to process. Or a response item that contains the failed / processed record info.

**Screenshots**
N.A.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: iOS
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.1.1.
 - ElasticSearch Version [e.g. 7.10.2]:7.10.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.1.1

**Additional context**
Not the finicky failure behaviour of the logging with larger chunk sizes.

**Comment by davidberenstein1957** [comment]
This issue is partially related to the failure representation `cannot log() + very long record string + Error of type <class ‘RuntimeError’>` and partially tot the ingress/timeout settings of our deployment/client connection.

**Comment by davidberenstein1957** [comment]
Partially covered here https://github.com/argilla-io/argilla/pull/2148.

**Comment by frascuchon** [comment]
Ref: #2208
