### ISSUE TITLE
no label is created in the UI for labelled prediction from `TokenClassificationRecord` after creating a new dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2006]
**Describe the bug**
After creating a new `TokenClassification` with predictions. No labels are created within the UI yet. They only show after manual creation.

**To Reproduce**
1. Upload TokenClassificationRecords with prediction labels to a new dataset
2. Go to the UI
3. No created labels in UI

**Expected behavior**
I would expect the labels to have been made for me.

**Screenshots**
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/25269220/206139285-09a7f978-5f5c-411a-8739-ed0f98965ae9.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: iOS
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.0.0
 - ElasticSearch Version [e.g. 7.10.2]: 7.10.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.0.0

**Additional context**
N.A:

**Comment by Amelie-V** [comment]
Thanks @davidberenstein1957

**Comment by davidberenstein1957** [comment]
Couldn´t reproduce this in DEV or PRE.
