### ISSUE TITLE
dataset pagination only allows to show first 10K records

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2007]
**Describe the bug**
I uploaded 21K records to a dataset and it only show 10K within the UI. Also, it doesn't allow me to paginate past the first 10K records without adding queries.

**To Reproduce**
1. Upload more than 10K records
2. Go to the dataset in the UI
3. Try to go past 10K record in pagination

**Expected behavior**
I would expect the record to be available or at least get a reference on why not all records are shown.

**Screenshots**
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25269220/206142097-71000701-9e03-44f5-9f3b-c8a59ffccef6.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: iOS
 - Browser [e.g. chrome, safari]: Firefeox
 - Argilla Version [e.g. 1.0.0]: 1.1.1
 - ElasticSearch Version [e.g. 7.10.2]:7.10.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.1.1

**Additional context**
N.A.

**Comment by frascuchon** [comment]
@leiyre @Amelie-V  we need to take into account this use case after removing the Records count in the filters header.

**Comment by davidberenstein1957** [comment]
Given that we can get the total number of records via Elastic, is seeing only 1000 pages a UI memory issue or something? If so, wouldn´t we be able to lazy-load only a part of the pages? The X surrounding pages for each one of the pages that we can directly click on? 

In the example above, we can directly click 1,2,3 and 1000, with X=3 we could load 1,2,3,4,5,6, 997,998,999,1000.
