### ISSUE TITLE
[Similarity search] Documentation guide will include HOWTO migrate to elasticsearch 8.5

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2028]

**Comment by davidberenstein1957** [comment]
Thanks, I will take a look at this next week.

**Comment by dvsrepo** [comment]
@frascuchon for this we will need your inputs about the content you think is important to cover

**Comment by frascuchon** [comment]
For sure, 

Here, we need to think about how to provide the server setup to users. 

If we decide to change the Setup & installation guides and point to the elasticsearch 8.5.x as the new backend engine for argilla, we need to warn and inform that manual data migration is needed. Then, we can refer to a new section on how to migrate data from elasticsearch 7.10 (I think this is the current one) to 8.5

If the docs remain the same and we add the backend configuration only in the new Similarity search section, we should warn there that data migration is needed if you have already datasets with previous argilla versions.

For both cases, the migration steps would be as follow (I will include the real step once the PR is created)

1. Stop your current elasticsearch service (we assume a migration for docker-compose setup)
2. Update elasticsearch image to 7.17.x
3. Start the elasticsearch service again.
4. Once is up and running, stop it again and set the es image to 8.5.x
5. Finally, start again the elasticsearch service. Data should be migrated properly.

Additionally, we can add a reference to the official elasticsearch migration guide https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.5.html

**Comment by dvsrepo** [comment]
Being tackled here #2060

TODOs:

- [x] @frascuchon add the real steps and some comments to the Similarity guide notebook in #2060
- [x] @dvsrepo maybe change the docker image in setup and a section on migration from 7.10 (need to test this once the steps are defined). Make sure we point to the different docker-compose files in the docs.
- [x] @davidberenstein1957 quick review of guide in #2060 and make sure it's added on the right place(s)
- [x] @Amelie-V @leiyre prepare a screenshot (or several) to add to the Argilla UI reference documentation. Send to @dvsrepo to add them

**Comment by dvsrepo** [comment]
Only pending thing:

- [ ] @frascuchon review deep dive section about OS and ES setup

**Comment by dvsrepo** [comment]
@frascuchon : this issue is duplicated we have several issues for docs. Please review what's left and close them accordingly. I will not add more docs for now
