### ISSUE TITLE
feat: add `str` and `__repr__` methods to Argilla classes like `Rule` and `Datasets`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2046]
**Is your feature request related to a problem? Please describe.**
I wanted to review some general information about data I was creating but wasn`t able to conveniently print this. Now I see this when printing a Rule for example, `<argilla.labeling.text_classification.rule.Rule at 0x3a6950640>`.

**Describe the solution you'd like**
I would like to see something like `pandas.DataFrame`for our `Dataset` and a similar implementation for `Rule`.

**Describe alternatives you've considered**
N.A.

**Additional context**
https://www.educative.io/answers/what-is-the-repr-method-in-python

**Comment by Ankush-Chander** [comment]
Hi @davidberenstein1957 ,
I would like to take it up(after coming back from vacations).

@frascuchon

**Comment by davidberenstein1957** [comment]
Hi @Ankush-Chander great that you want to pick this up! When will you come back from vacation? I will schedule a scoping meeting with @frascuchon about the requirements and then I can potentially walk you through it:)

Have you already seen our new [contributor guidelines](https://docs.argilla.io/en/latest/community/contributing.html)? What do you think about them? 🤓

**Comment by davidberenstein1957** [comment]
By the way, suggestions for the requirements are always welcome. I already identified 2 classes `Rule` and `Dataset` however, there probably might be more classes. Also, as a user, how would you like them to be represented?

**Comment by Ankush-Chander** [comment]
@davidberenstein1957 I will be back in Jan first week. Will ping back for/with more details.

**Comment by Ankush-Chander** [comment]
Hi David
Contibution guidelines are superb. 

I am thinking of putting `representation strings` as following: 
1.Rule class is simple hence it"s representation is somthing that helps user recreate that object.
2. datasets classes resembles more to dataframes so they can be represented in tabular form

```
import argilla as rg
from argilla.labeling.text_classification.rule import Rule

plz = Rule(query="plz OR please", label="SPAM")
print(repr(plz))
>>> Rule(query='plz OR please', label='SPAM', name='plz OR please')


records = [
        rg.TextClassificationRecord(text="example"),
        rg.TextClassificationRecord(text="another example"),
        rg.TextClassificationRecord(text="another example another example another example another example another example another example"),
    ]
dataset = rg.DatasetForTextClassification(records=records)
print(dataset)
>>>
    	text                          	annotation	prediction
0   	example                       	None      	None      
1   	another example               	None      	None      
2   	another example another exampl	None      	None      
...
3 TextClassificationRecord records
```
Let me know of your thoughts. I will add similar method for other type of datasets.

**Comment by frascuchon** [comment]
Hi, @Ankush-Chander, and thanks for your contribution.

It looks fine to me what you propose for datasets and, rules. Let me know if you need anything else to go on with this PR
