### ISSUE TITLE
`argilla.labeling.text_classification` rule-methods result in `argilla.api.errors::EntityNotFoundError`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2048]
**Describe the bug**
I cannot create rules and get an `argilla.api.errors::EntityNotFoundError`  when trying to do so via `update_rules`.

**To Reproduce**
```
from argilla.labeling.text_classification import Rule

rules_dict = {
    "room": ["room*", "bed", "bathroom", "tv", "towel*", "spacious"],
    "food": ["breakfast", "food", "restaurant*", "buffet", "drinks", "coffee"],
    "hygiene": ["clean*", "dirty", "fresh", "concierge", "spotless"],
    "service": ["gym", "bar", "pool", "sport*", "internet", "parking", "spa"],
    "staff": ["staff", "service", "friendly", "reception"],
    "price": ["cheap*", "price", "rate", "cost", "expensive"],
    "location": ["location*", "statio*", "beach", "city", "airport" "located", "central"]
}
rules = []
for key, value in rules_dict.items():
    for word in value:
        rules.append(Rule(word, key))

from argilla.labeling.text_classification import WeakMultiLabels, add_rules, delete_rules, update_rules

# Compute the weak labels for our dataset given the rules.
# If your dataset already contains rules you can omit the rules argument.

update_rules(dataset="tripadvisor-hotel-domains", rules=rules)
```
```
NotFoundApiError                          Traceback (most recent call last)
Cell In[104], line 6
      1 from argilla.labeling.text_classification import WeakMultiLabels, add_rules, delete_rules, update_rules
      3 # Compute the weak labels for our dataset given the rules.
      4 # If your dataset already contains rules you can omit the rules argument.
----> 6 update_rules(dataset="tripadvisor-hotel-domains", rules=rules)

argilla/labeling/text_classification/rule.py:212, in update_rules(dataset, rules)
    203 """Updates the rules of the given dataset
    204 
    205 Args:
   (...)
    209 Returns:
    210 """
    211 rules = [rule._convert_to_labeling_rule() for rule in rules]
--> 212 api.active_api().update_dataset_labeling_rules(dataset, rules)

argilla/client/api.py:623, in Api.update_dataset_labeling_rules(self, dataset, rules)
    621 """Updates the dataset labeling rules"""
    622 for rule in rules:
--> 623     text_classification_api.update_dataset_labeling_rule(
    624         self._client, name=dataset, rule=rule
    625     )
...
     59     error_type = MethodNotAllowedApiError
---> 61 raise error_type(**error_args)

NotFoundApiError: Argilla server returned an error with http status: 404
Error details: [{'code': 'argilla.api.errors::EntityNotFoundError', 'params': {'name': 'location*', 'type': 'ServiceLabelingRule'}}]
```
**Expected behavior**
The rules to be created.

**Screenshots**
N.A.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.1.1
 - ElasticSearch Version [e.g. 7.10.2]: PRE
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.1.1

**Additional context**
N.A:

**Comment by dvsrepo** [comment]
Hi @davidberenstein1957 does it work if use `add_rules` instead of `update_rules`?

**Comment by davidberenstein1957** [comment]
Neither work. Both `add_rules` instead of `update_rules` result in the same error. And all other functions with weak supervision do work.

**Comment by dvsrepo** [comment]
it's weird because this works for me on 1.1.0

```python
from argilla.labeling.text_classification import Rule
import argilla as rg

from argilla.labeling.text_classification import add_rules

rules_dict = {
    "room": ["room*", "bed", "bathroom", "tv", "towel*", "spacious"],
    "food": ["breakfast", "food", "restaurant*", "buffet", "drinks", "coffee"],
    "hygiene": ["clean*", "dirty", "fresh", "concierge", "spotless"],
    "service": ["gym", "bar", "pool", "sport*", "internet", "parking", "spa"],
    "staff": ["staff", "service", "friendly", "reception"],
    "price": ["cheap*", "price", "rate", "cost", "expensive"],
    "location": ["location*", "statio*", "beach", "city", "airport" "located", "central"]
}
rules = []
for key, value in rules_dict.items():
    for word in value:
        rules.append(Rule(word, key))
        
rg.log(name="my_dataset", records=rg.TextClassificationRecord(text="not good experience"))
          
# Define labeling schema
settings = rg.TextClassificationSettings(label_schema=list(rules_dict.keys()))

# Apply settings to a new or already existing dataset
rg.configure_dataset(name="my_dataset", settings=settings)

add_rules(dataset="my_dataset", rules=rules)
```
@frascuchon any idea?

**Comment by frascuchon** [comment]
I think you're using the wrong function. Did you try `add_rules` instead of `update_rules ` @davidberenstein1957 ?

```python
# Compute the weak labels for our dataset given the rules.
# If your dataset already contains rules you can omit the rules argument.

update_rules(dataset="tripadvisor-hotel-domains", rules=rules) # <---- HERE
```

**Comment by davidberenstein1957** [comment]
Yes, I retried it myself too now. 
I had a dict with duplicate values i.e. rules, therefore it failed to create them via `add_rules` and I tried to use `update_rules, which then failed due to not all rules being present yet. For me, this behavior is bit unclear, so perhaps it  makes more sense to provide warning is such cases?

In case of `add_rules` -> `You are over-writing this specific rules`
In case of `update_rules` -> `Rule wasn´t present yet, but has now been created.`

Or at least provide a bit more intuitive error message?

**Comment by frascuchon** [comment]
Mmm not sure to understand completely.

`add_rules` will overwrite existing rules and `update_rules` will create those that didn't exists?

In that case, what is the difference between both functions?

The current behavior is as follows:

`add_rules` will create new rules and will fail if the rule exists
`update_rules` will update existing rules and fail if the rule does not exist.

Maybe we can have a 3rd function combining both ones: 

`upsert_rules` will create if the rule does not exist and will update it if it already exists.

**Comment by davidberenstein1957** [comment]
Yes, I think `upsert_rules` behaviour is preferable. Especially, because rules are weak by nature, and there can be a lot of overlap even though they are not exactly the same. 

`add_rules` also allows creating `[Rule("w*", "class") Rule("we*", "class") Rule("wea*", "class") Rule("weak", "class")]` without errors, even though they heavily overlap, so perhaps raising an `Exception` is overkill and/or  we could add logging/warnings instead:
If a rules is present
`add_rules` -> `warnings.warn(You are trying to over-writing this specific rules)`
If a rules is not present 
`update_rules` -> `warnings.warn(Rule wasn´t present yet, first create it)`

or we could add a `force` flag to `add_rules` and `update_rules`. 
`add_rules` -> `warnings.warn(You are trying to over-writing this specific rules or set force=True to overrule this.)`
`update_rules` -> `warnings.warn(Rule wasn´t present yet, first create it or set force=True to overrule this.)`
