### ISSUE TITLE
bug: UI query highlights do work correctly and include `query+*` highlights

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2049]
**Describe the bug**
When querying for "spa" all of the instances of "spa*" in the records are highlighted.

**To Reproduce**
1. Go to the PRE dataset tripadvisor-hotel-domains
2. Click on query "spa"

**Expected behavior**
I would expect only to see the actual matches.

**Screenshots**
![Screenshot 2022-12-15 at 10-42-01 Argilla](https://user-images.githubusercontent.com/25269220/207826398-eff94d1d-04b0-44f9-a572-2a64f1a3e644.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.1.1
 - ElasticSearch Version [e.g. 7.10.2]: PRE
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.1.1

**Additional context**
N.A.

**Comment by Amelie-V** [comment]
@leiyre can you confirm that this issue needs to be tested and in which environment? Thanks :)

**Comment by leiyre** [comment]
@Amelie-V  Yes, some other problems have appeared after fixing it

**Comment by frascuchon** [comment]
@leiyre @davidberenstein1957 can you confirm this still happens? Changes introduced in https://github.com/argilla-io/argilla/pull/3621 could fix also this issue

**Comment by Amelie-V** [comment]
Tested on dev environment: still not solved: 
Dataset : metadata_example
View ss: 

![Image](https://github.com/argilla-io/argilla/assets/84135211/c953d4b2-4524-4b70-9057-ff2ba1cc9c1f)
