### ISSUE TITLE
feat: retrieve dataset settings along with dataset during `rg.load`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2051]
**Is your feature request related to a problem? Please describe.**
It takes additional effort to retrieve the setting, even though a lot of information is widely used.

**Describe the solution you'd like**
A variable `settings` is assigned to dataset classes that contain their setting.

**Describe alternatives you've considered**
N.A.

**Additional context**
could improve #2046

**Comment by davidberenstein1957** [comment]
This can also be used within the `to_datasets`, for assigning `.features` and label info.

**Comment by davidberenstein1957** [comment]
closed in favor of https://github.com/argilla-io/argilla/issues/2379

**Comment by nataliaElv** [comment]
@davidberenstein1957 would you say this issue is still relevant for 2.0?

**Comment by davidberenstein1957** [comment]
This ia already covered by the awesome changes from @burtenshaw

**Comment by nataliaElv** [comment]
Amazing! 😃 I'm closing it then
