### ISSUE TITLE
feat: integrate helper buttons with `.md` directly from docs.

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2053]
**Is your feature request related to a problem? Please describe.**
It takes time and effort to keep the helper button up to date and information is scattered throughout many places.

**Describe the solution you'd like**
Ideally, we would like to align the helper button info the actual doc markdown to update info directly from there.

**Describe alternatives you've considered**
N.A.

**Additional context**
Perhaps it is also worthwhile to look into linking other parts from the docs, like queries https://docs.argilla.io/en/latest/guides/features/queries.html?highlight=query etc.

**Comment by nataliaElv** [comment]
This is being addressed in #2438, so I'm closing this issue.
