### ISSUE TITLE
ARGILLA_API_KEY is different in documentation and codebase

### ISSUE THREAD

**Issue by rhoitjadhav** [recognai/rubrix#2074]
## Description
In the [python client](https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.init) and [user management](https://docs.argilla.io/en/latest/getting_started/installation/user_management.html#default-user) document section, `api_key` is different in documentation and codebase. Please find the screenshot of the documentation and codebase for reference. This needs to be updated to `argilla.apikey`, but this also needs to be backward compatible with older versions.

## Screenshots
1. [Codebase](https://github.com/argilla-io/argilla/blob/develop/src/argilla/_constants.py#L21)
![image](https://user-images.githubusercontent.com/25402160/208429835-bfc7597a-01de-4abe-a99a-75028aa9637d.png)

2. Python Client section

![image](https://user-images.githubusercontent.com/25402160/208429935-70aae3ea-cc46-4e95-bcc3-12406606cbf7.png)

3. User Management section

![image](https://user-images.githubusercontent.com/25402160/209956331-6885ae83-ccb8-4979-a3b8-9074d0646afa.png)

## Environment
 - OS: MacOS
 - Browser: Chrome
 - Argilla Version:
 - ElasticSearch Version: 7.10.2
 - Docker Image: argilla/argilla-server:pr-2057

**Comment by davidberenstein1957** [comment]
@rhoitjadhav good catch 🕵️

**Comment by davidberenstein1957** [comment]
@frascuchon I believe we don`t want to upgrade the API key because Rubrix instalments would still expect the old key, right? So in that case we would require the docs to be updated?

**Comment by rhoitjadhav** [comment]
Also found the same [here](https://docs.argilla.io/en/latest/getting_started/installation/user_management.html#default-user). Please check screeshots for reference.

**Comment by rhoitjadhav** [comment]
@davidberenstein1957, thanks for making the changes, however these changes won't reflect on documentation as it loads the data from `main` branch and I can see that you have merged the changes on `develop` branch.

**Comment by davidberenstein1957** [comment]
Yes, I know, but the changes also impacted the python client docstring, so I chose to add them to `develop` instead 🙂.

**Comment by dvsrepo** [comment]
Hi @rhoitjadhav and @frascuchon:

We now have an inconsistency for the argilla user, between the quickstart docker image and the local default installation:

- docker quickstart image: `argilla.apikey`
- local default deployment: `rubrix.apikey`

This causes friction in terms of having the tutorials easy to run on both deployments, something I highlighted during all our discussions about Spaces and quickstart: default values should be consistent and we should avoid asking the users too much if they are using different installations to get started.

I think it would be a good idea to update the default apikey to argilla.apikey and updating the docs mentioned on this issue accordingly. @frascuchon as it's been some time since we switched to Argilla, do you see any problem? Or is this going to cause issues on servers running Argilla?

**Comment by dvsrepo** [comment]
Another option is to change the value of the quickstart  docker `rubrix.apikey`. What we cannot do is to include in dozens of documents and tutorials: If you are running the Argilla server locally use this apikey, if you are running the quickstart docker image use this other apikey.

Whatever is easier and causes fewer problems

**Comment by frascuchon** [comment]
To avoid problems with recent clients, we need to allow also access with new API Key and remove the old one in 2 releases. 

I will create 2 issues: one for this release one for 1.5.0
Untill this, better to align both system to current API key. @rhoitjadhav please update quick start API key to rubrix.apikey

**Comment by dvsrepo** [comment]
Sounds great 👍

**Comment by rhoitjadhav** [comment]
@frascuchon Cool. I will create a PR for the same. Should I create a branch from `main` or `develop`?

**Comment by dvsrepo** [comment]
Thanks, @rhoitjadhav !

**Comment by frascuchon** [comment]
> @frascuchon Cool. I will create a PR for the same. Should I create a branch from `main` or `develop`?

If this will affect the official docs, better point to main, we will update the latest image with new changes
