### ISSUE TITLE
Change DatasetForTextGeneration to DatasetForText2Text

### ISSUE THREAD

**Issue by rhoitjadhav** [recognai/rubrix#2089]
## Description
In the [documentation](https://docs.argilla.io/en/latest/guides/features/datasets.html#Importing-a-Dataset), I see `DatasetForTextGeneration` is used which needs to be changed to `DatasetForText2Text`. 

## Screenshots
![image](https://user-images.githubusercontent.com/25402160/209133975-ba0ad24c-532d-4265-9500-fb1496530894.png)

**Comment by dvsrepo** [comment]
Thanks for noticing, can you do a PR to fix this?

**Comment by rhoitjadhav** [comment]
Created [PR](https://github.com/argilla-io/argilla/pull/2090). Please review

**Comment by davidberenstein1957** [comment]
Hi, I believe this change is already implemented in `development`

**Comment by rhoitjadhav** [comment]
@davidberenstein1957 you are right but its not in `main` branch and that's where the documentation page loads the data. Please correct me if any

**Comment by dvsrepo** [comment]
Yes, according to the development flow guide, fixes in the docs should go to `main`.
