### ISSUE TITLE
Add documentation to provide examples of how to run prepare_for_training for a specific framework

### ISSUE THREAD

**Issue by mgiardinelli** [recognai/rubrix#2107]
**Is your feature request related to a problem? Please describe.**
It wasn't easy to understand what to apply to the "prepare_for_training" method that will generate data for a specific framework (i.e. spaCy). I am submitting this at the request of David Berenstein (from Slack post). 

**Describe the solution you'd like**
Add documentation and examples for the prominent frameworks - spaCy, HuggingFace, etc. 

**Additional context**
An end-to-end example for this, like many others provided, would be really valuable. Upload data, label the data, prepare for training, train model, upload results -> rinse & repeat.

**Comment by davidberenstein1957** [comment]
Thanks @mgiardinelli I will create a PR for this and would love to get your feedback on it:)

**Comment by davidberenstein1957** [comment]
@mgiardinelli I added a PR with additional documentation you can check [here](https://docs.argilla.io/en/docs-2107-add-documentation-to-provide-examples-of-how-to-run-prepare_for_training-for-a-specific-framework/guides/features/datasets.html#Prepare-dataset-for-training). 

Additionally, I noticed we did not implement a method for doing this with TextClassification so I decided to create [an issue](https://github.com/argilla-io/argilla/issues/2122) for this. Do you feel this needs to be added and even better, do you think you could handle this in a PR yourself? 🤓
