### ISSUE TITLE
error while logging data post setup

### ISSUE THREAD

**Issue by abhishek1982228** [recognai/rubrix#2108]
**Describe the bug**
import argilla as rg

rg.log(
    rg.TextClassificationRecord(text="My first Argilla example"),
    name='example-dataset'
)

running on above scripts, server return following error.

argilla.client.sdk.commons.errors.GenericApiError: Argilla server returned an error with http status: 500
Error details: [{'code': 'argilla.api.errors::GenericServerError', 'params': {'type': 'argilla.server.daos.backend.elasticsearch.GenericSearchError', 'message': "TransportError(503, 'search_phase_execution_exception', None)"}}]
  0%|                                                                                                                                                                                       | 0/1 [00:05<?, ?it/s]

**Expected behavior**
data should be visible on app. a dataset is created on the app but with message "We cannot currently access example-dataset due to the following error: Request failed with status code 500"

**Screenshots**
![Capture](https://user-images.githubusercontent.com/49139826/210050060-709ef6f3-a43b-4763-bb18-f447a62e9b83.PNG)

**Environment (please complete the following information):**
 - OS : windows
 - Browser : chrome
 - Argilla Version : 1.1.1
 - ElasticSearch Version : 8.4.1
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Comment by dvsrepo** [comment]
thanks for reporting @abhishek1982228 do you have access to the server logs (the ones where you see the HTTP traces after running python -m argilla or the docker-compose up)? If you could share those, they usually contain more info.

**Comment by abhishek1982228** [comment]
Hi Daniel.
Thanks for your reply. Actually it was a space issue on my C drive which is causing problem. By the way can you help me out to locate the stored server logs (in case any) for any future reference? I am running this app on local.

**Comment by davidberenstein1957** [comment]
Hi, you can use `docker logs elasticsearch-for-argilla`
