### ISSUE TITLE
Gap between the records when changing the view mode

### ISSUE THREAD

**Issue by leiyre** [recognai/rubrix#2110]
**Describe the bug**
Virtual scroll does not update the size of records correctly when changing the view mode

**To Reproduce**
1. Go to a dataset where records size is different in explore and annotate
2. Change view mode

**Expected behavior**
Render record list without gaps between the items

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**
One option is to re-render the list when changing the view mode, but with this method the scroll position will be reset

**Comment by nataliaElv** [comment]
@leiyre Is this issue relevant for Argilla 2.0? If not, I think we can close it.
