### ISSUE TITLE
🍓 Rules page takes lot of time to load

### ISSUE THREAD

**Issue by rhoitjadhav** [recognai/rubrix#2117]
## Description
When we have more rules (e.g 100, 1000), the Rules page takes lot of time to load as it fetches all the rules which are present in the database.̉ 

## To Reproduce
1. Add 100 rules through python client or server api
2. Go to the corresponding dataset which we add rules.
3. Enter on _Weak Labeling_ mode, the **Manage Rules** button would be in disable state since all the rules are not loaded yet. Once they are loaded it will be enabled and we can click on the button.

## Expected behavior
It's obvious that it takes lot of time, but to avoid this kind of issues we should implement **pagination** so that it will fetch only certain amount of records per request.

## Screenshots

1. Fetching all rules at once
![image](https://user-images.githubusercontent.com/25402160/210208942-4f29bfa3-382d-445e-9a2d-394f55505ed9.png)

2. Manage Rules button in disable state
![image](https://user-images.githubusercontent.com/25402160/210208971-f5a5c4ac-9f9b-43d7-bbd3-f8d69b91325a.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by davidberenstein1957** [comment]
@rhoitjadhav wouldn't also be logical to create generalized versions of the rules, whenever possible? 

you might be able to generalize some of the rules using wildcard? or by setting up operator like `WORD*` or `WORD~` `WORD1 OR WORD2`.

**Comment by keithCuniah** [comment]
It would be interesting to put the loaded rules in a specific vexorm tables (see development in weak labellings)
