### ISSUE TITLE
fix messy branches on tutorials about gpt3 and setfit

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2127]
**Is your feature request related to a problem? Please describe.**
the branches for [setfit](https://github.com/argilla-io/argilla/pull/2096) and [gpt3](https://github.com/argilla-io/argilla/pull/2095) tutorials got messy. 

**Describe the solution you'd like**
Create a new branch from `main`.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by dvsrepo** [comment]
Thanks for that 😅

**Comment by davidberenstein1957** [comment]
NP🤓
