### ISSUE TITLE
change password via UI

### ISSUE THREAD

**Issue by alanpaulkwan** [recognai/rubrix#2130]
I have tried EXPORT $ARGILLA....  and following the example closely, but to no avail. I am wondering if it would be better to just allow people to change their password/add users via a webform.

**Comment by davidberenstein1957** [comment]
Hi @alanpaulkwan, could you add a bit more context please? :)

@keithCuniah has been looking at OAuth measures, but for now this is scoped to our cloud offering. If you need help setting things up, we can also schedule a [calendly meeting](https://calendly.com/argilla-office-hours/30min).

**Comment by alanpaulkwan** [comment]
Hi yes, sorry.

 ```
htpasswd -nbB "" somepassword
:$2y$05$ihM/I5jjJTnOPeA1Br69I.kbjVnMzG6VUW0pBFyGFxSPHzdGwfr4q

 export ARGILLA_LOCAL_AUTH_DEFAULT_PASSWORD="$2y$05$ihM/I5jjJTnOPeA1Br69I.kbjVnMzG6VUW0pBFyGFxSPHzdGwfr4q"
```
 
I could either try this when running Argilla, or export it first locally then start Argilla under that user. I can't log in, it doesn't seem like the password has changed. Maybe I'm doing something wrong but it is a bit difficult to figure out. The user interface would be easier.

**Comment by davidberenstein1957** [comment]
Could it potentially be caused by [this issue ](https://github.com/argilla-io/argilla/issues/1879). I initially also had a problem with this. @frascuchon do you think we could possibly integrate this workflow in the Argilla package. This would allow us to add a check for `&`, or provide a more extensive example in our docs?

**Comment by dvsrepo** [comment]
I think is a great idea to have this workflow as an util of the package. I got this question very often and even had issues myself too 😃

**Comment by davidberenstein1957** [comment]
@alanpaulkwan I created a feature request for this. https://github.com/argilla-io/argilla/issues/2196 could you provide some input on what you think might work best?

**Comment by alanpaulkwan** [comment]
wow, thank you for following up. at the very extreme, Apache Superset is a great example. they create two constructs: roles + users. they pre-define both. when you start it, you use the default password and can at the top right, there is a "User Management" page where you can 

1. add users
2. edit a user, changing their password + role. For roles, there is a text box which auto-completes the role names.

For roles, there is Admin, Alpha, Gamma, etc. I guess if you wanted to be fully featured, I would imagine one would could imagine a user who can administer users, a user who can write to datasets, a user who can annotate, a user who can override other annotations etc.

**Comment by davidberenstein1957** [comment]
@Amelie-V more input regarding https://github.com/argilla-io/argilla/issues/1857
