### ISSUE TITLE
Replace dynamic scroller librairy by custom development

### ISSUE THREAD

**Issue by keithCuniah** [recognai/rubrix#2139]
**Is your feature request related to a problem? Please describe.**
To depend less on an external librairy and to have better performance, we could replace this librairy by a custom development

**Describe the solution you'd like**
This could be achived by using : 
- the intersectionObserver API : see this [video](https://www.youtube.com/watch?v=dozWGIgCWF8)
- offset and limit params in vuexorm record table (so we need to create that record table instead of getting record from dataset) : see this [link ](https://vuex-orm.org/guide/data/retrieving.html#limit-offset)

**Describe alternatives you've considered**

**Additional context**

**Comment by frascuchon** [comment]
Ref: #1817
