### ISSUE TITLE
[FEATURE] similarity search through `BM25` from within the UI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2150]
**Is your feature request related to a problem? Please describe.**
I do not want to set up anything for vector search but I do want to use it.

**Describe the solution you'd like**
I would like to see a very straightforward model-agnostic way of using the feature without any specific implementation. 
`DatasetSettings.vectorsearch_tf_idf` = True.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by dvsrepo** [comment]
@frascuchon couldn't we resort to https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html when the records don't have `dense_vectors` so we can enable the find similar button by default and handle the logic of whether to use `ann` or `mlt` depending of the availability of records?

**Comment by frascuchon** [comment]
Totally agree. Even if the underlying logic in this process is a bit different from vector search (unlike, field selection), you could unify the functionality from the UI.

**Comment by davidberenstein1957** [comment]
https://www.elastic.co/blog/found-bm-vs-lucene-default-similarity
https://www.infoq.com/articles/similarity-scoring-elasticsearch

Add a `BM25` similarity mapping to `argilla/server/daos/backend/mappings/helpers.py`  `text_field()`-methods.
Differentiate between raw LQL `query`, and `vector`, where `vector` can potentially be a more generic semantic query. 
Add `should` match field to the query send to ES. Inspiration: https://github.com/deepset-ai/haystack/blob/main/haystack/nodes/retriever/sparse.py

**Comment by davidberenstein1957** [comment]
Burshed up as proposed by Damien Tanner

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2443

**Comment by davidberenstein1957** [comment]
@frascuchon experimented with this and mentioned it did not work so well out of the box but it might be relevant to do some additional experimentation to allow for "find similar" out of the box from within the UI
