### ISSUE TITLE
Validated status of annotated data gets set prematurely in MultiLabelText Classification

### ISSUE THREAD

**Issue by dhruvsakalley** [recognai/rubrix#2160]
**Describe the bug**
In case of labeling for a multilabeled classification exercise, the logic of considering a datapoint validated if any one class is annotated is only partially correct. The action of marking a datapoint completely validated must be configurable to be explicit rather than just defaulting implicit.

**To Reproduce**
1. Create multilabel text classification exercise with significantly high number of labels
2. Make only one class selection validated gets toggled, other class annotations do not affect the status

**Expected behavior**
Validate behavior should be configurable to be explicit toggle in case of multilabel text classification

**Comment by dvsrepo** [comment]
Thanks @dhruvsakalley, this is important feedback and I fully agree with your views on this.

There's some redesign work going on, led by @Amelie-V, we'll link this feedback with that issue and get back to you.

**Comment by Amelie-V** [comment]
Hi, thanks for your feedback @dhruvsakalley!
We are improving annotation status logic on individual and bulk annotation actions.

**Comment by frascuchon** [comment]
Fixed in #2273
