### ISSUE TITLE
Following columns are not supported by the TextClassificationRecordModel and are ignored

### ISSUE THREAD

**Issue by Haller-x** [recognai/rubrix#2161]
I was trying to pass a pandas dataframe to the argilla.DatasetForTextClassification.from_pandas using a dataframe with only one column that contains only strings, but no matter what variation I make in the dataset, even if I import using the datasets module, I always come across the same error: `Following columns are not supported by the TextClassificationRecordModel and are ignored: ['Text']`

**To Reproduce**
import argilla as rg
dataset = rg.DatasetForTextClassification.from_pandas(dataset_text)
error:
Following columns are not supported by the TextClassificationRecordModel and are ignored: ['text']
And the dataset has no rows at all (my pandas dataframe has more than 5000 rows)
I'm using argilla == 1.1.1

Is there any way to train the model without having to transform the dataset?

**Comment by davidberenstein1957** [comment]
Hi @Haller-x An `rg.DatasetForTextClassification` contains `rg.TextClassificationRecords`. You can check our [datamodel](https://docs.argilla.io/en/latest/reference/datamodel.html) and [quickstart](https://docs.argilla.io/en/latest/getting_started/quickstart.html).

**Comment by davidberenstein1957** [comment]
if you want, we can also schedule a brief meeting to discuss this https://calendly.com/argilla-office-hours/30min.

**Comment by dvsrepo** [comment]
Hi @Haller-x ! I've also noticed that on the error trace you shared at the beginning the column name is title-case `Text`: 

`Following columns are not supported by the TextClassificationRecordModel and are ignored: ['Text']`

The column containing your text should be `text` in lowercase, it's weird that it raises the Following columns are not supported .. message for the `text` column. Could you double check and make sure it's lowercase and with no whitespaces?

**Comment by Haller-x** [comment]
thanks @dvsrepo! It worked!
