### ISSUE TITLE
allow for easier usability of the tutorials from their `.html` build within the docs

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2162]
**Is your feature request related to a problem? Please describe.**
After looking at a cool tutorial, it is a bit unclear how it can be used easily without deep diving into the docs.

**Describe the solution you'd like**
I want to add references for starting argilla
1 Google Colab
2 HuggingFace spaces
3 quickstart/docker
4 cloud offering

I am considering several options
- download button for the corresponding `.ipynb`
- host them on Colab

**Describe alternatives you've considered**
Look in GitHub and download the docs there.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
Dani
  [38 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346120180989?thread_ts=1673344928.744139&cid=C044YNCMP9S)
Now I recall that we used to have this for biome-text  docs and I googled a bit and it's actually easier than I thought because you can have a button linking to our GitHub tutorial path which opens the notebook in Colab


Dani
  [37 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346162202569?thread_ts=1673344928.744139&cid=C044YNCMP9S)
I will ask chatGPT, give me one sec:bananadance_lsd:
:joy:
1



Dani
  [29 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346661242629?thread_ts=1673344928.744139&cid=C044YNCMP9S)
it's good:


Dani
  [29 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346666391829?thread_ts=1673344928.744139&cid=C044YNCMP9S)
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/<username>/<repo>/blob/<branch>/<path-to-notebook>)


Dani
  [28 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346740817449?thread_ts=1673344928.744139&cid=C044YNCMP9S)
for download the nb we could do something similar


Dani
  [27 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346773354769?thread_ts=1673344928.744139&cid=C044YNCMP9S)
maybe we have an env in sphinx to get the filename and/or path?


Dani
  [27 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346779361059?thread_ts=1673344928.744139&cid=C044YNCMP9S)
to avoid hardcoding it


Dani
  [27 minutes ago](https://argilla-team.slack.com/archives/C044YNCMP9S/p1673346822801409?thread_ts=1673344928.744139&cid=C044YNCMP9S)
Yes, you can use the sphinx-nb extension to generate the "Open in Colab" button along with the other parts of the notebook's URL (<path-to-notebook>, <username>, <repo>, <branch>) automatically.
The sphinx-nb extension is a Sphinx extension that allows you to include Jupyter notebooks in your Sphinx documentation. It can also generate the URLs for the notebooks, making it easy to add the "Open in Colab" button.
To use sphinx-nb to generate the "Open in Colab" button, you'll need to configure the extension to use the appropriate GitHub repository for your notebooks. In your Sphinx conf.py file, you can set the notebook_path, notebook_metadata and notebook_link_options variables, like this:

notebook_path = 'path/to/notebooks'
notebook_metadata = {'path': 'https://github.com/username/repo/blob/branch'}
notebook_link_options = {'source': 'Colab', 'icon': 'shield'}
Once you've done that, you can use the notebook directive to include a notebook in your documentation, like this:

.. notebook:: path/to/notebook.ipynb
The sphinx-nb extension will automatically generate the appropriate URLs and the Open in Colab button for the notebook, based on the configuration options you set in the conf.py file.
You can also use the notebook_link option to control the default link style, it can be set to github, local or none. Depending on the type you set it to it will link the notebook to the appropriate location

**Comment by frascuchon** [comment]
This issue is already handled in #2201, right?

cc @dvsrepo @davidberenstein1957

**Comment by davidberenstein1957** [comment]
That is correct, I was just reviewing this, because it doesn’t work properly within the newly deployed docs. Also we need to add some general introduction/reference to the quickstart/deployments.
