### ISSUE TITLE
cannot select text within `viewmode` for `TokenClassification`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2191]
**Describe the bug**
I cannot select text within `viewmode` for `TokenClassification`

**To Reproduce**
1. Go to a `TokenClassification` dataset
2. Click on 'viewmode'
3. Try to select text for copy-passting CTRL+C, CTRL+V

**Expected behavior**
I would expect to be able to copy paste and select text.

**Screenshots**
N.A.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.2.0
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: N.A..

**Additional context**
N.A.

**Comment by Amelie-V** [comment]
@leiyre @keithCuniah  would be nice to add a number effort there
