### ISSUE TITLE
add better support for python client navigation in `workspaces` and `datasets`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2195]
**Is your feature request related to a problem? Please describe.**
In order to get workspace info, dataset info and dataset settings, I need to go to the UI, which is annoying when working in python.

**Describe the solution you'd like**
Ideally, I would like to get basic things for getting info.

```python
rg.load("non_existing_dataset") -> None, value error, logged warning
rg.get_datasets() -> shows datasets and potentially users with access in UI-like table
rg.get_workspaces() -> shows workspaces and nested datasets and potentially users with access in UI-like table
ds.get_settings() -> shows dataset settings
ds.delete() -> shows dataset settings
ds.delete_records() -> shows dataset settings
```
Additionally, [this PR](https://github.com/argilla-io/argilla/pull/2148) is awesome for making things more visible.
Potentially, some additional behavior should be needed for [roles and permissions](https://github.com/argilla-io/argilla/issues/1857).

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
Ideally, something like .venv/lib/python3.9/site-packages/argilla/client/datasets.py.__all_labels__ should be replaced for `ds.get_settings().labels`

**Comment by frascuchon** [comment]
Issue #1859 is also related to this one.

**Comment by davidberenstein1957** [comment]
closed in favor of https://github.com/argilla-io/argilla/issues/2379
