### ISSUE TITLE
add `password` creation workflow to the Python Client

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2196]
**Is your feature request related to a problem? Please describe.**
The user creation workflow is troublesome for users and for ourselves.

**Describe the solution you'd like**
`rg.create_user(username, password, workspaces)` -> .config/cred file

**Describe alternatives you've considered**
N.A.

**Additional context**
https://github.com/argilla-io/argilla/issues/2130

Also align a bit with mimicking functionality to the Python client within these https://github.com/argilla-io/argilla/issues/2195 and https://github.com/argilla-io/argilla/issues/1857

**Comment by frascuchon** [comment]
Thanks @davidberenstein1957 

We need to define first a proper user management workflow with a minimal roles/permissions schema definition

**Comment by dvsrepo** [comment]
This is possible now
