### ISSUE TITLE
Add similarity record number into footer

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#2197]

**Comment by Amelie-V** [comment]
Just add "50" at right bottom

**Comment by davidberenstein1957** [comment]
Yes please

**Comment by Amelie-V** [comment]
<img width="961" alt="Captura de pantalla 2023-01-17 a las 16 33 38" src="https://user-images.githubusercontent.com/84135211/212945810-c80372f8-b0be-4f1d-873d-cae5fb0fc960.png">
