### ISSUE TITLE
argilla:stats is visible in metadata filter

### ISSUE THREAD

**Issue by leiyre** [recognai/rubrix#2217]
**Describe the bug**
argilla:stats is visible in metadata filter

**To Reproduce**
1. Go to a dataset with argilla:stats
2. Click on metadata filter
3. See error

**Expected behavior**
argilla:stats need to be excluded from available metadata filters

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Comment by dhruvsakalley** [comment]
https://github.com/argilla-io/argilla/issues/2220 Related perhaps
