### ISSUE TITLE
Date fields are being mishandled in the metadata search option

### ISSUE THREAD

**Issue by dhruvsakalley** [recognai/rubrix#2220]
**Describe the bug**
The date fields on the metadata do not display correctly on the metadata filtering.

**To Reproduce**
Create a multilabel text classification dataset with dates in the metadata column with the format 2023-01-15, they are text type when they get imported into the TextClassificationRecord. The date displays properly with record.metadata.get("date") but do not show up properly in the UI

**Expected behavior**
Ideally a date range slider timeline or at least a list of dates in the dataset

**Screenshots**
![image](https://user-images.githubusercontent.com/3661965/213015690-320cfa87-c824-42d5-bfe0-b2b5dc98deeb.png)

![image](https://user-images.githubusercontent.com/3661965/213015755-a05bd558-2dea-4f6a-b08c-412ce53a0462.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Windows Server 2019
 - Browser [e.g. chrome, safari]: Chrome
 - Argilla Version [e.g. 1.0.0]: 1.1.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]: NA

**Additional context**
Seems to be an elasticsearch related issue.

**Comment by leiyre** [comment]
Hi @dhruvsakalley, the idea is as you say, to use in the future a different approach to allow filtering dates (range or datepicker). For the moment we have hidden it in the UI https://github.com/argilla-io/argilla/issues/2217 until we have the right component to offer a good experience. Thank you very much for your feedback.

**Comment by frascuchon** [comment]
Fixed by #2218
