### ISSUE TITLE
Investigate how to automate help modal content from the docs

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#2221]
**Is your feature request related to a problem? Please describe.**
We will continuously create more "help content".
We are improving the modal UI to display many help content on the same view, it would be interesting to tackle how to reuse content from the docs and display it automatically in the UI 

**Describe the solution you'd like**
For now, only do research and think about the whole context
- UX How much "help text" can be reasonably shown at a time?
- UX What are the options to do it scalable? (slider menu, search engine...)
- UI FRONT Check the markdown 
- FRONT, DOC STRUCTURE Do we need to create a new text entry into the docs?

**Describe alternatives you've considered**
Duplicate info and do it manually

**Additional context**
It's a nice to have feature, it's not high prioritary

**Comment by nataliaElv** [comment]
This is being addressed in #2438 so I'm closing this issue.
