### ISSUE TITLE
Improve visibility of total records number

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#2227]
When the dataset contains more than 10000+ records, users can't access part of the dataset. Even more critical, users could think records are missing. 

So to bring a bit more visibility to the user we will work on the first version:

- Show total record numbers existing in the dataset (instead of 10000) at the right bottom counter.
- Improve the copy that informs the limit reach (view screenshots)

**Comment by Amelie-V** [comment]
![Image](https://user-images.githubusercontent.com/84135211/213415654-6b15f7ad-836e-4367-b34d-e23ceca524ce.png)

**Comment by frascuchon** [comment]
Ref #2007 
Ref #1848

**Comment by Amelie-V** [comment]
This is the reviewed message after QA. @keithCuniah : 

You cannot go through more than 10,000 records. To explore more records, you can combine queries, filters, and sorting to reduce your search results. Visit this [guide](https://docs.argilla.io/en/latest/guides/features/queries.html?highlight=queries#) for using advanced queries.
