### ISSUE TITLE
Elasticsearch configuration steps is outdated

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2229]
**Describe the bug**
The Elasticsearch configuration is outdated. 

- Role name
- index pattern
- screenshots

**To Reproduce**
Go here https://docs.argilla.io/en/latest/getting_started/installation/elasticsearch.html

**Comment by nataliaElv** [comment]
Closing this issue, since this page doesn't exist in the docs anymore so I'm assuming it was updated somethere.

**Comment by frascuchon** [comment]
Indeed exists yet https://docs.argilla.io/en/latest/getting_started/installation/configurations/elasticsearch.html. Just moved.

**Comment by nataliaElv** [comment]
Thanks for spotting that! Was the issue resolved in this new version of the page or can we keep this issue closed?
