### ISSUE TITLE
Sort the inputs of the text classification record on the UI

### ISSUE THREAD

**Issue by bonillam** [recognai/rubrix#2233]
**Is your feature request related to a problem? Please describe.**
When I display the `inputs={}` on the Argilla UI, I would like to have a way to sort the **keys**:values of the dictionary.  I need this feature to help the labeler do the job easier. 

**Describe the solution you'd like**
I want to be able to control the sort criteria for the inputs.  Like:  Date **yymm01**: will be shown before Date **yymm02**:.   Or **BEFORE**: text a can be be shown first and then **AFTER**: text b

**Comment by davidberenstein1957** [comment]
@frascuchon I suggested to be able to handle this with an OrderedDict, however, I am not sure how this is handled internally.

```python
import collections

collections.OrderedDict()
```

**Comment by frascuchon** [comment]
We need to validate that UI is not applying any default sort 

cc @leiyre @keithCuniah

**Comment by leiyre** [comment]
> We need to validate that UI is not applying any default sort
> 
> cc @leiyre @keithCuniah

I confirm that there is no default sorting

**Comment by frascuchon** [comment]
Refs #1881

**Comment by frascuchon** [comment]
We're using the `_source` filter when retrieving data, to control info send back as part of the response. When we use this, elasticsearch recreates the internal data structure and the original sort order is not preserved (See [here](https://github.com/elastic/elasticsearch/issues/17639))

To resolve this, we should provide inputs as a list of key-value pairs, or provide a template dataset record settings to show data in the proper order.

**Comment by frascuchon** [comment]
PR #2581 helps to control the input visual order
