### ISSUE TITLE
Allow to configure the pagination limit from server

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2239]
The current pagination flow has a limit of 10k since elasticsearch set a default safeguard limit when requesting docs with a high `from` value.

But this value can be increased by configuration. The problem is, even if the user defines a higher value on the elasticsearch level, the change won't be reflected.

We should allow adapting this value to the setup in the elasticsearch cluster.

See also discussion [here](https://github.com/argilla-io/argilla/pull/2231#issuecomment-1399982416)

**Comment by davidberenstein1957** [comment]
Closed in favor of a more robust solution mentioned here https://github.com/argilla-io/argilla/issues/2484
