### ISSUE TITLE
Validate predictions fails on Text2Text

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#2252]
**Describe the bug**
On version 1.2.1 when validating the prediction on text2text (see for example `news-summary` dataset, we get an error that the annotation couldn't be validated. The reason is that apparently, the JSON payload that we send does not contain the text field inside the annotation.text objects.

**To Reproduce**
1. Go to `news-summary`
2. Open the browser inspector and refresh if neccesary
3. Click on Hand labelling
4. Find a record with predictions but not validated
5. You'll see the error pop and on the inspector, you'll that the call to save the annotations fails because the above missing field `text` error.

I've only tested with page size 1 but I guess it's the same with other page sizes as it shouldn't affect this

**Expected behavior**
Save the annotation when validating the predictions

**Screenshots**
<img width="1382" alt="Screenshot 2023-01-27 at 10 13 26" src="https://user-images.githubusercontent.com/1107111/215051115-99e07eca-6dcc-4a02-a670-e8c1a3c551b5.png">

<img width="1646" alt="Screenshot 2023-01-27 at 10 13 33" src="https://user-images.githubusercontent.com/1107111/215051131-1bd0b09e-017f-4894-a166-7e8131016c35.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by keithCuniah** [comment]
Note : It seems that was failling in previous release also ( I've checked 1.2.0/1.x/0.7)
