### ISSUE TITLE
restructure deepdives with more intuitive structure.

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2258]
**Is your feature request related to a problem? Please describe.**
Poor interpretability deepdives.

**Describe the solution you'd like**
**- Title -> content**
- How to -> overview of NLP tasks.
- Log data and records -> https://docs.argilla.io/en/latest/guides/steps/3_deploying.html
- Manage datasets and training -> https://docs.argilla.io/en/latest/guides/features/datasets.html
- Schedule jobs using listeners -> https://docs.argilla.io/en/latest/guides/features/listeners.html
- API and UI query structure -> https://docs.argilla.io/en/latest/guides/features/queries.html
- Use Token Attributions -> https://docs.argilla.io/en/latest/guides/techniques/explainability.html#token-attributions
   This also needs additional code
- Track performance with metrics -> https://docs.argilla.io/en/latest/guides/features/metrics.html
- Find records with semantic search -> https://docs.argilla.io/en/latest/guides/features/semantic-search.html
- Classification rules with Weak supervision -> https://docs.argilla.io/en/latest/guides/techniques/weak_supervision.html
- Active learning -> https://docs.argilla.io/en/latest/guides/techniques/active_learning.html
- Pre-annotate few-shot learning -> https://docs.argilla.io/en/latest/guides/techniques/few_shot.html

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by dvsrepo** [comment]
Hi @davidberenstein1957 

This looks good. I have a few suggestions to simplify the structure:

- How-to: We could add the Basics section starting here: https://docs.argilla.io/en/latest/getting_started/quickstart.html#Connect-to-Argilla . what do you think?
- Read, prepare, and write data: it could be a merge of:
     -  Manage datasets and training  
     - log data and records (which could focus on data from model predictions) 
- Schedule jobs with listeners
- Label records with semantic search
- Programmatic labeling with rules -> https://docs.argilla.io/en/latest/guides/techniques/weak_supervision.html
- Query datasets
- Use active learning -> https://docs.argilla.io/en/latest/guides/techniques/active_learning.html
- Pre-annotate with few-shot learning -> https://docs.argilla.io/en/latest/guides/techniques/few_shot.html
- Log model explanations:
- Measure datasets with metrics:

**Comment by tomaarsen** [comment]
Some small nitpicks:
1. `Basic how to´s` should probably be `Basic how to's`, i.e. no forward tick/acute accent but a single quote instead.
2. (Tangentially related) Hovering over `🔦 Label records with semantic search` causes line shift for me.
    <details><summary>Click for screenshots</summary>

    Without hovering over it:
    ![image](https://user-images.githubusercontent.com/37621491/216368848-019f6d7d-c0e0-4b47-a253-3734c425482c.png)
    After hovering over it:
    ![image](https://user-images.githubusercontent.com/37621491/216368931-34dd022c-9950-4589-8644-d02ccbe7e781.png)
    <details>
3. The first (and thus main) subsection under "Guides" is too empty: It's just three sentences, not even a paragraph.

---

As for my personal feedback on the existing docs: I think that the "MLOps Steps" and "NLP Tasks" sections were already very clear, and that the main issues were:
1. Clicking on "Features" simply shows some vague terms like "Datasets", "Listeners", etc., and once you click on those, you're immediately taken in depth rather having than a quick overview or example first.
2. "Libraries" is unclear. What is really meant is "Third party libraries" or "Third party integrations", but that's not what "Libraries" makes a user think.
3. "Techniques" is also a big vague, although I think the subsections ("Active Learning", "Few-shot classification", etc.) are clear.

I'm glad to see that MLOps Steps and NLP Tasks remain as they were, and that Features was removed in your proposal.
