### ISSUE TITLE
Improve the bulk annotation process, specially for multi-label text classification

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2264]
# Description

The main effort on the bulk annotation will be to tackle the following tasks:

- Normalize the 2-step validation flow for all the tasks, except the single label text classification
- Enhance the bulk annotation labeling for multi-label text classification
- Disable automatic validation for multi-label text classification

## Tasks 
- [x] #2265
- [x] #2266
- [x] #2267
- [x] #2268

## Refs
-  #2160

**Comment by Amelie-V** [comment]
General comments:

Single label:

- Remove Clear and Reset action 

Bulk Multilabel:

Make evident the step to validate the selected records :
- Improving the validated icon behaviour. 
- Reviewing Text for: "Apply button", "Info message", "Toast messagex2".

Record card:

- Order: Validate, Discard, Clear, Reset
- Validate is the primary button: Green background + icon
- Discard, Clear, and Reset are secondary: Neutral bg and border-colour + icon (we can maintain the colour on the icon)
- Maintain default state in all secondary button
- When the record is validated, the "Validate" button is disabled.
- Align icon size between bulk list and record
- Reduce the size button

**Comment by keithCuniah** [comment]
Descriptions of the components : 
![image](https://user-images.githubusercontent.com/88380932/218515101-5d4f0b51-246f-4a41-9316-077207f862c1.png)

**Comment by dhruvsakalley** [comment]
Possibly related https://github.com/argilla-io/argilla/issues/2160
