### ISSUE TITLE
Undo & Redo Actions

### ISSUE THREAD

**Issue by cceyda** [recognai/rubrix#2278]
**Is your feature request related to a problem? Please describe.**
My use case is specifically for token classification where there are a lot of annotations per record but should be just as useful for other types too.
If the user accidentally clicks (x) on an annotation (or clicks "Clear annotations") or makes other types of mistake they have to manually tag it again. This is especially annoying if it is character level annotation & you are doing edits.
Additionally it would be nice to have a way to undo all actions done on a record in that session(? the actions that took place after first edit during `Pending` until `Validation`)
So the per record buttons would be "Save, Undo All, Clear Annotations"(these could be just emoji buttons too). So if a user edits a record it would go from 
`Validated->Pending-> annotate,annotate,annotate->clicks undo all->Validated (reverts all edits)`
This would also remove some confusion from the word 'discard'. Currently when being unfamiliar with the UI it is easy to confuse it as discarding actions. Is this the same as the Clear action mentioned at https://github.com/argilla-io/argilla/issues/2266 ?

**Describe the solution you'd like**
allow undo and redoing actions using keyboard shortcuts &| add buttons near Validate and Discard buttons. This can be done by keeping a limited buffer of actions (at least until the user clicks save) as also described [here
](https://github.com/argilla-io/argilla/issues/1711#issuecomment-1289234621)

**Describe alternatives you've considered**
😭  and do it all again

**Comment by Amelie-V** [comment]
thanks, @cceyda! That is a very insightful description.

**Comment by frascuchon** [comment]
Fixed in #2273
