### ISSUE TITLE
Docs: `docker-compose.yaml` URL in User Management documentation points to Rubrix

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#2288]
**Describe the bug**
The first URL in [this link](https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html#using-docker-compose) points to https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml?, which shows various outdated mentions of `rubrix`. Presumably this is an outdated script, and it should be replaced.

**To Reproduce**
1. Go to https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html#using-docker-compose
2. Click on the URL to go to https://raw.githubusercontent.com/recognai/rubrix/master/docker-compose.yaml
3. Observe some ~8 mentions of Rubrix

**Expected behavior**
I expect for this docker yaml to be usable with the most recent Argilla version, but I presume that it isn't.

**Screenshots**
N\A

**Environment (please complete the following information):**
N\A

**Additional context**
N\A

**Comment by dvsrepo** [comment]
Good catch Tom, the right yml is this one:  https://github.com/argilla-io/argilla/blob/develop/docker-compose.yaml, could you open a PR?
