### ISSUE TITLE
User Management: invalid username or password

### ISSUE THREAD

**Issue by sagarpanda09** [recognai/rubrix#2300]
The user management isn't working as expected even after 
1. set environment variable
2. mapped .user.yaml file in docker-config.yaml as mentioned in the docs.

Only the default credentials i.e "argilla" and "1234" works irrespective of changing the user config. Please advice what am I missing?

**Comment by frascuchon** [comment]
Hi @sagarpanda09 and thanks for reaching out.

I've followed the docs and it's working. Which docker version are you using? Also, are you using docker for windows/mac? Sometimes you need to fine-tune the volume mount for those OS 

See https://docs.docker.com/desktop/troubleshoot/topics/#volume-mounting-requires-file-sharing-for-any-project-directories-outside-of-home

**Comment by nataliaElv** [comment]
Hello! I'm closing this issue since it's been stale for a while. @sagarpanda09, please feel free to reopen if this is still an issue.
