### ISSUE TITLE
ssl authentication error

### ISSUE THREAD

**Issue by joonyeonglim** [recognai/rubrix#2311]
**Describe the bug**
ssl authentication error

**To Reproduce**

docker-compose.yml
```  
... 
      environment:
      - ARGILLA_ELASTICSEARCH_CA_PATH=/ssl/server.crt
      - ARGILLA_ELASTICSEARCH=https://elasticsearch:9200/
      - ARGILLA_ELASTICSEARCH_SSL_VERIFY=True
...      
```

**Screenshots**
<img width="822" alt="image" src="https://user-images.githubusercontent.com/58205130/217391745-443d2828-dda0-4629-8b79-d018104141f1.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]:  linux
 - Browser [e.g. chrome, safari]: chrome
 - Argilla Version [e.g. 1.0.0]: 1.2.1
 - ElasticSearch Version [e.g. 7.10.2]: 7.7.0
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla:v1.2.1

**Additional context**

Current Workaround
->
modify "argilla/server/daos/backend/client_adapters/factory.py" file

factory.py
```
from argilla.server.settings import settings

  def _fetch_cluster_version_info(cls, hosts: str) -> Tuple[str, str]:
      try:
          if settings.elasticsearch_ssl_verify:
              response = httpx.get(hosts, verify=settings.elasticsearch_ca_path)
          else:
              response = httpx.get(hosts)
              
          data = response.json()

          version_info = data["version"]
          version: str = version_info["number"]
          distribution: str = version_info.get("distribution", "elasticsearch")

          return version, distribution
      except Exception as error:
          raise GenericSearchError(error)
```

**Comment by davidberenstein1957** [comment]
@Joonyeong97 thanks for reporting this 🦾
