### ISSUE TITLE
define a more abstract and flexible implementation of `token-attribution`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2321]
**Is your feature request related to a problem? Please describe.**
Currently, token attributions can only be set with a fixed color and opacity based on the score between -1(red) and 1 (blue).

**Describe the solution you'd like**
OLD

```python
TokenAttributions(
     token="good", attributions={"label": "ENTITY_NAME"}
)
```
NEW
I would like to see something like, where the label is shown on hover.

```python
TokenAttributions(
     token="good", attributions={"label": "ENTITY_NAME", "opacity": 0.5, "color": "#FFFFFF"}
)
```

**Describe alternatives you've considered**
Only using red and blue.

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
Is there any motivation for not going for the following signature?
```python
TokenAttributions(
     token="good", label="ENTITY_NAME", opacity=0.5, color="#FFFFFF"
)
```
This ought to have better usability due to IDE autocompletions/suggestions.

**Comment by davidberenstein1957** [comment]
@tomaarsen that suggestion is even better.

**Comment by davidberenstein1957** [comment]
Perhaps this needs some additional review in general because it feels a bit buggy.

For some reason, by providing attributions without label that matches the prediction, records are visible without any text. @dvsrepo was it supposed to be the case that each label could have its own attributions? This doesn't seem to work within the UI.

![image](https://user-images.githubusercontent.com/25269220/218787140-36960bff-0fdd-49a8-88a6-e6a10d648bf8.png)

from the UI, maybe it would be possible to show something like 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/25269220/218788438-c5f1ebb0-660e-4b99-af95-2510f23145c5.png">

**Comment by davidberenstein1957** [comment]
Okay, it currently only works if the first label align with the token attribution label for some reason.

![image](https://user-images.githubusercontent.com/25269220/218790320-618e7c70-790e-4c9b-b6a3-db58e566b8bf.png)

![image](https://user-images.githubusercontent.com/25269220/218790658-7eb4d103-a315-4052-bf78-583b1aa8d7dc.png)

**Comment by dvsrepo** [comment]
@frascuchon can give more details about the data model. I think it was more or less prepared in terms of data model to be able to define attributions for each predicted class in the multi-label setting. But this was not at all supported by the UI. In the UI the assumption is: you provide a predicted class (single-label, multiclass scenario), and you add the attributions for that predicted class. If you don't put the attribution for the predicted class is buggy. I was fighting with this a few days ago.

This feature would benefit from a full revision

**Comment by dvsrepo** [comment]
> Okay, it currently only works if the first label align with the token attribution label for some reason.
> 
> ![image](https://user-images.githubusercontent.com/25269220/218790320-618e7c70-790e-4c9b-b6a3-db58e566b8bf.png)
> 
> ![image](https://user-images.githubusercontent.com/25269220/218790658-7eb4d103-a315-4052-bf78-583b1aa8d7dc.png)

I think in the UI the logic is looking at the `predicted_as` field which is a computed field from the predictions and in the single-label scenario is that with the highest score, and maybe just the first predicted label if all are zero  But I could be wrong :-) and it's confusing

**Comment by davidberenstein1957** [comment]
Yes the assigned labels are only shown for the highest corresponding prediction score.

**Comment by davidberenstein1957** [comment]
@jfcalvo @frascuchon these are the highlight discussed/mentioned during the feedback task discussion

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2785
