### ISSUE TITLE
Docs: mentions of `master` branch/version/image when we use develop/main now

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#2324]
Hello!

## Issue overview
* The documentation says `master branch` or `master version` on several locations, whereas we've moved to using the `main` and `develop` branches primarily.

## Details
* See `master branch` in this page: [developer_docs.rst](https://github.com/argilla-io/argilla/blob/main/docs/_source/community/developer_docs.rst) / [developer_docs.html](https://docs.argilla.io/en/latest/community/developer_docs.html)
* See `master version` in this page: [from_development.md](https://github.com/argilla-io/argilla/blob/2bc97c62380bb46aad6439323588051c005202f6/docs/_source/getting_started/installation/deployments/from_development.md) /  [from_development.html](https://docs.argilla.io/en/latest/getting_started/installation/deployments/from_development.html)
    Also note, this page recommends:
    ```bash
    ...
    wget -O docker-compose.yml https://raw.githubusercontent.com/argilla-io/argilla/develop/docker-compose.yaml
    # use the master image of the argilla container instead of the latest
    sed -i 's/argilla:latest/argilla:master/' docker-compose.yml
    ...
    ```
    `argilla:latest` does not occur in [docker-compose.yaml](https://raw.githubusercontent.com/argilla-io/argilla/develop/docker-compose.yaml), so there's no point in the replacement anymore. This ought to get looked at.

cc: @davidberenstein1957 @rhoitjadhav 

- Tom Aarsen

**Comment by garimau** [comment]
@tomaarsen I believe the second page (now [Docker compose](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker_compose.html)) doesn't have the issue anymore, but I can fix the mention of `master branch` on the first page!
