### ISSUE TITLE
Make it easy to do find records post annotation

### ISSUE THREAD

**Issue by dhruvsakalley** [recognai/rubrix#2330]
**Is your feature request related to a problem? Please describe.**
There are certain scenarios that are challenging to get to:
1. Records that have not been annotated by a label
2. Records that have been marked as validated but have not been annotated by any class.
3. Records that are correct/incorrect wrt a rule so that one can easily do basic rule tuning.

**Describe the solution you'd like**
Make annotations queryable in the UI with negation operators. A simple `not in` query and `is none` query on the annotations will solve the problem, this is possible in the python code, but not easy in the UI. 

**Describe alternatives you've considered**
this is possible in the python code, but not easy in the UI. 

**Additional context**
We typically use the argilla platform in a hierarchical multilabel setting and use rules to do some quick QA as well building towards weak supervision of the stack.

**Comment by dhruvsakalley** [comment]
I just realized there is a way to do `annotated_as:` queries so this might be possible with custom queries, still leaving it out there for further consideration.

**Comment by dvsrepo** [comment]
Thanks @dhruvsakalley ! I've reopened this issue because we could indeed facilitate this in the UI and there's an important request here: correct/incorrect annotations with respect to rules. Happy to look more deeply into your use cases if you have time next week

**Comment by dhruvsakalley** [comment]
Sorry for getting back to you on this, we can put something on the calendar for Friday maybe if you have time.
