### ISSUE TITLE
Getting the list of dataset names in Argilla from the Python API

### ISSUE THREAD

**Issue by bengsoon** [recognai/rubrix#2342]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it is a feature that I would have needed for work. I wanted to create an automation where I would need to have a list of the dataset names in a particular workspace through Python, but it is not available.

**Describe the solution you'd like**
A Python function that makes a `GET` request to the `/api/datasets` endpoint where it would return the metadata of all the datasets within the workspace. Similar to what was implemented with the existing [`get_dataset`](https://github.com/argilla-io/argilla/blob/ff4e79f537262d046ef43c5571d250927d8d76e5/src/argilla/client/sdk/datasets/api.py#L31)

**Describe alternatives you've considered**
Create a custom Python request to that endpoint, which would not be ideal as we already have Python API.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2195

**Comment by davidberenstein1957** [comment]
@frascuchon we might be able to tackle this in the 1.4.0 release right?

**Comment by davidberenstein1957** [comment]
@bengsoon FYI
any additional input would be welcome in the other issue, also you can check [here](https://github.com/argilla-io/argilla-streamlit/blob/2a5e34a092a3a555f422f2100ee2a0a5ee68ee4a/my_app/utils/commons.py#L111) for some methods you can use in the meantime. 

closed in favor of https://github.com/argilla-io/argilla/issues/2379
