### ISSUE TITLE
add custom pydantic `error_msg_templates` to help with error visualization

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2344]
**Is your feature request related to a problem? Please describe.**
With text, readable error logging is a difficult.

**Describe the solution you'd like**
I would like to see the `error_msg_templates` to be used.

**Describe alternatives you've considered**
N.A.

**Additional context**
As discussed here
https://github.com/argilla-io/argilla/pull/2337

**Comment by davidberenstein1957** [comment]
@tomaarsen FYI

**Comment by tomaarsen** [comment]
Pydantic is removing `error_msg_templates` in v2, so perhaps we shouldn't bother with this. I didn't find an alternative approach to do the same thing in v2 at a glance.
