### ISSUE TITLE
return similarity score during similarity search

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2348]
**Is your feature request related to a problem? Please describe.**
I don't know if something is actually similar or just the most similar available.

**Describe the solution you'd like**
A score that represents the outcome of the search both within the Python client and the UI

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by frascuchon** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/8.6/dense-vector.html#dense-vector-similarity

**Comment by davidberenstein1957** [comment]
IMO are some ways in which this needs to be integrated within our Python client methods:

- The PyDantic Basemodel for records in `argilla.client.models` should get a `similarity_score` field. This score should default to `None`, but should be equal to the vector similarity of the input vector and vector of the record. 
- The server should return the score values from all the `{task}:search` endpoints. This value should be returned in a separate response field (`scores`, `search_score`, or `similarity_score`). And will be filled only when a similarity search is applied (this could be extended in the future and always return the search score, but for now, is out-of-scope). Refs: https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#approximate-knn
- Ideally, I would like to execute all query-like methods based on a filter on the `query`-param and a new `similarity-threshold` param, before actually loading all records to the Python client side.`rg.load`
- These changes should be represented in the documentation `docs/_source/guides/label_records_with_semanticsearch.ipynb`, `docs/_source/guides/schedule_jobs_with_listeners.ipynb`, `docs/_source/guides/query_datasets.md`
- Lastly, these change should be tested.

**Comment by davidberenstein1957** [comment]
Perhaps we can also enable a [cool plugin](https://github.com/argilla-io/argilla-plugins/issues) with this feature, and allow for this [similarity based labelling feature](https://github.com/argilla-io/argilla/issues/2346)

**Comment by nataliaElv** [comment]
This was included in v1.19.0
