### ISSUE TITLE
Decide if we add sklearn as dep or include a error message when computing train_test_split

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#2367]
We currently use sklearn in two places: 1) prepare for training train test splits (new) and 2) metrics.

The way we handled it when we only had 2) was to have it as optional dep, and show the following message to users:

```python
try:
  import sklearn  # noqa: F401
        except ModuleNotFoundError:
            raise ModuleNotFoundError(
                "'sklearn' must be installed to compute the metrics! "
                "You can install 'sklearn' with the command: `pip install scikit-learn`"
            )
```

I remember @frascuchon commenting on this previously but I missed it. 

We could add sklearn as core dep but I have some concerns about opening the door to some installation problems and making the distribution of argilla less lightweight.

Thoughts @frascuchon , @davidberenstein1957 , @tomaarsen ?

For context: if you don't have scikit-learn installed prepare_for_training with train/test size params fails:

```python
Traceback (most recent call last):

  File "/Users/dani/argilla/projects/idealista-ner/scripts/preprocess.py", line 32, in <module>
    typer.run(main)

  File "/Users/dani/argilla/projects/idealista-ner/scripts/preprocess.py", line 26, in main
    ds = ds.prepare_for_training(framework="spacy", train_size=train_size, lang=nlp)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/argilla/client/datasets.py", line 492, in prepare_for_training
    from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'sklearn'
```

**Comment by davidberenstein1957** [comment]
Woops, my bad.

We can probably re-use some parts of the `datasets` code, or just write a part ourselves (this is what datasets did too). I wanted to avoid spending too much time on it and assumed sklearn was included. I am not sure about the installation issues you mentioned.

**Comment by tomaarsen** [comment]
Adding additional dependencies has three main consequences in my eyes:
1. Larger install size.
2. Slower import time.
3. Potential version conflicts.


As a result, I would recommend not adding dependencies that are only used by e.g. < 10% of users to the required install. I would also recommend lazily importing rarely used modules, e.g. not importing them at the top of files. That way, even if the import is wrapped in a `try-except ModuleNotFoundError`, users that have the dependency are not subjected to (slow) unnecessary imports. Furthermore, I would recommend always wrapping non-dependency imports with useful warnings notifying users how to resolve the dependency issue, like you proposed in your issue already. 
It may be a bit overkill, but a [versioning](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/versions.py#L55) utility may be nice to have in this case.

NLTK's import time halved when I moved rarely used imports from the top of the files to the functions in which the import is used. That said, NLTK is a much different piece of software, i.e. a large toolkit from which only a small percentage of the code is used by any user at a time.

**Comment by dvsrepo** [comment]
> Woops, my bad.
> 
> We can probably re-use some parts of the `datasets` code, or just write a part ourselves (this is what datasets did too). I wanted to avoid spending too much time on it and assumed sklearn was included. I am not sure about the installation issues you mentioned.

Yes, I think is/was a good idea not to spend time on building our own logic for this train/test split. And given @tomaarsen response, I think I'd be happy with wrapping this in `try-except ModuleNotFoundError`

**Comment by dvsrepo** [comment]
> Adding additional dependencies has three main consequences in my eyes:
> 
>     1. Larger install size.
> 
>     2. Slower import time.
> 
>     3. Potential version conflicts.
> 
> 
> As a result, I would recommend not adding dependencies that are only used by e.g. < 10% of users to the required install. I would also recommend lazily importing rarely used modules, e.g. not importing them at the top of files. That way, even if the import is wrapped in a `try-except ModuleNotFoundError`, users that have the dependency are not subjected to (slow) unnecessary imports. Furthermore, I would recommend always wrapping non-dependency imports with useful warnings notifying users how to resolve the dependency issue, like you proposed in your issue already. It may be a bit overkill, but a [versioning](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/versions.py#L55) utility may be nice to have in this case.
> 
> NLTK's import time halved when I moved rarely used imports from the top of the files to the functions in which the import is used. That said, NLTK is a much different piece of software, i.e. a large toolkit from which only a small percentage of the code is used by any user at a time.

This is how we are currently doing it: https://github.com/argilla-io/argilla/blob/develop/src/argilla/client/datasets.py#L43 maybe we could do the same for sklearn to reuse the annotations? cc @davidberenstein1957
