### ISSUE TITLE
basic integration of new api-structure with Python client methods

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2379]
**Is your feature request related to a problem? Please describe.**
accessibility structure is complex and un-intuitive with the current python client. 

**Describe the solution you'd like**
LETS CALL THIS SEMI_PSEUDOCODE 
`rg.whoami()` ->
```python
{
    "user_info": GET /api/v1/users/me,
    "workspaces": rg.get_workspace_list(),
    "datasets": rg.get_dataset_list()
}
```

`rg.get_workspace()` ->
`rg.get_workspace_list()` ->
```python
{
    "<workspace_name>": {
        "workspace_info": GET /api/v1/workspaces/:id,
        "datasets": rg.get_dataset_list()
    }
}
```

`rg.get_dataset()` ->
`rg.get_dataset_list()` ->
```python
{
    "<dataset_name>": {
        "dataset_info": GET /api/v1/datasets/:id,
        "dataset_settings": rg.get_dataset_settings()
    }
}
```

`rg.get_dataset_settings()` ->
```python
GET /api/v1/datasets/:id/settings
```

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2195

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/1859

**Comment by davidberenstein1957** [comment]
```python

def get_dataset_list(api_url, api_key):
    client = ArgillaSingleton.init(api_url, api_key)._client
    try:
        url = "{}/api/datasets".format(client.base_url)

        response = httpx.get(
            url=url,
            headers=client.get_headers(),
            cookies=client.get_cookies(),
            timeout=client.get_timeout(),
        )
        response.raise_for_status()
        response.json()
    except Exception:
        url = "{}/api/datasets/".format(client.base_url)

        response = httpx.get(
            url=url,
            headers=client.get_headers(),
            cookies=client.get_cookies(),
            timeout=client.get_timeout(),
        )
        response.raise_for_status()

    dataset_overview = []
    for dataset in response.json():
        metadata = dataset["metadata"].values()
        if (
            metadata
            and not isinstance(list(metadata)[0], str)
            and not isinstance(list(metadata)[0], int)
        ):
            metadata = list(metadata)[0].get(
                "labels", list(metadata)[0].get("entities")
            )
        else:
            metadata = None
        dataset_overview.append(
            {
                "name": dataset["name"],
                "task": dataset["task"],
                "owner": dataset["owner"],
                "id": dataset["id"],
                "labels": metadata,
            }
        )
    return dataset_overview


def whoami():
    client = active_client()._client
    url = "{}/api/me".format(client.base_url)
    response = httpx.get(
        url=url,
        headers=client.get_headers(),
        cookies=client.get_cookies(),
        timeout=client.get_timeout(),
    )
    return {**response.json()}


def get_dataset_settings(dataset_name, dataset_task):
    client = active_client()._client
    url = f"{client.base_url}/api/datasets/{dataset_task}/{dataset_name}/settings"
    response = httpx.get(
        url=url,
        headers=client.get_headers(),
        cookies=client.get_cookies(),
        timeout=client.get_timeout(),
    )
```

**Comment by davidberenstein1957** [comment]
think about https://github.com/argilla-io/argilla/issues/2046

**Comment by davidberenstein1957** [comment]
There currently aren't any methods to provide nice access to an overview of Role-based access control (RBAC). 

Ideally, we want to have several methods that provide an overview of the different `user` => `workspaces` => `datasets` => `settings`. A good source of inspiration might be the [HF API client ](https://huggingface.co/docs/huggingface_hub/package_reference/hf_api). Also, we already have some default methods for user creation `src/argilla/tasks/users`, which might be useful as reference.

We should have the following methods.

- a `whoami`: which indicates default user info and access
- a `get_workspace`: which shows the workspace and datasets + settings (we already have a `set_workspace` method.)
- a `get_workspace_list`: which lists all workspaces and their datasets + their settings
- a `get_dataset`: which shows the datasets + their settings
- a `get_dataset_list`: which lists all datasets + their settings
- a `get_dataset_settings`: which shows dataset settings

It would also be nice to integrate this with `__repr__` methods for each of the relevant classes like the `src/argilla/client/datasets.py` classes, also showing dataset settings and the `src/argilla/client/client.py` also showing some workspace and dataset access info.

**Comment by alvarobartt** [comment]
Closed in favour of some recent improvements on both the `User` and `Workspace` classes for managing those, as well as the extension of the CLI (cc @gabrielmbmb)
