### ISSUE TITLE
cannot change assigned label during "find similar" of selected record

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2385]
**Describe the bug**
cannot change assigned label during "find similar" of the selected record

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a dataset (textclassification) with vectors
2. select a record to find similar 
3. annotation buttons are disabled (perhaps overall removal is better)

**Expected behavior**
be able to change the predictions or just remove the buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/25269220/220403886-fc52a81f-110b-4a5b-b48f-934fdc5e5e04.png)

**Environment (please complete the following information):**
N.A.

**Additional context**
N.A.

**Comment by Amelie-V** [comment]
@davidberenstein1957 Yes, let's discuss the interest in maintaining the labels in the record reference. Selecting them to annotate involves some developments we can estimate depending on the priority we fix.
