### ISSUE TITLE
rg.load takes too long because of the vector field

### ISSUE THREAD

**Issue by cceyda** [recognai/rubrix#2398]
**Is your feature request related to a problem? Please describe.**
`rg.load` takes too long because of the `vector` field, even when I don't need it.

**Describe the solution you'd like**
Allow passing a param or through the query
use the elasticsearch `_source` query field to exclude `vector` when not needed.

```
"_source": {        
        "exclude": ["vector"]
    }
```

**Describe alternatives you've considered**
wait

**Additional context**
Low priority

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2261

**Comment by davidberenstein1957** [comment]
Hi @cceyda, thanks for picking this up! I think we need to review the `rg.log`/`rg.load` performance in general, given that a lot of users have had some issues with this for larger records. 

Perhaps we can implement something like you suggested, or some lazy loading. At least, I expect to be able to fix some of these load issues by implementing this https://github.com/argilla-io/argilla/issues/2341

**Comment by orasik** [comment]
Excluding vectors would be great. Technically vectors will not be required in some cases when training a model.

The option `vectors=None` in `rg.load` could be used to exclude the vector of the record? @davidberenstein1957

**Comment by dvsrepo** [comment]
thanks @cceyda and @orasik , this is a needed and requested feat. @frascuchon we discussed this a long time ago (get a projection of only some fields when using rg.load) Is there a relatively easy solution to this?

**Comment by davidberenstein1957** [comment]
I agree with the idea about the projection but IMO they are 2 separate things. Perhaps we can also think about quantization of the vectors to reduce the size a bit. Ideally, I also see this as a broader topic where we potentially can choose which attributes to load/update for a list of records.  On 24 Feb 2023, at 21:40, Daniel Vila Suero ***@***.***> wrote:﻿
thanks @cceyda and @orasik , this is a needed and requested feat. @frascuchon we discussed this a long time ago (get a projection of only some fields when using rg.load) Is there a relatively easy solution to this?

**Comment by orasik** [comment]
@davidberenstein1957 @frascuchon I found a bug when I tried to hard-code a list of fields to test. 

This line https://github.com/argilla-io/argilla/blob/c35d63a5323fd360f1ef79456e6816d3470b3151/src/argilla/client/client.py#L707

```
projection={"*"}
```
is leading to this code for selecting which fields to include

https://github.com/argilla-io/argilla/blob/c35d63a5323fd360f1ef79456e6816d3470b3151/src/argilla/client/apis/datasets.py#L185

```
"fields": list(projection) if projection else ["id"]
```

If you make `"fields": ["id"]`

You will receive this error:

```
records = [sdk_record_class.parse_obj(r).to_client() for r in records]
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TextClassificationRecord
```

Not sure what is the validation behind parse_obj that is causing this error.

**Comment by orasik** [comment]
Found the issue.

`inputs` is a required field in the validation. If I change the line
https://github.com/argilla-io/argilla/blob/c35d63a5323fd360f1ef79456e6816d3470b3151/src/argilla/client/apis/datasets.py#L185

to:
```
"fields": ["id", "inputs"]
```

it works fine. 

I will raise a PR soon

**Comment by orasik** [comment]
PR https://github.com/argilla-io/argilla/pull/2417

**Comment by davidberenstein1957** [comment]
@frascuchon I think we should add some w.r.t. which fields we update during a `rg.log` afterwards to avoid overwriting records without vector. Can this be done easily?
