### ISSUE TITLE
Support for multiple predictions for TokenClassificationRecord 

### ISSUE THREAD

**Issue by usamayaseen-veeva** [recognai/rubrix#2402]
Hello,

I have two NER models and I would like to compare their agreements and disagreement; at the moment one can only supply `prediction` out of only one model for `TokenClassificationRecord`. Basically, I would like to ask questions like:

1. Give me all the data points where the two models disagree?
2. Give me all the data points where the two models disagree for a specific entity type?

It would be nice if the UI can also reflect predictions from multiple models; one option is to have multiple lines to show the predicted entities from model A and model B.

I understand what I am requesting might be a very niche feature request, but I guess it's important for error analysis if multiple candidate models exist. This might help to identify and compare model behaviour for individual (important) data points.

**Comment by davidberenstein1957** [comment]
@usamayaseen-veeva thanks for the feedback. This isn't as niche as you might think. We are considering these things https://github.com/argilla-io/argilla/issues/1630 https://github.com/argilla-io/argilla/issues/1857. Could you provide your input #1630 too, so we can focus the conversation there?
