### ISSUE TITLE
`prepare_for_training`with transformers interprets int as absolute number

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2406]
**Describe the bug**
This results in selecting 1=>100%, but instead selecting 1 #1 record

**To Reproduce**
N.A.

**Expected behavior**
N.A.

**Screenshots**
N.A.

**Environment (please complete the following information):**
N.A.

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
Fixed in #2411
