### ISSUE TITLE
`prepare_for_training` keeps too much feature and some should be removed

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2407]
**Describe the bug**
`prepare_for_training` keeps too much feature and some should be removed in most cases only `text/tokens` and `annotation/ner_tag` are needed.

**To Reproduce**
`prepare_for_training` and push to autotrain with NER

**Expected behavior**
N.A.

**Screenshots**
N.A.

**Environment (please complete the following information):**
N.A.

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
Fixed in #2411
