### ISSUE TITLE
`prepare_for_training` evaluate `Sequence(feature=ClassLabel))`vs `ClassLabel`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2408]
**Is your feature request related to a problem? Please describe.**
training with autotrain does not work directly

**Describe the solution you'd like**
N.A. Evaluate if this should can be changed everywhere

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
Fixed in #2411
