### ISSUE TITLE
[Feature Request] Loading images for token classification

### ISSUE THREAD

**Issue by logan-markewich** [recognai/rubrix#2416]
**Is your feature request related to a problem? Please describe.**
There is no way (as far as I can tell) to display images in the app. This causes difficulties when annotating text from OCR, especially since the text is often in a bit of a weird order and the image provides valuable context. 

**Describe the solution you'd like**
When tagging tokens for NER that come from OCR text, it would be helpful to have the image beside the text.  Support for loading images next to text for token classification would be appreciated. 

Bonus points if the text NER annotations are reflected on the image :)

**Describe alternatives you've considered**
I mean, I guess I could make the PR/code change myself, I just haven't had time to dive into it

**Additional context**
Document Understanding and OCR is a hot topic recently (Donut, LayoutLMV1/2/3, LiLT, UDOP). Support in the app for tasks related to it (like NER), would be very cool.

**Comment by davidberenstein1957** [comment]
Hi @logan-markewich, @burtenshaw actually made a really cool hack to be able to do this.

**Comment by logan-markewich** [comment]
@davidberenstein1957 Perfect timing!! Is there any plans to merge that @burtenshaw ? Otherwise I'll try out your branch

**Comment by burtenshaw** [comment]
@logan-markewich Merging the hack requires some upstream work. For now, you can do any of these:
- pull the image `burtenshaw/argilla-image`
- duplicate my HF space: https://huggingface.co/spaces/burtenshaw/argilla-image
- build from the fork: https://github.com/burtenshaw/argilla

I'm also working on a tutorial at the moment that uses it.

**Comment by logan-markewich** [comment]
@burtenshaw cool, that should work!
