### ISSUE TITLE
Cannot Open Local Argilla UI

### ISSUE THREAD

**Issue by logan-markewich** [recognai/rubrix#2418]
**Describe the bug**
I want to run Argilla outside of docker. I've launched elasticsearch and and the argilla server locally (i.e. `python -m argilla`) and everything looks to be running smoothly.

On top of that, I've also logged a smaple dataset using `rg.log()`

However, when I open the UI at `localhost:6900/`, I just get a not found json response. On the server logs, I see the message `"GET / HTTP/1.1" 404 Not Found`

What steps am I missing? How do I access the UI and annotate my dataset?

**To Reproduce**
1. launch your elasticsearch server locally
2. launch agrilla locally `python -m argilla`
3. Try to open `localhost:6900/`

**Expected behavior**
The URL `localhost:6900/` should be opening the UI, but it's not

**Screenshots**
![image](https://user-images.githubusercontent.com/22285038/221380470-fb3e8f37-00c7-4806-8dc5-208c2530614d.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Rocky Linux
 - Browser [e.g. chrome, safari]: Firefox, Chrome, Edge
 - Argilla Version [e.g. 1.0.0]: 1.4.0
 - ElasticSearch Version [e.g. 7.10.2]: 7.10.2

**Comment by dvsrepo** [comment]
Hi @logan-markewich , it seems like you are building argilla from source. In this case you need to build the front end package locally too (see https://docs.argilla.io/en/latest/community/developer_docs.html). In any case I'd recommend you to pip install argilla[server] even for running argilla locally without Docker, to make sure you're using the latest stable version

**Comment by logan-markewich** [comment]
That's exactly what I missed, thanks! 

I need to run from source, since I'm using a custom branch that hasn't been merged yet, so that I can load images from the metadata :)
