### ISSUE TITLE
Sort by length

### ISSUE THREAD

**Issue by orasik** [recognai/rubrix#2419]
**Is your feature request related to a problem? Please describe.**
When annotating a large dataset, sorting by length can help speed up the process, especially when doing text classifications. Some short sentences are easier to spot.

**Describe the solution you'd like**
When annotating data manually, it would be great to sort results by text length.

**Describe alternatives you've considered**
None

**Additional context**

<img width="583" alt="sort" src="https://user-images.githubusercontent.com/9113844/221404945-c5cc746c-211d-45cf-b4cd-b0162d45f1ab.png">

**Comment by dvsrepo** [comment]
Hi @orasik , nice suggestions! We've been using this technique a lot but passing a generated metadata field which will then appear in the sort filter. Let me know if that could work for you. In any case we will think about making this available generally as we compute it as a metric

**Comment by orasik** [comment]
Thank you @dvsrepo, for the quick response! 
I was just reading about the metadata and noticed it would add filters at the top. I will check this out today.

 But for newcomers like me, I think adding length by default as metadata will:

1. Help solve this issue without much work.
2. Make the new users aware of the metadata filters. 

Your thoughts?

**Comment by dvsrepo** [comment]
Fully agree @orasik , we'll discuss adding this with the team! Thanks again for the great feedback!
