### ISSUE TITLE
`un-validate` or `un-discard` a record from within the UI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2423]
**Is your feature request related to a problem? Please describe.**
after validating a record (by accident) I potentially want to revert this.

**Describe the solution you'd like**
This could be done by pressing the validate button again. I believe this used to be possible before.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
this also applies to un-discarding

**Comment by Amelie-V** [comment]
Pending to be implemented into T2T at bulk action level
