### ISSUE TITLE
🍓 Add shortcuts section to the help box

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2438]
**Is your feature request related to a problem? Please describe.**
It is not clear what shortcuts are available to use while annotating.

**Describe the solution you'd like**
Add a concise shortcuts guide to the help box.

**Describe alternatives you've considered**
Perhaps a shortcuts section in the docs.

**Additional context**

**Comment by nataliaElv** [comment]
For example, a user mentioned that they didn't know that they could delete labels using the double-click. Maybe we should add this to the shortcuts help?

**Comment by Amelie-V** [comment]
@nataliaElv would be nice to dress a list from the main shortcuts that need to be more explicit threw the app, then let's see if we can categorize them by type, and define an information architecture. 

I would push the main ones into the help box and publish the extended list into the docs (linked to the help box)
