### ISSUE TITLE
Installing argilla on my office mac

### ISSUE THREAD

**Issue by vahuja4** [recognai/rubrix#2452]
**Describe the bug**
Unable to install argilla[server] on my office laptop. Here is the error:
```
ERROR: Could not find a version that satisfies the requirement segment-analytics-python==2.2.0; extra == "server" (from argilla[server]) (from versions: 2.2.2)
ERROR: No matching distribution found for segment-analytics-python==2.2.0; extra == "server"
```

**To Reproduce**
NA

**Expected behavior**
NA
**Screenshots**
NA
**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS Ventura 13.2.1
 - Browser [e.g. chrome, safari]: NA
 - Argilla Version [e.g. 1.0.0]: 2.2.0
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**
I am able to install other open-source packages on my office mac but argilla's installation fails.

**Comment by davidberenstein1957** [comment]
Hi, what python version are you using? Also, there is no 2.2.0 version of argilla yet. Perhaps you mean 0.2.2?

**Comment by vahuja4** [comment]
Python 3.8.16

Sorry, I was not trying to install any particular version. I just used the command `pip install argilla[server]`

**Comment by vahuja4** [comment]
Should I try a different python version? Any suggestions for the version number?

**Comment by davidberenstein1957** [comment]
[It seems](https://pypi.org/project/segment-analytics-python/#history) there is a `segment-analytics-python==2.2.0` available from here for python>3.6, so I am unsure about the error. Could you use `which python` and `pip list` within your environment?

**Comment by vahuja4** [comment]
```
/usr/local/jpmc/bin/anaconda3/envs/argilla/bin/python

Package    Version
---------- ---------
certifi    2021.5.30
pip        21.2.2
setuptools 58.0.4
wheel      0.37.1

```

**Comment by davidberenstein1957** [comment]
And `python --version`?

**Comment by vahuja4** [comment]
Python 3.6.13 :: Anaconda, Inc.

**Comment by davidberenstein1957** [comment]
That is the issue. Because [Python 3.6 is not officially supported anymore](https://endoflife.date/python), we stopped support for it too. You can try using a newer version of python, like 3.9.

**Comment by vahuja4** [comment]
ok, I updated to 3.9, but now I get this:

```
Collecting argilla[server]
  Using cached https://artifacts-read.gkp.jpmchase.net/artifactory/api/pypi/pypi/packages/argilla/1.3.0/argilla-1.3.0-py3-none-any.whl (2.0 MB)
ERROR: Cannot install argilla[server]==1.3.0 and argilla[server]==1.3.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    argilla[server] 1.3.1 depends on segment-analytics-python==2.2.0; extra == "server"
    argilla[server] 1.3.0 depends on segment-analytics-python==2.2.0; extra == "server"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by davidberenstein1957** [comment]
Hi, are you trying to install both 1.3.1 and 1.3.0 at the same time?

I use python 3.9 and cannot reproduce this error. 

To get started you can host the server separate form the client and use `pip install argilla`.
- [server at hugginface](https://docs.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html)
- [server via docker-compose](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker_compose.html)
- [server via docker](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker-quickstart.html)

**Comment by vahuja4** [comment]
The thing is that we can't download 3rd party docker images, so I was wanting to install this via pip..Is there a way for me to build the docker image locally?

**Comment by davidberenstein1957** [comment]
Yes, but then I would recommend using [HuggingFace](https://docs.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html) spaces to get started and play around instead .

**Comment by vahuja4** [comment]
The dataset is confidential - can't use HF spaces.

**Comment by vahuja4** [comment]
So, we need to use a command, so that a pypi package gets pulled into our internal system. The command looks like this:
`repo procure --artifact-type PYPI --artifact-id requests==2.24.0`

What would the artifact-id be for argilla[server]

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2476
