### ISSUE TITLE
Normalization of deprecation warnings

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#2456]
**Is your feature request related to a problem? Please describe.**
I would like for all deprecation warnings to have:
1. The same text format.
2. Be thrown in the same way, either via `warnings.warn` or via `logger.warning`.
3. If `warnings.warn` is decided on, I would like for all deprecation warnings to have the same category. Currently, we use UserWarning, FutureWarning, DeprecationWarning

**Describe the solution you'd like**
I would like to see one approach used throughout Argilla.

**Describe alternatives you've considered**
Sticking with the current approach of mixing and matching `_LOGGER.warning(...)` and `warnings.warn`:
![image](https://user-images.githubusercontent.com/37621491/222385569-08de3564-4fa7-4508-a363-249ea2668d56.png)

**Additional context**
N/A

Note that the `warnings.warn` warnings are not formatted nicely using `rich`, while the logger ones obviously are.
I'd like to have a bit of a discussion on this topic, so we can reach a consensus on which approach we should use throughout the project.

cc: @dvsrepo @frascuchon @davidberenstein1957 

- Tom Aarsen

**Comment by davidberenstein1957** [comment]
For me `_LOGGER.warning` seems like the way to go. And I would like to use `FutureWarning` to ensure the fact that it is being reported.

**Comment by tomaarsen** [comment]
I don't think we can use a `Warning` class if we use `_LOGGER.warning`, can we? The `Warning` classes are only for `warning.warn(..., category=FutureWarning)` etc.

**Comment by davidberenstein1957** [comment]
Ahh, I assumed we could pass that there too.

**Comment by alvarobartt** [comment]
Hi @tomaarsen and @davidberenstein1957, so in order to handle this we can rely on https://docs.python.org/3/library/logging.html#logging.captureWarnings, so that we can still use the `warnings` library and keep the `DeprecationWarning`/`FutureWarning` messages.

I'm happy to tackle this.
