### ISSUE TITLE
evaluate `speed` and `efficiency` improvements for `rg.load` and `rg.log` 

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2458]
**Is your feature request related to a problem? Please describe.**
`rg.load` and `rg.log` slow from time to time. 
- https://github.com/argilla-io/argilla/issues/2398
- https://github.com/argilla-io/argilla/issues/2261

**Describe the solution you'd like**
as a quick fix:
- https://github.com/argilla-io/argilla/issues/2454
- https://github.com/argilla-io/argilla/pull/2417
- https://github.com/argilla-io/argilla/issues/2341

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
Your first quick fix is also described in #2454. I'll be tackling that issue today. 
Edit: I now see that you linked to #2454 already, whoops.
