### ISSUE TITLE
🍓 Train: Adding code snippets

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#2475]
**Is your feature request related to a problem? Please describe.**
This new feature is currently in the specification with a high priority.

**Describe the solution you'd like**
Reduce the gap between training and annotation activities.
Provide some code snippets from a selection of libraries into the UI (All dataset views and mode)

**Describe alternatives you've considered**
-

**Additional context**
- Spec in Notion

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2391
