### ISSUE TITLE
add an `argilla.training` module to the core library with training workflows

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2504]
**Is your feature request related to a problem? Please describe.**
Some users find it difficult to grasp the step from annotated data to a trained model.

**Describe the solution you'd like**
```
from argilla.training import AutoTrainer, TransformersTrainer, SpacyTrainer

autotrain("dataset", query="status: Validated AND event_timestamp > *")
```
**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/2391

**Comment by dvsrepo** [comment]
@tomaarsen @davidberenstein1957 

Given the demonstrated benefits and huge interest of the community in SetFit, I'd propose adding it as our first training workflow.

**Comment by tomaarsen** [comment]
@davidberenstein1957 Do you want to open a draft PR for this, so we have a clearer place to discuss this work?

**Comment by davidberenstein1957** [comment]
Currently, we are working on support for `transformers` and already wrapped up support for `setfit`. Ideally we want to include support for `spacy` too. By default, we would like to see support for `token_classificaiton`, but due to the `prepare_for_training(framework="spacy", nlp=nlp)` method within Argilla, it should be straightforward to add `text_classification` support too. You can just look at the setfit implementation, but the outcome of the PR should be.

```python
from argilla.training import ArgillaTrainer
​
trainer = ArgillaTrainer("dataset_name", "model_path_or_name" framework="spacy", train_size=0.8)
trainer.update_config(num_epochs=2, **kwargs)
trainer.train(path="test_model")
records = trainer.predict("This is a test", as_argilla_records=True)
```

Even though spaCy focuses on CLI-based training it should be accessible via the Python client too and can thus be nicely integrated here too.

```python
from spacy.cli.train import train as spacy_train
config_path = "spacy_textcat/config.cfg"
output_model_path = "output/spacy_textcat"
spacy_train(
    config_path,
    output_path=output_model_path,
    overrides={
        "paths.train": "train.spacy",
        "paths.dev": "valid.spacy",
    },
)
```

Including some hyperparameter optimization might also be an option.

**Comment by alvarobartt** [comment]
Hi @davidberenstein1957! Are you happy if I tackle #2594? Also, do I need to wait until #2574 is out of draft-mode, or can I start working on top of that PR already? Thanks :hugs:

**Comment by davidberenstein1957** [comment]
Hello Álvaro,Feel free to pick this up. You do not need to wait untill it is out of draft-mode. Good luck👍Regards,DavidOn 24 Mar 2023, at 09:04, Alvaro Bartolome ***@***.***> wrote:﻿
Hi @davidberenstein1957! Are you happy if I tackle #2594? Also, do I need to wait until #2574 is out of draft-mode, or can I start working on top of that PR already? Thanks 🤗
