### ISSUE TITLE
Export dataset to HF Hub from the UI

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#2520]
**Is your feature request related to a problem? Please describe.**
I want an action in the UI to push the dataset to the Hub. We currently can push two "types" of datasets to the Hub:

1. Prepared for training: which applies pre-processing to align the dataset format with "standard" training sets and now can also split the dataset into train and test
2. Argilla Dataset: this pushes the full dataset with an "Argilla" format that can be used to import back the dataset using `rg.load`

At first, I would say the most relevant is type 2. as I think the main goal at firs is to let users keep a copy of the datasets (especially crucial for Argilla HF spaces) and be able to restore the dataset, as we do for most of our tutorials. But I'm open to additional export "types" which include the option to export type 2. as well.

Another thing to take into account, maybe for further iterations if this is a blocker is that users might want to push to a private dataset so we need to ask them for an HF token.

**Describe the solution you'd like**
I would like to have a button and modal box somewhere in the UI to push the dataset to the Hub. In this modal box we can require the users to input:

1. HF organization target: where to push the dataset
2. Dataset name: we can propose the same name as in Argilla but let users change this
3. A query to filter the dataset to push? Not sure we need/desire this but might be a good feat.

If something went wrong when pushing the dataset, provide a clear message to the user of what went wrong.

This will require to have the logic of pushing the dataset in the backend, and add `datasets` as a dependency for at least the server but I don't see an issue there.

**Describe alternatives you've considered**
Using listeners or the Python client but this is already possible and leaves non-developers out of this feature.

**Additional context**
We have something along these lines in the `export-to-hub` (https://huggingface.co/spaces/argilla/argilla-streamlit-customs) but as I said first use case is pushing even without preparing for training.

**Comment by davidberenstein1957** [comment]
So, ideally I was wondering if it would be possible to create a similar card where you add (title, description, buttonText and buttonLink), and potentially add `required_environment_var`, `endpoint` `request_type`, and `payload/form`.

- it should only show when the `required_environment_var  is not None.
- there should be some definition option for the `payload`, being either set to the `required_environment_var`, and/or a `form` with customizable fields. (I would like to use a form to keep it as flexible as possible for potential other integrations).
- there should be a FastAPI Server `endpoint` which does something with this request and `payload`, like exporting data to the hub, csv, or excel.
- in this way, we could potentially also let users import data from the hub or potentially via a form upload.
- In the future, similar configurations might be used to start training on `AutoTrain`.

**Comment by nataliaElv** [comment]
Importing and exporting directly from the UI is a popular request in our community, so I'm removing this from stale.
