### ISSUE TITLE
Image2TextRecord 

### ISSUE THREAD

**Issue by santialferez** [recognai/rubrix#2557]
It would be interesting to have something like an Image2TextRecord to create datasets that could be useful for models involving both text and images, such as embeddings (sentence Transformers).

Thank you for this wonderful framework!

**Comment by davidberenstein1957** [comment]
Hi @santialferez sorry for the late reply. We missed this at first. We do have [basic multimodal support](https://docs.argilla.io/en/latest/getting_started/installation/configurations/image_support.html). Does it work for your usecase?
