### ISSUE TITLE
Issue with annotation rules that are considered as existing rules

### ISSUE THREAD

**Issue by pierre-ollivier** [recognai/rubrix#2561]
**Describe the bug**
This bug appears while trying to add an annotation rule on weak annotation mode.

On the picture below, I try to add a rule from the query `text:"jobs"`. This rule isn't part of the rules I already set, however it is considered by Argilla as "already saved as rule".
<img width="1307" alt="Screenshot 2023-03-16 at 10 20 34" src="https://user-images.githubusercontent.com/99399264/225734063-3f71c0bb-47d4-4806-be06-baee1f538b03.png">

After two clicks on the "Workforce & organizational" button, the message disappears and it becomes possible to add the rule, reaching the second picture below. The number of rules increased from 10 to 11 as well as the total coverage.
<img width="1315" alt="Screenshot 2023-03-16 at 10 20 49" src="https://user-images.githubusercontent.com/99399264/225734085-04505593-9efb-4e28-8c75-f5cd015be94f.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: iOS
 - Browser [e.g. chrome, safari]: Chrome

**Additional context**
Argilla instance used by Datamaran

**Comment by chozelinek** [comment]
Same here using argilla server version 1.2.1 and Chrome Version 111.0.5563.64 (Official Build) (x86_64) Watch the video below:
https://user-images.githubusercontent.com/2077497/225859107-8f945dfb-93ce-4f9c-b2a0-dacd5b3f51c1.mp4

**Comment by keithCuniah** [comment]
A correction of this problem have been implemented on this issue #2117
