### ISSUE TITLE
Similiarity search with score

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2565]
The current implementation of `rg.load` allows querying records by a vector and returns them sorted by similarity score. However, it's challenging to include the record score as part of the response since `rg.load` is tightly coupled with the record structure definition. Therefore, new functionality is required to fetch records and their scores separately while querying by a vector.

The new method should accept the dataset name, the dataset workspace, a filter applied to data (optional), and the vector to apply as inputs. The output of the method should be a list of tuples containing the records' data in raw format and their corresponding scores. For example:

```python
[({ "text": "This is a text", ....}, 0.93),({ "text": "This is not a text", ....}, 0.83)....)]
```

The server should return the score values from all the `{task}:search` endpoints in a separate response field such as "scores", "search_score", or "similarity_score". This value should be returned only when a similarity search is applied. However, it could be extended in the future to always return the search score, but this is currently out of scope. Reference can be taken from this link: https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#approximate-knn

These changes should be updated in the documentation files such as `docs/_source/guides/label_records_with_semanticsearch.ipynb`, `docs/_source/guides/schedule_jobs_with_listeners.ipynb`, and `docs/_source/guides/query_datasets.md`.

Finally, these changes should be tested thoroughly to ensure that the new functionality is working as expected.

**Comment by frascuchon** [comment]
Refs: https://github.com/argilla-io/argilla/issues/2348

**Comment by burtenshaw** [comment]
@frascuchon This seems doable, but I have a couple of functionality questions.

On the client side, 
- Are you suggesting a new `client.api` method (something like `load_similar`) with the inputs and outputs you describe? 
- If so, should `load` remain as-is without returning scores?

This makes sense to me because `load` loads datasets, and the new method returns tuples of records and scores.
