### ISSUE TITLE
Notebook template in ToC

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2567]
**Is your feature request related to a problem? Please describe.**
The template to create new notebooks appears in the ToC in the left sidebar as "INSERT TITLE". 
https://docs.argilla.io/en/latest/tutorials/notebooks/template.html

**Describe the solution you'd like**
It could appear at the very end of the section as "Template for new notebooks" or not appear in the ToC at all, just accessible from the repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by garimau** [comment]
@nataliaElv I think having it as just a file in the repo would be fine because anyone who wants to use the template will be accessing the repo regardless, right? I can move it to the bottom of the section with the title you suggested too, just let me know what is preferable!
