### ISSUE TITLE
🍓 Automate year shown in UI and sites

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2569]
**Is your feature request related to a problem? Please describe.**
The year shown in Argilla UI, docs and website is outdated. 

**Describe the solution you'd like**
Automate the year that is displayed in these sites.

**Describe alternatives you've considered**

**Additional context**

**Comment by tomaarsen** [comment]
<details><summary>Click here for screenshots</summary>

![image](https://user-images.githubusercontent.com/37621491/225900583-c4c20983-0121-4be4-99b5-30a19a4eeb8f.png)
![image](https://user-images.githubusercontent.com/37621491/225900604-8e1f4cdf-3d4e-45db-9420-6c1e76981613.png)
![image](https://user-images.githubusercontent.com/37621491/225900609-ab77d135-5166-4083-9e25-b912587c9044.png)
</details>

The docs take the copyright from here:
https://github.com/argilla-io/argilla/blob/dcabc4ee08abed20a95208cc57ba4866e2d6a644/docs/_source/conf.py#L44

**Comment by leiyre** [comment]
- [x] Automate year in App
- [x] Automate year in Website
- [x] Automate year in Docs
  - https://github.com/argilla-io/argilla/pull/2603

**Comment by Amelie-V** [comment]
How can we finish this update? @nataliaElv

**Comment by nataliaElv** [comment]
I'll give it a go on Monday. It shouldn't be difficult 😃

**Comment by jfcalvo** [comment]
> I'll give it a go on Monday. It shouldn't be difficult 😃

Sorry I just saw this. BTW what about fixing this too on the corporate website? (I mean at https://argilla.io) Looks like is showing 2023 but probably is some static string.

**Comment by jfcalvo** [comment]
> > I'll give it a go on Monday. It shouldn't be difficult 😃
> 
> Sorry I just saw this. BTW what about fixing this too on the corporate website? (I mean at https://argilla.io) Looks like is showing 2023 but probably is some static string.

@leiyre already changed it to be dynamic.
