### ISSUE TITLE
add document reference in case of error in query and ref in query bar from UI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2575]
**Is your feature request related to a problem? Please describe.**
@tomaarsen mentioned query options might be a  bit vague from within the UI. 

**Describe the solution you'd like**
Perhaps it makes sense to directly link this to the [docs](https://docs.argilla.io/en/latest/guides/query_datasets.html).

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
In particular, it is not clear what the syntax is for the query in the top left of the UI. Only through Googling did I find out that the [Query Datasets](https://docs.argilla.io/en/latest/guides/query_datasets.html) docs show the syntax. Thanks for opening this issue @davidberenstein1957.
