### ISSUE TITLE
Upgrade tutorials to use latests argilla python package version

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#2583]
**Describe the bug**

Some Argilla tutorials like [this one](https://github.com/argilla-io/argilla/blob/develop/docs/_source/tutorials/notebooks/labelling-textclassification-setfit-zeroshot.ipynb) are using an specific version of `argilla` Python package:

```sh
%pip install argilla==1.3.0 datasets==2.8.0 sentence-transformers==2.2.2 setfit==0.6.0 plotly==4.1.0 -qqq
```

This is causing some errors on the tutorial with a deprecated behavior associated with missing workspace provided when creating records.

The idea is to review our tutorials and if it's possible use latests versions of our Python packages.

I have found too some warnings with deprecated functions executing the tutorials notebooks. Not sure if this is really important or not.

**To Reproduce**

1. Go to [Zero-shot and few-shot classification with SetFit tutorial](https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-setfit-zeroshot.html).
2. Click on "Open in Colab" button and follow the tutorial.
3. Notice how a specific version of `argilla` is used.
4. Execute the notebooks steps until a workspace missing error is raised by Argilla server.

**Expected behavior**

- Our tutorials should use by default the latest version of our Python packages.
- Should work as expected and without errors.
- If possible remove warning messages upgrading necessary packages.

**Additional context**

@davidberenstein1957 I have assigned you but I have noticed that @tomaarsen and @dvsrepo are authors of some of these tutorials too. Please feel free to reassign the issue if necessary.

**Comment by garimau** [comment]
@davidberenstein1957 Sorry, I forgot to mention that I made the quick fix for this earlier (it was only an issue in two tutorials from what I could tell).
