### ISSUE TITLE
Quickstart users cannot create labels or set label schema from Python (since 1.5.0)

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#2590]
I'm preparing the challenge for the Alpaca Dataset ([see](https://huggingface.co/datasets/somosnlp/somos-alpaca-es/blob/main/README.md)).

I realized that the `team` user can no longer create or set the labeling schema (via UI or Python).

I understand `v1.5.0` is a transition towards the DB, but if we don't set the `team` user as `superuser` for `1.5.0` no user can create labels. There seems to be a user field for this instead of the `workspaces=[]` logic we had before (or maybe it's just too late and I'm messing something up 💤 ).

At the bottom of this notebook you can find the issue:

https://colab.research.google.com/drive/1KyikSFeJe6_lQNs-9cHveIOGM99ENha9#scrollTo=NWtQedKhg7I_

**Comment by frascuchon** [comment]
Yes, you're right. A user with `workspces=[]` is considered a normal user and won't be able to store settings (from v1.5.0, before, the restriction was also about dataset creator, but this will change) I've made changes to the quickstart image setup to fix this. 

It's working as expected now.

**Comment by dvsrepo** [comment]
Yihaaa
