### ISSUE TITLE
Update image classification tutorial

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2592]
**Is your feature request related to a problem? Please describe.**
This [tutorial](https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-image-bulk-labelling.html?highlight=image%20bulk) was written before argilla supported image urls. We should probably update it to reflect the changes after v1.5.0

**Comment by burtenshaw** [comment]
This relates to these changes:

- https://github.com/argilla-io/argilla/commit/70628192461835e39d71d92a89f55f1551ca48f5
- https://github.com/argilla-io/argilla/commit/941233b248bf7f9e46f42a5c6d90f240048ffb23

- [ ] The tutorial should be updated to the `_image_url` metadata field.
- [ ] The guidelines for the custom docker image should be replaced with standard instructions.

I can take this up.

**Comment by burtenshaw** [comment]
This relates to these changes #2571 

- [ ] The tutorial should be updated to the `_image_url` metadata field.
- [ ] The guidelines for the custom docker image should be replaced with standard instructions.

I can take this up.

**Comment by nataliaElv** [comment]
Thanks @burtenshaw ! Go ahead 😃
