### ISSUE TITLE
Add `argilla.training` module for spaCy integration

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2594]
Currently, we are working on support for `transformers` and already wrapped up support for `setfit`. Ideally, we want to include support for `spacy` too. By default, we would like to see support for `token_classificaiton`, but due to the `prepare_for_training(framework="spacy", nlp=nlp)` method within Argilla, it should be straightforward to add `text_classification` support too. You can just look at the setfit implementation, but the outcome of the PR should be.

```python
from argilla.training import ArgillaTrainer
​
trainer = ArgillaTrainer("dataset_name", "model_path_or_name" framework="spacy", train_size=0.8)
trainer.update_config(num_epochs=2, **kwargs)
trainer.train(path="test_model")
records = trainer.predict("This is a test", as_argilla_records=True)
```

Even though spaCy focuses on CLI-based training it should be accessible via the Python client too and can thus be nicely integrated here too.

```python
from spacy.cli.train import train as spacy_train
config_path = "spacy_textcat/config.cfg"
output_model_path = "output/spacy_textcat"
spacy_train(
    config_path,
    output_path=output_model_path,
    overrides={
        "paths.train": "train.spacy",
        "paths.dev": "valid.spacy",
    },
)
```

Including some hyperparameter optimization might also be an option.

_Originally posted by @davidberenstein1957 in https://github.com/argilla-io/argilla/issues/2504#issuecomment-1480981433_

**Comment by alvarobartt** [comment]
Hi @frascuchon can you please assign this ticket to me? Thanks 👍🏻
