### ISSUE TITLE
bulk log fails in case of single record is anomalous

### ISSUE THREAD

**Issue by Ankush-Chander** [recognai/rubrix#2625]
**Describe the bug**
In case of logging records in bulk, single invalid record leads to failure for entire batch.

**To Reproduce**
```
import argilla as rg
valid_record = rg.TokenClassificationRecord(
                            text="My valid record",
                            tokens="My valid record".split(),
                            prediction=[("first", 0, 2), ("second", 3, 8)],
                            prediction_agent="stanford_openie"
                        )

invalid_record = rg.TokenClassificationRecord(
        text="My valid record",
        tokens="My valid record".split(),
        prediction=[("first", 0, 2), ("second", 0, 8)],
        prediction_agent="stanford_openie"
    )

records = [valid_record, invalid_record]
x = rg.log(name="mock-ds1", records=records)
```
Leads to 500 response on client side

Server side error log leads to following:
```
INFO:     127.0.0.1:60252 - "POST /api/datasets/mock-ds1/TokenClassification%3Abulk HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
...
    return await dependant.call(**values)
  File "/home/ankushchander/workplace/open_source/argilla/src/argilla/server/apis/v0/handlers/token_classification.py", line 117, in bulk_records
    records=records,
  File "/home/ankushchander/workplace/open_source/argilla/src/argilla/server/services/tasks/token_classification/service.py", line 67, in add_records
    record_type=ServiceTokenClassificationRecord,
  File "/home/ankushchander/workplace/open_source/argilla/src/argilla/server/services/storage/service.py", line 66, in store_records
    record.metrics = metrics.record_metrics(record)
  File "/home/ankushchander/workplace/open_source/argilla/src/argilla/server/services/tasks/token_classification/metrics.py", line 278, in record_metrics
    predicted_tags = cls._compute_iob_tags(span_utils, record.prediction) or []
  File "/home/ankushchander/workplace/open_source/argilla/src/argilla/server/services/tasks/token_classification/metrics.py", line 313, in _compute_iob_tags
    return span_utils.to_tags(spans)
  File "/home/ankushchander/workplace/open_source/argilla/src/argilla/utils/span_utils.py", line 156, in to_tags
    raise ValueError("IOB tags cannot handle overlapping spans!")
ValueError: IOB tags cannot handle overlapping spans!
```
**Expected behavior**
I can think of following possible solutions: 
1. failed records should be communicated back to user so that they can be fixed. It is similar to how elasticsearch returns failed records in index, update apis. [my favourite]
2. silently ignore records with error while indexing valid records
3. Index all records. Ignore prediction logging in case of invalid records 

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by Ankush-Chander** [comment]
Hi team,
I intend to take this issue up. 
Will come up with a PR soon.
Would appreciate help on zeroing in the desired behaviour.

**Comment by Ankush-Chander** [comment]
Hi team,
I intend to take this issue up. 
Will come up with a PR soon.
Would appreciate help on zeroing in the desired behaviour.

**Comment by mnschmit** [comment]
Hi @Ankush-Chander , I just found your issue and this is also something that bugs me a lot. Currently, I have to log one record at a time to make sure that all valid records are indexed and I correctly identify all invalid ones to only log these to be fixed later.

So my favorite behavior would be that all valid elements in a batch are indexed and that the `BulkResponse` not only returns the total number of processed/failed records but also which ones failed. This could be a list of indices into the input iterable of records / Dataset or the failed records themselves or the record ids.
@davidberenstein1957 recently told me that the record ids are created on client side (did I get that right?). So if we know them in the client code, the ids of failed records would also be a valuable response to identify the invalid ones.

What do you think @Ankush-Chander ? Have you already started working on this?

**Comment by davidberenstein1957** [comment]
You did get that right:)

**Comment by Ankush-Chander** [comment]
Hi @mnschmit ,
+1  on the desired behaviour.
 
I did follow through the related code but not much thereafter.
Let me give it a try on weekend. 

@davidberenstein1957

**Comment by mnschmit** [comment]
Hi @Ankush-Chander ,
any update on this? Can I help?

**Comment by Ankush-Chander** [comment]
Hi @mnschmit 
I am sorry, I am not able to make time for this as much as I would want to lately.
Would be better if someone can take it up for now.
