### ISSUE TITLE
Cannot run several log concurrently

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2631]
**Describe the bug**
Since `rich` dependency is included, the `rg.log` cannot be called concurrently:

**To Reproduce**
```python
import argilla as rg

ds_01 = ...
rg.log(ds_01, name="my-dataset", background=True)


ds_02 = ...
rgl.log(ds_02, name="my-dataset02", background=True)
```
```bash
03/31/23 16:00:30] ERROR    ERROR:argilla.client.client:                                                                                                                   client.py:103
                             Cannot log data in dataset 'my-dataset02'
                             Error: LiveError
                             Details: Only one live display may be active at once
```

**Expected behavior**
Logging data concurrently should be allowed.

**Screenshots**

**Environment (please complete the following information):**
 - OS  := MacOS
 - Browser [e.g. chrome, safari]:
 - Argilla Version := v1.5.1
 - ElasticSearch Version := 8.5.2

**Additional context**

**Comment by davidberenstein1957** [comment]
https://rich.readthedocs.io/en/stable/live.html#nesting-lives

**Comment by davidberenstein1957** [comment]
https://github.com/Textualize/rich/issues/1530
