### ISSUE TITLE
add `argilla.training` support for `hyperparamoptimization` with `setfit`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2661]
**Is your feature request related to a problem? Please describe.**
I want my hyperparameters to be better

**Describe the solution you'd like**
using their [implementation](https://github.com/huggingface/setfit#running-hyperparameter-search) 

**Describe alternatives you've considered**
Manual optimization by eye-balling.

**Additional context**
N.A.

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 can I pick this up ?
