### ISSUE TITLE
psycopg2 wheel missing from Docker image

### ISSUE THREAD

**Issue by baudlord** [recognai/rubrix#2686]
**Describe the bug**
Argilla cannot start with a PostgreSQL database backend, as the psycopg2 wheel is missing from the Docker image.

**To Reproduce**
1. Start up an Argilla 1.6.0 container defining `ARGILLA_DATABASE_URL` with a PostgreSQL URL.

**Expected behavior**
Argilla uses the PostgreSQL database backend.

**Screenshots**
`ModuleNotFoundError: No module named 'psycopg2'`

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Linux
 - Browser [e.g. chrome, safari]: N/A
 - Argilla Version [e.g. 1.0.0]: 1.6.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.5.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla:v1.6.0

**Additional context**
N/A

**Comment by jfcalvo** [comment]
Adding here build requirements for psycopg2:
* https://www.psycopg.org/docs/install.html#build-prerequisites
* `libpq` could be installed using Conda: https://anaconda.org/conda-forge/libpq
