### ISSUE TITLE
Block data for each annotator

### ISSUE THREAD

**Issue by anhphong22** [recognai/rubrix#2688]
**Description**
- When the annotators labeled data in workspace, another annotators also labeled this data in the same workspace and task. The problem is that data fetched does not be allocated for each user. In the other word, the first annotator labels for document 1, and the another also labels for document 1, they do not whether teammate have done this document or not. In current solution, annotator coming later will overlaps in the results of that of the first one. This makes many users work on the same task leading to conflict the results. 

**Solution**
- Data is allocated for each annotator, and invisible for the others but workload of the project is visualized
- Reference: https://rasa.com/docs/rasa-enterprise/user-guide/annotate-nlu-examples/

**Comment by nataliaElv** [comment]
Hi @anhphong22 ! We had a similar problem while doing an internal annotation project and we found a workaround: we added an "annotator" field in the metadata and we assigned the records randomly between the available annotators, then we asked them to filter the records with their name using the "Metadata" filter in the UI. That way they only see records assigned to them and we avoided overlap. 
Does this sound like something that solves your issue?

**Comment by anhphong22** [comment]
Hi @ Natalia Elvira
Your solution sounds good. From my experience, I design a database with multiple stage for fetching and syncing data from local to remote. The annotator was assigned or selected what records you want, these records sent status (in progress, subjected to timeout) to remote database, meaning that the others could not employ these records.

From: Natalia Elvira ***@***.***>
Date: Monday, 17 April 2023 at 15:59
To: argilla-io/argilla ***@***.***>
Cc: Nguyen Thanh Phong ***@***.***>, Mention ***@***.***>
Subject: Re: [argilla-io/argilla] Block data for each annotator (Issue #2688)

Hi @anhphong22<https://github.com/anhphong22> ! We had a similar problem while doing an internal annotation project and we found a workaround: we added an "annotator" field in the metadata and we assigned the records randomly between the available annotators, then we asked them to filter the records with their name using the "Metadata" filter in the UI. That way they only see records assigned to them and we avoided overlap.
Does this sound like something that solves your issue?

**Comment by nataliaElv** [comment]
I'm thinking of a solution to do this using roles and workspaces.  I'm putting together a tutorial inspired by this issue #2705
