### ISSUE TITLE
Make keywords clickable

### ISSUE THREAD

**Issue by PhilipMay** [recognai/rubrix#2695]
Argilla offers a keyword list of the texts. See screenshot:

![image](https://user-images.githubusercontent.com/229382/231837570-cd490b5c-3d7f-47fb-8f79-be41f15c6399.png)

It would be nice if the keywords could be clickable so I see all datasets that are connected with these keywords.

**Comment by nataliaElv** [comment]
Hi @PhilipMay! Could you provide more details about this issue? What would be the behaviour you expect when you click on a keyword?

**Comment by PhilipMay** [comment]
The list of keywords and numbers provide a list of keywords and the number of documents that contain this keyword. Right?

Now I would like to click the individual keywords and then see only those documents that match this keyword.

If I click "def" (see screenshot) I get those 113 documents pre-filtered and can work on them.

**Comment by nataliaElv** [comment]
Ok I see! So this means that on click we would pre-fill the query field and run the query to get the records that match the keyword. I think it would be very useful to make this filtering much faster and intuitive 😃.
In the meantime, you can always enter the keyword you would like to work with in the query field.

**Comment by PhilipMay** [comment]
> Ok I see! So this means that on click we would pre-fill the query field and run the query to get the records that match the keyword. I think it would be very useful to make this filtering much faster and intuitive 😃.

Exactly!

**Comment by PhilipMay** [comment]
Can we repoen it please. Would still be very nice to have....

**Comment by PhilipMay** [comment]
@nataliaElv
