### ISSUE TITLE
Output blocks are difficult to read

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2707]
**Is your feature request related to a problem? Please describe.**
Output blocks in tutorial notebooks are difficult to read in the dark mode because of the white lettering on salmon background:
<img width="1169" alt="Captura de pantalla 2023-04-17 a las 16 38 30" src="https://user-images.githubusercontent.com/126158523/232538049-9ddca43e-e2ea-4670-863f-ca07f4ad54d2.png">

This is how it looks in light mode:
<img width="1165" alt="Captura de pantalla 2023-04-17 a las 16 36 25" src="https://user-images.githubusercontent.com/126158523/232537814-41c9078d-29b2-46e8-8672-144df0937f85.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by garimau** [comment]
@davidberenstein1957 I can work on this!
