### ISSUE TITLE
Ability to remove workspaces

### ISSUE THREAD

**Issue by bengsoon** [recognai/rubrix#2732]
**Is your feature request related to a problem? Please describe.**
I have several empty workspaces in Argilla that I would like to remove, but I'm not able to. Neither does the UI, Python SDK nor the API have a way to removing workspaces.

**Describe the solution you'd like**
- An API endpoint for DELETE `/api/workspaces/{workspace_id}`.
- Additional "Danger Zone" delete option in the UI.
- Python SDK to delete workspace like `argilla.delete`

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by frascuchon** [comment]
Fixed by https://github.com/argilla-io/argilla/pull/3358
