### ISSUE TITLE
Allow discarding/submitting responses for a record

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2733]
## Description 

We need to add an APIv1 feature allowing users to discard or submit (confirm) a response for a single record.  This response can be discarded by admin users or the user which created the response previously. 

After that action, the status of the response will become `Discarded` / `Submitted` depending on the action. 

This issue can be tackled in two separate tasks: 
- Submit responses and
- Discard responses

You could tackle one of them and is not necessary to finish the whole feat.

# Notes

Feel free to propose the endpoint definition that you consider better for this. Also, feel free to modify the database schema/table to support this new feature.

**Comment by gabrielmbmb** [comment]
hi @frascuchon, I'll create a draft PR with an initial proposal. Can you assign this issue to me? Thanks!
