### ISSUE TITLE
Adapt frontend API calls to the new structure for endpoints returning list

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2735]
Ref: #2716

**Comment by keithCuniah** [comment]
3 vue components are concerned : 
- page of datasets list (frontend/pages/datasets/index.vue)
- page of feedback task (frontend/pages/dataset/_id/annotation-mode/index.vue)
- the main content of the page of feedbacktask (frontend/components/page-contents/feedback-task-content)
