### ISSUE TITLE
Add environment variables for default credentials to documentation for user management

### ISSUE THREAD

**Issue by mnschmit** [recognai/rubrix#2749]
**Is your feature request related to a problem? Please describe.**
Prior to 1.6.0 I used to set `ARGILLA_LOCAL_AUTH_DEFAULT_APIKEY` and `ARGILLA_LOCAL_AUTH_DEFAULT_PASSWORD` to change the default credentials. Now this doesn't work anymore.

**Describe the solution you'd like**
The section about the default user (https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html#default-user) should contain information about the new environment variables `DEFAULT_USER_PASSWORD` and `DEFAULT_USER_API_KEY`.

**Comment by davidberenstein1957** [comment]
@mnschmit this was sadly removed in `1.6.0` so the documentation was removed around that time too.
