### ISSUE TITLE
user can upload/download the datasets in different formats (like CSV/excel/avro/arrow/JSON/Parquet etc) using UI

### ISSUE THREAD

**Issue by sdhaker2** [recognai/rubrix#2752]
**Is your feature request related to a problem? Please describe.**
Currently, there is no feature where users can upload/download the datasets from UI, and  Non-tech users struggle to upload/download the datasets and configure them accordingly. 

**Describe the solution you'd like**
I want to add a feature and make it more simple and easy where users can upload/download datasets from different formats using the UI. During upload, the user can assign column names to annotation, prediction, labels, and text similar to what we do during logging the datasets and can provide a link to the dataset from hugging face also and download/export the datasets in different formats (like CSV/excel/AVRO/arrow/JSON/Parquet, etc). I want to contribute to this feature.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by sdhaker2** [comment]
This is similar to #1870 and #1888 where I did not see any activity from the past 2-3 months.

**Comment by nataliaElv** [comment]
Hi @sdhaker2 ! This is definitely something we want to work on. While we work on making this available through the UI, you could check out this repo: https://github.com/argilla-io/argilla-streamlit 
This streamlit app has a data manager to import/export data in some of the formats that you mention in the issue. You could deploy it in a huggingface space, for example.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/1888

**Comment by camilleborrett** [comment]
Hi @nataliaElv ! I would also find this feature (also in [#1888](https://github.com/argilla-io/argilla/issues/1888)) really very useful.   

If you have been working on this, do you have any idea of when this feature will be official?   

The current work around you posted above no longer seems available. I get a 404 error message for both the GitHub repo [https://github.com/argilla-io/argilla-streamlit](https://github.com/argilla-io/argilla-streamlit) and the HuggingFace space [https://huggingface.co/spaces/argilla/data-manager](https://huggingface.co/spaces/argilla/data-manager).

**Comment by nataliaElv** [comment]
Hi @camilleborrett !  Exactly, that workaround doesn't apply anymore, but here's something that you can do to easily import your data:
- you can create a dataset repo and upload your data to the Hugging Face Hub.
- make sure your version of Argilla is up to date and use the "Import from Hub" directly in the UI.
I also explained this workflow here: https://www.linkedin.com/posts/neastoreca_disaster-response-dataset-how-to-upload-activity-7259488995741470720-efTl?utm_source=share&utm_medium=member_desktop

This currently works only with public datasets, but we're working to make it work for private datasets as well in the next release. Also, we expect to ship in that release the functionality to export your data to the hub as a public or private dataset. 

Do you think this should work for you?

**Comment by camilleborrett** [comment]
Thanks a lot for your quick response @nataliaElv ! That's very cool :) 
It doesn't really fit my use case though: I work in a sector that uses sensitive/confidential data, which means we cannot upload data to the Hugging Face Hub (either publicly or privately). A functionality to enable, mainly exporting, annotated data directly from the interface would be very useful. We have a tech team that uploads data to Argilla but we have non-tech annotators who would benefit from being able to export their annotations themselves in a format they can use (i.e. csv/xlsx), without always having to go through the tech team.
