### ISSUE TITLE
`gutenberg_spacy-ner-monitoring` shows duplicate records in similarity search

### ISSUE THREAD

**Issue by stephantul** [recognai/rubrix#2755]
**Describe the bug**
Hi! I was trying out the Argilla demo, and ran a similarity search on the Gutenberg NER demo. Every record showed up twice, but with different IDs (i.e., UUID), and different annotations. I'm not sure if this is meant to happen. I'm assuming the data just got included twice, but it is a bit confusing to first time users.

**To Reproduce**
1. follow the quickstart docs to deploy the docker container.
2. click on `gutenberg-spacy-ner-monitoring`
3. click `find similar` on the first record.

This will show every record twice, but with different annotations, and different IDs.

**Expected behavior**
Every record should be shown a single time.

**Screenshots**
<img width="1282" alt="Screenshot 2023-04-23 at 13 14 09" src="https://user-images.githubusercontent.com/8882233/233836586-3e161f87-3059-4463-8e7f-507bc46b1eec.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS Monterey 12.5
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.6.0
 - ElasticSearch Version [e.g. 7.10.2]: Not sure, I 
 - Docker Image (optional) [e.g. argilla:v1.0.0]: latest

**Comment by stephantul** [comment]
If you tell me how I can find which elasticsearch is bundled with the Argilla quickstart image, I can also supply that information.

**Comment by dvsrepo** [comment]
Hi @stephantul ! Thanks for reaching out, this dataset and tutorial are a bit dated but it logs indeed the records twice. This is intentional, to compare two spacy models: the TRF version to the smaller spacy model. Are you able to see the prediction agent and verify that is different for each record? You can see this with view data option as well as using the filters

**Comment by dvsrepo** [comment]
We'll update this tutorial and dataset soon to make it  more useful/clear to get started

**Comment by stephantul** [comment]
Yep, one is annotated by `en_core_web_sm`, the other with `en_core_web_trf`. Cool, thanks! I didn't realize that the same document annotated by two different agent would get different IDs.
