### ISSUE TITLE
Load a dataset for the new `FeedbackTask`

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2764]
Users can load the dataset using the Python client. The current path to do this is using the `rg.load` method, but could make sense (for technical or other implications) to use a different way to do it.

**Comment by alvarobartt** [comment]
Just as a clarification for anyone reading this before #2827 is merged, the approach for the new `FeedbackTask` datasets is to load them through `rg.FeedbackDataset.from_argilla`, and or `rg.FeedbackDataset.from_huggingface` (the latter when #2765 is completed)

So we're no longer relying on `rg.load` to load datasets for the new `FeedbackTask`, but on `rg.FeedbackDataset` to both create them (as an alternative `rg.create_feedback_dataset` can also be used) and load them from either Argilla Server or the HuggingFace Hub 🤗
