### ISSUE TITLE
Explain how to delete labels from the dataset

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2778]
**Is your feature request related to a problem? Please describe.**
Users sometimes ask how they can delete labels from their datasets. This information should be made explicit in the docs. We can use [this notebook](https://colab.research.google.com/drive/1SW-GsoYblHgIj4bJQTmZaS8ZWvBLmnwq#scrollTo=zqF9X9EZLQdj&line=7&uniqifier=1) as a starting point.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MohamedBenhammouda** [comment]
import (
        "context"
        "fmt"

        "cloud.google.com/go/bigquery"
)

// deleteDatasetLabel demonstrates removing a specific label from a dataset's metadata.
func deleteDatasetLabel(projectID, datasetID string) error {
        // projectID := "my-project-id"
        // datasetID := "mydataset"
        ctx := context.Background()

        client, err := bigquery.NewClient(ctx, projectID)
        if err != nil {
                return fmt.Errorf("bigquery.NewClient: %w", err)
        }
        defer client.Close()

        ds := client.Dataset(datasetID)
        meta, err := ds.Metadata(ctx)
        if err != nil {
                return err
        }
        update := bigquery.DatasetMetadataToUpdate{}
        update.DeleteLabel("color")
        if _, err := ds.Update(ctx, update, meta.ETag); err != nil {
                return err
        }
        return nil
}
