### ISSUE TITLE
Make displaying explanations togglable

### ISSUE THREAD

**Issue by rockwalrus** [recognai/rubrix#2785]
#**Is your feature request related to a problem? Please describe.**
The token attribution is extremely helpful for evaluating models, but can distract or bias when annotating. Some words are broken into multiple tokens, which can make them harder to read.

**Describe the solution you'd like**
A button to switch explanation on or off.

**Describe alternatives you've considered**
Logging the same data twice to different sets would require twice as much storage, but one could not have the explanation.

**Comment by davidberenstein1957** [comment]
Hi @rockwalrus, thank you for the suggestion. We will tackle this in the issue mentioned above.
