### ISSUE TITLE
Show an 'optional' tag for optional questions

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2787]
Instead of showing an asterisk for required questions in the UI, we'll show `(optional)` next to any optional question.

**Comment by frascuchon** [comment]
If we remove the asterisk for required questions, how we should tackle validations in UI when a user tries to submit a response with multiple required questions and more than one is missing?

cc @nataliaElv @Amelie-V

**Comment by frascuchon** [comment]
So, the submit button won't be available until all required questions are filled out

cc @keithCuniah @leiyre

**Comment by nataliaElv** [comment]
This has been already solved, so I'm closing this issue.
