### ISSUE TITLE
Docs still partially refer to the old argilla user credentials

### ISSUE THREAD

**Issue by anammari** [recognai/rubrix#2816]
Although the `argilla` workspace was replaced by the `admin` workspace, since users only have access to their own/assigned workspaces, the Argilla documentation still partially refers to the old `argilla` credentials

![image](https://user-images.githubusercontent.com/2264734/235412735-660361ac-9377-48e7-9861-3803930ba936.png)

![image](https://user-images.githubusercontent.com/2264734/235412754-6a0c056c-8673-4258-9d95-7e7a7e2a22e9.png)

**Comment by tomaarsen** [comment]
Similarly, our demo space still shows the old login:
![image](https://user-images.githubusercontent.com/37621491/235603646-2c4b2a98-02bf-498e-9bff-00e888d7755f.png)

I've updated the org card on Hugging Face though:
![image](https://user-images.githubusercontent.com/37621491/235603770-78415c4c-3c25-4949-95c2-fd171f161aa4.png)

But perhaps we want to recommend "admin" instead?
