### ISSUE TITLE
Wrong formatting in the Argilla Documentation - Tutorials

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#2819]
**Describe the bug**

The width of an element in the Argilla Documentation has a mismatching width with respect to some other elements of the same kind in the same view.

**To Reproduce**

1. Go to https://docs.argilla.io/en/latest/tutorials/tutorials.html
2. See the `Libraries` section

**Expected behavior**

The `Libraries` section to either contain the names of the supported/integrated libraries, or just the current but formatted to have the same width as the rest of the elements.

**Screenshots**

<img width="1186" alt="Screenshot 2023-05-02 at 12 00 32" src="https://user-images.githubusercontent.com/36760800/235642727-5904d576-9b7f-4067-ac32-444eb5fc8a8b.png">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS
 - Browser [e.g. chrome, safari]: Safari, Chrome, Arc
 - Argilla Version [e.g. 1.0.0]: Latest as of today (1.6.0)
 - ElasticSearch Version [e.g. 7.10.2]: N/A
 - Docker Image (optional) [e.g. argilla:v1.0.0]: N/A

**Comment by garimau** [comment]
Also, the libraries page has two buttons that link to our OpenAI tutorials for some reason. @davidberenstein1957 Can I please be assigned this issue?

**Comment by alvarobartt** [comment]
Sure @garimau, sorry for the delay! Feel free to tackle this 👍🏻
