### ISSUE TITLE
feat: add better `CLI` support for user and workspace management

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2838]
**Is your feature request related to a problem? Please describe.**
Currently, we provide the bare minimum support for these operation.

**Describe the solution you'd like**
workspace creation / deletion
user update / deletion
dataset config and deletion

**Describe alternatives you've considered**
N.A.

**Additional context**
since 1.7.0, we can user `python -m argilla` with typer

**Comment by alvarobartt** [comment]
Closed in favor of https://github.com/argilla-io/argilla/issues/3579
