### ISSUE TITLE
Allow persist & load feedback datasets from/to configuration files

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2872]
We need a process to serialize a dataset configuration (fields and questions) and load a dataset from the serialization

```python
ds.persist("my-dataset-file-or-folder")

another_dataset = FeedbackDataset.from_config("my-dataset-file-or-folder")
```

**Comment by alvarobartt** [comment]
As of commit https://github.com/argilla-io/argilla/commit/c841f2e1dceb07db27a066730b9cf832a65ef49e, we're already defining `FeedbackDatasetConfig` to dump and load the `guidelines`, `fields`, and `questions` from a configuration file.

So what we're doing is: map `guidelines`, `fields`, and `questions` to a `pydantic.BaseModel`, then save the `pydantic.BaseModel` in a file via `.json()`, and then loading it back. For the moment it's just available internally within the scope of `rg.FeedbackDataset.push_to_huggingface` and `rg.FeedbackDataset.from_huggingface`

**Comment by frascuchon** [comment]
Thanks @alvarobartt! Can you share a code snippet showing how to load or save the dataset from the configuration files?

**Comment by alvarobartt** [comment]
> Thanks @alvarobartt! Can you share a code snippet showing how to load or save the dataset from the configuration files?

Sure, I'll share it once it's more mature and push the branch too, I'm currently focused on a relevant improvement regarding the record logging!
