### ISSUE TITLE
Cannot start Argilla 1.6.0

### ISSUE THREAD

**Issue by ThomasA** [recognai/rubrix#2875]
**Describe the bug**
Argilla fails to start according to instructions

**To Reproduce**
1. Follow the [instructions](https://docs.argilla.io/en/latest/getting_started/installation/installation.html) to install Argilla 1.6.0
   I do this in a Python virtual environment and it appears to succeed.
2. I continue following the instructions to retrieve and start the Opensearch Docker container. This appears to work; afterwards `docker container ls` reports to containers running, apparently related to Opensearch.  
   I have also tried the Elasticsearch option, but this results in the same kind of error in step 3.
3. I follow step 3 to launch Argilla Server. This fails, see the error below.

**Expected behavior**
I expect `python -m argilla` to return without an error code, possibly stating a port on the localhost to contact the service on.

**Screenshots**
Not really a screenshot, but the command to launch Argilla Server prints the following output to terminal:

    $ python -m argilla
    INFO:     Started server process [102003]
    INFO:     Waiting for application startup.
    ERROR:    Traceback (most recent call last):
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
        self.dialect.do_execute(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
        cursor.execute(statement, parameters)
    sqlite3.OperationalError: no such table: users
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/tari/argilla/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
        async with self.lifespan_context(app):
      File "/home/tari/argilla/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
        await self._router.startup()
      File "/home/tari/argilla/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
        await handler()
      File "/home/tari/argilla/lib/python3.10/site-packages/argilla/server/server.py", line 231, in log_default_user_warning_if_present
        default_user = accounts.get_user_by_username(db, DEFAULT_USERNAME)
      File "/home/tari/argilla/lib/python3.10/site-packages/argilla/server/contexts/accounts.py", line 87, in get_user_by_username
        return db.query(User).filter_by(username=username).first()
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2743, in first
        return self.limit(1)._iter().first()  # type: ignore
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
        result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2231, in execute
        return self._execute_internal(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2126, in _execute_internal
        result: Result[Any] = compile_state_cls.orm_execute_statement(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 292, in orm_execute_statement
        result = conn.execute(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
        return meth(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
        return connection._execute_clauseelement(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
        ret = self._execute_context(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1841, in _execute_context
        return self._exec_single_context(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
        self._handle_dbapi_exception(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
        raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
        self.dialect.do_execute(
      File "/home/tari/argilla/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: users
    [SQL: SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.username AS users_username, users.role AS users_role, users.api_key AS users_api_key, users.password_hash AS users_password_hash, users.inserted_at AS users_inserted_at, users.updated_at AS users_updated_at 
    FROM users 
    WHERE users.username = ?
     LIMIT ? OFFSET ?]
    [parameters: ('argilla', 1, 0)]
    (Background on this error at: https://sqlalche.me/e/20/e3q8)
    
    ERROR:    Application startup failed. Exiting.

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 22.04)
 - Browser: Firefox 112.0.2 (I never get to the stage where the browser is involved)
 - Argilla Version: 1.6.0
 - ElasticSearch Version: 8.5.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]: N/A

**Additional context**

**Comment by alvarobartt** [comment]
Hi @ThomasA, thanks for opening this issue!

Can you try running `python -m argilla.tasks.users.migrate` before `python -m argilla`?

**Comment by frascuchon** [comment]
Thanks, @ThomasA for reaching out. I think exactly what @alvarobartt is pointing out. The latest version of Argilla introduces a user and workspace management that need some extra setup. 

Anyway, we should update this doc section, and refer to launching the [DB migrations](https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html#add-new-users-and-workspaces)

Refs #2876

**Comment by ThomasA** [comment]
`python -m argilla.tasks.users.migrate` also errs:

    ╭───────────────────── Traceback (most recent call last) ──────────────────────╮
    │ /usr/lib/python3.10/runpy.py:196 in _run_module_as_main                      │
    │                                                                              │
    │   193 │   main_globals = sys.modules["__main__"].__dict__                    │
    │   194 │   if alter_argv:                                                     │
    │   195 │   │   sys.argv[0] = mod_spec.origin                                  │
    │ ❱ 196 │   return _run_code(code, main_globals, None,                         │
    │   197 │   │   │   │   │    "__main__", mod_spec)                             │
    │   198                                                                        │
    │   199 def run_module(mod_name, init_globals=None,                            │
    │                                                                              │
    │ /usr/lib/python3.10/runpy.py:86 in _run_code                                 │
    │                                                                              │
    │    83 │   │   │   │   │      __loader__ = loader,                            │
    │    84 │   │   │   │   │      __package__ = pkg_name,                         │
    │    85 │   │   │   │   │      __spec__ = mod_spec)                            │
    │ ❱  86 │   exec(code, run_globals)                                            │
    │    87 │   return run_globals                                                 │
    │    88                                                                        │
    │    89 def _run_module_code(code, init_globals=None,                          │
    │                                                                              │
    │ /home/tari/argilla/lib/python3.10/site-packages/argilla/tasks/users/migrate. │
    │ py:110 in <module>                                                           │
    │                                                                              │
    │   107                                                                        │
    │   108                                                                        │
    │   109 if __name__ == "__main__":                                             │
    │ ❱ 110 │   migrate()                                                          │
    │   111                                                                        │
    │                                                                              │
    │ /home/tari/argilla/lib/python3.10/site-packages/click/core.py:1130 in        │
    │ __call__                                                                     │
    │                                                                              │
    │   1127 │                                                                     │
    │   1128 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:       │
    │   1129 │   │   """Alias for :meth:`main`."""                                 │
    │ ❱ 1130 │   │   return self.main(*args, **kwargs)                             │
    │   1131                                                                       │
    │   1132                                                                       │
    │   1133 class Command(BaseCommand):                                           │
    │                                                                              │
    │ /home/tari/argilla/lib/python3.10/site-packages/click/core.py:1055 in main   │
    │                                                                              │
    │   1052 │   │   try:                                                          │
    │   1053 │   │   │   try:                                                      │
    │   1054 │   │   │   │   with self.make_context(prog_name, args, **extra) as c │
    │ ❱ 1055 │   │   │   │   │   rv = self.invoke(ctx)                             │
    │   1056 │   │   │   │   │   if not standalone_mode:                           │
    │   1057 │   │   │   │   │   │   return rv                                     │
    │   1058 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!           │
    │                                                                              │
    │ /home/tari/argilla/lib/python3.10/site-packages/click/core.py:1404 in invoke │
    │                                                                              │
    │   1401 │   │   │   echo(style(message, fg="red"), err=True)                  │
    │   1402 │   │                                                                 │
    │   1403 │   │   if self.callback is not None:                                 │
    │ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)            │
    │   1405 │                                                                     │
    │   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List │
    │   1407 │   │   """Return a list of completions for the incomplete value. Loo │
    │                                                                              │
    │ /home/tari/argilla/lib/python3.10/site-packages/click/core.py:760 in invoke  │
    │                                                                              │
    │    757 │   │                                                                 │
    │    758 │   │   with augment_usage_errors(__self):                            │
    │    759 │   │   │   with ctx:                                                 │
    │ ❱  760 │   │   │   │   return __callback(*args, **kwargs)                    │
    │    761 │                                                                     │
    │    762 │   def forward(                                                      │
    │    763 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # no │
    │                                                                              │
    │ /home/tari/argilla/lib/python3.10/site-packages/argilla/tasks/users/migrate. │
    │ py:106 in migrate                                                            │
    │                                                                              │
    │   103 @click.command()                                                       │
    │   104 def migrate():                                                         │
    │   105 │   """Migrate users defined in YAML file to database."""              │
    │ ❱ 106 │   UsersMigrator(settings.users_db_file).migrate()                    │
    │   107                                                                        │
    │   108                                                                        │
    │   109 if __name__ == "__main__":                                             │
    │                                                                              │
    │ /home/tari/argilla/lib/python3.10/site-packages/argilla/tasks/users/migrate. │
    │ py:45 in __init__                                                            │
    │                                                                              │
    │    42 │   def __init__(self, users_filename: str):                           │
    │    43 │   │   self._users_filename = users_filename                          │
    │    44 │   │                                                                  │
    │ ❱  45 │   │   with open(users_filename) as users_file:                       │
    │    46 │   │   │   self._users = yaml.safe_load(users_file.read())            │
    │    47 │                                                                      │
    │    48 │   def migrate(self):                                                 │
    ╰──────────────────────────────────────────────────────────────────────────────╯
    FileNotFoundError: [Errno 2] No such file or directory: '.users.yml'

**Comment by ThomasA** [comment]
I am not sure where I should be when issuing this command. Above I tried it in my $HOME/argilla which is a directory I created as a Python virtual environment to test Argilla out in.

**Comment by frascuchon** [comment]
Sorry @ThomasA ,

I realize that the command provided is wrong. You should apply database migrations instead of users migration, so:

```bash
python -m argilla.tasks.database.migrate
```

Sorry for the confusion and the late response.

**Comment by davidberenstein1957** [comment]
Closing, this assuming it worked @ThomasA .
