### ISSUE TITLE
Allow admin user fetching dataset records with responses for all users

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#2879]
Admin users need to fetch records with all user responses for each record. 

The current endpoint `GET /api/v1/me/dataset/:dataset_id/records` allows returning only data for the connected user.

Get should have a similar admin endpoint `GET /api/v1/dataset/:dataset_id/records` fetching all record responses

The Python client should use this endpoint in order to fetch the whole dataset info.

# Tasks

- [x] Backend: Create a new endpoint used by admins to fetch records with all responses -> #2912 
- [x] Python client: Consume the new endpoint -> f06a0e23afda75632b3b92f1ac8053faa9599b05

**Comment by alvarobartt** [comment]
Just to confirm, as of commit f06a0e23afda75632b3b92f1ac8053faa9599b05 we're already using the `/api/v1/datasets/{id}/records` to fetch the records with ALL the annotations/responses 😄
