### ISSUE TITLE
Add `KerasNLP` integration in `ArgillaTrainer`

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#2894]
**Describe the solution you'd like**

I think it'll be nice to integrate [`KerasNLP`](https://github.com/keras-team/keras-nlp) as another integrated framework for the `ArgillaTrainer` to also allow users train/fine-tune Keras models.

More information at https://keras.io/keras_nlp/

**Comment by alvarobartt** [comment]
Thanks for closing @davidberenstein1957 we may eventually come back to this, but I think that due to the complexity of the installation is better to keep it away for the moment.

**Comment by davidberenstein1957** [comment]
No problem, I trimmed down some of the open issues with very low prio.
