### ISSUE TITLE
Message that warns about losing changes multiplies

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#2895]
**Is your feature request related to a problem? Please describe.**
When I get the toast message that warns the user about losing changes, it multiplies if I click on 'Next' before closing the message. 
This happens over all types of datasets.

**Describe the solution you'd like**
I'd like to see the message only once. 

**Describe alternatives you've considered**

**Additional context**

**Comment by frascuchon** [comment]
I think we need to review how the notification toast is used in this case, maybe we should use another kind of communication.
