### ISSUE TITLE
Button to close `Metrics` in UI closing the panel but not releasing the occupied space

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#2915]
**Describe the bug**

When opening the `Metrics` bar from the left panel button and trying to close it with the `>` symbol on the top left of the opened panel, it closes it, but the space occupied by it remains until refreshing the page, either via the `Refresh` button or pressing F5, Ctrl+R, or any other command to refresh the page. It does work indeed, when clicking on the `Metrics` button again.

**To Reproduce**

1. Go to your Argilla instance
2. Open any dataset
3. Click on the `Metrics` button on the left bar
4. Try to close it with the `>` button on the top left of the opened panel

**Expected behavior**

The `Metrics` panel to be closed and the space occupied by it to be released when clicking on the `>` button.

**Screenshots**

Here's a short video on what happens:

https://github.com/argilla-io/argilla/assets/36760800/772c5c88-585a-4727-89a6-0eb18d80cbb6

This is the button that doesn't work as expected:

<img width="366" alt="Screenshot 2023-05-16 at 11 08 33" src="https://github.com/argilla-io/argilla/assets/36760800/91978cf4-8bc4-4b20-aa9c-f8e4bb2d1450">

And this is the result when using that button:

<img width="1471" alt="Screenshot 2023-05-16 at 10 56 35" src="https://github.com/argilla-io/argilla/assets/36760800/74e71846-1ebb-4831-a9d3-35411d8f2857">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS
 - Browser [e.g. chrome, safari]: Chrome, Safari, Arc
 - Argilla Version [e.g. 1.0.0]: Latest (1.8.0)
 - ElasticSearch Version [e.g. 7.10.2]: N/A
 - Docker Image (optional) [e.g. argilla:v1.0.0]: N/A

**Comment by keithCuniah** [comment]
Thanks @alvarobartt.
@leiyre, this could be tackle in the same PR to update metrics style
