### ISSUE TITLE
[Question] multiple multiclass for same text classification task

### ISSUE THREAD

**Issue by felipemello1** [recognai/rubrix#2938]
Hi, I am very interested in using argilla in my company. Very exciting solution/software.

My question is the following: imagine I have an excel file, where each row is a text, and I want to do text classification. In excel, I can create multiple columns, each with its own drop down menu. Is something like this possible in argilla? For example, for the same text I could choose one of [sports, tech, finance] AND [well written,  poorly written], representing this as two columns in the excel sheet. I read the documentation, but every example I saw would only show me how to configure this as pick multiple or one from [sports, tech, finance, well written, poorly written].

Any thoughts? Thanks in advance!!

**Comment by nataliaElv** [comment]
Hi @fmellomascarenhas! This is something that we're currently working on. 

We're planning to incorporate this functionality within a new type of dataset called `FeedbackDataset` that will allow users to combine multiple questions of different types (Rating, Classification, Free text, etc.). Feedback Datasets will be included in the upcoming 1.8.0 release and we expect to include Text Classification questions (single & multi-label) in the following release 1.9.0. 

I hope this solves the question 🙂 Let me know if I can help with anything else.

**Comment by nataliaElv** [comment]
#3022
