### ISSUE TITLE
 Error when running Argilla Quickstart on Docker Desktop

### ISSUE THREAD

**Issue by lirondos** [recognai/rubrix#2951]
Hola! 
I'm trying to run Argilla locally through Docker but I get the following error: 
`
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value`

I'm using Docker Desktop on Windows.

Any hints on how to solve this? Thanks and hats off for creating an amazing product.

**Comment by lirondos** [comment]
Solved it!

Deleting the context folder as suggested by this SO reply did the trick :)
https://stackoverflow.com/a/70665766

**Comment by dvsrepo** [comment]
Hi @lirondos so good to see you here! Happy to see that you solved it. Don't hesitate to ask questions and suggestions as you go.

I still need to get back to you about Argilla Cloud
