### ISSUE TITLE
create `prepare_for_training` methods for `AutoTrain` LLM fine-tuning

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2954]
**Is your feature request related to a problem? Please describe.**
LLM fine-tuning is a requirement nowadays.

**Describe the solution you'd like**
I want to be able to dynamically select fields and responses to facilitate this for the new FeedbackTask

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by dvsrepo** [comment]
@davidberenstein1957 I realise now one thing we hadn't discussed: when you have more than one response per record you need to do some postprocessing to select/build the response to use. This can be very involved and custom (computing a ranking of annotators, pick most similar responses, I don't know :)) as of now. So we need to take this case into account. I see several options here we can discuss.

**Comment by davidberenstein1957** [comment]
@dvsrepo I agree. I just realized that there are a lot of workflows where you also have a suggestion field, which you would prefer to use if filled and otherwise use another field.
