### ISSUE TITLE
Add a user-management layer from the Python client

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#2968]
**Is your feature request related to a problem? Please describe.**

Even though the users can already be managed through the API, I think it would be much clearer if we also included that within the Python client, to avoid having to define requests to the API via Python to get information about the users in Argilla.

This would prevent users from having to do the following to list Argilla users:

```python
import httpx

rg_client= rg.active_client().client
auth_headers = {"X-Argilla-API-Key": rg_client.token}
http=httpx.Client(base_url=rg_client.base_url, headers=auth_headers)
users = http.get("/api/users").json()
```

**Describe the solution you'd like**

The class to manage the users should allow to create new users, change roles, see their information, delete/remove users, list users, filter users, etc. and any other feature that the current user-management allows via the API.

**Comment by alvarobartt** [comment]
@frascuchon I think this would be a nice-to-have at some point, but is there any plan to refactor the current API for the user management? I can tackle this for the next release if considered relevant 😄

**Comment by dvsrepo** [comment]
@alvarobartt fully agree,having this supported with proper methods in the Python SDK is important
