### ISSUE TITLE
Curate generated `DatasetCard` for `FeedbackDataset`s

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3018]
**Describe the bug**

The generated `DatasetCard` for `FeedbackDataset` when calling `push_to_huggingface` with `generate_card=True` the generated `DatasetCard` seems to have some issues when not all the information is there e.g. `description` for questions.

**Screenshots**

<img width="805" alt="image" src="https://github.com/argilla-io/argilla/assets/36760800/991f94e6-faf2-4498-8d9a-bcb3aef53977">

**Comment by tomaarsen** [comment]
Relevant lines:
https://github.com/argilla-io/argilla/blob/a37b5401d58bd42bcaa447c0080479f0dad18a13/src/argilla/client/feedback.py#L834-L839

**Comment by tomaarsen** [comment]
![image](https://github.com/argilla-io/argilla/assets/37621491/7712401e-c485-4d3b-bb62-57f96ea8ffd4)
Can we also map e.g. `<class 'str'>` to the Python class name, so add `.__class__.__name__`, preferably also highlighted in code formatting.

So, not 
<class 'str'>
but
`str`
