### ISSUE TITLE
Disallow `fields` and/or `questions` with same `name`

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3034]
**Describe the bug**

When defining a `FeedbackDataset` the following use-cases shouldn't be accepted and an exception should be raised in the client-side:

```python
import argilla as rg

ds = rg.FeedbackDataset(fields=[rg.TextField(name="text"), rg.TextField(name="text")], questions=...)
ds = rg.FeedbackDataset(fields=..., questions=[rg.TextQuestion(name="text"), rg.TextQuestion(name="text")])
ds = rg.FeedbackDataset(fields=[rg.TextField(name="text")], questions=[rg.TextQuestion(name="text")])
```

So on, we should handle that all the names across `fields` and `questions` are unique.

**Expected behavior**

A `ValueError` to be raised if the names across `fields` and `questions` are not unique.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: N/A
 - Browser [e.g. chrome, safari]: N/A
 - Argilla Version [e.g. 1.0.0]: 1.8.0
 - ElasticSearch Version [e.g. 7.10.2]: N/A
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla:v1.8.0

**Comment by nataliaElv** [comment]
Maybe also check that values / options / labels aren't repeated?
