### ISSUE TITLE
Enhance Dataset Card Structure and Content

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#3066]
**Is your feature request related to a problem? Please describe.**
I'd like to enhance the structure and content of the generated dataset card. It might be a good idea to start using a template where we can update the structure rather than doing it programmatically (in the feedback.py)

**Describe the solution you'd like**
There are a few changes I'd like to make and it's open to suggestions from @alvarobartt @davidberenstein1957  @tomaarsen @gabrielmbmb:

Include details in the  metadata YML content at the beginning of the file, at least the following:

```yaml
---
tags:
- argilla
- human-feedback
size_categories:
- 1K<n<10K (I assume we can compute this easily?)
---
```

Start with an H1 where we include the dataset name. If we think this is an issue, let's use the provided path/dataset name from the Hub but let's add something:

`# Dataset card for {dataset_name}`

Then this section is fine:

`## Load with Argilla`

To load this dataset with Argilla, you'll just need to install Argilla as `pip install argilla --upgrade` and then use the following code:

```python
import argilla as rg

ds = rg.FeedbackDataset.from_huggingface('argilla/comparison-dataset-dolly-curated-falcon')
```

`## Load with Datasets`

To load this dataset with Datasets, you'll just need to install Datasets as `pip install datasets --upgrade` and then use the following code:

```python
from datasets import load_dataset

ds = load_dataset('argilla/comparison-dataset-dolly-curated-falcon')
```

Then the `questions` and `fields`. Can we maybe make this more human-readable, provide the full info about the attributes and have them in a markdown table?

Then the Guidelines, but I'd recommend including Annotation Guidelines ( I know we use guidelines internally but for people outside it's not so clear what these are.

Finally what would be awesome (and good for the community) is to use the [recommended template](https://github.com/huggingface/datasets/blob/main/templates/README.md) (based on the Dataset cards paper).

Here we could try to align and fit our content as much as possible (the order of the content is not so relevant and we could push the things we know or can compute at card creation time).

Let me know what you think!

**Comment by alvarobartt** [comment]
Similar to https://github.com/argilla-io/argilla/issues/3018, could be tackled together!

**Comment by davidberenstein1957** [comment]
@alvarobartt hi, I think it would be great to tackle this together. Let's schedule a meeting or define the scope.
