### ISSUE TITLE
Problem while using push_to_argilla to a FeedbackDataset

### ISSUE THREAD

**Issue by rovargasc** [recognai/rubrix#3069]
Hello, I'm following this tutorial: https://docs.argilla.io/en/latest/guides/llms/examples/curating-feedback-instructiondataset.html

This is how my data looks like:

![image](https://github.com/argilla-io/argilla/assets/69723017/bae5efa0-81ac-47a7-8046-5b1dc682fb93)

Now, when I try to replicate with my data, this error occurs (it's the same when I tried with the example dataset of daatabricks)

─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/lib/python3.10/dist-packages/argilla/client/feedback.py:1142 in                       │
│ feedback_dataset_in_argilla                                                                      │
│                                                                                                  │
│   1139 │   │   │   raise ValueError(f"Workspace must be a `rg.Workspace` instance or a string,   │
│   1140 │   │                                                                                     │
│   1141 │   │   try:                                                                              │
│ ❱ 1142 │   │   │   datasets = datasets_api_v1.list_datasets(client=httpx_client).parsed          │
│   1143 │   │   except Exception as e:                                                            │
│   1144 │   │   │   raise Exception(f"Failed while listing the `FeedbackTask` datasets from Argi  │
│   1145                                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/argilla/client/sdk/v1/datasets/api.py:174 in             │
│ list_datasets                                                                                    │
│                                                                                                  │
│   171 │   response = client.get(url=url)                                                         │
│   172 │                                                                                          │
│   173 │   if response.status_code == 200:                                                        │
│ ❱ 174 │   │   parsed_response = [FeedbackDatasetModel.construct(**dataset) for dataset in resp   │
│   175 │   │   return Response(                                                                   │
│   176 │   │   │   status_code=response.status_code,                                              │
│   177 │   │   │   content=response.content,                                                      │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/httpx/_models.py:756 in json                             │
│                                                                                                  │
│    753 │   │   │   encoding = guess_json_utf(self.content)                                       │
│    754 │   │   │   if encoding is not None:                                                      │
│    755 │   │   │   │   return jsonlib.loads(self.content.decode(encoding), **kwargs)             │
│ ❱  756 │   │   return jsonlib.loads(self.text, **kwargs)                                         │
│    757 │                                                                                         │
│    758 │   @property                                                                             │
│    759 │   def cookies(self) -> "Cookies":                                                       │
│                                                                                                  │
│ /usr/lib/python3.10/json/__init__.py:346 in loads                                                │
│                                                                                                  │
│   343 │   if (cls is None and object_hook is None and                                            │
│   344 │   │   │   parse_int is None and parse_float is None and                                  │
│   345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):              │
│ ❱ 346 │   │   return _default_decoder.decode(s)                                                  │
│   347 │   if cls is None:                                                                        │
│   348 │   │   cls = JSONDecoder                                                                  │
│   349 │   if object_hook is not None:                                                            │
│                                                                                                  │
│ /usr/lib/python3.10/json/decoder.py:337 in decode                                                │
│                                                                                                  │
│   334 │   │   containing a JSON document).                                                       │
│   335 │   │                                                                                      │
│   336 │   │   """                                                                                │
│ ❱ 337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                  │
│   338 │   │   end = _w(s, end).end()                                                             │
│   339 │   │   if end != len(s):                                                                  │
│   340 │   │   │   raise JSONDecodeError("Extra data", s, end)                                    │
│                                                                                                  │
│ /usr/lib/python3.10/json/decoder.py:355 in raw_decode                                            │
│                                                                                                  │
│   352 │   │   try:                                                                               │
│   353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│ ❱ 355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│   357                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <ipython-input-185-9fc6f24dff8a>:23 in <cell line: 16>                                           │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/argilla/client/feedback.py:582 in push_to_argilla        │
│                                                                                                  │
│    579 │   │   │   if isinstance(workspace, str):                                                │
│    580 │   │   │   │   workspace = rg.Workspace.from_name(workspace)                             │
│    581 │   │   │                                                                                 │
│ ❱  582 │   │   │   dataset_exists, _ = feedback_dataset_in_argilla(name=name, workspace=workspa  │
│    583 │   │   │   if dataset_exists:                                                            │
│    584 │   │   │   │   raise RuntimeError(                                                       │
│    585 │   │   │   │   │   f"Dataset with name=`{name}` and workspace=`{workspace.name}`"        │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/argilla/client/feedback.py:1144 in                       │
│ feedback_dataset_in_argilla                                                                      │
│                                                                                                  │
│   1141 │   │   try:                                                                              │
│   1142 │   │   │   datasets = datasets_api_v1.list_datasets(client=httpx_client).parsed          │
│   1143 │   │   except Exception as e:                                                            │
│ ❱ 1144 │   │   │   raise Exception(f"Failed while listing the `FeedbackTask` datasets from Argi  │
│   1145 │   │                                                                                     │
│   1146 │   │   for dataset in datasets:                                                          │
│   1147 │   │   │   if dataset.name == name and dataset.workspace_id == workspace.id:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Exception: Failed while listing the `FeedbackTask` datasets from Argilla with exception: Expecting value: line 1 
column 1 (char 0)

**Comment by dvsrepo** [comment]
Hi @rovargasc , can you share part of the code you're using to load your data, build the records, and push the data?

**Comment by alvarobartt** [comment]
Hi @rovargasc, it seems that the issue comes due to the `workspace` that you're providing to the `push_to_argilla(name, workspace)` function, as either doesn't exist or are providing something that is neither a `str` nor a `Workspace` 😄

**Comment by dvsrepo** [comment]
@alvarobartt is there any way we can provide a more meaningful error message for these cases?

**Comment by rovargasc** [comment]
> Hi @rovargasc, it seems that the issue comes due to the `workspace` that you're providing to the `push_to_argilla(name, workspace)` function, as either doesn't exist or are providing something that is neither a `str` nor a `Workspace` 😄

But I'm with the "admin" workspace and does not work. I don't know if has something to do with this Google Colab warning:

/usr/local/lib/python3.10/dist-packages/argilla/client/client.py:152: UserWarning: You're connecting to Argilla Server 1.6.0 using a different client version (1.8.0).
This may lead to potential compatibility issues during your experience.
To ensure a seamless and optimized connection, we highly recommend aligning your client version with the server version.

**Comment by alvarobartt** [comment]
Hi @rovargasc! I see now, it seems that the Argilla Server that your using is not updated, so make sure you either upgrade Argilla with `pip install argilla --upgrade`, and then re-deploy the server with `argilla server`; or just update the Docker image or HuggingFace Space you're using to be the latest (1.8.0)

Feel free to ping me back if you need any help! 🤗

**Comment by rovargasc** [comment]
> Hi @rovargasc! I see now, it seems that the Argilla Server that your using is not updated, so make sure you either upgrade Argilla with `pip install argilla --upgrade`, and then re-deploy the server with `argilla server`; or just update the Docker image or HuggingFace Space you're using to be the latest (1.8.0)
> 
> Feel free to ping me back if you need any help! 🤗

Ohh okay! So, how can I update the HuggingFace Space? It seems that I have the 1.6.0 version. Thanks in avance.

**Comment by rovargasc** [comment]
Hi. I created a new space on Hugging Face and now it does have the same version as the one Colalb has. Thank you very much.

**Comment by alvarobartt** [comment]
No problem @rovargasc feel free to ping us anytime!
