### ISSUE TITLE
Custom validations in Feedback Datasets

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3073]
**Is your feature request related to a problem? Please describe.**
As an admin, I would like to set up custom validations for a Feedback Dataset, for example: if a user gives a response to question x, then question y should have an answer; labels x & y in `MultiSelect` questions are incompatible; no question is required but at least 1 should have an answer... 

**Describe the solution you'd like**
When creating a `FeedbackDataset` pass a function or set of functions defined by the user as an argument. These will have a custom validation and error messages. These will run whenever the user tried to submit a form and the error message(s) can be displayed as a toast.

**Describe alternatives you've considered**
Enabling/disabling questions following an ITTT workflow is an option, but perhaps this cannot cover all of the possible scenarios e.g. having no required question but needing at least an answer to one of them.

**Additional context**

**Comment by keithCuniah** [comment]
Does that mean that the question `y` should be disable to the user until the question `x` have an answer ?

**Comment by nataliaElv** [comment]
We should think about this carefully, but yes, probably we want to disable/enable questions given certain conditions.

**Comment by nataliaElv** [comment]
#3112

**Comment by davidberenstein1957** [comment]
@nataliaElv I believe #3112 is a different issue right?

**Comment by nataliaElv** [comment]
Yes it's different. I just mentioned it here because it was created after the discussion we had above.
