### ISSUE TITLE
Allow to set up argilla server settings through config file

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3076]
Support for `settings.json` or `settings.yaml` file containing Argilla server configurations.

This can enhance the way users can set up specific settings for backend or database configuration. Also, can help users to know all available settings from a well-documented settings file.

**Comment by davidberenstein1957** [comment]
I agree, and ideally, we should also align this with CLI support.

**Comment by alvarobartt** [comment]
@gabrielmbmb is there any plan to maintain more than one `settings.json` or sort those by name? e.g.

```json
{
    "default": {
        "host": ...,
        "key": ...,
    },
    "project-a": {
        "host": ...,
        "key": ...,
    },
    ...
}
```

And select one of those as `argilla use project-a`? I'm asking in case we want to allow logging in different existing Argilla server instances, while keeping always one with the identifier `default` to be used by default, and changing that based on the `argilla use` value or something similar.
