### ISSUE TITLE
feature: extend `CLI` support for user management

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3079]
**Is your feature request related to a problem? Please describe.**
We want to add extended CLI support for `src/argilla/tasks/users` because it is limited now.

**Describe the solution you'd like**
Our [docs](https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html) mention a lot of operations which are not supported by our CLI. 

**Describe alternatives you've considered**
Using the examples from the docs directly.

**Additional context**
https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html

https://github.com/argilla-io/argilla/issues/2968

**Comment by khishh** [comment]
Hi @davidberenstein1957, can I pick this up? I might need some extra context but am interested in contributing this!

**Comment by davidberenstein1957** [comment]
Hi @khishh, that would be awesome. Do you need help getting started with this?

**Comment by davidberenstein1957** [comment]
@alvarobartt, perhaps it is good to align this with the new user management layer PR.

**Comment by alvarobartt** [comment]
Sure, @khishh feel free to contact me and/or the community via Slack at https://rubrixworkspace.slack.com/archives/C05BCGM277B, and I can follow up with you there to help if needed 😄

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/pull/3169

**Comment by khishh** [comment]
> Sure, @khishh feel free to contact me and/or the community via Slack at https://rubrixworkspace.slack.com/archives/C05BCGM277B, and I can follow up with you there to help if needed 😄

That would be great!! I set the dev environment up locally using docker-compose but I will probably need some context before working on this ticket. I will reach out to you on Slack👋🏼

**Comment by alvarobartt** [comment]
Closed as completed in the following PRs:
* https://github.com/argilla-io/argilla/issues/3590
* https://github.com/argilla-io/argilla/issues/3589
* https://github.com/argilla-io/argilla/issues/3590
