### ISSUE TITLE
feature: extend `CLI` support for FastAPI server

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3080]
**Is your feature request related to a problem? Please describe.**
We want to add extended CLI support for `src/argilla/tasks/server` because it is limited now.

**Describe the solution you'd like**
I would like to mimic https://www.uvicorn.org/deployment/

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/blob/292d2e38b91c44c1e9a49c44fcaa76b60f63c478/src/argilla/tasks/server/__main__.py#L24

`server(*args, **kwargs)` should contain and forward all variables to `uvicorn.run()` 

https://github.com/argilla-io/argilla/blob/292d2e38b91c44c1e9a49c44fcaa76b60f63c478/src/argilla/tasks/server/__main__.py#L25-L30

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 can I pick this up ?

**Comment by davidberenstein1957** [comment]
@vasudevanubrolu to pick up this issue, you just need to for our repo, clone your fork and make changes to the `argilla/tasks/server` file. Let me know if you need additional context.

**Comment by davidberenstein1957** [comment]
@vasudevanubrolu can we re-align w.r.t. this issue too?

**Comment by vasudevanubrolu** [comment]
@davidberenstein1957 sure I want to complete it this week if its ok

**Comment by davidberenstein1957** [comment]
Yes that would be great 💪🏽 Let me know if I can help with anything.

**Comment by davidberenstein1957** [comment]
@vasudevanubrolu You should be able to copy a lot of code from the `main` and/or `run` method in the uvicorn codebase.

https://github.com/encode/uvicorn/blob/fc2130bf1a740acaa502530079bfbd595fa7a94c/uvicorn/main.py#L467-L518

Also, you will need to update. 
https://github.com/argilla-io/argilla/blob/292d2e38b91c44c1e9a49c44fcaa76b60f63c478/src/argilla/tasks/server/__main__.py#L25-L30

And update the docs and reference the [uvicorn options](https://www.uvicorn.org/deployment/).
- docs/_source/getting_started/installation/configurations/server_configuration.md

**Comment by alvarobartt** [comment]
@gabrielmbmb shouldn't this be tracked as part of #3579?

**Comment by davidberenstein1957** [comment]
src/argilla/cli/server/start.py

**Comment by davidberenstein1957** [comment]
https://github.com/encode/uvicorn/blob/fc2130bf1a740acaa502530079bfbd595fa7a94c/uvicorn/main.py#L467-L518
