### ISSUE TITLE
argilla work offline or with custom models?

### ISSUE THREAD

**Issue by mehrdad2000** [recognai/rubrix#3082]
Hi
2 questions about argilla

1-does it work offline totally?
2-can use below model in argilla?

[Falcon](https://huggingface.co/tiiuae/falcon-40b-instruct) Or these models [xlm-roberta-large-fa-qa](https://huggingface.co/SajjadAyoubi/xlm-roberta-large-fa-qa) and [bert-base-fa-qa](https://huggingface.co/SajjadAyoubi/bert-base-fa-qa/) ?

**Comment by davidberenstein1957** [comment]
Hi @mehrdad2000 you do need to export and gather data for these models into a [deployment of Argilla](https://docs.argilla.io/en/latest/getting_started/installation/deployments/deployments.html). Afterwards you can use Argilla to curate the data and fine-tune such models.

**Comment by mehrdad2000** [comment]
@davidberenstein1957 would please explain steps that i need to do?

**Comment by nataliaElv** [comment]
Hi @mehrdad2000 !
This is a tutorial that shows how to see the predictions from a spaCy model in Argilla: https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-tokenclassification-spacy-pretrained.html
And yes, you can use one of the local installations mentioned in the link that @davidberenstein1957 mentioned above.
I hope it helps! If you need extra help, don't hesitate to reach out.

**Comment by mehrdad2000** [comment]
@nataliaElv thanks for answer, would you please give me sample code that use one of those models that i mentioned in issue?

**Comment by davidberenstein1957** [comment]
@mehrdad2000 did you manage to set this up? I think the models you request can be used in combination with our FeedbackDataset. And specific examples can be found [here](https://docs.argilla.io/en/latest/guides/llms/examples/examples.html)
