### ISSUE TITLE
style: update field title style in UI

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3089]
As shown in the screenshot below, the UI presents the same style for both the field name and value, which may be confusing, so IMO we should use a different style to differentiate between the title and the value.

![image](https://github.com/argilla-io/argilla/assets/36760800/e41f695d-0ad7-46ef-99d1-b4cfb8b3eb68)

cc @keithCuniah @leiyre

**Comment by leiyre** [comment]
Hi @alvarobartt, yes, is fixed in #3072
