### ISSUE TITLE
Add preference field for Human Feedback

### ISSUE THREAD

**Issue by tugot17** [recognai/rubrix#3095]
As of today, there are two types of feedback fields: we can have `TextQuestion` and `RatingQuestion`. However, another useful type of field would be a `ChoiceQuestion`, where the user could choose one of n options.

This would be a useful example for specifying the preference: Which outcome A or B do you prefer?

The feature could be implemented as a radio button with the following interface:

```py
class ChoiceQuestion(QuestionSchema):
    settings: Dict[str, Any] = Field({"type": "rating"})
    values: List[Any] = Field(unique_items=True)
```

![image](https://github.com/argilla-io/argilla/assets/27293258/013e49fb-1ffd-4246-b67e-42b9ceb8b70f)

Another fix would be to allow `values` in `RatingQuestion` to be not only ints but also strings.

**Comment by gabrielmbmb** [comment]
Hi @tugot17, thank you for posting here! We've been working on this feature that will be available in next release, as well as the multi choice question 😄

**Comment by keithCuniah** [comment]
Hi @tugot17 . Thanks for the suggestion :) . This next release will be next week.

**Comment by tugot17** [comment]
Looking forward to it 😄

**Comment by keithCuniah** [comment]
Hi @tugot17. The new release is available since today. More info [here](https://www.linkedin.com/posts/daniel-vila-suero-484b6b45_argilla-llms-opensource-activity-7072958482651455488-h3OX?utm_source=share&utm_medium=member_desktop).
Enjoy !
