### ISSUE TITLE
[FEATURE] add stratification methods for `prepare_for_training` methods

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3116]
**Is your feature request related to a problem? Please describe.**
When using the `ArgillaTrainer` I have issues with unbalanced data

**Describe the solution you'd like**
I would like to use a stratification method like the one from sklearn.

**Describe alternatives you've considered**
N.A.

**Additional context**
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html#sklearn.model_selection.train_test_split

**Comment by davidberenstein1957** [comment]
`src/argilla/client/datasets.py`

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 can I pick this up ?

**Comment by davidberenstein1957** [comment]
Yes you can @vasudevanubrolu, can I help you with getting started?

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 that would be helpful, I am setting up argilla locally and woud like to complete the feat(3 at the moment) attached to me by end of this month to pick up more
