### ISSUE TITLE
Duplicated question error message upon creating dataset

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3123]
**Is your feature request related to a problem? Please describe.**
If I create in a dataset a question that already exists in that dataset, I get an error message when I try to push the dataset. I would like to have this validation & error message when I create the dataset locally, not when I push it.

**Comment by alvarobartt** [comment]
Hi @nataliaElv, thanks for reporting! Just to confirm, do you mean something like:

```python
import argilla as rg

rg.FeedbackDataset(
  questions=[
    rg.TextQuestion(name="a"),
    rg.TextQuestion(name="a")
  ],
  fields=...,
  guidelines=...
)
```

**Comment by nataliaElv** [comment]
Yes, exactly!

**Comment by alvarobartt** [comment]
This is a duplicate of https://github.com/argilla-io/argilla/issues/3034, will be tackled together in the same PR 😄
