### ISSUE TITLE
[FEATURE] `github actions` will deprecate node:14 and start using node:16

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3135]
**Is your feature request related to a problem? Please describe.**
We are currently using `node-version: "14"` in ours `.github/package.yml`, which will be deprecated soon.

**Describe the solution you'd like**
Update to 16

**Describe alternatives you've considered**
N.A.

**Additional context**
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by frascuchon** [comment]
This is already updated. See [here](https://github.com/argilla-io/argilla/blob/develop/.github/workflows/build-python-package.yml#L24)
