### ISSUE TITLE
[DOCS] The installation link is wrong in the developer documentation

### ISSUE THREAD

**Issue by hjain5164** [recognai/rubrix#3145]
## Which page or section is this issue related to?
The issue is present here: https://docs.argilla.io/en/latest/community/developer_docs.html
Check the link for the text **Setup and Installation** under the **ElasticSearch or OpenSearch** sub-heading.

**Comment by hjain5164** [comment]
@davidberenstein1957 I think one of the below links shoud work: 
- https://docs.argilla.io/en/latest/getting_started/installation/configurations/elasticsearch.html
- https://docs.argilla.io/en/latest/getting_started/quickstart_installation.html

Can you confirm which one is correct?

**Comment by davidberenstein1957** [comment]
Hi,I think it is supposed to lead here https://docs.argilla.io/en/latest/getting_started/installation/deployments/deployments.htmlPRs are welcome:)Cheers,DavidOn 10 Jun 2023, at 15:09, Harsh Jain ***@***.***> wrote:﻿
@davidberenstein1957 Can you tell which link should be pointed here?

**Comment by hjain5164** [comment]
Okay, I will fix this and create the PR :)

**Comment by hjain5164** [comment]
A couple of more links seems to be broken. Will fix it in my PR

**Comment by davidberenstein1957** [comment]
Great :)
