### ISSUE TITLE
[DOCS] add additional documentation about running the docs locally within contributor docs

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3148]
## Which page or section is this issue related to?
For the developers it might be relevant to know that you can install the doc requirements via these steps:
1. `pip install docs/_source/requirements.txt` 
2. `sphinx-autobuild docs/_source docs/_build/html`
3. visit localhost:8000 
4. make changes until satisified
5. do a PR

**Comment by MedAmine-SUDO** [comment]
Hello @davidberenstein1957, I'll take this issue

**Comment by davidberenstein1957** [comment]
Hi @MedAmine-SUDO that would be great. I will help a bit.

**Comment by davidberenstein1957** [comment]
We have a channel focusing on contributors without our [Slack](https://join.slack.com/t/rubrixworkspace/shared_invite/zt-whigkyjn-a3IUJLD7gDbTZ0rKlvcJ5g). Feel free to join so we can discuss things more easily. @MedAmine-SUDO 

Or you can set up a meeting with me to get started https://calendly.com/argilla-office-hours/30min
