### ISSUE TITLE
[BUG] server and database migration related errors are too undescriptive

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3158]
**Describe the bug**
```
OperationalError: (sqlite3.OperationalError) no such table: users
[SQL: SELECT users.id AS users_id, users.first_name AS users_first_name, users.last_name AS users_last_name, users.username AS users_username, users.role AS users_role, users.api_key AS users_api_key, users.password_hash AS
users_password_hash, users.inserted_at AS users_inserted_at, users.updated_at AS users_updated_at
FROM users
WHERE users.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('argilla', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Expected behavior**
get some ref to the docs or a more  descriptive error
`python -m argilla database migrate` 
`rm -rf`

**Environment:**
N.A. 

**Additional context**
N.A.

**Comment by gabrielmbmb** [comment]
Hey @davidberenstein1957, I'll work on this! I think that we can try to catch this error, and if it happens we can log some message pointing the user to check the docs for applying the migrations.

**Comment by davidberenstein1957** [comment]
@nataliaElv do you know of a good way to keep track of smaller issue like these, besides the major feature thingies?
