### ISSUE TITLE
[FEATURE] add pydantic validation for values used in `QuestionSchema` models

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3183]
**Is your feature request related to a problem? Please describe.**
When working locally. Setting for example `LabelQuestion` labels to `yes`, `no`. Allows for adding other types of labels during the `add_records` functionality. I would expect this to fail.

**Describe the solution you'd like**
Add additional pedantic validators to review this.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by dvsrepo** [comment]
If this behavior is still happening this issue shouldn't be tagged as stale

**Comment by davidberenstein1957** [comment]
Closed in favor of https://github.com/argilla-io/argilla/pull/3938
