### ISSUE TITLE
Review  the `sdk.v1.datasets` data model API

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3191]
The low-level layer is using direct feedback schemas or raw dictionaries to communicate with. We should improve this layer definition to:

1. Improve data serialization/deserialization using pydantic features
2. Decouple low-level schemas and feedback client schemas

**Comment by alvarobartt** [comment]
Closed as completed upon https://github.com/argilla-io/argilla/pull/3784 completion
