### ISSUE TITLE
[FEATURE] add `workspace` and `dataset_name` info to the `FeedbackDataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3193]
**Is your feature request related to a problem? Please describe.**
I can't find from which `workspace` and `dataset_name` I obtained a dataset.

**Describe the solution you'd like**
I would like to do something like `dataset.name` and `dataset.workspace`.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by alvarobartt** [comment]
Hmm we can include that for the `FeedbackDataset`, but note that it will be just applicable to Argilla datasets, not by default. Maybe in the `from_argilla` and `from_huggingface` methods we can set the workspace and username, or org-user/repo, respectively. In which scenarios you load a `FeedbackDataset` from one of those sources and you just lose track of where did those come from? Just curious

**Comment by davidberenstein1957** [comment]
Hi, I think it would be nice to be able to represent the `FeedbackDataset` with their corresponding hf_info or rg_info when doing for example `print(dataset)`.

**Comment by alvarobartt** [comment]
We can for sure add an `info` field to be created either on `push_to_...` or during `from_...` to fulfil it, I guess that can be a workaround for the moment! I can review this with you early next week for the upcoming release 😄

**Comment by alvarobartt** [comment]
Closed as completed as part of https://github.com/argilla-io/argilla/pull/3465
