### ISSUE TITLE
[BUG] Can't make use of api

### ISSUE THREAD

**Issue by amm297** [recognai/rubrix#3201]
**Describe the bug**
I am trying to use the swagger API to understand how this works but I get always `401: Unauthorized `
 
I am following the documentation [here](https://docs.argilla.io/en/latest/getting_started/installation/configurations/server_configuration.html#rest-api-docs) 

I am following the [Docker Quickstart](https://docs.argilla.io/en/latest/getting_started/quickstart_installation.html#🐳-Argilla-Quickstart-with-Docker)

**Comment by davidberenstein1957** [comment]
Hi, @amm297 the docker quickstart has slightly different [config info](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker-quickstart.html).
