### ISSUE TITLE
[DOCS] Add elasticsearch version list support somewhere in docs

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3211]
Argilla installation setup should provide a list of supported elasticsearch/opensearch backend versions.

## Which page or section is this issue related to?
Setup or installation guides

**Comment by davidberenstein1957** [comment]
Hi @frascuchon could you provide me with a list?

**Comment by davidberenstein1957** [comment]
I would add it here https://docs.argilla.io/en/latest/getting_started/installation/configurations/elasticsearch.html

**Comment by frascuchon** [comment]
> Hi @frascuchon could you provide me with a list?

Sorry, I missed this message. We can base the list on our CI pipeline configuration [here](https://github.com/argilla-io/argilla/blob/develop/.github/workflows/package.yml#L38) and [here](https://github.com/argilla-io/argilla/blob/develop/.github/workflows/package.yml#L114)

**Comment by garimau** [comment]
@davidberenstein1957 I can add this :)

**Comment by davidberenstein1957** [comment]
Thanks, that would be amazing:)
