### ISSUE TITLE
[FEATURE] Argilla versions check

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3225]
**Is your feature request related to a problem? Please describe.**
Sometimes when trying to log / push data to an Argilla instance, errors come up that have to do with the fact that the server has a different Argilla version that is different to the local Argilla version. This happens often with Argilla Spaces in huggingface. However, the error messages don't make it obvious that this is the problem.

**Describe the solution you'd like**
I'd like a warning message when using the `rg.init` method that says clearly that the server is not using the same Argilla version and that might lead to issues. The warning message should also mention that the way to solve this is by installing in your local environment the same version as the one in the server.

**Describe alternatives you've considered**
An error message upon using `rg.log` or `FeedbackDataset.push_to_argilla` methods that clearly states that the error has to do with version compatibility issues.

**Additional context**

**Comment by alvarobartt** [comment]
Hi @nataliaElv we already have this 👍🏻  It was included by @frascuchon in 1.9.0 at https://github.com/argilla-io/argilla/pull/2980, and it works as you describe indeed, during `rg.init` a warning is raised if there's a version mismatch between the Python client and the server.

Maybe we could extend it more, but I guess the current works, anyway, feel free to ask @frascuchon as he created the original PR!

**Comment by nataliaElv** [comment]
Does it work retroactively though? Because yesterday there was a long conversation with a user who was having issues because they had 1.2.0 locally and 1.10.0 in the huggingface space and there was no indication whatsoever that this was the problem: https://rubrixworkspace.slack.com/archives/C02G1NSLSRZ/p1687173482414069

**Comment by alvarobartt** [comment]
So there's no way we can add a warning message on previous Argilla client versions, as those packages have already been published, but from now on we're checking the versions and letting users know when there's a mismatch, also in the GitHub issue reporting, users are asked to add the version of Argilla they're using so that, I guess, should cover most of the cases, anyway, this is just available from 1.9.0 onwards 😄

**Comment by nataliaElv** [comment]
Got it, I'm closing this issue then.
