### ISSUE TITLE
[FEATURE] align datasets uses in docs with the ones used in CI/CD (testing)

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3235]
**Is your feature request related to a problem? Please describe.**
It would be great to have one source of truth for all of the datasets floating around our codebase instead of redefining them.

**Describe the solution you'd like**
Create uniform fixtures and directly push them to the hub.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
@nataliaElv could you share some of the preliminary work you have done?

**Comment by nataliaElv** [comment]
Check this space: https://nataliaelv-argilla-demo.hf.space
The argilla default user and password should work.
Just note that the text question in the feedback dataset doesn't work great because the text is in html and it's not pure markdown.
