### ISSUE TITLE
[DOCS] Correct the argilla server python command in developer docs

### ISSUE THREAD

**Issue by manulpatel** [recognai/rubrix#3238]
## Which page or section is this issue related to?
There is typo in command to run Argilla **server** in the [Developer Docs](https://docs.argilla.io/en/latest/community/developer_docs.html#running-argilla-server).

Need to change `python -m argilla`  to `python -m argilla server`

**Comment by davidberenstein1957** [comment]
@manulpatel @davidberenstein1957 I would like to work on this.
