### ISSUE TITLE
[DOCS] Fix URLs in weak supervision with sentence transformers tutorial

### ISSUE THREAD

**Issue by garimau** [recognai/rubrix#3241]
## Which page or section is this issue related to?

In a couple different places (linked below), it references an earlier/previous weak supervision tutorial but the link leads you to the same page. 
- https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-sentencetransformers-weaksupervision.html#:~:text=Weak%20supervision%20with%20Argilla%20tutorial
- https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-sentencetransformers-weaksupervision.html#appendix:-visualize-changes:~:text=as%20in%20the-,previous%20tutorial,-%2C%20but%20on%20the
- https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-sentencetransformers-weaksupervision.html#appendix:-visualize-changes:~:text=model%20from%20the-,previous%20tutorial,-.%20Remember%20we%20achieved

Under the "Detailed Workflow" section, the following hyperlink does not exist at all.
- https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-sentencetransformers-weaksupervision.html#:~:text=weak%20supervision%20guide

References to the Appendix (which is at the bottom of the page) in step 5 do not work because the URLs don't match the capitalization for the header permalinks.

**Comment by davidberenstein1957** [comment]
Great work Garima, I assigned the issues to you:)
