### ISSUE TITLE
Implement __str__ and __repr__ for new User and Workspace client models

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3261]
Python consoles should show user info properly instead of the generic one: 

```python
In [4]: rg.User.me()
Out[4]: <argilla.client.users.User at 0x7fdf9247e130>
```

**Comment by davidberenstein1957** [comment]
might be a good first issue?

**Comment by alvarobartt** [comment]
It is already implemented indeed 😄 See `argilla/client/users.py` and `argilla/client/workspaces.py`

**Comment by frascuchon** [comment]
Sorry @alvarobartt  I didn't see the code base. I was just doing some testing in a Python console, and I realized that user where shown as the generic representation:
```python
In [4]: rg.User.me()
Out[4]: <argilla.client.users.User at 0x7fdf9247e130>
```

We should implement the `__repr__`  to achieve this, I think.
