### ISSUE TITLE
[FEATURE] refactor usage of `import argilla as rg` in `src` and `tests`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3267]
**Is your feature request related to a problem? Please describe.**
Navigation for the package is unclear because we user `import argilla as rg` and `rg.TextClassificationRecord`, but we should use the entire import path like `from argilla.client.models import TextClassificationRecord`

**Describe the solution you'd like**
We should directly import from official modules.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by garimau** [comment]
@davidberenstein1957 I can work on this!
