### ISSUE TITLE
[BUG] - suppression of sorting by prediction score discourage active learning

### ISSUE THREAD

**Issue by fmakereel** [recognai/rubrix#3269]
**Describe the bug**
We are using argilla for annotation (text classification with multi-label) in an "active learning" mode. The UI was really usefull in argilla 1.2.1 as the record were presented with the labels sorted by prediction scores.

As we have around 60 classes, this sorted view was a wonderful accelarator for the manual annotation as the model behind become more and more accurate.

Since this commit : fix: Remove sorting by score in labels (https://github.com/argilla-io/argilla/pull/2623 - https://github.com/argilla-io/argilla/commit/6fb3ce23426e8c7155cea1a233b32e7f08008597), the view always sort the predictions by classes names which makes are anotations very slow to do (Many click and scroll instead of one before as model was accurate...)

We are disappointed that the change did not allowed to choose to keep old sort mode insted of replacing it...

**To Reproduce**
1. Open dataset with already calculated predictions
2. Check that sorting is only done by natural classes names and do not use at all confidence for simple annotation when model is accurate
3. See error

**Expected behavior**
We would like to be able to choose a mode in the UI to allow a sorting by prediction confidence for annotation, or to restore the default sorting in previous argilla versions.

**Screenshots**
![Capture_ecran_argilla](https://github.com/argilla-io/argilla/assets/13587799/712ac612-b169-43e0-b951-f101e4f7cab6)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: (cf docker image)
 - Browser [e.g. chrome, safari]: chrome
 - Argilla Version [e.g. 1.0.0]:1.11.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.5.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]: v.1.11.0

**Additional context**

**Comment by nataliaElv** [comment]
Hi @fmakereel , I'm sorry to hear that this change broke your workflow. We'll try to find a solution to this. In the meantime, are you ok with using an earlier version?

**Comment by fmakereel** [comment]
Thank you @nataliaElv for your reply.

We would be very happy if it could be integrated in a future release. For now, we will try to stay on the last version as you added very cool features like the "semantic search" with the vectors...

We hoped to be able to patch in local the UI to restore the sort on the Annotation area, but sadly i did not succeeded to build the frontend (Some erros with the dependencies installation)...

**Comment by nataliaElv** [comment]
@fmakereel According to the changelog, the change in the sorting was included in v1.5.1, so you should be able to use v1.4.1 that has the old sorting and semantic search 😄 I hope that helps while we work on solving this issue.

**Comment by nataliaElv** [comment]
Keeping it open, because I think this is still something to consider.

**Comment by schoibs** [comment]
Hey I am of the same opinion too that the sorting-by-prediction-score feature would be very useful in implementing active learning. 😄 

Any update on the progress of this bug fix?

**Comment by nataliaElv** [comment]
Ordering labels by score is now available in Feedback datasets (from Argilla 1.28.0), which are becoming the main dataset type in Argilla 2.0. Have you tried this feature @fmakereel @schoibs? 
 
 Let us know what you think. I'll be closing this issue as we won't be implementing it in legacy datasets, but feel free to reopen it or open a new one if you have any issues with the current implementation 😸
