### ISSUE TITLE
[FEATURE] add different pull request templates in `.github/PULL_REQUEST_TEMPLATE/pull_request_template.md`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3284]
**Is your feature request related to a problem? Please describe.**
Some pull requests require less checklist thingies.

**Describe the solution you'd like**
`.github/PULL_REQUEST_TEMPLATE/pull_request_template.md`

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by garimau** [comment]
@davidberenstein1957 i can tackle this :)
