### ISSUE TITLE
[BUG] Pagination errors in dev environment

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3286]
**Describe the bug**
All bugs are in dev environment:
1. empty status queues show the form instead of an empty page with the "You have no {pending/submitted/discarded} records" message. 
2. it allows to paginate indefinitely.
3. the last record in the queue gets duplicated.

**To Reproduce**
Steps to reproduce bugs 1 & 2:
1. Go to any Feedback Task dataset in the dev environment.
3. Check in the progress sidebar whether it has submitted or discarded records.
4. If one of those has 0 records, choose that queue in the status selector.
5. If you then click next, you will see that it can move pages indefinitely.

To reproduce no.3 & 2:
1. In the same dataset, go to pending and submit a response for a record.
2. Go to the "submitted" queue.
3. Click next multiple times.

**Expected behavior**
Check Feedback Task datasets in pre environment for the expected behavior.

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by damianpumar** [comment]
Fixed here #3177 

Thanks @nataliaElv
