### ISSUE TITLE
[BUG] newline span annotations shift underline and labels

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3290]
**Describe the bug**
![image](https://github.com/argilla-io/argilla/assets/25269220/82e12cd4-0051-4f39-b7d7-7a2108b8a4d7)

**To Reproduce**
1. Go to tokenclassificaiton data
2. Annotate a span over multiple lines
3. See error

**Expected behavior**
I wouldn't expect it to happen

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.11
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.11

**Additional context**
N.A.

**Comment by AmanSal1** [comment]
@davidberenstein1957 Can I give it a try to solve this bug ?

**Comment by davidberenstein1957** [comment]
Yes @AmanSal1, that would be amazing! Perhaps @damianpumar can give some guidance where needed:)

**Comment by AmanSal1** [comment]
@davidberenstein1957Thank you! I will begin working on it for now.

**Comment by AmanSal1** [comment]
@damianpumar Can you please give some basic steps to compile the project locally on my computer (Windows 10) . I am facing some issues.

**Comment by davidberenstein1957** [comment]
I notified Damian, but perhaps this will help. https://docs.argilla.io/en/latest/community/developer_docs.html#building-frontend-static-files

**Comment by AmanSal1** [comment]
@davidberenstein1957 I want to know that will I have to install elastic search also(through pip)
and as I am on a windows pc so the front end cli command will not work .

**Comment by damianpumar** [comment]
Hello @AmanSal1, thank you for your interest in Argilla.
I will provide you with some step-by-step instructions on how to run the Argilla frontend.

- First, make sure you have [Docker](https://www.docker.com/products/docker-desktop/) installed. If you don't have it installed, please download and install it.
- Run the Argilla backend using Docker with the following command:
    - `docker run -d --name quickstart -p 6900:6900 argilla/argilla-quickstart:latest`
- Navigate to the frontend folder from your project's root directory.
- Execute the command `npm run dev`
- To log in, use the username `admin` and the password `12345678` (if you need more information, please check [here](https://docs.argilla.io/en/latest/getting_started/quickstart_installation.html)).
- I'm not sure about this issue, you could start from [here](https://github.com/argilla-io/argilla/blob/bdd53147c6e4168b0264b80d28841feb6ff4f7f8/frontend/components/token-classifier/results/RecordTokenClassification.vue)

Please let me know if you need any further assistance!

**Comment by AmanSal1** [comment]
@damianpumar So, first I cloned the repository and then changed the directory to it. After that, I ran the docker command you provided. Following that, I tried running 'npm run dev' in the frontend folder, but encountered an error stating, 'nuxt' is not recognized as an internal or external command.' To resolve this issue, I attempted to run 'npm install nuxt,' but it seems there is a conflict between the dependencies. Can you help me out?

![1](https://github.com/argilla-io/argilla/assets/121633121/15b124d3-1e6b-403c-a986-155239f65610)

**Comment by damianpumar** [comment]
Which version of node and npm did you use?
I'm using 18.16 and the installation step works!

**Comment by AmanSal1** [comment]
![3](https://github.com/argilla-io/argilla/assets/121633121/978e91d2-f3d0-4834-9137-74e2c710d010)

@damianpumar You can look into it I have attached the screenshot

**Comment by damianpumar** [comment]
Hello @AmanSal1 
Yes, you're right!

Please, change these versions. 
```
"vuex": "^3.1.3",
"@vuex-orm/core": "^0.36.4",
```

I'll fix it ASAP in the next release.

<img width="1186" alt="Screenshot 2023-06-30 at 23 01 06" src="https://github.com/argilla-io/argilla/assets/7398909/a655ad9a-7e72-49b2-86ca-6353b7eb9cb0">

**Comment by AmanSal1** [comment]
@damianpumar Yup it works now!

**Comment by AmanSal1** [comment]
@damianpumar I am not able to figure out how to annotate a span that extends over multiple lines. Do we need to add annotation labels using code, or can we do it directly from the site's UI?

**Comment by damianpumar** [comment]
Hello @AmanSal1, I don't know how to reproduce it, may be @davidberenstein1957 we can help us.

**Comment by davidberenstein1957** [comment]
Hi @AmanSal1, I just found out I was using a client deployment which was using an older version of Argilla. In the newer versions I cannot reproduce this either, so it was already fixed. @damianpumar do you know of any other small issues @AmanSal1 might be able to tackle?

**Comment by AmanSal1** [comment]
@davidberenstein1957 Yup you can assign me an issue .

**Comment by davidberenstein1957** [comment]
@AmanSal1 Could you contact me on our Slack or via Calendly, then we can discuss something.
https://calendly.com/argilla-office-hours/30min

**Comment by AmanSal1** [comment]
@davidberenstein1957 I have messaged you at slack
