### ISSUE TITLE
[FEATURE] View annotation guidelines into a draggable dialog

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3322]
**Is your feature request related to a problem? Please describe.**
I want to open the annotation guidelines directly in the annotation view instead of opening another tab with the dataset settings.

**Describe the solution you'd like**
Add the annotation guidelines to the sidebar so I can open/close while annotating.

**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
@nataliaElv can this be combined with another roadmap issue.

**Comment by nataliaElv** [comment]
I'm not sure this is something that we're planning to do. Any comments @Amelie-V ?

**Comment by Amelie-V** [comment]
![Image](https://github.com/argilla-io/argilla/assets/84135211/ad60e9e9-41b3-4b9d-ab0d-2de90081d056)
![Image](https://github.com/argilla-io/argilla/assets/84135211/de92317a-ed95-41a5-9d58-835e7cc3f9ba)
