### ISSUE TITLE
[FEATURE] Upgrade to `pydantic>=2.0.0`

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3369]
Pydantic V2 has been released recently. It brings with a lot of changes in its core, mainly that it has been rewritten to Rust which makes it much much faster (between 5x - 50x faster).

We're using `pydantic.BaseModel` pretty much everywhere... The `FeedbackRecord` is a `pydantic.BaseModel`. One `FeedbackDataset` can have more than 1000 records easily, so I think we would be able to see some performance improvement once we update to `pydantic>=2.0`

Thing to take into consideration:

1. Many methods names of the `BaseModel` class have been changed. There is a v1 to v2 migration guide https://docs.pydantic.dev/latest/migration/ and also a tool https://github.com/pydantic/bump-pydantic to help with it.
2. If we update to `pydantic>=2.0`, then we need to update the API to use `fastapi>=0.100.0` which is the release that comes with `pydantic>=2.0` support.

**Comment by todowa** [comment]
Any updates on this? Or potentially just making the current setup using pydantic v1 compatible with pydantic v2, as for instance done in langchain? Thanks!
https://github.com/langchain-ai/langchain/tree/master/libs/langchain/langchain/pydantic_v1

**Comment by kdutia** [comment]
I'm also keen on seeing support for this – my team have recently upgraded our data access layer to use `pydantic>=2.0` which now unfortunately means we can't use `argilla` and our data access layer in the same environment

**Comment by dbuades** [comment]
I agree that this would be very useful if you have the bandwith to tackle it.
With the scheduled release of Ray 2.9.0 next week, Argilla will be the last library in our tech stack that does not support `pydantic >= 2.0.0`

**Comment by THOR300** [comment]
I'm also very keen on upgrading this to pydantic v2, currently we have upgraded our SDK to `pydantic v2` and Argilla is the only dependency that relies on `pydantic v1` and is this holding back our data science team from using the latest version of our sdk.

**Comment by besaleli** [comment]
Bumping on this – would love to add Argilla to our stack but this is currently blocking us.

**Comment by bergr7** [comment]
Same here. Any estimate of when you are planning to ship the upgrade?

**Comment by minaamshahid** [comment]
Bumping this - this is a major blocker for us (and preventing us from using Argilla)

**Comment by davidberenstein1957** [comment]
@bergr7 @minaamshahid @besaleli @THOR300 @dbuades @kdutia @todowa and @dbuades, this should be covered in the next release==1.22.0 thanks to @gabrielmbmb 💪🏽

**Comment by THOR300** [comment]
> @bergr7 @minaamshahid @besaleli @THOR300 @dbuades @kdutia @todowa and @dbuades, this should be covered in the next release==1.22.0 thanks to @gabrielmbmb 💪🏽

@davidberenstein1957 this is great news! 

@gabrielmbmb I don't know if you've seen but there's a transformation tool for updating pydantic version which I found quite useful when updating our stack. 

Please see this [here](https://docs.pydantic.dev/latest/migration/#code-transformation-tool). 

More than happy to help out with this, just drop me an email at mark@climatepolicyradar.org.

**Comment by frascuchon** [comment]
Ref: #4466

**Comment by JonnyTran** [comment]
Hi devs! I'm wondering if there's any plan to upgrade to pydantic v2 for `argilla_server`. I noticed many unit tests and CI/CD steps in `argilla_v1` required pip installing both `argilla_server` and `argilla`, which would cause an error since `argilla_server` still have the `pydantic >= 1.10.7,< 2.0` dependency pin.
