### ISSUE TITLE
Filters area improvement [:: Next Release]

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#337]
- Don't show active filters in main view
- Active grey bt BG on hover
- Active shadow on the searchbox on hover
- Manage "score" filter to show it when its actived
- Review modal style

**Comment by dvsrepo** [comment]
- [x] Remove short separator line
- [x] Cancel bt = remove filters selected
- [x] Adapt new style to Sort by filter

**Comment by dvsrepo** [comment]
<img width="396" alt="Captura de pantalla 2021-10-13 a las 11 55 53" src="https://user-images.githubusercontent.com/1107111/137117224-71a49c93-d2e9-403f-af56-8f111a40398f.png">
