### ISSUE TITLE
[FEATURE] add `CarperAI/trlx` `promp-completion` support to `ArgillaTrainer`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3378]
**Is your feature request related to a problem? Please describe.**
I cannot do RewardModelling with the `TextField` or `TextQuestion`.

**Describe the solution you'd like**
We should add support for https://github.com/CarperAI/trlx. 
This support should include 
- a `.for_supervised_fine_tuning()` class method for the `TrainingTaskMapping`. 
- a method to support `TextField` and `TextQuestion` function for [Promp-Completsion](https://github.com/CarperAI/trlx#using-a-prompt-completion-dataset)
- support for the `prepare_for_training()` method of the `FeedbackDataset`
- support for the `FrameWork(Enum)` via `trlx`
- alignment with our [docs](https://docs.argilla.io/en/latest/guides/llms/practical_guides/fine_tune.html)

**Describe alternatives you've considered**
consider taking `lvwerra/trl` into account too. https://github.com/argilla-io/argilla/issues/3377

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
Lower usage and value than TRL, so we'll disregarding this for now.
