### ISSUE TITLE
[FEATURE] add `lvwerra/trl` `SFT` support to `ArgillaTrainer`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3379]
**Is your feature request related to a problem? Please describe.**
I cannot do RewardModelling with the `TextField` and `TextQuestion`.

**Describe the solution you'd like**
We should add support for https://github.com/lvwerra/trl. 
This support should include 
- a `.for_supervised_fine_tuning()` class method for the `TrainingTaskMapping`. 
- a method to support `TextField` and `TextQuestion` function for [SFTTrainer](https://github.com/lvwerra/trl#sfttrainer)
- support for the `prepare_for_training()` method of the `FeedbackDataset`
- support for the `FrameWork(Enum)` via `trl`
- alignment with our [docs](https://docs.argilla.io/en/latest/guides/llms/practical_guides/fine_tune.html)

**Describe alternatives you've considered**
consider taking `CarperAI/trlx` into account too. https://github.com/argilla-io/argilla/issues/3378

**Additional context**
N.A.

**Comment by tomaarsen** [comment]
I'd love some clarification on the workflow of how users prepare the Feedback Dataset for training. I found the following snippet, but it extremely doesn't work:
https://github.com/argilla-io/argilla/blob/2cbcafbf4ba5bc11655ab712ac430d079ec872b2/src/argilla/client/feedback/training/schemas.py#L136-L142

* The `TrainingTaskMapping` import doesn't work.
* `argilla_id` isn't valid, it should be `name`, 
* `TrainingTaskMapping.for_text_classification` returns a task mapping, not `training_data`,
* `dataset.prepare_training_data` does not exist, only `dataset.prepare_for_training` does, which does accept a `task_mapping`.

So, after some experimentation I've come to this:
```python
dataset = rg.FeedbackDataset.from_argilla(name="imdb-single-label-all-records")
task_mapping = TrainingTaskMapping.for_text_classification(
    text=dataset.fields[0],
    label=dataset.questions[0],
)
data = dataset.prepare_for_training(framework="setfit", task_mapping=task_mapping)
```
Which fetches the full dataset *twice* and then crashes like so:
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ [sic]/demo_3379.py:12 in <module>                                                      │
│                                                                                                  │
│    9 │   text=dataset.fields[0],                                                                 │
│   10 │   label=dataset.questions[0],                                                             │
│   11 )                                                                                           │
│ ❱ 12 data = dataset.prepare_for_training(framework="setfit", task_mapping=task_mapping)          │
│   13 # data = task_mapping._prepare_for_training_with_transformers(dataset, train_size=0.5, s    │
│   14                                                                                             │
│   15 breakpoint()                                                                                │
│                                                                                                  │
│ [sic]\argilla\client\feedback\dataset.py:812 in prepare_for_training               │
│                                                                                                  │
│   809 │   │   else:                                                                              │
│   810 │   │   │   raise ValueError(f"Training data {type(task_mapping)} is not supported yet")   │
│   811 │   │                                                                                      │
│ ❱ 812 │   │   data = task_mapping._format_data(self.records)                                     │
│   813 │   │   if framework in [                                                                  │
│   814 │   │   │   Framework.TRANSFORMERS,                                                        │
│   815 │   │   │   Framework.SETFIT,                                                              │
│                                                                                                  │
│ [sic]\argilla\client\feedback\training\schemas.py:61 in _format_data               │
│                                                                                                  │
│    58 │   │   │   │   │   explode_columns.add(pydantic_field_name)                               │
│    59 │   │   │   formatted_data.append(data)                                                    │
│    60 │   │   df = pd.DataFrame(formatted_data)                                                  │
│ ❱  61 │   │   df = df.explode(list(explode_columns))                                             │
│    62 │   │   df = df.drop_duplicates()                                                          │
│    63 │   │   df = df.dropna(how="any")                                                          │
│    64 │   │   return df.to_dict(orient="records")                                                │
│                                                                                                  │
│ [sic]\site-packages\pandas\core\frame.py:9023 in explode  │
│                                                                                                  │
│    9020 │   │   │   is_scalar(c) or isinstance(c, tuple) for c in column                         │
│    9021 │   │   ):                                                                               │
│    9022 │   │   │   if not column:                                                               │
│ ❱  9023 │   │   │   │   raise ValueError("column must be nonempty")                              │
│    9024 │   │   │   if len(column) > len(set(column)):                                           │
│    9025 │   │   │   │   raise ValueError("column must be unique")                                │
│    9026 │   │   │   columns = column                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: column must be nonempty
```

**Comment by davidberenstein1957** [comment]
Hi @tomaarsen,

I believe this should shed some light https://docs.argilla.io/en/latest/guides/llms/practical_guides/fine_tune_others.html.

> The TrainingTaskMapping import doesn't work.

This was handled in [a PR](https://github.com/argilla-io/argilla/pull/3346) and patch that Paco was supposed to release last week. Not sure what happened there.

> argilla_id isn't valid, it should be name

I think I copy pasted this from an older API version.

> TrainingTaskMapping.for_text_classification returns a task mapping, not training_data,

That is the intended behaviour `FeedbackDataset.prepare_for_training` takes a task mapping to prepare the training data given a strategy and task.

> dataset.prepare_training_data does not exist, only dataset.prepare_for_training does, which does accept a task_mapping.

I think I missed this during renaming.

**Comment by davidberenstein1957** [comment]
w.r.t. explode columns, I should have added another check to see if the columns were required.

@tomaarsen this might also be a useful resource https://docs.argilla.io/en/latest/guides/llms/practical_guides/collect_responses.html#unifying-disagreements

Could you review the Docstring as a fix along with this PR? and maybe align with @frascuchon regarding the import error patch?

And the idea is that we add multiple `TrainingTaskMapping.for_task_mapping()` methods for tasks like RewardModelling or TokenClassification etc. to allow for versatile training methods based on any mapping we provide based on fields and questions

**Comment by davidberenstein1957** [comment]
@tomaarsen this might also be a useful resource https://docs.argilla.io/en/latest/guides/llms/practical_guides/collect_responses.html#unifying-disagreements

**Comment by davidberenstein1957** [comment]
Could you review the Docstring as a fix along with this PR? and maybe align with @frascuchon regarding the import error patch?

**Comment by tomaarsen** [comment]
I've done some additional brainstorming on how to best go about this. In the end, we want either:
1. A dataset with a `text` column that has already been preprocessed following some template.
2. A dataset with numerous columns that can later be preprocessed using some template.

The first one can be solved in at least two ways:

1a. Let the user provide a string `template`, which is filled in based on variables in the template string, e.g.:
```python
"""
### Title: {title}
### Tags: {tags}
### Question:
{question}

### Answer:
{answer}
"""
```
However, e.g. `title` can both be a `fields` or `questions` schema item, so we would need something like `{fields.title}` instead. Additionally, this has a crucial problem that you may want different templates based on certain circumstances, e.g. if one of the texts is empty.

1b. An alternative is to let users provide a function instead. This function is then provided with all texts from a record. In practice, users will likely want to be able to filter training samples, for example on annotation rankings. In that case, we must also provide those question outputs (that must be unified using some approach). So, users would also have to specify the unification strategy.

2. The second approach could be done by simply returning a Dataset with all data. However, users would also have to specify the unification strategies in some way.

I'm unsure what API would work best for users. We can also keep it "simple" for now and only use the text fields and questions. In that case, perhaps option 1a or 1b is best.

cc: @alvarobartt perhaps you have an opinion on this.

- Tom Aarsen
