### ISSUE TITLE
Remove records from a Feedback Dataset using Python SDK

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3388]
As an owner/admin, I want to be able to remove records from a Feedback Dataset using a method in the Python SDK.

## Acceptance criteria
- [x] Given a list of records, use a method in the Python SDK to delete them permanently from the dataset.
- [x] If an annotator tries to use this method, they should get an error message saying that they don't have permission to perform that action.

**Comment by articoder1** [comment]
Is there also a way to log/add records into an existing dataset?

I'm trying to use lg.log with the Feedback dataset and getting:
`InputValueError: Unknown record type <class 'argilla.client.feedback.schemas.FeedbackRecord'>. Available values are
(<class 'argilla.client.models.TextClassificationRecord'>, <class 
'argilla.client.models.TokenClassificationRecord'>, <class 'argilla.client.models.Text2TextRecord'>, <class 
'argilla.client.models.TextGenerationRecord'>)`

**Comment by nataliaElv** [comment]
> Is there also a way to log/add records into an existing dataset?
> 
> I'm trying to use lg.log with the Feedback dataset and getting: `InputValueError: Unknown record type <class 'argilla.client.feedback.schemas.FeedbackRecord'>. Available values are (<class 'argilla.client.models.TextClassificationRecord'>, <class 'argilla.client.models.TokenClassificationRecord'>, <class 'argilla.client.models.Text2TextRecord'>, <class 'argilla.client.models.TextGenerationRecord'>)`

Hi @articoder1 ! Sorry for the late response. Here's how you can add records in an existing Feedback dataset:
```python
import argilla as rg

# connect to your instance
rg.init(api_url="<ARGILLA_API_URL>", api_key="<ARGILLA_API_KEY>")

# load an existing dataset
dataset = rg.FeedbackDataset.from_argilla(name="my_dataset", workspace="my_workspace")

# list of records you want to add
new_records = ...

# add records to the dataset and push
dataset.add_records(new_records)
dataset.push_to_argilla()
```

**Comment by nataliaElv** [comment]
Closed by https://github.com/argilla-io/argilla/pull/3526
