### ISSUE TITLE
[FEATURE] Manually change the width of record card & feedback form

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3395]
**Is your feature request related to a problem? Please describe.**
Sometimes records are more crowded than the feedback form and in other datasets it might be the other way. 

**Describe the solution you'd like**
I'd like to see on hover a dragging bar between the record card and the feedback form so that I can adjust manually the width of these two elements.

**Comment by davidberenstein1957** [comment]
@damianpumar @nataliaElv I noticed this got lost so I added it to the sprint again.

**Comment by Amelie-V** [comment]
I close this issue which will be tackle with other layout improvements we are progressively integrating
