### ISSUE TITLE
[INTEGRATION] JupyterLab integration due to upstream dependency constraint on Rich

### ISSUE THREAD

**Issue by RobFirth** [recognai/rubrix#3407]
**Describe the bug**
Tracebacks in jupyter notebooks in project virtual environment with `argilla` are broken as a result of upstream bug in old version of `rich`. Version constraint on `rich = "<=13.0.1"`, this behaviour was fixed in `rich==`[v13.3.1](https://github.com/Textualize/rich/releases/tag/v13.3.1).

```
import argilla as rg

def f(x):
    return x/0

f(42)
```
returns:

```python
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tmp/ipykernel_1885/2875885747.py:1 in <module>                                                  │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_1885/2875885747.py'                         │
│                                                                                                  │
│ /tmp/ipykernel_1885/3374322498.py:2 in f                                                         │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_1885/3374322498.py'                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ZeroDivisionError: division by zero
```

**Expected behaviour**
the traceback gets displayed correctly.

**Environment:**
 - Argilla Version [e.g. 1.12.1]: 1.12.1
 - rich: 13.0.1

**Additional context**

This bug is described in the following issues:

* https://github.com/Textualize/rich/issues/2271
* https://github.com/Textualize/rich/pull/2754
* https://github.com/jupyterlab/jupyterlab/issues/13759
* https://github.com/ipython/ipykernel/issues/1075

This doesn't affect my Argilla workflow other than making it a total pain to debug issues in notebooks! Hopefully a version bump isn't too onerous - it would be a massive QOL improvement.

**suggested fix**
Version bump rich e.g. `rich<=13.3.1`

**Comment by tomaarsen** [comment]
Hello!

When we integrated `rich` in #2350, I specifically set `rich = "<=13.0.1"` because `rich==13.1.0` was failing for me with [this error](https://github.com/Textualize/rich/issues/2800#issuecomment-1428764064). At that time, 13.1.0 was the most recent version.

Now I've installed the most recent version (13.4.2), and the aforementioned issue does not occur anymore. Because of this, I think we can lift the `"<=13.0.1"` restriction without causing crashes for users.

I'll make a PR for this.

- Tom Aarsen

**Comment by RobFirth** [comment]
> Hello!
> 
> When we integrated `rich` in #2350, I specifically set `rich = "<=13.0.1"` because `rich==13.1.0` was failing for me with [this error](https://github.com/Textualize/rich/issues/2800#issuecomment-1428764064). At that time, 13.1.0 was the most recent version.
> 
> Now I've installed the most recent version (13.4.2), and the aforementioned issue does not occur anymore. Because of this, I think we can lift the `"<=13.0.1"` restriction without causing crashes for users.
> 
> I'll make a PR for this.
> 
> * Tom Aarsen

Thanks for this @tomaarsen - I was hoping that this was the reason for pinning the version and it wouldn't impact on anything elsewhere. Cheers for the speed 🚀
