### ISSUE TITLE
Add `delete` and `list` methods for `FeedbackDataset` in Argilla via the Python client

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3413]
Since we can now delete workspaces, we need to tackle two main goals to improve this feature when datasets are linked to the workspace:

- [ ] Support for removing a feedback dataset from the Python client
```python
...
ds = FeedbackDataset.from_argilla(...)
ds.delete()
# or just (since the from_argilla will try to fetch all records locally
FeedbackDataset.delete(dataset_id)
```

- [ ] Fetch the infor about which datasets are linked to the workspace 

_As a first approach, we could return the needed info as part of the delete error response. The name for "old" datasets, and the id for feedback ones_

### Listing and deleting old task datasets
```python
import argilla as rg

ws = rg.Workspace.from_name("ws")

# listing old datasets for a workspace
datasets = rg.list_datasets(workspace=ws)
# or for all workspaces
datasets = rg.list_datasets()

# deleting old datasets
for dataset in datasets:
    rg.delete(name=dataset.name, workspace=datase.workspace)
```

### Listing and deleting new feedback datasets

```python
from argilla.feedback import FeedbackDataset

datasets = FeedbackDataset.list(workspace=ws)
# or all workspaces
datasets = FeedbackDataset.list()
for dataset in datasets:
    dataset.delete()
```

**Comment by alvarobartt** [comment]
Now users can call `delete()` over an existing `FeedbackDataset` in Argilla, as well as deleting records from Argilla via `delete_records` or in-place deletion of records via `record.delete()`.

But listing `FeedbackDataset` datasets is still pending, we just need to decide whether a `list()` method is the best approach to tackle it or not.

**Comment by alvarobartt** [comment]
Re-opened, as the `FeedbackDataset.list()` method is still missing
