### ISSUE TITLE
[DOCS] `FeedbackDataset.from_huggingface` code snippet doesn't work

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#3417]
The following snippet doesn't work (anymore):
```python
from argilla.feedback import FeedbackDataset

dataset = FeedbackDataset.from_huggingface(
    repo_id="argilla/stackoverflow_feedback_demo"
)
```

Even after #3415 which solves a critical TypeError for this, we'll now get:
```python
ValidationError: 4 validation errors for DatasetConfig
questions -> 0
  Discriminator 'type' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type)
questions -> 1
  Discriminator 'type' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type)
questions -> 2
  Discriminator 'type' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type)
questions -> 3
  Discriminator 'type' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=type)
```
We should try to replace `"argilla/stackoverflow_feedback_demo"` with an example that uses the more recent `argilla.yaml`. Alternatively, we should update https://huggingface.co/datasets/argilla/stackoverflow_feedback_demo.

## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/guides/llms/practical_guides/fine_tune_others.html#define-a-task-mapping

**Comment by alvarobartt** [comment]
I've fixed it at #3416 👍🏻

**Comment by tomaarsen** [comment]
I haven't ran it locally, but I think it'll still fail with the ValidationErrors.

**Comment by tomaarsen** [comment]
Nevermind, it works now!
