### ISSUE TITLE
[DOCS] Typos in  "Train a Model" Docs

### ISSUE THREAD

**Issue by peppinob-ol** [recognai/rubrix#3429]
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/guides/train_a_model.html#the-argillatrainer

missing "e" in Datas**e**tFor-
- [ ] change **DatastForTextClassification** to  **DatasetForTextClassification**
- [ ] change **DatastForTokenClassification** to  **DatasetForTokenClassification**
- [ ] change **DatastForTokenClassification** to  **DatasetForTokenClassification**

Traindirectly>Example Workflow
Missing "from argilla.training import ArgillaTrainer" in the code snippet
- [ ] add **from argilla.training import ArgillaTrainer**  in the code snippet

**Comment by nataliaElv** [comment]
This issue was solved in PR #3443
