### ISSUE TITLE
Allow to running test with other than the default DB

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3437]
The current configuration for tests does not allow running tests with a different database configuration, but it makes sense to run tests in other than the default `sqlite` database.

Refs https://github.com/argilla-io/argilla/pull/3438

**Comment by gabrielmbmb** [comment]
Yes, I agree. I think that running the unit tests in `tests/server` would be enough to check that everything works OK with the specific database.

**Comment by gabrielmbmb** [comment]
Resolved by #3487.
