### ISSUE TITLE
[BUG] rg.log fails to add FeedbackRecord to the dataset

### ISSUE THREAD

**Issue by articoder1** [recognai/rubrix#3441]
**Describe the bug**
An rg.log() call to add FeedbackRecord fails with:

```
InputValueError: Unknown record type <class 'argilla.client.feedback.schemas.FeedbackRecord'>. Available values are
(<class 'argilla.client.models.TextClassificationRecord'>, <class 
'argilla.client.models.TokenClassificationRecord'>, <class 'argilla.client.models.Text2TextRecord'>, <class 
'argilla.client.models.TextGenerationRecord'>
```

**To Reproduce**
1. Create and push new Feedback dataset
2. Assign it to annotators and annotate a few records there 
3. Attempt to add a new FeedbackRecord with rg.log

**Expected behavior**
There should be a way to add or log new records to a partially annotated FeedbackRecord dataset, as the annotation progresses. 

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Ubuntu 22.04
 - Argilla Version [e.g. 1.0.0]: 1.12.0

**Comment by dvsrepo** [comment]
Hi!

To add or log new records to a Feedback dataset you should use dataset.add_records and then push to argilla, like you did after dataset creation. We're aware the rg log incompatibility is confusing so thanks for reporting

**Comment by articoder1** [comment]
I've tried doing .push_to_argilla, but that one was also failing, because I was calling it with the dataset name in the arguments.  I'll try it with no arguments.

**Comment by articoder1** [comment]
I'd guess, it's a bug against documentation then.  As there are no samples there that show how to do add FeedbackRecord to existing dataset.  And both .log() and .push_to_argilla(dataset_name) that are present in the documentation don't allow to add records.

**Comment by dvsrepo** [comment]
@alvarobartt might be able to provide a code snippet example with the flow for adding records to an existing dataset

**Comment by alvarobartt** [comment]
Hi @articoder1, indeed the solution to it should be something along the lines:

```python
import argilla as rg

ds = rg.FeedbackDataset.from_argilla(name=..., workspace=...)  # Existing `FeedbackDataset` in Argilla
ds.add_records(records=[rg.FeedbackRecord(...)])
ds.push_to_argilla()  # No need to provide the name and workspace as the `argilla_id` is retrieved when calling `from_argilla`
```

So yes, as @dvsrepo mentioned, `rg.log` is the former approach for the rest of the datasets, but the `FeedbackDataset` comes with a brand new interface, so everything's done using the class instance.

Anyway, if you feel any part of the documentation is unclear, feel free to ping @nataliaElv with your thoughts so that we can tackle that! Thanks 🤗

**Comment by davidberenstein1957** [comment]
@articoder1 Have you been able to resolve this?
