### ISSUE TITLE
[DOCS] Deprecated "chunk_size" argument in Semantic Search docs

### ISSUE THREAD

**Issue by peppinob-ol** [recognai/rubrix#3447]
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/guides/label_records_with_semanticsearch.html

In the following code snippet "chunk_size" is deprecated:

```

import argilla as rg

rg_ds = rg.DatasetForTextClassification.from_datasets(dataset, annotation="label")

rg.log(
    name="banking77-openai",
    records=rg_ds,
    chunk_size=50,
)

```
According to  [latest python client docs](https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.log):
`chunk_size (Optional[int]) – DEPRECATED! Use batch_size instead.`

**Comment by davidberenstein1957** [comment]
hi @peppinob-ol, thanks for pointing to this. I will have a look.
