### ISSUE TITLE
[FEATURE] Sentence similarity for Group of sentences

### ISSUE THREAD

**Issue by peppinob-ol** [recognai/rubrix#3460]
**Is your feature request related to a problem? Please describe.**
I want to bootstrap text classification labeling by finding sentences that are similar to the others already labeled, not just similar to one sentence

**Describe the solution you'd like**
I would like a "find similar" button next to labels in "progress" side bar. This will enable what you have in prodigy by the "teach" recipe. 

**Describe alternatives you've considered**
Clicking on "find similar" button on every sentence with the label of interest. It takes more time and is suboptimal.

**Additional context**
"find similar" button can be placed also in other places. A nice feature (more flexible) would be also to use the "OO" (intersection) button in the top bar to find similar sentences to the ones already filtered with other criterias.

**Comment by davidberenstein1957** [comment]
@peppinob-ol I think this could be achieved via the API by creating an average vector and using that to search. 
@nataliaElv might we add this as part of the vector search integration to the Feedback Task?

**Comment by davidberenstein1957** [comment]
@Amelie-V
