### ISSUE TITLE
[INTEGRATION] Huggingface: optional questions not shown properly in dataset card

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3464]
**Describe the bug**
In the same dataset card, in the `Data Structure` section all questions appear as `Required=True`, whereas in the `Data Fields` section some questions are marked as being optional. See the snapshots below:
<img width="893" alt="Captura de pantalla 2023-07-27 a las 12 24 34" src="https://github.com/argilla-io/argilla/assets/126158523/16cc4280-b515-4f27-b27a-c4f9816cd020">
<img width="939" alt="Captura de pantalla 2023-07-27 a las 12 24 28" src="https://github.com/argilla-io/argilla/assets/126158523/9e4f9ea2-9d00-4d19-9e80-bcc34b067eb7">

Also it looks like in the `Data Structure` table labels aren't shown for the `Label` and `MultiLabel` questions.
This can be seen in [this dataset](https://huggingface.co/datasets/argilla/oasst_response_quality).

**Comment by alvarobartt** [comment]
Hi @nataliaElv, thanks for reporting!

Which Argilla version did you use to generate that card? Because if I recall properly I guess this was fixed at https://github.com/argilla-io/argilla/pull/3366 (see screenshots attached)

**Comment by nataliaElv** [comment]
Not sure which version when the dataset was created, but I updated it using our latest version (1.13.0) to change the `content_class` question from `LabelQuestion` to `MultiLabelQuestion` and at least the issue with the Values/Labels seems to persist or maybe it wasn't updated properly.

**Comment by alvarobartt** [comment]
Could you share a code-snippet so that I can reproduce the issue and explore further? Thanks 👍🏻

**Comment by nataliaElv** [comment]
Closed by #3499
