### ISSUE TITLE
[CI] Skip CI trigger when PR is created as a draft

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3466]
## Description

To avoid triggering the CI on draft PRs, we should be including something along the lines of `if: github.event.pull_request.draft == false`, this way we would avoid triggering the CI when not needed/desired. As in most of the cases creating a draft PR implies that the PR is still WIP, and the CI can be tackled later once the PR is published.

**Comment by alvarobartt** [comment]
cc @gabrielmbmb @frascuchon is there any counterpart on doing this? If not I'll proceed

**Comment by frascuchon** [comment]
Nope. You can go ahead with this @alvarobartt
