### ISSUE TITLE
[BUG] `ModuleNotFoundError` and `ImportError` when importing `argilla.feedback.*`

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3468]
**Describe the bug**
When trying to use import something from `argilla.feedback` module a `ModuleNotFoundError` is raised because `fastapi` is not installed and an `ImportError` because `pyyaml` is not installed either.

**Stacktrace and Code to create the bug**
```bash
pip install argilla==1.13.2
```

```python
from argilla.feedback import SuggestionSchema
```

**Expected behavior**
I can import stuff from `argilla.feedback` module without getting a `ModuleNotFoundError` and without installing `fastapi` and `PyYAML` dependencies which should be only needed for the server and extra integrations.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.13.2
 - ElasticSearch Version [e.g. 7.10.2]: 8.5.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]: Not relevant

**Additional context**
The bug was introduced in https://github.com/argilla-io/argilla/pull/3336, when the telemetry used in the server (it imports `fastapi`) was added to the Argilla Trainer.

**Comment by alvarobartt** [comment]
Additionally, we should refactor `argilla.feedback` to either be replaced with the whole content of `argilla.client.feedback` or to be removed, as it's confusing to have both and one just being a replica with the imports from the other.
