### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LordWaif** [recognai/rubrix#3476]
**Describe the bug**
I execute a configure_dataset_settings for each workspace where each workspace belong a one unique user. This form each dataset/workspace  supports the labels configurations. The records is shipped separately for each user. However in listener, only is recognized the shipped for the last workspace configured, i believe this could happend because the client.active_client() support just one workspace at same time. The listener is not oriented for work with many workspace where each one work separately from the other.

**Stacktrace and Code to create the bug**
```
rg.client.active_client().set_workspace(workspace)
rg.configure_dataset_settings(name=dataset.name, settings=settings, workspace=workspace)
rg.log(records=records, name=dataset.name, workspace=workspace)

@listener(
        dataset=dataset.name,
        query="status:Validated AND metadata.batch_id:{batch_id}",
        condition=lambda search: search.total == dataset.num_samples,
        execution_interval_in_seconds=3,
        batch_id=0,
        isInitial=True,
        qtd=dataset.num_samples,
)
def active_learning_loop(records, ctx):
```
```bash
Logging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
5 records logged to http://127.0.0.1:6900/datasets/victor/papers
Logging... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
5 records logged to http://127.0.0.1:6900/datasets/auditor/papers
```

**Expected behavior**
Recognize data from the auditor and victor workspaces and treat each separately. The Communication works only for the last workspace (auditor).

**Environment:**
 - Argilla Version [e.g. 1.12.1]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla-quickstart:v1.12.1]:

**Additional context**

**Comment by frascuchon** [comment]
Hi @LordWaif and thanks for reaching out.

Exactly, the current client connection works based on a preset session workspace. We plan to work on this to support contextualized workspace support.

**Comment by LordWaif** [comment]
thank you for the explanation
