### ISSUE TITLE
Update datasets for quickstart image

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3492]
Add 2 new datasets in the quickstart docker images:

- https://huggingface.co/datasets/argilla/oasst_response_quality
- https://huggingface.co/datasets/argilla/oasst_response_comparison

Note: this may affect to the demo setup

**Comment by frascuchon** [comment]
@alvarobartt can you tackle this? Just adding these 2 new datasets in [this script](https://github.com/argilla-io/argilla/blob/develop/docker/scripts/load_data.py)

**Comment by alvarobartt** [comment]
Sure I'll check this later today!
