### ISSUE TITLE
Allow create users from the Python client with linked workspaces

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3493]
Changes introduced in https://github.com/argilla-io/argilla/pull/3462 allow to simplify the user creation workflow using the Python client. 

Instead of creating a new user and then assigning one or several workspaces, we could easily create a new user in one single step. If the provided workspaces don't exist, they will be automatically created.

```python
ws = Workspace.create(...)
ws2=Workspace.from_name(...)


user = User.create(username=...,password=...,workspaces=[ws,ws2,"other_workspace_from_string"])

```

**Comment by alvarobartt** [comment]
Hmm should we create the workspaces by default or just when the user provides a flag e.g. `create_workspace=True`?

**Comment by nataliaElv** [comment]
Perhaps creating the workspace automatically could be problematic, for example if the user makes a typo. I think it's nice to assign workspaces directly using the name of the workspace as a string, but I would still send an error message if one of the workspaces doesn't exist  prompting the user to create it if that's their real intention.

**Comment by nataliaElv** [comment]
To me this issue seems solved and closed by what @gabrielmbmb did here: https://github.com/argilla-io/argilla/pull/3462
Please, confirm @frascuchon @alvarobartt

**Comment by alvarobartt** [comment]
Yes it's solved, but only the `workspace` assignment, the open topic is still the automatic creation of workspaces if not created already. IMO I'm happy with the current approach and we shouldn't automatically create anything, and if that's a priority or requested by many users we could add an arg as mentioned before e.g. `create_workspaces=True`, but IMO we can just skip that and raise an exception if a workspace is not created.
