### ISSUE TITLE
[BUG] Workspace not found in `rg.configure_dataset`

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3505]
**Describe the bug**
When using the method `rg.configure_dataset(name="my_dataset", workspace="my_workspace", settings=settings)` the following error occurs:

```
BadRequestApiError: Argilla server returned an error with http status: 400
Error details: [{'code': 'argilla.api.errors::MissingInputParamError', 'params': {'message': 'A workspace must be 
provided'}}] 
````

**Stacktrace and Code to create the bug**
```python
rg.init(
    api_url="API_URL",
    api_key="API_KEY"
)
settings = rg.TextClassificationSettings(label_schema = ["a", "b", "c"])
rg.configure_dataset(name="my_dataset", workspace="my_workspace", settings= settings)
```

**Expected behavior**
The dataset is found correctly and the new configuration is pushed.

This can be solved by setting a workspace beforehand using `rg.set_workspace("my_workspace")`, but it would be good to be able to skip that step and set the workspace as an attribute of `configure_dataset` directly.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.13.3
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by alvarobartt** [comment]
Hi @nataliaElv thanks for reporting this, it was also reported by Alejandro Boix from ODEC in the Slack Community channel (don't have his GitHub handle so I cannot tag him)

**Comment by nataliaElv** [comment]
Yes, exactly! I created this issue after the thread he started 😄

**Comment by alvarobartt** [comment]
Oops thought that was reported by two different users as Alejandro also contacted me privately 🤣

**Comment by frascuchon** [comment]
We need to provide the workspace also here https://github.com/argilla-io/argilla/blob/develop/src/argilla/client/apis/datasets.py#L167
