### ISSUE TITLE
[FEATURES] Add `list_datasets` and allow deleting records from UI

### ISSUE THREAD

**Issue by ivsanro1** [recognai/rubrix#3521]
**Is your feature request related to a problem? Please describe.**

It's not exactly a problem, but more like a couple things I feel that are missing

**Describe the solution you'd like**

There are some things I that I think are missing from the UI and the python client:
- Be able to `list_datasets` using the py client. I tried `rg.datasets.api.list_datasets_api_v1(client.http_client.httpx)` but it gives empty result despite having one dataset.
- Permanently delete records from the UI -> Unless I missed it in the UI, this one would be great. For me, "discard" is for different purposes.

**Describe alternatives you've considered**

To delete records I had to copy/paste record uuids which is far from optimal

**Additional context**

N/A

**Comment by alvarobartt** [comment]
Hi @ivsanro1 thanks for reporting those things!

Regarding the `list_datasets` I also agree that it would be nice to have something similar to `FeedbackDataset.list()` to list all the `FeedbackDataset`s in Argilla. Anyway, the endpoint should work fine, can you let me know which user role are you using i.e. which user's credentials are you using on `rg.init`.

Regarding the record deletion from the UI maybe @nataliaElv or @leiyre can give you more details, but record deletion from the Python client is coming in the next release later this week!

Thanks again!

**Comment by ivsanro1** [comment]
Hi @alvarobartt , thanks for the quick response.

> can you let me know which user role are you using i.e. which user's credentials are you using on rg.init.

To to list the datasets, I'm trying to use a user which is defined (and was migrated on argilla server startup) in `config.yaml` like this:

```yaml
- username: user1
  api_key: api_key_1
  hashed_password: $2y..............................Ufq

- username: user2
  api_key: api_key_2
  hashed_password: $2y..............................1rK
```

And then I'm doing:

```python
rg.init(api_url="http://localhost:6900/", api_key=api_key_1, workspace="workspace_name")
from argilla.client import api
client = api.active_client()
rg.datasets.api.list_datasets_api_v1(client.http_client.httpx)
```

However, and despite I can see the dataset in that workspace if I connect via browser to `http://localhost:6900/datasets`, the output is:

```
Response(status_code=200, content=b'{"items":[]}', headers=Headers({'date': 'Tue, 08 Aug 2023 12:24:34 GMT', 'server': 'uvicorn', 'content-length': '12', 'content-type': 'application/json'}), parsed=[])
```


> but record deletion from the Python client is coming in the next release later this week!

Nice! Is this from the UI? For Python client I understand argilla lib, for which AFAIU we can already delete records by doing:

```python
rg.delete_records(name=DATASET, ids=list_record_ids_to_remove)
```

**Comment by alvarobartt** [comment]
Hi @ivsanro1, I was referring to the record deletion from the `FeedbackDataset` class. Find more information about it at #3526.

Regarding your issue with the `FeedbackDataset` listing, I would suggest you to check whether the user has access to the workspace where the dataset is placed first. You can do so via `rg.Workspace.list()` to list all the available workspaces for the active user, and check whether the workspace where the dataset is placed is there.

Regarding the record deletion from the UI I guess either @nataliaElv and/or @leiyre maybe be able to answer you better.

**Comment by nataliaElv** [comment]
Hi @ivsanro1! Deleting records from the UI is not something we've considered yet, as we consider the "Annotation mode" (which is the only we cover for now) is not the right place for this functionality. However, as @alvarobartt already mentioned, we're working to make this possible from the Python client. 
Could you describe a bit more what the use case is for deleting records from the UI and how would be the ideal workflow look like?

**Comment by ivsanro1** [comment]
> You can do so via rg.Workspace.list() to list all the available workspaces for the active user, and check whether the workspace where the dataset is placed is there.

Thanks for the suggestion @alvarobartt . I've checked this and the Workspace appears. Is it possible that `rg.datasets.api.list_datasets_api_v1` does not show the dataset because it is deprecated? Because I see that recent dataset developments are made in `argilla/client/datasets.py`.

Do you have a working example of how to list datasets using the python client?

> However, as @alvarobartt already mentioned, we're working to make this possible from the Python client.

Hi @nataliaElv . I thought that deleting records from the python client was already possible by calling `rg.delete_records`. In fact that's how I'm deleting them, but my current workflow is far from optimal, because I have to search the records I want to delete in the UI, I have to copy and paste the record ids into a notebook and then I have to call `rg.delete_records`.

> Could you describe a bit more what the use case is for deleting records from the UI and how would be the ideal workflow look like?

Sure. Actually, another use case that I forgot mentioning is creating records from the UI, but I understand this one might require much more work.

In general, my use case is creating a dataset to fine-tune a LLM. For that, I already have a dataset in csv format, which I upload using the python client, but then I want to inspect the dataset in the UI and remove records that I consider invalid, either because they don't pass a data quality test or because they're outliers/unrelated.

In the same scenario, and since every data point in an instruction dataset is just plain text, I'd also like to be able to create a record through the UI. This means I'd only write an instruction and an answer myself in the UI, and I'd add this record it to the dataset.

As how would I expect them to appear in the UI, I think it's quite subjective but I think this would be pretty self-explanatory:

![image](https://github.com/argilla-io/argilla/assets/30293331/403d3ca5-6e00-4d88-9aa1-b224ddb7dfe9)

The "delete" button workflow would be very straightforward. Just a confirmation message and upon deletion it reloads the page to show that it has been deleted.

The "add record" would bring the user to a new page. The page would contain empty text fields for the text inputs (the same as the API of `rg.Text2TextRecord` takes, i.e. `text`, `annotation`, etc.). For the metadata it's tricky because the dataset might already contain metadata fields with categorical values (e.g. `split` that can be "train", "test"), that could be used to guide the user to enter the value. Here I'd suggest a combo box or a dropdown with search, but any could work

**Comment by nataliaElv** [comment]
Hi @ivsanro1 ! You're totally right. For some reason, I assumed you were using a `FeedbackDataset` and that's why I said that we were working on adding the possibility of deleting records. In the case of a `Text2TextDataset` you can always use a query to make this deleting step a bit easier as explained here: https://docs.argilla.io/en/latest/reference/python/python_client.html#argilla.delete_records 
If there is nothing that makes those records easily searchable/filterable, what you could do is, as you explore your records in the UI, change the answer to some recognisable tag that you could use in your filter. For example, you could write `[DELETE]` as the answer and then use the filter `rg.delete_records(query="annotated_as:[DELETE]")`. I understand this is still not optimal for you, but I hope this makes your workflow somehow simpler.

**Comment by ivsanro1** [comment]
Thanks for the recommendation @nataliaElv , I'll use this when I want to delete records, although a more direct way from the UI would always be more user-friendly.

As a side note, I'm also missing the ability of modifying in the UI the `text` field from the `Text2TextRecord`, as currently only the `annotation` can be modified.

Do you think there will be mid-term plans to add more functionality to the UI to modify the datasets (add/delete/change text)? Even if it's a mode that is not "Annotation mode", but "Admin mode" or "Edit Records mode"?

**Comment by nataliaElv** [comment]
Hi @ivsanro1 . Could you explain the use case for editing records? To me it sounds like it would be problematic to modify the dataset that one is annotating in such a way, but I want to understand the specific needs of your use case and why it involves modifying and eliminating records. Would you be up to having a conversation with me about this? If so, please book a slot using this link: https://calendar.app.google/zaxvdzsGNGfPDf2R8 Thanks!

**Comment by alvarobartt** [comment]
Hi @ivsanro1, from Argilla 1.15.0 you can already call `FeedbackDataset.list()` and from Argilla 1.14.0 you can also call `rg.list_datasets` to list the rest of the available datasets i.e. `TextClassificationDataset`, `TokenClassificationDataset`, and `Text2TextDataset` :hugs:

**Comment by ivsanro1** [comment]
Thanks @alvarobartt , I just tried it and works perfectly!

Do you think I should close this feature request and open other(s) with the other requests?

**Comment by alvarobartt** [comment]
> Thanks @alvarobartt , I just tried it and works perfectly!
> 
> Do you think I should close this feature request and open other(s) with the other requests?

Sure, that would be great! Also thanks for the feedback, much appreciated 👍🏻
