### ISSUE TITLE
[BUG] Highlighting of terms in a query

### ISSUE THREAD

**Issue by pierre-ollivier** [recognai/rubrix#3525]
**Describe the bug**
Argilla does not highlight terms followed by a dot, but it does with comas or brackets (see screenshots)

**To Reproduce**
1. Go to an Argilla dataset
2. Make a text query

**Expected behavior**
In the screenshots below, both 'Montana Department of Justice' instances should be highlighted.

**Screenshots**
![image](https://github.com/argilla-io/argilla/assets/99399264/f5e06da3-14e8-4291-8324-127e53467519)
![image](https://github.com/argilla-io/argilla/assets/99399264/6a0c35bf-3522-4725-b86a-e8d524a987bd)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: iOS
 - Browser: Chrome 114.0.5735.198
 - Argilla Version : 1.12.1

**Comment by gabrielmbmb** [comment]
Thanks @pierre-ollivier for reporting this issue! I'll have a look.
