### ISSUE TITLE
[DOCS] Add `FeedbackDataset` references in Quickstart Workflow

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#3532]
## Which page or section is this issue related to?

The [Quickstart Workflow page](https://docs.argilla.io/en/latest/getting_started/quickstart_workflow.html) doesn't have any references to Feedback datasets. We should update it to give relevance to this type of dataset.

**Comment by alvarobartt** [comment]
Closing this as completed as part of #3714 where https://docs.argilla.io/en/latest/getting_started/quickstart_workflow_feedback.html was included, thank you both @davidberenstein1957 and @nataliaElv 🤗
