### ISSUE TITLE
[FEATURE] allow `require_version` and `requires_version` decorator to also accept lists of requirements   

### ISSUE THREAD

**Issue by plaguss** [recognai/rubrix#3554]
**Is your feature request related to a problem? Please describe.**
There are functions in the codebase that explicitly require a version to proceed, like for example when instantiating some [trainers](https://github.com/argilla-io/argilla/blob/5aa7096141abc94b19dadf0ed811a4a3fce1f1b3/src/argilla/training/setfit.py#L30-L33).
Updating `require_version` and `requires_version` could help improving readability as suggested in [this link](https://github.com/argilla-io/argilla/pull/3527#discussion_r1288090507).

**Describe the solution you'd like**
Instead of calling a number of times the function (or the decorator):

```python
require_version("torch")
require_version("datasets")
require_version("transformers")
require_version("setfit>=0.6")
```

A list could be used for such cases:

```python
require_version(["torch", "datasets", "transformers", "setfit>=0.6"])
```

**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
Thanks @plaguss !
