### ISSUE TITLE
[FEATURE] Refactor `RatingQuestionStrategy` and `RankingQuestionStrategy` to inherit from a common mixin

### ISSUE THREAD

**Issue by plaguss** [recognai/rubrix#3556]
**Is your feature request related to a problem? Please describe.**
Both `RatingQuestionStrategy` and `RankingQuestionStrategy` have a common `unify_responses` method which can be extracted into a mixin class.

**Describe the solution you'd like**
Move the method `unify_responses` to a separate mixin class `RatingQuestionStrategyMixin`.

**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
Thanks @plaguss 💪🏽
