### ISSUE TITLE
[BUG] Overlapped entities when tagging 

### ISSUE THREAD

**Issue by dmartincc** [recognai/rubrix#3564]
**Stacktrace and Code to create the bug**
```python
ValueError: [E1010] Unable to set entity information for token 1 which is included in more
than one span in entities, blocked, missing or outside.
```

**Expected behavior**
Spacy doesn't allow overlapping entities. Argilla should check for and remove them before start training.

**Environment:**
 - Argilla (1.13.2)
 - argilla==1.10.0

**Comment by davidberenstein1957** [comment]
@dmartincc I have also thought about this before. Do you feel that something like this makes sense? 
https://spacy.io/api/top-level#util.filter_spans
