### ISSUE TITLE
[FEATURE] Add logout command `python -m argilla logout`

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3585]
Add a new `logout` command that will remove the stored credentials generated by the login function introduced in #3582. This command will use `ArgillaCredentials.remove` method to remove the credentials and "logout" from the configured Argilla server. 

```shell
python -m argilla logout
```

**Comment by eshwarhs** [comment]
@gabrielmbmb Can I take this up?

**Comment by gabrielmbmb** [comment]
@eshwarhs sure! If you have any question don't hesitate to ask
