### ISSUE TITLE
[FEATURE] Allow changing `text` field in the UI for Text2Text records Dataset, at least for `Admin`/`Owner`

### ISSUE THREAD

**Issue by ivsanro1** [recognai/rubrix#3606]
**Is your feature request related to a problem? Please describe.**
Some of our data points need refinement in the input (text field). For example, we have a translation task (text2text records and dataset are perfect for our use case, we don't need FeedBack dataset for this task for now), but we cannot edit the text field in the UI.

**Describe the solution you'd like**
The ability to edit in the UI the text for each record, even if it's only for `Admin`/`Owner` role. For now it's only possible to edit the ground truth.

**Describe alternatives you've considered**
I've considered creating a small app in streamlit that uses the python API to achieve this, as with the python API is 100% possible to load a record and update the text only, but having it in Argilla UI would be a plus.

I've also considered putting the entire record in the `annotation` field, just because it's editable in the app, and parse it in python, but obviously this is not optimal given that I'd have to leave the `text` practically empty, and it would be a hacky way of using the app

**Additional context**

**Comment by davidberenstein1957** [comment]
@nataliaElv this is useful feedback and might be relevant to take into account.

**Comment by nataliaElv** [comment]
thanks @davidberenstein1957. @ivsanro1 and I already had a discussion about this and the notes are in Notion :)

**Comment by davidberenstein1957** [comment]
Perfect, I'll skim through them quickly.
