### ISSUE TITLE
[BUG] Update response endpoint returning 422 when status sent is `draft`

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3612]
**Describe the bug**
@damianpumar detected a bug in which the `PUT /api/v1/responses/{response_id}` endpoint returns a `422` HTTP status code when trying to update a response and the sent status is `draft`.

This bug is being caused because we don't have a `DraftResponseStatusCode` class:

https://github.com/argilla-io/argilla/blob/aeb5b8e9d1dbb52429bc3d1bec508c44659e7e9b/src/argilla/server/schemas/v1/responses.py#L50-L60

**Expected behavior**
The endpoint return a `200` HTTP status code when called and the sent status is `draft`.

**Comment by eshwarhs** [comment]
@gabrielmbmb Can I work on this?
