### ISSUE TITLE
[BUG] `push_to_argilla` from existing `FeedbackDataset.from_argilla` does not work

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3627]
**Describe the bug**
When I have an existing 

**Stacktrace and Code to create the bug**
```python
import argilla as rg

dataset = rg.FeedbackDataset.from_argilla(name=f"old", workspace="argilla")
# potentially do something
dataset.push_to_argilla(name=f"new", workspace="argilla")
```
new-dataset is not created

**Expected behavior**
I would expect a new dataset/copy to be created or I expect to see a warning this is not possible.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.14.1
 - ElasticSearch Version [e.g. 7.10.2]: 
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.14

**Additional context**
Might be related to the changes in the `RemoteFeedbackDataset` too.

**Comment by alvarobartt** [comment]
Hi @davidberenstein1957 indeed `push_to_argilla` from a `RemoteFeedbackDataset` raises a `DeprecationWarning`, please check https://github.com/argilla-io/argilla/blob/843f819862ec84a29ee2c4d5e4a315152e42bdd5/src/argilla/client/feedback/dataset/remote.py#L361

**Comment by davidberenstein1957** [comment]
Yes, but then the `push_to_argilla` for older version still doesn't work correct? And, will we add an option to copy datasets?

**Comment by alvarobartt** [comment]
So `push_to_argilla` works in any version before 1.14.0, the thing is that from 1.14.0 onwards we're assuming that the `FeedbackDataset` in Argilla is a `RemoteFeedbackDataset` and we don't store the records locally, since those are fetched from Argilla in real time instead. So on, to make sure that users don't try to "clone" the `FeedbackDataset` in Argilla into Argilla under a different dataset name and/or workspace, we included a `DeprecationWarning` in `push_to_argilla` to reflect that.

**Comment by frascuchon** [comment]
https://github.com/argilla-io/argilla/blob/v1.14.0/CHANGELOG.md#deprecated

As far as I understand, your code should add a `ds.pull()` before calling the `push_to_argilla`, right @alvarobartt?

```python
import argilla as rg

dataset = rg.FeedbackDataset.from_argilla(name=f"old", workspace="argilla")
# potentially do something
dataset.pull().push_to_argilla(name=f"new", workspace="argilla")
```

In future releases, a `copy` or `clone` method will be provided to do this kind of work. @davidberenstein1957 Do you have identified any issue related to the `copy` functionality for `FeedbackDataset`s? Maybe we can just close this issue in favor of this new feature.

**Comment by alvarobartt** [comment]
Yes, exactly! Otherwise the `push_to_argilla` won't work, as you will first need to pull the data from Argilla before cloning it. Anyway, the `push_to_argilla` for the `FeedbackDataset` datasets in Argilla will be removed completely in 1.15.0, as stated in the `DeprecationWarning`s over the code.

**Comment by davidberenstein1957** [comment]
Yes, we can close this issue and open a feature request. @frascuchon I also had the comment about being able to work with a local version of the data, because I don't always want all dataset changes to be represented in the actual database.

**Comment by frascuchon** [comment]
Do you mean combining a dataset export + load from local @davidberenstein1957 ?

**Comment by davidberenstein1957** [comment]
@frascuchon 
I think having an option not to use the `RemoteFeedbackDataset`.

```python
dataset = rg.FeedbackDataset.from_argilla(name=f"old", workspace="argilla", sync_with_remote=False) # defaults to True
```

**Comment by frascuchon** [comment]
If I understand well, the `sync_with_remote=False` will fetch all the dataset info once and let you work with a local copy, right? Something equivalent to:

```python
dataset = rg.FeedbackDataset.from_argilla(name="name", workspace="argilla")
local = dataset.pull()

# continue working with local
for record in local.records:
   ...
```

**Comment by davidberenstein1957** [comment]
@frascuchon 

Yes that is what I meant but I did not get the memo about `pull` creating a local copy, but based on the current docs and the naming of the methods it is not very clear to me that:
- all changes are synced to the "golden" data in the remote Argilla instance
- there is an option to work with a local copy via `pull`
- we have an option to resync local and remote data via `push_push_to_argilla`

**Comment by davidberenstein1957** [comment]
I am just afraid that someone might by accident alter or even worse delete records from their deployment without being aware it is happening because normally you always work with local copies in Python. For me, syncing with the Argilla instance is a cool feature but more an optional one for people who know what they are doing or make it more explicit that it is happening.

**Comment by davidberenstein1957** [comment]
closed in favor of https://github.com/argilla-io/argilla/issues/3654
