### ISSUE TITLE
[next-release] Use thousand separator big numbers

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#363]
We should review which numbers larger than 1000 we have in the UI and add a decorator to show thousand/million separators.

For example:

- total number of records
- total annotations
- annotations by label

See:

<img width="1599" alt="Screenshot 2021-09-17 at 15 05 14" src="https://user-images.githubusercontent.com/1107111/133787476-0a3d67d1-7563-493a-a4c6-7f132fa1fe55.png">

**Comment by dcfidalgo** [comment]
Maybe slightly related: In our python client we provide a `score` with the prediction (which is normally in the range from 0 - 1), but in the web app we show percentages. Maybe worth aligning it, especially if at some point we want to allow scores outside of the 0 - 1 range.
