### ISSUE TITLE
[FEATURE] ArgillaTrainer - allow passing `device` parameter

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#3632]
**Is your feature request related to a problem? Please describe.**
Related: https://github.com/argilla-io/argilla/pull/3467#discussion_r1305230854

**Describe the solution you'd like**
I want users to be able to provide a device so the model can always be put on the right device, no matter whether that's cpu, gpu, mps, etc.:
```python
trainer = ArgillaTrainer(
    dataset=...,
    device="mps",
    ...
)
```

Currently we support `gpu_id` exclusively for spaCy. I propose that we replace `gpu_id` with `device`, which takes either an int, a string or a torch.device. Initially, we'll have:
```
if not device and gpu_id:
    warnings.warn(...)
    device = gpu_id
self.device = device
```
and spaCy will use the `self.device` as the `gpu_id`. That way we'll have backwards compatibility there.

**Describe alternatives you've considered**
* Use `update_config` to change the device and/or move the device with `trainer._trainer.model.to("...")` or something.
* Make sure torch is compiled correctly so that cuda or mps is available.

**Additional context**
Should be implemented after #3467

---

- Tom Aarsen

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 can I pick this up ?

**Comment by davidberenstein1957** [comment]
Files can be found in two places:
- src/argilla/training (old)
- src/argilla/client/feedback/training (new)

The `ArgillaTrainer.__init__` should allow for a `device` param and be handled as `self.device` as @tomaarsen suggested above.
- src/argilla/training/base.py
- src/argilla/client/feedback/training/base.py

The framework classes defined by `Argilla*Trainer.__init__()` should use this `device` and set for further usage.
- src/argilla/client/feedback/training/frameworks/spacy.py
- src/argilla/client/feedback/training/frameworks/span_marker.py
- src/argilla/client/feedback/training/frameworks/transformers.py
- src/argilla/client/feedback/training/frameworks/trl.py 
- src/argilla/training/peft.py
- src/argilla/training/spacy.py
- src/argilla/training/span_marker.py
- src/argilla/training/transformers.py

Also, you will need to define a test for the current implementation and outdated `gpu_id` param.
- tests/integration/training/test_base.py
