### ISSUE TITLE
[FEATURE] add `filter_by` method to the `ArgillaTrainer` 

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3646]
**Is your feature request related to a problem? Please describe.**
From this PR, it is possible to filter the a dataset.

**Describe the solution you'd like**
I want to use this to filter on submitted records by default and allow for changing this via a filter_by arg during trainer definition and the `train` method.

**Describe alternatives you've considered**
N.A.

**Additional context**
#3610

**Comment by alvarobartt** [comment]
FYI if you are planning to include this, it should be something similar to:

```python
trainer = ArgillaTrainer(..., filter_by={"response_status": ["draft", "submitted", "discarded", "missing"])
```

**Comment by davidberenstein1957** [comment]
Did you want to include it to the PR mentioned above or a separate one?

**Comment by davidberenstein1957** [comment]
@tomaarsen might be interested?

**Comment by alvarobartt** [comment]
Hi @eshwarhs feel free to comment here, so that we can assigning this to you, as you kindly asked at [Argilla - Slack Community](https://rubrixworkspace.slack.com/archives/C05BCGM277B/p1693524416228969?thread_ts=1693492161.044759&cid=C05BCGM277B)

**Comment by eshwarhs** [comment]
@davidberenstein1957 @alvarobartt I'd like to give it a try

**Comment by alvarobartt** [comment]
> @davidberenstein1957 @alvarobartt I'd like to give it a try

Assigned to you already! Feel free to start with it 👍🏻

**Comment by davidberenstein1957** [comment]
@plaguss are you interested in having a shot at this too?
