### ISSUE TITLE
[BUG] Unexpected scrolling in docs.argilla.io sidebar

### ISSUE THREAD

**Issue by tomaarsen** [recognai/rubrix#3653]
**Describe the bug**
If I hover to the right-hand side of the "Contents" column in the [API Reference of our documentation](https://docs.argilla.io/en/latest/reference/python/python_client.html#python-client), then I expect for the "Contents" column to scroll. However, it does not. It only scrolls if I hover directly over the "Contents" column.

**To Reproduce**
1. Go to https://docs.argilla.io/en/latest/reference/python/python_client.html#python-client
2. Hover your mouse on the right side of the "Contents" column, somewhere above the "Free Office Hours" button
3. Notice that it scrolls the main page and not the contents column.

**Expected behavior**
I expect it to scroll the Contents column with all methods/functions/classes. Perhaps the div for the toc-tree contents section can simply be extended all the way to the right side of the screen?

**Screenshots**
![image](https://github.com/argilla-io/argilla/assets/37621491/397cd62a-5b81-4ffc-bf1f-78aa32a49648)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: N/A
 - ElasticSearch Version [e.g. 7.10.2]: N/A
 - Docker Image (optional) [e.g. argilla:v1.0.0]: N/A

**Additional context**
-

cc: @leiyre 

---

- Tom Aarsen

**Comment by davidberenstein1957** [comment]
@leiyre was this fixed already?
