### ISSUE TITLE
[FEATURE] Add workspace add user command `python -m argilla workspaces add-user`

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3680]
Add a new command that will allow to add an existing user to an existing workspace. To do so, create a new Typer command in `src/argilla/tasks/workspaces` and use `argilla.client.workspaces.Workspace` class and its method `add_user`.

```bash
python -m argilla workspaces --name my-workspace add-user user_name
```

**Comment by eshwarhs** [comment]
@gabrielmbmb Can I take this up?
