### ISSUE TITLE
[FEATURE] Ability to add Regex rules to Text Questions

### ISSUE THREAD

**Issue by vmehta-cohere** [recognai/rubrix#3692]
We would require a way if possible either in FeedbackDataset with TextQuestion or Text2Text Dataset to have
Regex rules so that annotators can validate their outputs for example

The score of the student is zero point 4. 

Text box: 0.4 

Here 0.4 should be validated before submission, this can enable annotators to avoid errors and help train LLMs in much more domain specific tasks that are essential. 

Underlying question is that can functional rules be also applied for validation before annotators can submit their tasks. 

Thanks 

```[tasklist]
### Tasks
```

**Comment by vmehta-cohere** [comment]
@davidberenstein1957 @Amelie-V

**Comment by davidberenstein1957** [comment]
@nataliaElv this might be interesting for you to consider

**Comment by nataliaElv** [comment]
#3073

**Comment by vmehta-cohere** [comment]
Do we have any updates regarding this feature?

**Comment by davidberenstein1957** [comment]
@vmehta-cohere no updates yet but it is scheduled I believe @nataliaElv can you confirm?

**Comment by davidberenstein1957** [comment]
@vmehta-cohere I am closing this in favor of this https://github.com/argilla-io/argilla/issues/3073
