### ISSUE TITLE
[BUG] `FeedbackTask` dataset question panel is lost if field title exceeds N consecutive chars

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3695]
**Describe the bug**

As a follow up of https://github.com/argilla-io/argilla/issues/3405, I've realised that the maximum number of characters of the field titles is 500, but when setting a title of N consecutive characters, then the side-panel with the questions is also lost.

I assume this may lead to potential conflicts on the following:
* Field Titles
* Question Titles
* Question Descriptions

Just in case you also want to check/explore other scenarios.

**To Reproduce**

Steps to reproduce the behaviour:

1. Deploy Argilla v1.15.0
2. Add a `FeedbackTask` dataset
3. Go to the `FeedbackTask` dataset settings and set the title of a field to N consecutive characters
4. Go back to the record view and see that the questions disappear

**Expected behaviour**

The field title to be automatically stripped or separated with a hyphen when reaching the end of the width so as not to continue.

**Screenshots**

<img width="1624" alt="image" src="https://github.com/argilla-io/argilla/assets/36760800/3506c732-d30c-4bb5-9efd-82c8f27c827c">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOS
 - Browser [e.g. chrome, safari]: Arc (based in Chromium)
 - Argilla Version [e.g. 1.0.0]: 1.15.0
 - ElasticSearch Version [e.g. 7.10.2]: N/A
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla:v1.15.0

**Comment by damianpumar** [comment]
@alvarobartt, I can not reproduce it.
