### ISSUE TITLE
[FEATURE] Allow to reset response value when `status!=submitted`

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3696]
**Is your feature request related to a problem? Please describe.**
Right now it's not possible to remove a response (when updating the responses values using `PUT /api/v1/responses/{response_id}`) for certain question and record. It would be useful to have this feature, as the user may want to clean up the responses of a record with draft status to get the suggestions back.

If the question doesn't have any value in the form (after clearing the responses for example), the frontend could send `"value": null`, so the backend would be able to remove the response for a question. This way, if the page is refreshed in the frontend, it will receive no responses and it would be able to show the suggestions again.

**Describe the solution you'd like**
The input payload of the `PUT /api/v1/responses/{response_id}` endpoint can be (if `status!=submitted`):

```json
{
    "values": {
        "my-question": {
            "value": null
        }
    },
    "status": "draft"
}
```

**Additional context**
This case was reported by @keithCuniah :)

**Comment by damianpumar** [comment]
Why we need to do that?

**Comment by Amelie-V** [comment]
We don't need it @damianpumar . The clear does not reload the suggestion.
