### ISSUE TITLE
Basic highlight results for Feedback Datasets

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#3697]
# Description

The aim of this feature is to enable highlighting for the Feedback dataset annotations view. 

## Solution proposal

Since the search for Feedback datasets allows only searches by terms, and the search results do not include any info on highlighting results (and it's not planned since depends on the backed search engine and the current one could change in the future), the highlighting will be easily resolved on the frontend side (based on the input search text).

So text for record inputs will be processed to highlight terms matching the search.

Additionally, this should work when the record field shows a rendered markdown (`use_markdown=True`) (need to validate this with @damianpumar and @leiyre

**Comment by damianpumar** [comment]
- [ ] We need to refactor our `RecordFeedbackTaskComponent`to support highlighting.
- [ ] Create new function in `highlight-search.js`to support feedback task datasets.
- [ ] Reuse the function `htmlHighlightText`

@keithCuniah
