### ISSUE TITLE
[FEATURE] Add search and replace functionality for the `FeedbackDataset` on the UI

### ISSUE THREAD

**Issue by plaguss** [recognai/rubrix#3698]
**Is your feature request related to a problem? Please describe.**
I think it could be handy to have a Search and Replace functionality via the UI that could apply to the whole dataset, instead of record by record.

Let me use the next records from an example dataset, altough this may apply to different cases:

![image](https://github.com/argilla-io/argilla/assets/56895847/c908b724-16bf-47c8-af5e-8941282539aa)

![image](https://github.com/argilla-io/argilla/assets/56895847/0c8ad44f-ffdd-4031-8883-9f63a508a7ed)

The dataset is made of lines of characters in a TV series, and includes extra information regarding what the character does in the scene between square brackets. I would like this "explanations" texts to be removed.

**Describe the solution you'd like**
Some functionality to search and replace text, optionally using regular expressions, like the one you have in text editors (the following is an example in VSCode aflter typing Ctrl+H).

![image](https://github.com/argilla-io/argilla/assets/56895847/71754a97-58c4-4cd4-94e1-6bb6f0c0033a)

It should apply to all the text fields in the dataset, and I think to the pending records only.

**Describe alternatives you've considered**

This process can easily be done in pandas, for example, using the following function:

```python
df[column].str.replace(re.compile("\[(.*?)\]"), "", regex=True)
```
Where the `column` could be any of the `fields` in the `FeedbackDataset`. 

- It could be done before uploading the dataset to argilla.
- Download the dataset, process it and load it again.

**Additional context**

**Comment by davidberenstein1957** [comment]
@plaguss I am closing this to prioritize https://github.com/argilla-io/argilla/issues/4050
