### ISSUE TITLE
[DOCS] Write a prompt engineering tutorial

### ISSUE THREAD

**Issue by mnschmit** [recognai/rubrix#3700]
After a discussion related to [this recent tutorial](https://docs.argilla.io/en/latest/guides/llms/examples/fine-tuning-openai-rag-feedback.html#Evaluating-base-vs-fine-tuned-with-human-preference-data), I suggested that a similar tutorial showcasing a GPT3 **prompt engineering** workflow with argilla would be exciting for a lot of people. [This paper](https://aclanthology.org/2023.acl-industry.24/) from the ACL 2023 industry track found that prompt engineering - if done well - can be both cheaper and lead to better performance (in terms of saving time and money) than fine-tuning for a use case in customer service. This would serve as a terrific motivation for such a tutorial.

**Comment by vasudevanubrolu** [comment]
Hi @mnschmit @davidberenstein1957 I have read the paper and found it very practical and resourceful. Would love your insights on it and start a tutorial with relevant use-case and evaluation metrics. I am not clear on the dataset and evaluation metrics. Would love to connect on this and start working

**Comment by davidberenstein1957** [comment]
@mnschmit @vasudevanubrolu are you still working on aligning this?

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 I started my work on argilla this week, will keep you posted on the progress on the items assigned to me

**Comment by davidberenstein1957** [comment]
hi @vasudevanubrolu, that would be great. Thank you 👍  Let me know if you need help.

**Comment by mnschmit** [comment]
Likewise, let me know if you need help :)
