### ISSUE TITLE
[DOCS] Extend `Using a proxy` section in docs

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3706]
Extend the [Using a proxy](https://docs.argilla.io/en/latest/getting_started/installation/configurations/server_configuration.html#using-a-proxy) section with examples on how to setup an NGINX and Traefik proxy to forward requests to the Argilla server.

**Comment by davidberenstein1957** [comment]
@gabrielmbmb hasn't his been finished already?
