### ISSUE TITLE
[FEATURE] allow for adding a note when discarding a record

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3737]
**Is your feature request related to a problem? Please describe.**
It is good to have context as to why a record got discarded from a dataset.

**Describe the solution you'd like**
Ideally, I would like to have the option to add text.

**Describe alternatives you've considered**
Having a dedicated optional `TextField` for every record, but this might not be saved on discard.

**Additional context**
N.A.

**Comment by tugot17** [comment]
Maybe a popup textfield, apearing while clicking `Discard` or something like this
