### ISSUE TITLE
[FEATURE] Add `rg.FeedbackDataset.for_task*` for commonly used task schemas

### ISSUE THREAD

**Issue by kursathalat** [recognai/rubrix#3764]
**Is your feature request related to a problem? Please describe.**

Some tasks always use a basic template for dataset and the task.  FeedbackDataset requires that one creates each component seperately for any task, which makes implementing it a bit tiresome.

**Describe the solution you'd like**

`FeedbackDataset` can have methods to create an instance for a task with that particular task's template (text classification, ner etc.)

**Describe alternatives you've considered**

**Additional context**

**Comment by alvarobartt** [comment]
Hi @kursathalat thanks for proposing this! Indeed we internally talked about exposing some sort of templates, and this is a nice idea to easily create those 👍🏻 We're currently under active refactoring of the `FeedbackDataset` internally, but we can tackle this as soon as that's more stable!

**Comment by davidberenstein1957** [comment]
Yes I agree @alvarobartt, I asked Kursat to outline the configuration that might be required for relevant tasks from a `field` and `question` point of view.

I can for example see something like

```python
ds = rg.FeedbackDataset.for_task("text-classification", labels=["a", "b"])
print(ds.field[0])
# TextField("text")
print(ds.questions[0])
# LabelQuestion("label", values=["a", "b"])

ds = rg.FeedbackDataset.for_task("text-classification", labels=["a", "b"], multi_label=True)
print(ds.field[0])
# TextField("text")
print(ds.questions[0])
# MultiLabelQuestion("label", values=["a", "b"])
```
etc.

**Comment by dvsrepo** [comment]
this is awesome

**Comment by davidberenstein1957** [comment]
And I think this would fit in nicely with the thing I suggested about linking `fields` to `questions` too.

**Comment by dvsrepo** [comment]
yep!

**Comment by tomaarsen** [comment]
This sounds great.

**Comment by davidberenstein1957** [comment]
https://github.com/argilla-io/argilla/issues/3768
