### ISSUE TITLE
[FEATURE] allow to create a reference between `fields` and `questions`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3768]
**Is your feature request related to a problem? Please describe.**
I think it would be useful to create a reference between `fields` and `questions`. For some usecases it might be nice to keep track of the link between the two in general. Also, it might help smoothen out providing the `questions` with potential tasks like linking a `TextField` to a `TokenClassificationQuestion`, potentially linking multiple `TextFields` to a `RankingQuestion`, or even linking a `TextField` to a `TableQuestion`.

**Describe the solution you'd like**
```python
import argilla as rg

field = rg.TextField(name="token_cat_text")
question = rg.TokenClassificationQuestion(name="token_cat_span_overlay", fields=field)
```
or 
```python
import argilla as rg

field_1 = rg.TextField(name="text_1")
field_2 = rg.TextField(name="text_2")
question = rg.RankingQuestion(name="ranking", fields=[field_1, field_2])
```

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by dvsrepo** [comment]
💯
