### ISSUE TITLE
[UI] Text2text

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#377]
New UI

**Comment by Amelie-V** [comment]
- [x] When Edit show Validate instead of validated in the blue CTA.
- [x] Comment "Discarded" on top right side en texttotext task.
- [x] Add opacity to discard records (can be en all tasks). 
- [x] "1 of 3 predictions" : Add predictions into the slider.
- [x] Show "edit" and "view prediction/annotation" only on hover.
- [x] Add "3 puntitos menu" in place of old status (Top right side)
- [x] Show shorcut only when text area is focus and after the field
- [x] Show score 
- [x] Add "..." and include view meta data and discard at the top right
- [x] Remove small lapiz
- [x] Fix Score + slide predictions at the bottom of the card

**Comment by leiyre** [comment]
- [x] Raw annotation
- [x] Conflict with pagination shortcut

**Comment by Amelie-V** [comment]
- [x] Give a minimum size to the card
- [x] (In explore : when it exists an annotation show "validated" button disabled by default (not on hover))
- [x] Apply new changes on hover (sketch/explore view) : all interactions on the right side should appear on hover including menu "..."
- [x] Center slide "1 of 3 pred" on the content size not on the card lenght.
- [x] Slide "1 of 3 pred": remove arrow in place of "disabled arrow" (do exactly as on main pagination)
- [x] 10 px between each card and add grey border on hover
- [x] Integrate ... menu (including hover style)
- [x] Change button position into the card (sketch)
- [x] change "View annotation" to "Back to annotation"
- [x] When user is editing annotation, elements thats appeared on hover should stay fixed/actived
- [x] When user is typing (text area actived), if I click in the active, the text area must stay open until I click on Back or Validate
- [x] Annotation mode: on click on "annotation text" the edit mode is automatically actived (same if I click on Edit)

**Comment by Amelie-V** [comment]
- [x] Center the hover grey square on prediction slide number
- [x] Make "..." thiner
- [x] When I start typing in the text area cant see the CTAs to validate/back (use the checkbox to validate as other option doesnt work either
- [x] When there only 1 prediction, show "1 of 1 prediction" 
- [x] Set size of the right column (will help to separate more text from "view prediction/back annotation" link
- [x] In explore show first prediction, In annotation show first annotation
- [x] Add "Annotation" and "Prediction" as a small title under the text (sketch)

**Comment by Amelie-V** [comment]
- [x] Quit "Prediction" "Annotation" info in Edit mode
- [ ]  Action global : After clic : add confirmation during text 3 seconds: "The action has been correctly applied to x records" and quit border on the button 
- [x] Discard > Discarded disabled in menu ...
