### ISSUE TITLE
[DOCS] Typos code snippets for unification strategies

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#3807]
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/practical_guides/collect_responses.html#code

1. Should import `FeedbackDataset` instead of `FeedbackRecord`
2. Missing comma in function attributes
3. And should be `question_by_name` instead of `get_question_by_name`

**Comment by dvsrepo** [comment]
@tomaarsen @davidberenstein1957 @alvarobartt related to this doc issue. It seems that now unified_responses is protected instead of what's shown in the examples above? Does anyone know if this has changed or was it like that before?

This works:
```python
from argilla import RatingQuestionStrategy, FeedbackDataset

dataset = rg.FeedbackDataset.from_argilla("content-generation-rating", workspace="content-team").pull()
strategy = RatingQuestionStrategy("majority") # "mean", "max", "min"
dataset.unify_responses(
    question=dataset.question_by_name("description-rating"),
    strategy=strategy
)
dataset.records[0]._unified_responses
```
this doesn't
```python
from argilla import RatingQuestionStrategy, FeedbackDataset

dataset = rg.FeedbackDataset.from_argilla("content-generation-rating", workspace="content-team").pull()
strategy = RatingQuestionStrategy("majority") # "mean", "max", "min"
dataset.unify_responses(
    question=dataset.question_by_name("description-rating"),
    strategy=strategy
)
dataset.records[0].unified_responses
```

**Comment by alvarobartt** [comment]
Indeed it's always been a private/protected field of the `FeedbackRecord` schema because it's optional and just used internally, we can explore whether it's worth to have it like that or just as a property with a setter which will be probably the best option. The thing is that when defining the `pydantic.BaseModel` all the fields are args of the `__init__` unless specified otherwise, that's why we didn't include it as `unified_responses` (public) so that users don't see it and try to set it when creating the `FeedbackRecord` instance.

Anyway, we'll review the docs extensively before the v1.17.0 comes out for sure, thanks for reporting! 🤗

**Comment by dvsrepo** [comment]
From the docs it makes it seem like a user facing method and I think getting the unified responses should be a user facing functionality, not only an internal method so I'd suggest finding the best way to provide the unified responses without compromising the data model, validation, etc. Then we can reflect it in the docs

**Comment by alvarobartt** [comment]
> From the docs it makes it seem like a user facing method and I think getting the unified responses should be a user facing functionality, not only an internal method so I'd suggest finding the best way to provide the unified responses without compromising the data model, validation, etc. Then we can reflect it in the docs

Sure, then I guess we can just make it a property, I'll do so on an upcoming PR before the v1.17.0 is released, ideally letting @davidberenstein1957 know before doing anything, as he conducted the development for that!

**Comment by dvsrepo** [comment]
Great @alvarobartt !

**Comment by tomaarsen** [comment]
I'll tackle the typos themselves shortly, and I'll leave the `_unified_responses` discussion to @davidberenstein1957 and co.
