### ISSUE TITLE
[FEATURE] add `datetime` to `ResponseSchema`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3820]
**Is your feature request related to a problem? Please describe.**
I wanted to propose an analysis for responses w.r.t. different users but was not really able to do so due to the fact that we don't store date-times for responses.

**Describe the solution you'd like**
ideally an automatically generated `datetime` to store along with responses.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by frascuchon** [comment]
Thanks @davidberenstein1957 .

We already store the inserted_at and updated_at values for responses.

I think it would be enough with this, right? We just need to expose as part of the response model in the python client.

**Comment by alvarobartt** [comment]
I'll tackle this later today, as with the new refactor it's pretty easy to add while keeping it detached from the user client schema 👍🏻

**Comment by davidberenstein1957** [comment]
Yes, that would be perfect and a great addition for the Python client. Thanks @alvarobartt.

**Comment by dvsrepo** [comment]
Perfect! When this is added please make sure to update the docs and provide a meaningful example beyond docstrings.
