### ISSUE TITLE
[FEATURE] Use `rich` and `tqdm` for better logging bars

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3823]
**Is your feature request related to a problem? Please describe.**

When uploading or downloading records from Argilla for the `FeedbackDataset` from the Python client, the current `tqdm` bars are not as nice as the former ones, so we should either bring back those or propose a new cool formatting when pulling records.

Ideally this should just happen when calling the `pull` method (to be renamed to `pull_from_argilla`) from a `RemoteFeedbackDataset` i.e. a `FeedbackDataset` in Argilla.

Also those bars should be present when pushing a `FeedbackDataset` to Argilla for the first time via `push_to_argilla` and when adding records to an existing `FeedbackDataset` in Argilla i.e. a `RemoteFeedbackDataset`.

**Describe the solution you'd like**

A solution that combines `rich` and `tqdm` in a similar way as for the `rg.log` function that was being used to upload the records on the former datasets i.e. `DatasetForTextClassification`, `DatasetForTokenClassification`, and `DatasetForText2Text`.

**Additional context**

This issue has been created as a follow up of https://github.com/argilla-io/argilla/issues/3120, suggested by @dvsrepo

**Comment by davidberenstein1957** [comment]
@alvarobartt could you add some reference to ultralabel?
