### ISSUE TITLE
[BUG] `TextClassification` dataset displays the labels in wrong order

### ISSUE THREAD

**Issue by gabrielmbmb** [recognai/rubrix#3828]
**Describe the bug**
When setting the `label_schema` for a `TextClassification` dataset the order in which the labels were provided is lost.

**Stacktrace and Code to create the bug**
```python
import argilla as rg

rg.set_workspace("admin")

settings = rg.TextClassificationSettings(label_schema=[
    "1 (extremely positive/supportive)",
    "2 (positive/supportive)",
    "3 (neutral)",
    "4 (hateful/unsupportive)",
    "5 (extremely hateful/unsupportive)",
    "6 (can't say!)"
])

rg.log(rg.TextClassificationRecord(text="blablabla"), name="test-order-labels")

rg.configure_dataset_settings(name="test-order-labels", settings=settings)
```

![image](https://github.com/argilla-io/argilla/assets/29572918/a930e62f-43de-4dc0-9e86-6fb7bef6cd4d)

**Expected behavior**
The order in which the labels were provided is not lost.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.16.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.8.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Comment by davidberenstein1957** [comment]
@frascuchon do we want to fix this or just allow for this in the `FeedbackDataset`?

**Comment by dvsrepo** [comment]
I think @gabrielmbmb fixed this for a community user..please confirm

**Comment by jfcalvo** [comment]
@gabrielmbmb please can you confirm that this is already solved? If that's the case please close the issue.

**Comment by gabrielmbmb** [comment]
@dvsrepo @jfcalvo this is still pending to be fixed, will work on it soon.

**Comment by davidberenstein1957** [comment]
@gabrielmbmb, this might be an issue in the TokenClassification dataset due in terms of visualizing the label order in the UI.
