### ISSUE TITLE
[DOCS] Correcting typo, grammar and links of the quickstart section

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#3863]
## Which page or section is this issue related to?
Checking the three files of the quickstart section: https://docs.argilla.io/en/latest/getting_started/quickstart.html

**Comment by MohdSaquib114** [comment]
Hey can you describe a little bit more about this issue i want work on this.

**Comment by davidberenstein1957** [comment]
@sdiazlor can you confirrm this can be closed?

@MohdSaquib114 help is very welcome. Could you look at comments here? https://github.com/argilla-io/argilla/labels/good%20first%20issue

**Comment by sdiazlor** [comment]
PR completed
