### ISSUE TITLE
[DOCS] fix typos, grammar and others in Reference and Community

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#3881]
## Which page or section is this issue related to?

https://docs.argilla.io/en/latest/reference/python/index.html
https://docs.argilla.io/en/latest/community/developer_docs.html

**Comment by davidberenstein1957** [comment]
@sdiazlor can you confirm this can be closed?

**Comment by sdiazlor** [comment]
@davidberenstein1957 Yes, I'll close them

**Comment by sdiazlor** [comment]
PR completed
