### ISSUE TITLE
[FEATURE] progress visibility for the annotation progress

### ISSUE THREAD

**Issue by vmehta-cohere** [recognai/rubrix#3882]
**Is your feature request related to a problem? Please describe.**
Yes the problem is regarding cross visibility for an annotation team, Currently with feedback datasets that support situations like multi task multi label and other complex tasks, labeling can be a tough challenge for annotators especially non domain experts, They might need guidance and reviews from principal annotators, thus progress visibilty is essential aswell as admin access to edit annotations in datasets that are truly shared with a single record per annotation. 

**Describe the solution you'd like**
Annotators with admin role can view annotation progress in a better manner so anotator roles can get the work reviewed. (especially feedback datasets. ) The same annotators also have the ability to edit responses in the dataset in 'annotator' workspace.

**Comment by davidberenstein1957** [comment]
@nataliaElv this might be relevant feedback for you

**Comment by nataliaElv** [comment]
Hi @vmehta-cohere thanks for leaving a comment after our discussion! Just to make sure I'm getting this right, it's not so much about seeing the progress metrics (e.g. annotator submitted 20 out of 100 records) but the actual labels they applied during the annotation, right?

**Comment by vmehta-cohere** [comment]
Yes the latter but both will be nice to have. @nataliaElv

**Comment by FMelloMascarenhas-Cohere** [comment]
@nataliaElv , we work with healthcare related datasets. We have nurses going over text data and labeling, for example, "chest pain symptomatic". Many cases are tricky and two things happen:

1. They need to ask a doctor to check the case and make a final decision;
2. They need to have a supervisor going over some of their labels and making sure that they are labeling as intended;

Ideally, we would like to give the admin role, or some other role, the ability to go to the examples ids ABC, or filter every example with some tag: NEED_CONFIRMATION, read them and change labels if necessary, to guarantee quality of the process.

Let us know if that makes sense. Thanks for replying to the issue!!

**Comment by nataliaElv** [comment]
Thank you @FMelloMascarenhas-Cohere ! We will have this in mind when we design review workflows.
