### ISSUE TITLE
[DOCS] Add `configure_settings` snippet for `DatasetForTokenClassification`

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3883]
## Which page or section is this issue related to?

In the following documentation page https://docs.argilla.io/en/latest/getting_started/quickstart_workflow.html#2.-TokenClassification, the documentation is there on how to configure the dataset settings for the `DatasetForTextClassification`, but it's missing for the `DatasetForTokenClassification`, so we should be adding the following snippet there too, under the `TokenClassfication` section.

## Code snippet

```python
import argilla as rg

rg.init(
    api_url="<API_URL>",
    api_key="<API_KEY>",
    workspace="admin",
)

settings = rg.TokenClassificationSettings(label_schema=["PER", "ORG", "LOC", "MISC"])
rg.configure_dataset_settings(name="token-classification-dataset", settings=settings)

rg.log(rg.TokenClassificationRecord(text="Hello world!", tokens=["Hello", "world", "!"], name="token-classification-dataset"))
```

**Comment by sdiazlor** [comment]
PR completed
