### ISSUE TITLE
[INTEGRATION] Update `argilla/oasst_response_comparison` to use `RankingQuestion`

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3884]
**Describe the bug**

The `FeedbackDataset` uploaded to the Hugging Face Hub at https://huggingface.co/datasets/argilla/oasst_response_comparison is using a `TextQuestion` to ask the annotator to rank certain fields, while it could now use the `RankingQuestion` instead.

Taking into consideration that this dataset is being used in the `Dockerfile.quickstart` image as a default example, would be nice to actually showcase the Argilla feature to do that, rather than an outdated workaround.

**Expected behaviour**

The `FeedbackDataset` to be exported to the Hugging Face Hub using the `RankingQuestion` instead of the `TextQuestion`.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: N/A

cc @nataliaElv @davidberenstein1957

**Comment by alvarobartt** [comment]
cc @nataliaElv @davidberenstein1957

**Comment by nataliaElv** [comment]
Not sure what you mean. I've always seen it as a `RankingQuestion`. Could you maybe share some screenshots to see what's the issue with the dataset?

**Comment by alvarobartt** [comment]
So I saw this in some recent PRs, but maybe those were outdated, see the following screenshot:

<img width="1624" alt="image" src="https://github.com/argilla-io/argilla/assets/36760800/c13018ab-fb17-4ad4-ab3b-76728c520eed">

I see that the [`argilla.cfg`](https://huggingface.co/datasets/argilla/oasst_response_comparison/blob/main/argilla.cfg) file does use the `RankingQuestion`, so I'll try to double-check.
