### ISSUE TITLE
[BUG]  FeedBack record ID is getting overridden with an autogenerated uuid internally by Argilla

### ISSUE THREAD

**Issue by raghulrider** [recognai/rubrix#3892]
**Describe the bug**

- The FeedBackRecord class has the option to send the user given ID as the record identifier with id as parameter - [Code Ref](https://github.com/argilla-io/argilla/blob/40dc948ec563bee8ea8ef2f6c1f09d7d1718ebcd/src/argilla/client/feedback/schemas.py#L138)
- The issue is the user given ID is getting overridden with an autogenerated uuid internally by Argilla.
[](url)

**Code to create the bug**

```python
import argilla as rg

rg.init("<API url>", "<API key>")

record_identifier = "<UUID generated by us>"
record = rg.FeedbackRecord(
    id=record_identifier,
    fields={},
    metadata={},
)

dataset = rg.FeedbackDataset.from_argilla(name="<dataset-name>", workspace="<workspace-name>", with_records=False)
dataset.add_records(record)
dataset.push_to_argilla()

dataset.fetch_records()

record_found = False
for record in dataset.records:
    if record.id == record_identifier:
        record_found = True
        break

if not record_found:
    print(f"Record with id {record_identifier} not found")
else:
    print(f"Record with id {record_identifier} found")
```

**Expected behaviour**

- There should be an option for the user to give the record identifier for the FeedbackRecord similar to TextClassificationRecord
- ID given by the user should be the record identifier and it should not be overridden by Argilla 

**Environment:**
 - Argilla Version: 1.13.2
 - OpenSearch Version: 2.5
 - Docker Image: argilla/argilla-server:v1.13.2

**Comment by alvarobartt** [comment]
Hi @raghulrider thanks for reporting! Indeed this will already be fixed in v1.17.0, as now the remote schemas are detached from the local schemas, as the `id` is not intended to be used outside Argilla, so that's the reason why it's overwritten.

So feel free to use `external_id` in the meantime, which is indeed intended for external usage e.g. outside and unrelated to Argilla.

```python
rg.FeedbackRecord(
    ...,
    external_id="<EXTERNAL_ID>",
)
```
