### ISSUE TITLE
[DOCS] Fine-tuning bi and cross encoder for RAG using the Argilla Trainer blogpost

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#3896]
## Which page or section is this issue related to?

The main idea is to write a blog post about using the Argilla Trainer to fine-tune bi- or cross-encoder for RAG.

**Comment by davidberenstein1957** [comment]
returnin an iterator might still be blocking

**Comment by sdiazlor** [comment]
Tutorial updated to the latest fixes and images added. I think we should wait until the fixes are implemented so that people can run it.

**Comment by davidberenstein1957** [comment]
Yes, we can merge it in `develop`
