### ISSUE TITLE
[BUG] Multiple error popups with end of document

### ISSUE THREAD

**Issue by vmehta-cohere** [recognai/rubrix#3904]
**Describe the bug**
Multiple error popups with end of document 
**To Reproduce**
1. Go to any dataset/feedbackdataset
2. Click on 'next' at end of document

**Expected behavior**
Only one message pop up should appear and not flood the ui blocking tasks 

**Screenshots**
<img width="481" alt="image" src="https://github.com/argilla-io/argilla/assets/107134330/c36222d3-62b3-49e6-928e-4ed28c275565">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: macOs
 - Browser [e.g. chrome, safari]: chrome
 - Argilla Version [e.g. 1.0.0]: 1.16.0
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.16.0

**Comment by alvarobartt** [comment]
Hi @vmehta-cohere thanks for reporting, I think this is intended as I assume you got all those toast messages due to spamming the `Next` button to navigate between records, anyway if that's not the case, could you give us more tips on how to reproduce? Tagging here @damianpumar to help solve this!

**Comment by dvsrepo** [comment]
thanks @vmehta-cohere this is a known limitation and something we'll try to avoid/improve

**Comment by damianpumar** [comment]
This issue was fixed here 👉 https://github.com/argilla-io/argilla/pull/4334
