### ISSUE TITLE
[FEATURE] Question navigation ability in feedback datasets

### ISSUE THREAD

**Issue by vmehta-cohere** [recognai/rubrix#3905]
@davidberenstein1957 @nataliaElv 
**Is your feature request related to a problem? Please describe.**
There is no way to navigate to particular questions  in feedback dataset with regard to question 
number or a simple search

**Describe the solution you'd like**
ability to navigate questions

**Comment by nataliaElv** [comment]
Hi @vmehta-cohere ! Could you explain a bit further what you mean by navigating to questions here and in which context you need this feature?

**Comment by davidberenstein1957** [comment]
@vmehta-cohere Is this still relevant?
