### ISSUE TITLE
[FEATURE] align `rg.*` default methods for old and new datasets

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3915]
**Is your feature request related to a problem? Please describe.**

This feature has been requested by @dvsrepo so that we're able to list all the datasets for a given workspace via an intuitive method such as `list_datasets`.

The current approach is `rg.FeedbackDataset.list(workspace="argilla")` but that's to list just the `FeedbackDataset` datasets and may be not as intuitive as `Workspace(name="argilla").list_datasets()`.

**Describe the solution you'd like**

Ideally we should add a `list_datasets` method to list all the datasets from a given workspace.

**Additional context**

We should clearly see how to combine both the `FeedbackDataset` with the previous datasets i.e. `DatasetForTextClassification`, `DatasetForTokenClassification` and `DatasetForText2Text`. And also evaluate whether we should be returning just the `name` and `type` of those or a class instance if working with `FeedbackDataset` datasets, etc.

**Comment by dvsrepo** [comment]
We should also unify the current existing `rg.list_datasets()` to return both legacy and feedback datasets or less ideal but better than currently: warn the user that for listing feedback datasets they need to call other method

**Comment by davidberenstein1957** [comment]
@dvsrepo I believe the `rg.delete_dataset()` also just return a succesfull status code.

**Comment by davidberenstein1957** [comment]
Also align the `rg.*` methods for the different dataset types.

**Comment by davidberenstein1957** [comment]
Related to this https://github.com/argilla-io/argilla/pull/4159
