### ISSUE TITLE
[BUG] `push_to_argilla` does not accept missing values for optional `TextField`s

### ISSUE THREAD

**Issue by kursathalat** [recognai/rubrix#3927]
**Describe the bug**
When a `TextField` of a Feedback dataset is not `required`, it is supposed to accept records that do not have items for the non-required field. However, while pushing such datasets to the server, it throws an error that states that the record has `NoneType` for the missing item rather than proceeding. Since there might be datasets that do not have items for all fields, it might be better if such datasets are accepted.

**Stacktrace and Code to create the bug**
```python
# a dataset that has a mandatory field and an optional field
ds = rg.FeedbackDataset(
    fields=[
        rg.TextField(name="text1", required=True),
        rg.TextField(name="text2", required=False),
    ],
    questions=[
        rg.TextQuestion(name="question1", description="This is the first question"),
    ]
)

# this works perfectly as expected
record_with_text2 = rg.FeedbackRecord(
    fields={"text1": "This is the first text", "text2": "This is the second text"},
)

# this would be a possible dataitem that a user would submit, which will raise an error
record_with_no_text2 = rg.FeedbackRecord(
    fields={"text1": "This is the first text"},
)

# no problem adding it to the dataset
ds.add_records([record_with_no_text2])

# this will raise an error
remote_dataset = ds.push_to_argilla(name="my-dataset", workspace="admin")
```
```bash
Exception: Failed while adding the records to the `FeedbackDataset` in Argilla with exception: Argilla server 
returned an error with http status: 422
Error details: [{'response': "Wrong value found for field 'text2'. Expected 'str', found 'NoneType'", 'params': 
{}}]
```

**Expected behavior**
The dataset should be uploaded with the missing values as they are optional. Or, it can be something like `NA`, as well. 

**Environment:**
│  • Client version: 1.17.0-dev
│  • Server version: 1.14.1
│  • ElasticSearch version: 8.8.2

**Additional context**

**Comment by alvarobartt** [comment]
Hi @kursathalat this has already been fixed as of https://github.com/argilla-io/argilla/pull/3846, but thanks for reporting! For context, the issue was the the API was preventing from `None` or even empty values, and always checking the value, so something like `{"required-field": "text", "optional-field": ""}` does the work, but from now on, one can do `{"required-field": "text", "optional-field": None}` and/or `{"required-field": "text"}`
