### ISSUE TITLE
[FEATURE] create `utils` to create git-like text-diff for markdown Fields

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3928]
**Is your feature request related to a problem? Please describe.**
N.A.

**Describe the solution you'd like**
```python
from argilla.feedback.util import text_dif

before = "my name is"
after = "y name is"
html_str = text_dif(before, after)
```
![image](https://github.com/argilla-io/argilla/assets/25269220/8fc417ea-ce1b-43cd-aa3e-f4514a5650e6)

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
@dvsrepo

**Comment by dvsrepo** [comment]
this compares the suggestion for corrected_text with the first response to that question

```python
import diff_match_patch as dmp_module
from IPython.core.display import display, HTML

def extract_text_from_object(obj):
    """Extract the 'value' text from the object."""
    return obj[0]['value']

# Initialize the diff_match_patch object
dmp = dmp_module.diff_match_patch()

# Extract the 'value' text from the validated object
incorrect_df.loc[:, 'text_from_response'] = incorrect_df['corrected-text'].apply(extract_text_from_object)

def visual_diff(s1, s2):
    """Get a visual representation of the differences between two strings."""
    diff = dmp.diff_main(s1, s2)
    dmp.diff_cleanupSemantic(diff)
    return dmp.diff_prettyHtml(diff)

# Let's apply this function to the DataFrame
incorrect_df['visual_diff_html'] = incorrect_df.apply(lambda row: visual_diff(row['new-text'], row['text_from_response']), axis=1)

# Print the visual diffs in Colab
for index, row in incorrect_df.iterrows():
    print(f"Row {row.metadata_article_name}:")
    display(HTML(row['visual_diff_html']))
```

**Comment by davidberenstein1957** [comment]
@dvsrepo, do you still feel this should be added to the `utils`

**Comment by davidberenstein1957** [comment]
@sdiazlor might not be relevant

**Comment by taha-yassine** [comment]
Sorry for reviving an old issue, but was this ever implemented?

**Comment by sdiazlor** [comment]
Hi @taha-yassine. We didn't implement it directly. However, we added the [custom field](https://docs.argilla.io/latest/how_to_guides/custom_fields/) which allows this feature as shown here: https://huggingface.co/blog/burtenshaw/custom-interface-data-labeling-annotation-html-css#document-revision-and-text-comparison

**Comment by taha-yassine** [comment]
This is perfect, thanks!
