### ISSUE TITLE
[BUG-UI/UX] fields and questions don't scroll up after record submit

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3931]
**Describe the bug**
After submitting a form, if fields and questions are scrollable, we don't scroll up after a submit.

**To Reproduce**
See video

**Expected behaviour**
I would expect the scroll to start from scratchc

**Screenshots**
https://github.com/argilla-io/argilla/assets/25269220/076ab46b-3ebc-4143-9fee-7852b31cb190

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MaxOS
 - Browser [e.g. chrome, safari]: FireFox
 - Argilla Version [e.g. 1.0.0]: 1.14
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.14

**Additional context**
N.A.

**Comment by damianpumar** [comment]
Fixed here -> https://github.com/argilla-io/argilla/pull/3830
