### ISSUE TITLE
[FEATURE] Move CLI commands under `argilla server`

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3942]
**Is your feature request related to a problem? Please describe.**

I think it's a bit counter-intuitive to have some server-related commands in the CLI under a different entry-point e.g. `argilla login` is login into an Argilla server, as well as `argilla logout` so those should be `argilla server login` and `argilla server logout` IMO.

**Describe the solution you'd like**

Here I list some CLI commands I would just move under `server`:

- `argilla login` -> `argilla server login`
- `argilla info` -> `argilla server info`
- `argilla logout` -> `argilla server logout`

Eventually, we would also add a new command to replace `argilla info` to display local information such as the Python package version, but could be extended to any other arg we feel like can be useful.

And we should re-write the `ISSUE_TEMPLATES` to let users know that to run `argilla server info` (former `argilla info`) they need to `argilla server login` (former `argilla login`) first.

**Comment by davidberenstein1957** [comment]
@alvarobartt to double check, this has not been handled yet right?

**Comment by davidberenstein1957** [comment]
We chose not to tackle this issue anymore.
