### ISSUE TITLE
[REFACTOR] Align `@abstractmethod` definition within `argilla`

### ISSUE THREAD

**Issue by alvarobartt** [recognai/rubrix#3943]
**Is your feature request related to a problem? Please describe.**

As of the [Python documentation](https://docs.python.org/3.11/library/abc.html#abc.abstractproperty) the usage of `@abstractproperty` is discouraged and deprecated since Python 3.3, so we should stop using those in the first place, replacing them with `@property` + `@abstractmethod`.

Then regarding the body of those `@abstractmethod`s we should define an standard way of defining those.

**Describe the solution you'd like**

- Adding a one-line docstring
  
  ```python
  from abc import abstractmethod
  
  class A:
     ...
  
     @abstractmethod
     def implement_me(self) -> None:
        """This is a docstring"""
  ```

- Adding `pass`

  ```python
  from abc import abstractmethod
  
  class A:
     ...
  
     @abstractmethod
     def implement_me(self) -> None:
        pass
  ```
- Adding `...`

  ```python
  from abc import abstractmethod
  
  class A:
     ...
  
     @abstractmethod
     def implement_me(self) -> None:
        ...
  ```

**Comment by davidberenstein1957** [comment]
@frascuchon @jfcalvo @gabrielmbmb
