### ISSUE TITLE
Installation issue on Amazon Ec2

### ISSUE THREAD

**Issue by SowmyaSharath** [recognai/rubrix#395]
I wanted to try to install your service on Amazon Ec2 (Amazon Linux). 
I first tried using docker-compose and on running the yaml it is throwing File not found issue.
Then i tried by manually installing Elastic Search with instructions given in this link https://gist.github.com/hydeenoble/e3edb7e73df13095a8804bc1cbd31e10

elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product

**Comment by frascuchon** [comment]
Hi @SowmyaSharath 

First of all, thanks for your feedback. It's very appreciate.

For the docker-compose installation, did you follow the [setup instuctions guide](https://rubrix.readthedocs.io/en/stable/getting_started/setup%26installation.html#setup-and-installation)?

The `File not found issue` could be raise by wrong permission access to download folder and cannot be stored. Could you give some logs from your installation setup?

For the second part, I'm guessing your're launching a local rubrix server instance using python command:

```bash
python -m rubrix.server
```

In that case, be sure the elasticsearch-cli dependency is not higher than 7.13. 

```bash
pip install 'elasticsearch<7.14.0'
```

From 7.14, official elasticsearch clients checks the elasticsearch server flavour and raise this kind of error for Open source distributions. 

See here https://github.com/elastic/elasticsearch-py/issues/1639

**Comment by dvsrepo** [comment]
Additionally, in case you haven't seen this other guide:

https://rubrix.readthedocs.io/en/stable/getting_started/advanced_setup_guides.html#deploy-to-aws-instance-using-docker-machine

**Comment by SowmyaSharath** [comment]
I tried changing the permissions and i can see the yaml file downloaded , but when i issue the docker-compose up command it throws this error. I am uploading the logs. Meanwhile i will check the version on Elastic Search
[rubrix_logs (1).txt](https://github.com/recognai/rubrix/files/7259671/rubrix_logs.1.txt)
.

**Comment by SowmyaSharath** [comment]
> Additionally, in case you haven't seen this other guide:
> 
> https://rubrix.readthedocs.io/en/stable/getting_started/advanced_setup_guides.html#deploy-to-aws-instance-using-docker-machine

Oh did not see that. Will try that as well. Thank you !

**Comment by frascuchon** [comment]
> I tried changing the permissions and i can see the yaml file downloaded , but when i issue the docker-compose up command it throws this error. I am uploading the logs. Meanwhile i will check the version on Elastic Search [rubrix_logs (1).txt](https://github.com/recognai/rubrix/files/7259671/rubrix_logs.1.txt) .

Regarding the logs it's look like docker is not running or  is running as root. 

You can check the docker installation with hello-world image 

```bash
docker run hello-world
```

You can also check guide referred by @dvsrepo

**Comment by SowmyaSharath** [comment]
> > I tried changing the permissions and i can see the yaml file downloaded , but when i issue the docker-compose up command it throws this error. I am uploading the logs. Meanwhile i will check the version on Elastic Search [rubrix_logs (1).txt](https://github.com/recognai/rubrix/files/7259671/rubrix_logs.1.txt) .
> 
> Regarding the logs it's look like docker is not running or is running as root.
> 
> You can check the docker installation with hello-world image
> 
> ```shell
> docker run hello-world
> ```
> 
> You can also check guide referred by @dvsrepo

Awesome this solved my issues! My docker has some issues once i rectified it was ok.
