### ISSUE TITLE
[DOCS] update the contributor documentation

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3962]
## Which page or section is this issue related to?
It is not very clear how people can comfortably contribute and work with us on Git and Slack etc so we should update this.
https://docs.argilla.io/en/latest/community/contributing.html
- work with git and GitHub page
    - https://weaviate.io/developers/contributor-guide/getting-started/git-and-github

**Comment by sdiazlor** [comment]
PR merged #3996
