### ISSUE TITLE
[DOCS] update developer documentation for documentation

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#3963]
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/community/developer_docs.html

  - work on documentation
      - install doc requirements
      - sphinx-autobuild
          - sphinx-autobuild docs/_source docs/_build/html
      - make changes
          - indexing them properly within sphinx
      - ensure changes are mentioned in the sphinx index

**Comment by sdiazlor** [comment]
Added this section in the following [PR](https://github.com/argilla-io/argilla/pull/3986).
