### ISSUE TITLE
[FEATURE] Allow passing metadata to task templates

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#3997]
**Is your feature request related to a problem? Please describe.**
I want to be able to pass a metadata property list when creating my task template like this:

```python
import argilla as rg

ds = rg.FeedbackDataset.for_supervised_fine_tuning(
    context=True,
    use_markdown=True,
    guidelines=None,
    metadata_properties =metadata
)
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dvsrepo** [comment]
what do you think @kursathalat ?

**Comment by davidberenstein1957** [comment]
I think this makes sense as an issue to pick up for @kursathalat. I initially did not want to block this to avoid blocking the release, since we can just do `.add_metadata` after, but an integrated option would be nicer.

**Comment by kursathalat** [comment]
Sounds good, I will be creating a branch for this.
