### ISSUE TITLE
[FEATURE] Add metadata properties table to auto-generated HF dataset card

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#4007]
**Is your feature request related to a problem? Please describe.**
We have very nice tables showing the fields and questions, we could do the same with metadata properties.

See:

https://huggingface.co/datasets/argilla/text-descriptives-metadata#data-in-argilla

<img width="900" alt="Captura de pantalla 2023-10-20 a las 15 42 33" src="https://github.com/argilla-io/argilla/assets/1107111/06631865-71fd-4227-8f6c-4f1037c317ce">

**If you'd like to contribute this you can ask @alvarobartt to guide you**

**Comment by dcfidalgo** [comment]
Hola! :) Before Hacktober is over, I wanted to contribute to at least one awesome open-source project, and why not to the most awesome one? So If no one is working on this issue, can I give it a try? Big hug and saludos!

**Comment by dvsrepo** [comment]
Oooooh!! That'd be an honor!
