### ISSUE TITLE
[UI] Record cards standardization ¨Next Release¨

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#401]
Cross model type

**Comment by Amelie-V** [comment]
- [x] Text classifier (single and multi) : Show "Validate" button. Once one label is selected, button "Validate" pass to "Validated".
- [x] NER: Active "check box" and "Validate" button when user starts selecting part of the text record.
- [ ] NER: Find a way to make evident user need to validate to save the annotation. (Amélie)
- [ ] NER: Create an alert to inform annotation is unsaved when user is about to change the view : clic on "Filter" "Sort" "Explore"
- [x] All models: Keep showing "Validate" button once the record has been edited.

**Comment by Amelie-V** [comment]
### Global

- [x] Electric blue for : save, edit, back
- [x] Dark grey for : "...", view annotation / back to annotation
- [x] Reduce margen between bt 6px
- [x] Save/edit bt should be shorter : reduce padding
- [x] Add "pending" status in Text2Text and NER when user is editing records. 
- [x] Use copy "Validate" in all model type 
- [x] Use copy "Save" with "back" in edition mode in Text2text 
- [x] Change copy: Shift enter to save
- [x] NER and Text2Text : changes are saved (meanwhile there is no Refresh), so editing many records at the same time is facilited
- [x] Record cards: 20 px margen
- [x] records card Text2Text: Button in edition should be on an independant line
- [x] Icon explore change cross to check when its different
- [x] Text2Text Review font text size of "prediction/view prediction"

**Comment by frascuchon** [comment]
New changes changes the action `Validate` to `Save`. This should be aligned with global actions, that keep as `Validate`

In my opinion, the action `Validate` match better for annotation process than `Save`. For records that are not edited but want to be annotated, the validation action  should be better placed than generic save action.

The only case where a save action could make more sense than validate, is when users manually edit the record. But I think that case penalizes the overall UI logic.

What do you think @Amelie-V @leiyre @dcfidalgo @dvsrepo ?

**Comment by Amelie-V** [comment]
Thanks for the feedback, I understand and I agree.
I think we should maintain "Validate" as main call to action for all models types.
But I also think an "edit" has to coexist with a "Save" and not with a "Validate".
That why in NER and text2text I recommend to use the copy "Save" in the button when the record is edited

@leiyre @dcfidalgo @dvsrepo @frascuchon

**Comment by frascuchon** [comment]
For all of you @leiyre @Amelie-V @dvsrepo @dcfidalgo 

About task point:
>  Allow uncheck all labels in single labels Text Classification

Since It's not quite simple implement all cases for that functionality and it there are some edge cases that we should discuss before (records without predictions), i will remove that functionality from PR for the sake of the QA until we decide the correct behavior.

**Comment by dvsrepo** [comment]
Great, it's not highly critical

**Comment by dvsrepo** [comment]
For the sake of completeness, just to mention that on previous versions (see app) the behaviour to deselect labels for single-label worked by changing to status=Edited.

**Comment by frascuchon** [comment]
Great! Anyway we can treat the "deselect to Default" as a separate issue.
