### ISSUE TITLE
[FEATURE] Improve visualization of questions with `use_markdown` enabled

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#4011]
**Is your feature request related to a problem? Please describe.**

Two minor improvements

1. It would be useful for users  to see that a response text area has markdown enabled. Maybe with a [pill tag](https://codepen.io/hyumankind/pen/ExaYNGm):

When markdown is rendered it can be obvious (but not always):
<img width="604" alt="Captura de pantalla 2023-10-20 a las 20 18 39" src="https://github.com/argilla-io/argilla/assets/1107111/d75c8b6f-63c9-4653-aa18-7c2308d5b343">

When on focus on is less obvious:
<img width="604" alt="Captura de pantalla 2023-10-20 a las 20 18 39" src="https://github.com/argilla-io/argilla/assets/1107111/4bf65239-c36c-4137-8255-775be23bdd7c">

2. Give a more explicit preview option (as we do for guidelines, could we reuse that?), currently users need to know that if they click outside (remove focus) they'll see the markdown rendered.

<img width="1070" alt="Captura de pantalla 2023-10-20 a las 20 24 25" src="https://github.com/argilla-io/argilla/assets/1107111/27fef9e6-e609-4e94-9866-cc5bcbc4d20b">

**Comment by davidberenstein1957** [comment]
I agree with this, but maybe even something more complete would be nicer for some text formatting. @dvsrepo what do you think?

![image](https://github.com/argilla-io/argilla/assets/25269220/926c2fc2-31d9-4162-aaf9-ddaf0dd13866)
