### ISSUE TITLE
[FEATURE] improve robustnes of server connection within `push_to_argilla`, `add_records` and `update_records`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4015]
**Is your feature request related to a problem? Please describe.**
As with many other tools, I would like to have some control over the connection like `batch_size` `retries`. It is fore example, common to retry during status_codes like `500` because they generally involve load-related issues.

**Describe the solution you'd like**
N.A.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
re-introduce the `iter` with more flexibility there

**Comment by davidberenstein1957** [comment]
src/argilla/client/sdk/v1/datasets/api.py

**Comment by davidberenstein1957** [comment]
@alvarobartt, can you provide some context here for one of our contributors that's interested in picking this up?

**Comment by vasudevanubrolu** [comment]
Hi @alvarobartt @davidberenstein1957 I would love contribute on this. It would be great to hear back on that. I have good amount of time weekly (approx 8 hrs) to work on.

**Comment by davidberenstein1957** [comment]
hi @vasudevanubrolu, thanks for the offer but we'll tackle this issue internally because it is blocking for one of our clients. I believe you also have other issues you can focus on.
