### ISSUE TITLE
[FEATURE] add out of the box `embedding` support via `client.feedback.integrations`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4018]
**Is your feature request related to a problem? Please describe.**
It is sometimes unclear what all the cool Argilla features are.

**Describe the solution you'd like**
Ideally, I want to see this happen when calling this `add_records` and run this code this before uploading data to Argilla. Use one of the [TaylorAI models](https://x.com/andersonbcdefg/status/1710708732534108413?s=20).
```python

rg.FeedbackDataset(..., vector_settings="TaylorAI/bge-micro-v2")
```

**Describe alternatives you've considered**
Doing this manually, always.

**Additional context**
https://github.com/argilla-io/argilla/issues/4017

**Comment by plaguss** [comment]
Hi @davidberenstein1957 should we let this for when we are sure about the definition of remote vs local dataset? Otherwise maybe I can start tomorrow.

**Comment by davidberenstein1957** [comment]
Lets wait until later, feel free to focus a bit more distilabel.
