### ISSUE TITLE
[DOCS] correct `ArgillaTrainer` section `older` dataset

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4025]
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/practical_guides/fine_tune.html#id18 this does not show the `ArgillaTrainer` for older datasets. But it should look like https://docs.argilla.io/en/v1.13.0/guides/train_a_model.html

**Comment by sdiazlor** [comment]
Regarding this, I can work on that, as I already have an issue and branch created to modify this file

**Comment by sdiazlor** [comment]
PR completed #4053
