### ISSUE TITLE
[FEATURE] create record assignment `utils`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4031]
**Is your feature request related to a problem? Please describe.**
We need to maintain code in out docs for record assignment.
https://docs.argilla.io/en/latest/practical_guides/assign_records.html

**Describe the solution you'd like**
```python
from argilla.client.feedback.utils import assign_records

assign_records(user, records, overlap)
```

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by Luckydhingra** [comment]
- [x] I am Particiapting in Hactoberfest 2023
- [x] I would like to work on this issue 
- [ ] Assign me this issue @davidberenstein1957

**Comment by davidberenstein1957** [comment]
hi @Luckydhingra, @sdiazlor was already going to work on this issue, but perhaps you can find a separate smaller issue among https://github.com/argilla-io/argilla/labels/good%20first%20issue? I can add the hacktoberfest tag later :)

**Comment by davidberenstein1957** [comment]
You can also briefly mention https://github.com/argilla-io/argilla/issues/4067 in the docs update.
