### ISSUE TITLE
[FEATURE] change default questions in FeedbackDataset templates

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4041]
**Is your feature request related to a problem? Please describe.**
I think the default questions for the FeedbackDataset.for_sentence_similarity and FeedbackDataset.for_retrieval_augmented_generation should be changed from ratingquestion to rankingquestion or labelquestion, as the ArgillaTrainer for sentence similarity only accept those, this way we can keep the flow.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sdiazlor** [comment]
@kursathalat I assigned you because you're working with the Templates and can be more straightforward, if not let me know

**Comment by kursathalat** [comment]
Sure thing. But I guess RatingQuestion is highly used for sentence similarity though Ranking seems fine as well. Maybe they can both exist to be comprehensive and to ensure the flow. What do you think @davidberenstein1957 ?

**Comment by sdiazlor** [comment]
In fact, I have some more thoughts about this, we can maybe discuss it tomorrow

**Comment by davidberenstein1957** [comment]
@sdiazlor I will close this. Can you create a new one for the things we discussed.

**Comment by sdiazlor** [comment]
@davidberenstein1957 Yes, I was on it
