### ISSUE TITLE
[FEATURE] create an example `multi-modal-audio-image-video` dataset on the Hugging Face hub

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4046]
**Is your feature request related to a problem? Please describe.**
https://github.com/argilla-io/argilla-workshop

**Describe the solution you'd like**
I would like to see it combined with the `utils`

**Describe alternatives you've considered**
N.A.

**Additional context**
Also, add some metadata and add it to the `demo.argilla.io`

**Comment by davidberenstein1957** [comment]
@sdiazlor, this can be combined with this issue. https://github.com/argilla-io/argilla/issues/4048

**Comment by davidberenstein1957** [comment]
Create a basic dataset
- `image`
- `video`
- `audio`

**Comment by davidberenstein1957** [comment]
@gabrielmbmb, can you help @sdiazlor  to add it to the demo.argilla.io

**Comment by sdiazlor** [comment]
Dataset created and available in HF (argilla/multi-modal) and demo.argilla.io (multi-modal-video-audio-image)
