### ISSUE TITLE
[FEATURE] RatingQuestion should be added intead of RankingQuestion

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4049]
**Is your feature request related to a problem? Please describe.**

1. It looks like only LabelQuestion and RankingQuestion work when training for sentence similarity. Instead of using the RankingQuestion, it is better to use the RatingQuestion.

2. In fact, RankingQuestion does not work properly as it takes the values (which are strings) instead of the rank.

3. In addition, check that in the TrainingTask, dataset.question_by_name supports any possible name given to the LabelQuestion or RatingQuestion other than just "label".

```python
task = TrainingTask.for_sentence_similarity(
    texts=[dataset.field_by_name("premise"), dataset.field_by_name("hypothesis")],
    label=dataset.question_by_name("other_name")
)
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
@plaguss Sara noticed this, maybe you can help and outline the best approach?

**Comment by plaguss** [comment]
Sure! @sdiazlor I'll review it and let you know

**Comment by plaguss** [comment]
Hi @sdiazlor, https://github.com/argilla-io/argilla/pull/4171 should answer questions 1 and 2 from this issue. For the point 3 do you have some example dataset that I can work with? I think that should be working
