### ISSUE TITLE
[FEATURE] cleanup tests for the task templates

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4058]
**Is your feature request related to a problem? Please describe.**
The tests for the task_templates are a bit lengthy.

**Describe the solution you'd like**
Simplify and re-use the logic.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by plaguss** [comment]
Hi @davidberenstein1957, should we close this with #4087?

**Comment by davidberenstein1957** [comment]
Yes, thanks for the reminder.
