### ISSUE TITLE
[BUG-python/deployment] Required Multilabel question should accept blank as a valid response

### ISSUE THREAD

**Issue by dmri2z** [recognai/rubrix#4060]
**Describe the bug**
In my FeedbackDataset the Multilabel question is the only required question, but I need the user to be able to submit without selecting any label (the record might not fit any of the labels)

**Expected behavior**
The Submit button should be enabled if the only required question is a Multilabel even if no label has been selected

**Environment:**
 - Argilla Version: 1.17.0
 - ElasticSearch Version: 8.10.1

**Comment by davidberenstein1957** [comment]
However, we currently don’t allow for this. Meaning that if the MultiLabelQuestion(…required=True) and there have no labels been applied, the submit button does not activate. I am not sure if this is a back-end or frontend thing.

**Comment by dvsrepo** [comment]
Initially we will not support this in the coming future because it adds a lot of complexity to manage required/submitted statuses and validation processes.

We recommend adding a None label
