### ISSUE TITLE
[DOCS] Use metadata to assign annotations

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4067]
## Which page or section is this issue related to?

Now that it's possible to filter records in Feedback Datasets using metadata, we can modify [this page](https://docs.argilla.io/en/latest/practical_guides/assign_records.html) to explain how to make assignments using this method.

**Comment by davidberenstein1957** [comment]
@nataliaElv, did you already asign users by metadata?

**Comment by nataliaElv** [comment]
Yes for old datasets, but not for the new Feedback, so maybe we can modify the page to use that in favor of duplicating datasets 😄

**Comment by sdiazlor** [comment]
@nataliaElv thanks, then, by the moment, i will add the assign_records to the utils module  (with the proper changes), then I will update this page
