### ISSUE TITLE
 [BUG-python/deployment] backwards compatibility `src/argilla/client/sdk/v1/datasets/api.py` `get_metadata_properties`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4073]
**Describe the bug**
Whenever retrieving a dataset from server 1.17 with client 1.19 there seems to be an incompatibility issue when calling `response.json`. I think this might be a more recurrent issue, where for some reason the response does return with `response.status_code==200` even though the endpoint is not defined in FastAPI. Hence this might also occur with the semantic search update. 

**Stacktrace and Code to create the bug**
https://github.com/argilla-io/argilla/blob/38c279984b007576880118e2ab8b66451bac60b5/src/argilla/client/sdk/v1/datasets/api.py#L423
Try loading a dataset from the 1.17 server with a 1.19 client.

**Expected behavior**

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.19
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.17

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
ahh nop, is the 404 page
is the frontend redirection
Ideally, the frontend should be mounted in a different path for example [argilla.io/ui](http://argilla.io/ui). for the ui and [argilla.io/api](http://argilla.io/api) for the api. This will simplify to handle this kind of problems

**Comment by frascuchon** [comment]
The 404 page returned is returning a 200 status code, but it should return a 404. Not sure if this can be handled by the frontend application in an easy way @damianpumar 

```bash
curl -I -XGET http://localhost:6900/bad-url
```
```bash
HTTP/1.1 200 OK
date: Sat, 11 Nov 2023 14:41:43 GMT
server: uvicorn
content-type: text/html; charset=utf-8
content-length: 3343
last-modified: Sat, 11 Nov 2023 14:38:57 GMT
etag: 203c3b25094c8251a8ea2f427745a917
```

**Comment by davidberenstein1957** [comment]
This seems related https://github.com/argilla-io/argilla/issues/4302
