### ISSUE TITLE
[UI/UX] sort on `inserted_at` `updated_at` does not show without metadata props

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4078]
**Describe the bug**
I expected to always be able to sort on `inserted_at` `updated_at` but this does not show in the UI without metadata.

**To Reproduce**
Add a dataset without metadata and one with metadata.

**Expected behavior**
I would expect sort to be available.

**Screenshots**
with 
<img width="1495" alt="image" src="https://github.com/argilla-io/argilla/assets/25269220/f1688ed5-9cfe-4e35-a833-65ffd60ce04e">
without
<img width="1493" alt="image" src="https://github.com/argilla-io/argilla/assets/25269220/556e07c9-4d18-40ec-a431-b4237eed5557">

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.18
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.18

**Additional context**
N.A.

**Comment by damianpumar** [comment]
Hi @davidberenstein1957 from my point of view, this case is a new feature. The next Monday we'll talk about it. Thanks for report it mate!

**Comment by davidberenstein1957** [comment]
@Amelie-V, could you elaborate a bit on this choice?

**Comment by Amelie-V** [comment]
Sorry did not see your question before @davidberenstein1957 . It was something out of the scope because we tackled the sort first iteration from the metadata filter point of view. But thanks for spotting it, because we were about to forget it!
