### ISSUE TITLE
[BUG-python/deployment] subsequent calls to `/api/v1/metadata-properties/<id>/metrics` are slow

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4079]
**Describe the bug**
When loading the dataset there are subsequent call to the `/api/v1/metadata-properties/<id>/metrics`-endpoint where the server takes up to 6 seconds to respond, which is too slow to wait with a blank and unresponsive screen.

**Stacktrace and Code to create the bug**
N.A.

**Expected behavior**
I would expect this to be faster

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 1.18
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.18

**Additional context**
N.A.

**Comment by damianpumar** [comment]
I would like to talk about this, because i detected this little thing some days ago, and it affects the frontend performance.

**Comment by jfcalvo** [comment]
Not sure if this will improve the slowness but we can reduce the number of requests to only one creating a new `GET /api/v1/datasets/:dataset_id/metadata-properties/metrics` returning all the metrics at once.

What do you think @frascuchon ?

**Comment by frascuchon** [comment]
This is also related to the nature of the data. @davidberenstein1957, Which kind of properties are taking slower? how can we reproduce it?

**Comment by davidberenstein1957** [comment]
Hi @frascuchon , I was using the https://huggingface.co/datasets/argilla/text-descriptives-metadata/discussions dataset.

**Comment by damianpumar** [comment]
- Data fetching too slow, not only for metadata metrics.
- Spike new way to load the metrics.
- Understand why the metrics are too slow.
- Why the metadata-properties does not have the "metrics" why we need to consume other endpoint.
- Query params to load all metrics in same endpoint?
- Set metadata properties by default using "metrics" endpoint on initialization step from SDK ? 

@davidberenstein1957 @frascuchon @jfcalvo
