### ISSUE TITLE
[FEATURE] formatting_func for sentence similarity return list

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4088]
**Is your feature request related to a problem? Please describe.**
From PR #3955, Regarding the relation between the dataset for rag and the 'formatting func'. What it makes more sense to me is to use the FeedbackTemplate with the query and all  the retrieved documents, indicating, for instance, `number_of_retrievals=3`, and then after annotating in the ArgillaUI, when using the formatting_func, be able to make the matches: query-retrieved_document_1-label1, query-retrieved_document_2,-label2 query-retrieved_document_3-label3.

**Describe the solution you'd like**

```python
# Adding records to the dataset
records = [
    rg.FeedbackRecord(
        fields={"query": question, "retrieved_document_1": context[0], "retrieved_document_2": context[1], "retrieved_document_3": context[2]},
    )
    for question, answer, context in tqdm(zip(questions, contexts))
]

# Add records to the dataset
dataset_rag.add_records(records)

```
Then, we would annotate using the ArgillaUI and add the LabelQuestion. So, now to define the task we would have to use a `formatting_func` to create the appropriate data matching the query with each of the retrieved_documents and the corresponding label.

Using a list

```python
def formatting_func(sample):

    records = []

    for i in range(1, 4):
        record = {"sentence-1": sample["query"], "sentence-2": sample[f"retrieved_document_{i}"]}
        values = [resp["value"] for resp in sample[f"label{i}"]]
        label = int(values[0])
        record["label"] = label
        records.append(record)

    return records
   ```
Or yield

```python
def formatting_func(sample):
    for i in range(1, 4):
        record = {
            "sentence-1": sample["query"],
            "sentence-2": sample[f"retrieved_document_{i}"]
        }
        values = [resp["value"] for resp in sample[f"label{i}"]]
        label = int(values[0])
        record["label"] = label
        yield record
```
Even if we could return a dictionary of dictionaries.

**Describe alternatives you've considered**

**Additional context**

I also checked the code and, for instance, in test_model_card.py, they seem to use something similar to what I want in the case 'c', but it doesn't work:

```python
    def formatting_func(sample):
        labels = [
            annotation["value"]
            for annotation in sample["question-3"]
            if annotation["status"] == "submitted" and annotation["value"] is not None
        ]
        if labels:
            # Three cases for the tests: None, one tuple and yielding multiple tuples
            if labels[0] == "a":
                return None
            elif labels[0] == "b":
                return {"sentence-1": sample["text"], "sentence-2": sample["text"], "label": 1}
            elif labels[0] == "c":
                return [
                    {"sentence-1": sample["text"], "sentence-2": sample["text"], "label": 1},
                    {"sentence-1": sample["text"], "sentence-2": sample["text"], "label": 0},
                ]

    task = TrainingTask.for_sentence_similarity(formatting_func=formatting_func)

```

**Comment by davidberenstein1957** [comment]
@plaguss, I believe there is a small issue where we don't allow for returning iterable items within the formatting func implementation for the task `for_sentence_similarity`, I believe we do allow for this in other tasks but it is good to double check across all tasks.
