### ISSUE TITLE
[FEATURE] add `sort_by` to `ArgillaTrainer`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4096]
**Is your feature request related to a problem? Please describe.**
From this PR, it is possible to filter the dataset.

**Describe the solution you'd like**
I want to use this to filter on submitted records by default and allow for changing this via a `sort_by` arg during trainer definition and the `train` method.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
@plaguss Are you interested in having a shot at this too?

**Comment by plaguss** [comment]
Sure!
