### ISSUE TITLE
[FEATURE] Adapt filters area to new design (UI)

### ISSUE THREAD

**Issue by leiyre** [recognai/rubrix#4097]
**Is your feature request related to a problem? Please describe.**
The current filter area does not support the inclusion of more filters without breaking the design

**Describe the solution you'd like**
Make more flexible filter area

**Describe alternatives you've considered**
Make a collapsable filter area and include some styling to make the area lighter

- [x] Make area collapsable
- [x] Include new styles and sizes
- [x] Include filters in records column
- [x] Adapt layout to two columns

**Comment by jfcalvo** [comment]
@leiyre what is the status of this issue? We are working toward new release 1.19.0 and I would like to know if this could be part of that release.

**Comment by jfcalvo** [comment]
I asked @leiyre on slack and the issue it's already solved. Closing it.
