### ISSUE TITLE
[Python client] Display dataset URL after rb.log()

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#410]
Currently if a user logs some records using `rubrix.log` there's no indication of the dataset URL where the records have been logged.

The idea would be to print a INFO log message using the `_LOGGER` object with the url to the dataset, something like: `f"Your Rubrix dataset is available at {dataset_url}"`. In principle the info for dataset URL can be retrieved from `self._client`, together with `name` parameter (e.g., http://localhost:6900/dataset_name) and the log message should be added here https://github.com/recognai/rubrix/blob/ac7bb730483a2ceb30aa0b37444a406afe2fefd9/src/rubrix/client/__init__.py#L216.

**Comment by frascuchon** [comment]
Fixed in #609
