### ISSUE TITLE
[FEATURE] Align `FeedbackDataset.*_by_name` methods for better integration with conditional creation flows 

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4101]
**Is your feature request related to a problem? Please describe.**
The current behavior for the several `FeedbackDataset.*_by_name` method is to raise a `KeyError` when the entity is not found by name. Instead of that, we could just return a `None` value. This scenario could work when admin users want to control when a new entity must be created for an existing dataset:

#### What we need to do right now
```python
try:
   dataset.question_by_name("label_question")
except KeyError:
   dataset.add_question(rg.LabelQuestion(name="label_question",...)
```

**Describe the solution you'd like**

#### What I propose
```python
question = dataset.question_by_name("label_question")
if question is None:
   dataset.add_question(rg.LabelQuestion(name="label_question",...)
```
We're using questions as an example, but this can work with other entities.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by davidberenstein1957** [comment]
I agree. Will tackle this.
