### ISSUE TITLE
[DOCS] Update tutorials

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4127]
## Which page or section is this issue related to?

In the tutorials section, some tutorials have code that is outdated. For example: https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/labelling-feedback-setfit.html

Check all tutorials and update code.

**Comment by davidberenstein1957** [comment]
@nataliaElv could you potentially add some context here for @ignacioct.
@kursathalat also noticed one outdated tutorial.

**Comment by davidberenstein1957** [comment]
@ignacioct add these https://docs.argilla.io/en/latest/practical_guides/create_dataset.html#task-templates where applicable.

**Comment by ignacioct** [comment]
I've rerun all of the tutorials, and I've found several errors that I think would be nice to address as individual issues. Once they are all solved, we can close this issue. The issues are:

- [ ] https://github.com/argilla-io/argilla/issues/4151
- [ ] https://github.com/argilla-io/argilla/issues/4152
- [ ] https://github.com/argilla-io/argilla/issues/4153
- [ ] https://github.com/argilla-io/argilla/issues/4154
- [ ] https://github.com/argilla-io/argilla/issues/4155
