### ISSUE TITLE
[FEATURE] Add `ruff formatter` instead of `black`

### ISSUE THREAD

**Issue by plaguss** [recognai/rubrix#4139]
**Is your feature request related to a problem? Please describe.**
Ruff recently added a [formatter](https://docs.astral.sh/ruff/formatter/) of its own, it could be a good addition given we already use `ruff`.

**Describe the solution you'd like**
Run `ruff format` instead of `black` as part of `pre-commit` if it makes sense.

**Describe alternatives you've considered**

**Additional context**
There is a [FAQ](https://docs.astral.sh/ruff/faq/).

**Comment by davidberenstein1957** [comment]
@plaguss don't forget the labels ;)
