### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#414]
We want to further standardize our code format by including [pre-commit](https://pre-commit.com/) hooks. For now, we can just include the standard ones + black + isort.

**Comment by krishnajalan** [comment]
Can I take this issue? as Hacktoberfest?

**Comment by dvsrepo** [comment]
Of course, thanks a lot! Dont hesitate to ask questions

**Comment by krishnajalan** [comment]
Can you assign me this issue?

**Comment by dvsrepo** [comment]
Done

**Comment by krishnajalan** [comment]
created a PR

**Comment by krishnajalan** [comment]
hey, can you add `Hacktoberfest` to the project topic or `hacktoberfest-accepted` to the PR label
else this won't be counted in hacktobefest!

**Comment by dcfidalgo** [comment]
Closed by #426
