### ISSUE TITLE
[Python client] Add usage example to docstrings in record models 

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#415]
Include usage examples for:

Text2Text, TextClassification, TokenClassification records to be shown in the docs here:
https://rubrix.readthedocs.io/en/stable/reference/python_client.html#module-rubrix.client.models

You can see how it's done for the methods here for example:

https://github.com/recognai/rubrix/blob/02e6b752ed445acd076dcda7a910cfdb96bc05ba/src/rubrix/__init__.py#L99

The relevant file is src/client/models.py: https://github.com/recognai/rubrix/blob/master/src/rubrix/client/models.py

**Comment by issam9** [comment]
I'll work on this

**Comment by dvsrepo** [comment]
Thanks @issam9 !!
