### ISSUE TITLE
[DOCS] Add Changelog changes to Contributor Documentation

### ISSUE THREAD

**Issue by kursathalat** [recognai/rubrix#4150]
## Which page or section is this issue related to?
https://docs.argilla.io/en/latest/community/contributing.html

The contributor documentation lacks a part about how changes should be added to CHANGELOG.md file. It would be better for the contributors to have this information.

**Comment by davidberenstein1957** [comment]
@kursathalat , also add the comments about updating the branches and added the correct tags
