### ISSUE TITLE
[DOCS] Training LLM Mistral SFT crashes

### ISSUE THREAD

**Issue by ignacioct** [recognai/rubrix#4151]
Solve the problem of execution that this tutorial has at the end of the workflow.

**Comment by ignacioct** [comment]
The problem in this tutorial is the Mistral model does not fit inside the RAM. I'm trying to provide an offload folder to allow it to temporary save on disk.

**Comment by davidberenstein1957** [comment]
Feel free to skip, actually loading the model for this example.

**Comment by davidberenstein1957** [comment]
Alternatively, test with GPT2 or something.

**Comment by davidberenstein1957** [comment]
Did you try colab (pro)?

**Comment by ignacioct** [comment]
@davidberenstein1957 if I change to GPT2, it works. Should we close the issue?

**Comment by davidberenstein1957** [comment]
Yes, then the issue can be closed. Thanks @davidberenstein1957
