### ISSUE TITLE
[DOCS] Labelling Feedback Setfit Tutorial uses a wrong default workspace name

### ISSUE THREAD

**Issue by ignacioct** [recognai/rubrix#4152]
In [https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/labelling-feedback-setfit.html](https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/labelling-feedback-setfit.html), we are using by default the workspace name 'argilla', while the workspace name by default is 'admin'. Should we change it @davidberenstein1957 ?

**Comment by davidberenstein1957** [comment]
Yes, using "admin" is better if it doesn't work otherwise.
