### ISSUE TITLE
[DOCS] Revisit Argilla Installation Process

### ISSUE THREAD

**Issue by ignacioct** [recognai/rubrix#4156]
To-Do

- [ ] Anaconda/Pip environment differentiation, similar to the other dev-related installation. Maybe tab-depth structure.
- [x] Add environment in [https://docs.argilla.io/en/latest/community/developer_docs.html#install-with-pip](https://docs.argilla.io/en/latest/community/developer_docs.html#install-with-pip)
- [x] #4268
- [x] all command w.r.t. the python -m argilla server database have moved to python -m argilla database
**No mention of either in the docs.**
- [x] maybe https://docs.argilla.io/en/latest/community/developer_docs.html#create-the-default-user is better located here https://docs.argilla.io/en/latest/community/developer_docs.html#relational-database-and-migration
**I've duplicated, as if somebody skips the database installation, they are also going to need to create the user for server. If it's redundant I can remove it.**
- [x] #4269
- [x] make the difference between the documentation and development more explicit.
- [x] #4191 
- [x] Write that we only need the first part for building doc, but for the main product we need all

Structure
<img width="141" alt="Screenshot 2023-11-17 at 08 53 36" src="https://github.com/argilla-io/argilla/assets/56955040/75cc18f1-5f09-49b7-8fa1-6c90cc3e6647">
:

**Comment by davidberenstein1957** [comment]
This would be great. I think the documentation can be another `anaconda`/`pip` environment and we should provide 2 options, similar to the other dev-related installation. Similarly, we can potentially create a better tab-depth to differentiate from development and documentation.

**Comment by davidberenstein1957** [comment]
@ignacioct , could you also add something about creating an environment [here](https://docs.argilla.io/en/latest/community/developer_docs.html#install-with-pip)? Similar to the one in the documentation section proposed in this issue.

`python -m venv .env`
`source .env/bin/activate`

**Comment by davidberenstein1957** [comment]
Also, I noticed we should be able to run https://docs.argilla.io/en/latest/community/developer_docs.html#set-up-the-server

`python -m argilla server start`

**Comment by davidberenstein1957** [comment]
Additionally, all command w.r.t. the `python -m argilla server database` have moved to `python -m argilla database`

**Comment by ignacioct** [comment]
@davidberenstein1957 I've started this by analyzing what was wrong in the first time that I installed the environment, and I'm still unable to run the documentation only by installing the doc requirements. Therefore, I've started writing an enviroment_docs.yml to simplify the installation process and do it also with conda (afterwards we can specify the pip environment). The two main points are:

- sphinx-autobuild must be downloaded, in the dev environment only sphinx-build is contemplated. I think that is one of the problems that I have, that in order to autobuild, you need packages from both the documentation requirements and the developer's environment. 
- In the documentation requirements we use sphinx 6.0, but in the dev environment, 4.5. Should we go for 6.0?

We can discuss these details on Monday.

**Comment by davidberenstein1957** [comment]
Let's discuss on Monday sphinx 6.0 is better
we stopped using anaconda to reduce build times of readthedocs but having both would be great.

**Comment by davidberenstein1957** [comment]
@ignacioct did you also notice my comments above?

**Comment by ignacioct** [comment]
> @ignacioct did you also notice my comments above?

Yes :) I think the tab division can be really nice, and I have taken into account the changes in commands and adding the environment. Do you prefer separate issues or all in one?

**Comment by davidberenstein1957** [comment]
@sdiazlor suggested also looking into command differences for windows/mac/linux

**Comment by davidberenstein1957** [comment]
Also, the frontend files don't seem to be built for windows. So @sdiazlor might have some additional updates.

**Comment by sdiazlor** [comment]
Regarding the connection to the frontend, it would be nice to check the installation of the latest versions of npm and node

**Comment by davidberenstein1957** [comment]
source bin activate, `which pip`

**Comment by davidberenstein1957** [comment]
source .env/bin/activate

**Comment by ignacioct** [comment]
Haven't been able to fix it @davidberenstein1957 , no matter what I do, auto-build is not found. Could you give a try to the current installation process and see if it's the same for you or is my computer being weird? If not I think I will try to clean install conda

**Comment by davidberenstein1957** [comment]
@ignacioct, Just including a working `anaconda` is fine for now. Can you still outline the pip install with creating an env etc and include that for the non-documentation dev environment too? I will have a look at this later. Could you already process the remainder of the comments mentioned above and update the `.md`file too?

**Comment by ignacioct** [comment]
@davidberenstein1957 I think we can review the content, and afterwards iterate over the structure. I've created a draft PR so you can see my changes :) https://github.com/argilla-io/argilla/pull/4261
