### ISSUE TITLE
[FEATURE] add `metadata_properties` to the `__repr__` method of the `FeedbackDataset` and `RemoteFeedbackDataset`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4190]
**Is your feature request related to a problem? Please describe.**
As of Argilla 1.18, we have added support for `metadata_properties` but these have not been added to the `__repr__` methods of the  `FeedbackDataset` and `RemoteFeedbackDataset`.

**Describe the solution you'd like**
I would expect them to be added to the `__repr__`-methods.
- `argilla/client/feedback/dataset/remote/dataset.py`
- `argilla/client/feedback/dataset/local/dataset.py`

**Describe alternatives you've considered**
Not seeing the metadata after initialization.

**Additional context**
N.A.

**Comment by subhajit20** [comment]
hey @davidberenstein1957 , can you help out on how I can get those properties as mentioned in the description?

**Comment by subhajit20** [comment]
hey @davidberenstein1957 I have made pr.
Please check that and let me know if further changes needed.

**Comment by davidberenstein1957** [comment]
Hi @subhajit20, thanks a lot for this contribution. I assigned you to the issue and thanks for the PR, I will have a look later today.

**Comment by subhajit20** [comment]
Okay 😁
