### ISSUE TITLE
[DOCS] Update button Deploy on HF Spaces url

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4193]
## Which page or section is this issue related to?

It seems HF has changed the query param for creating new spaces, so our button Deploy on HF Spaces doesn't work.
Now is https://huggingface.co/new-space?template=Argilla

**Comment by davidberenstein1957** [comment]
Note that this should also be fixed in the Argilla Readme https://github.com/argilla-io/argilla

**Comment by davidberenstein1957** [comment]
And that we should contact HF to fix that here https://huggingface.co/docs/hub/spaces-sdks-docker-argilla

**Comment by davidberenstein1957** [comment]
and it should be fixed here https://argilla.io/blog/launching-argilla-huggingface-hub/

**Comment by davidberenstein1957** [comment]
I will contact HF for a PR and fix the one on our website

**Comment by davidberenstein1957** [comment]
@sdiazlor, could you also update these references to private space deployments? https://www.youtube.com/watch?v=rqv4AMmuMbM

**Comment by sdiazlor** [comment]
> @sdiazlor, could you also update these references to private space deployments? https://www.youtube.com/watch?v=rqv4AMmuMbM

@davidberenstein1957 okay, yes, I'll update them too

**Comment by davidberenstein1957** [comment]
Discussed with HF and we are waiting for their response.

**Comment by davidberenstein1957** [comment]
Handled on the side of HF
