### ISSUE TITLE
[DOCS] create a tutorial of using Argilla with `llama-index`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4209]
## Which page or section is this issue related to?
@alvarobartt, perhaps you would like to work on exploring this during the coming weeks.

**Comment by alvarobartt** [comment]
Sure, thanks for proposing it @davidberenstein1957! Let's discuss internally and prepare something 👍🏻

**Comment by davidberenstein1957** [comment]
https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/fine-tuning-openai-rag-feedback.html

**Comment by davidberenstein1957** [comment]
@alvarobartt , I @ignacioct  to tackle this because he has a bit more time and enjoys creating and sharing these kinds of contents.
