### ISSUE TITLE
[BUG-UI/UX] Unable To Change Labels

### ISSUE THREAD

**Issue by maryc-sullivan** [recognai/rubrix#4213]
**Describe the bug**

For previously validated records, if you change the record label and then refresh your page the change is not saved and original label is still attached to record. 

**To Reproduce**
1. Select Record
2. Click Annotate As 
3. Select Different Annotation Label
4. Select Refresh
5. Error

OR 

1. Change label beneath record text
2. Select refresh
3. Error

**Expected behavior**
Label actually changes 

**Screenshots**

https://github.com/argilla-io/argilla/assets/82959849/27ce9c52-f985-4e82-a6cc-610c676e88a0

**Environment (please complete the following information):**
Most up to date docker compose deployment
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]: Brave
 - Argilla Version 1.19.0
 - ElasticSearch Version [e.g. 8.5.3]: 
 - Docker Image (optional) [e.g. argilla v1.19.0]:

**Additional context**
These records were loaded into the dataset as already labelled records.

**Comment by leiyre** [comment]
Hi @maryc-sullivan! Thank you very much for the feedback. 
In which task is the problem happening? Is it a multiple label annotation? It would be super helpful to have a video or screenshot. Thanks again!

**Comment by maryc-sullivan** [comment]
Updated comment to include screenshot. It occurs with text classification records and it is not a multiple-label annotation. 

Worth mentioning -- I do not have this issue for a different dataset that was loaded with unvalidated/unlabelled text classification records. This seems to occur only for a dataset that is loaded with already labelled text classification records.

**Comment by leiyre** [comment]
Hi @maryc-sullivan, thanks for the info. Looking at the UI, it's a pretty old version of Argilla, you could try upgrading to a newer version to see if the error still occurs.

**Comment by maryc-sullivan** [comment]
Error appears to be resolved -- just took a minute for the UI to update from the newest version. Thanks for your help.
