### ISSUE TITLE
[Server] Add tests for `rubrix.server.security`

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#423]
We are still missing tests for our `LocalAuth` classes.

**Comment by AlexJakubko** [comment]
Hi can I take this issue?

**Comment by dvsrepo** [comment]
Of course!

**Comment by dvsrepo** [comment]
Hi @AlexJakubko , did you manage to take a look at this? Let us know if you need support

**Comment by AlexJakubko** [comment]
Hi @dvsrepo , i managed to create tests for LocalAuth classes. I will make a pull request today and you can check it out and give me a feedback. I'm not really sure if I used right method so if there be any problems I`m looking forward to fix them.

**Comment by AlexJakubko** [comment]
#593

**Comment by frascuchon** [comment]
fixed in #593
