### ISSUE TITLE
[FEATURE] create `llama-index` observability and tracability integration

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4236]
**Is your feature request related to a problem? Please describe.**
LlamaIndex has a number of community integrations, from vector stores, to prompt trackers, tracers, and more!
https://docs.llamaindex.ai/en/stable/community/integrations.html#observability-tracing-evaluation

**Describe the solution you'd like**
I would like to see a similar traceability integration as the one we've got [with LangChain and the one we've outlined for Haystack](https://github.com/argilla-io/argilla/issues/4235). This should be setup as a direct PR for `llama-index` but can be coordinated with us for best usability.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by vasudevanubrolu** [comment]
Hi @davidberenstein1957 I am very much interested in this and would like to start working on it from this week

**Comment by davidberenstein1957** [comment]
Great!
