### ISSUE TITLE
Devise workflow to test the tutorials via a github action

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#424]
The idea here is to devise a workflow to test our [tutorials](https://rubrix.readthedocs.io/en/stable/) in a semi-automatic way. Ideally, we have a workflow that we can launch manually and let's say every two weeks or so, to test our tutorials. Maybe we can use [nbmake](https://github.com/treebeardtech/nbmake) for this and follow this [blogpost](https://semaphoreci.com/blog/test-jupyter-notebooks-with-pytest-and-nbmake). The tricky part is that for some tutorials we need to change/add/delete a few cells to be able to run them in an automated way ...

**Comment by krishnajalan** [comment]
can you elaborate on `change/add/delete cells to run`?

**Comment by dcfidalgo** [comment]
Sure! Let's take for example the [active learning tutorial](https://rubrix.readthedocs.io/en/stable/tutorials/05-active_learning.html). In the [annotation step](https://rubrix.readthedocs.io/en/stable/tutorials/05-active_learning.html#1.-Annotate-samples) the notebook expects a few examples to be annotated by the user via Rubrix. To test this tutorial in an automated way, I think here the best way would be to add a cell before the [`rb.load` call](https://rubrix.readthedocs.io/en/stable/tutorials/05-active_learning.html#2.-Teach-the-learner), where we upload the same records, but with annotations included.

@krishnajalan I hope this example illustrates better the "tricky part" I was talking about above. I guess each one of the tutorials has these parts, so we should go one by one.

**Comment by dcfidalgo** [comment]
Maybe we could start devising a GitHub action with [this tutorial](https://rubrix.readthedocs.io/en/stable/tutorials/07-find_label_errors.html) which does not require any modification. And with the GitHub action at hand, tackle the more challenging tutorials @krishnajalan What do you think?

**Comment by alex-remedios** [comment]
hey @dcfidalgo, I maintain nbmake -- would it work if you included the test cell in git, then use nbsphinx to [hide it](https://nbsphinx.readthedocs.io/en/0.8.7/hidden-cells.html) when you build html?

**Comment by dcfidalgo** [comment]
Thanks @alex-treebeard for the tip! This could definitely work! I am not sure if it solves all our use cases, but for the tutorial described above it should work. Is it possible in nbmake to skip certain cells when testing?

**Comment by alex-remedios** [comment]
AFAIK it is possible to flag a cell as allowing errors (undocumented feature of nbclient under the hood)

https://github.com/jupyter/nbclient/issues/36

I don't think we currently support more than that.

**Comment by frascuchon** [comment]
Can we close this issue, @dcfidalgo ?

**Comment by dcfidalgo** [comment]
@krishnajalan Are you still considering this? If not, I will assign myself to it and try to provide a PR this week.

**Comment by krishnajalan** [comment]
sorry, for the late reply.
I tried working on this issue but was not quite successful my actions/builds are failing.

**Comment by dcfidalgo** [comment]
ok, thanks a lot for trying anyway!! If you want to continue to work on this issue and need help, just let me know. I will assign myself to it for now.
