### ISSUE TITLE
Query string DSL for advanced queries

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#4240]
### Summary
_Summarize the functionality or added value of the feature:_

Enable a way for power users to do complex queries to get a very specific subset of a dataset. 

### User needs
_Set out the problem to be solved and the preferences or needs of users:_

- Perform actions on specific subsets of a dataset with a complex combination of conditions that may include: text, status, responses, suggestions, etc.

### Proposed solution
_Outline the initial solution to the problems or needs of the user:_

- A DSL for string queries.

### Further context
_Add any additional information or details needed to understand the feature:_

**Comment by nataliaElv** [comment]
Duplicate. Closed in favor of: https://github.com/argilla-io/roadmap/issues/20
