### ISSUE TITLE
TokenClassification Question

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#4246]
### Summary
_Summarize the functionality or added value of the feature:_

A new question for the Feedback Datasets, where it is possible to draw spans to highlight fragments of text while applying a label.

### User needs
_Set out the problem to be solved and the preferences or needs of users:_

- Respond to Token Classification and Text Classification tasks within the same dataset.
- In some projects, users need overlapping spans.

### Proposed solution
_Outline the initial solution to the problems or needs of the user:_

- Add a Token or Spans question to Feedback Datasets.

### Further context
_Add any additional information or details needed to understand the feature:_

**Comment by nataliaElv** [comment]
Duplicate. Closed in favor of: https://github.com/argilla-io/roadmap/issues/19
