### ISSUE TITLE
Dataset creation and configuration from the UI

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#4247]
### Summary
_Summarize the functionality or added value of the feature:_

Dataset creation menu in the UI.

### User needs
_Set out the problem to be solved and the preferences or needs of users:_

Configuration of datasets from the SDK can become cumbersome. The high level of customization of the Feedback datasets make the process in the SDK long and prone to error due to the lack of visualization.

We want to provide a way for users to create and configure datasets from the UI so that they can visualize the configuration as they are doing it.

### Proposed solution
_Outline the initial solution to the problems or needs of the user:_

- A dataset creation menu in the UI that allows to create and configure a new Feedback dataset.

### Further context
_Add any additional information or details needed to understand the feature:_

**Comment by nataliaElv** [comment]
Duplicate. Closed in favor of: https://github.com/argilla-io/roadmap/issues/21
