### ISSUE TITLE
[DOCS] fix on reference to HF Spaces

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4255]
## Which page or section is this issue related to?

It looks like this did not rendered properly in ipyb files
![Captura](https://github.com/argilla-io/argilla/assets/127759186/5d6d2ab2-5f00-4a89-acc7-47a823ba7fbb)
Two branches will be created, one in main to fix the existing notebooks and the other in develop to fix the last two uploaded notebooks

**Comment by davidberenstein1957** [comment]
Good catch @sdiazlor
