### ISSUE TITLE
[REFACTOR] align structure and usage of `unification` with `metrics`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4263]
**Is your feature request related to a problem? Please describe.**
We aim to introduce the https://github.com/argilla-io/argilla/pull/4175, but ideally this should be aligned as much as possible with our existing `unification`

**Describe the solution you'd like**
N.A.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by plaguss** [comment]
Closed per #4271
