### ISSUE TITLE
Add python -m argilla server start in Set up the server

### ISSUE THREAD

**Issue by ignacioct** [recognai/rubrix#4268]
@davidberenstein1957 should I add it as an alternative to the Docker installation, in two differents headings? https://docs.argilla.io/en/latest/community/developer_docs.html#set-up-the-server

It would be something like this:

```
## Set up the Server

Before running the Argilla server, it is recommended to [build the frontend files](#build-frontend-static-files) to be able to access the UI on your local host.

### Set up locally

python -m argilla server start

### Set up with Docker

Then, to run Argilla backend, you will need an ElasticSearch instance up and running for the time being. You can get one running using Docker with the following command:
sh
docker run -d --name elasticsearch-for-argilla -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:8.5.3
```

If I should place it in any other place, or it is not an alternative, please let me know :)

**Comment by davidberenstein1957** [comment]
https://docs.argilla.io/en/latest/reference/cli.html#server

**Comment by davidberenstein1957** [comment]
move https://docs.argilla.io/en/latest/community/developer_docs.html#create-the-default-user to setup the database after running migrations

**Comment by davidberenstein1957** [comment]
https://docs.argilla.io/en/latest/community/developer_docs.html#set-up-the-server reference that we need the vector database up and running
