### ISSUE TITLE
Add monitoring examples with FastAPI: Hugging Face and spaCy

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#427]
The idea would be to add a guide (as a Jupyter Notebook) to be included under docs/guides. This Jupyter notebook will showcase the `RubrixHTTPMiddleware` for monitoring the predictions of a FastAPI inference endpoint. Here is the example with Hugging Face + FastAPI:

```python
from fastapi import FastAPI
from typing import List
from transformers import pipeline
from rubrix.client.asgi import RubrixLogHTTPMiddleware

classifier = pipeline("sentiment-analysis", return_all_scores=True)

app = FastAPI()

# define the middleware for logging predictions into a Rubrix Dataset
app.add_middleware(
    RubrixLogHTTPMiddleware,
    api_endpoint="/predict",
    dataset="monitoring_dataset_v1",
    # you could post-process the predict output with a custom record_mapper function
    # record_mapper=custom_text_classification_mapper,
)

# prediction endpoint
@app.post("/predict")
def predict_batch(batch: List[str]):
    predictions = classifier(batch)
    return [
        {
            "labels": [p["label"] for p in prediction],
            "probabilities": [p["score"] for p in prediction],
        }
        for prediction in predictions
    ]
```

The steps would be to:

1. Create a notebook and include the above example
2. Add an example with a pre-trained  transformer TokenClassifier (for example: https://huggingface.co/dslim/bert-base-NER)
3. Add an example with a spaCy NER pipeline.
4. (Optionally) Include an example dashboard with Kibana (screenshots, gif or video)
5. (Optionally) Include an example with `ray serve`

**Comment by Aymane11** [comment]
Hello @dvsrepo , can I work on this issue?

**Comment by dvsrepo** [comment]
Of course! I'd be happy to guide you through. I'll assign it to you

**Comment by prashant-ssharma** [comment]
@dvsrepo Hii, I want to contribute into open source project related to NLP but I started my journey in ml recently. I know some basic ml algorithm like supervised and unsupervised, how guassian work etc.I don't have much experience in terms of project but really want to contribute any of the project.

**Comment by dvsrepo** [comment]
> @dvsrepo Hii, I want to contribute into open source project related to NLP but I started my journey in ml recently. I know some basic ml algorithm like supervised and unsupervised, how guassian work etc.I don't have much experience in terms of project but really want to contribute any of the project.

Hi @MrSharma003 , welcome! Do you have basic knowledge of Python? Take a look at some of the open issues (with the tag good first issue, and maybe the documentation one) that don't have anyone assigned, and if you find anything interesting we can talk there to resolve doubts and how to approach. Also we are open to suggestions, as Rubrix can be used as an annotation tool you can also think about ideas for training a text classifier for a specific use case and do the annotation + training part.

**Comment by Aymane11** [comment]
@dvsrepo can you please take a look on the [notebook](https://github.com/Aymane11/rubrix/commit/9046756a56ce024493a63dbb0c87b05cb7f1ff3b) i made and tell me if it needs any changes ?

**Comment by dvsrepo** [comment]
Hi @Aymane11 it's looking great! Thanks a lot.

Would like to include also an example for spaCy NER entities or HuggingFace NER? Otherwise is fine like this and we could tackle this in another issue.

I'll add some editorial things in the PR

**Comment by Aymane11** [comment]
Hello @dvsrepo , I'll try to add them, should I include them in the same notebook or in a different one ?
Thank you.

**Comment by dvsrepo** [comment]
In the same notebook is perfect! Let me know if you jump into any issues!

**Comment by Aymane11** [comment]
Hello @dvsrepo , concerning spaCy's NER, what can I log to Rubrix, since their pipeline outputs entities with their labels only with no probability ?

**Comment by dvsrepo** [comment]
Hi!

In principle, adding the scores/probs for entities is optional. You should
only need the spans and the labels. Here are some examples:

https://github.com/recognai/rubrix/blob/c66649e9028b83a1ea7edd2c1cb0fd30a8b15b8f/tests/client/test_asgi.py#L96


https://rubrix.readthedocs.io/en/stable/tutorials/02-spacy.html#Using-a-smaller-but-more-efficient-pipeline

If you encounter issues do not hesitate to write here and we will take a
look.

**Comment by Aymane11** [comment]
Hi,
I'm facing an issue, the results from both endpoints are returned but not logged into Rubrix; here's the code I'm using:

```python
from typing import List

import spacy
from fastapi import FastAPI
from rubrix.client.asgi import RubrixLogHTTPMiddleware
from transformers import pipeline

from app1 import app_transformers
from app2 import app_spacy

nlp = spacy.load("en_core_web_sm")
classifier = pipeline("sentiment-analysis", return_all_scores=True)

app = FastAPI()

@app.get("/")
def root():
    return {"message": "alive"}

app_spacy = FastAPI()
app_transformers = FastAPI()

# prediction endpoint using spacy pipeline
@app_spacy.post("/spacy")
def predict_spacy(batch: List[str]):
    predictions = []
    for text in batch:
        doc = nlp(text)  # spaCy Doc creation
        # Entity annotations
        entities = [
            {"label": ent.label_, "start": ent.start_char, "end": ent.end_char}
            for ent in doc.ents
        ]

        prediction = {
            "text": text,
            "entities": entities,
        }
        predictions.append(prediction)
    return predictions

# prediction endpoint using transformers pipeline
@app_transformers.post("/transformers")
def predict_transformers(batch: List[str]):
    predictions = classifier(batch)
    return [
        {
            "labels": [p["label"] for p in prediction],
            "probabilities": [p["score"] for p in prediction],
        }
        for prediction in predictions
    ]


app_spacy.add_middleware(
    RubrixLogHTTPMiddleware,
    api_endpoint="/spacy",
    dataset="monitoring_spacy",
)

app_transformers.add_middleware(
    RubrixLogHTTPMiddleware,
    api_endpoint="/transformers",
    dataset="monitoring_transformers",
    # you could post-process the predict output with a custom record_mapper function
    # record_mapper=custom_text_classification_mapper,
)


app.mount("/transformers", app_transformers)
app.mount("/spacy", app_spacy)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="127.0.0.1", port=5000)
```

**Comment by frascuchon** [comment]
Hi @Aymane11 

For token classification you should include the `record_mapper` function. As default, the `RubrixLogHTTPMiddleware` take as nlp task a basic text-classification.

In your case, you should define your own token_classification mapper function, Based on [provided by rubrix](https://github.com/recognai/rubrix/blob/master/src/rubrix/client/asgi.py#L35): 

```python
spaces_regex = re.compile(r"\s+")
def token_classification_mapper(inputs, outputs):
    text = inputs
    return TokenClassificationRecord(
        text=text,
        tokens=spaces_regex.split(text),
        prediction=[
            (entity["label"], entity["start"], entity["end"])
            for entity in (
                outputs.get("entities") if isinstance(outputs, dict) else outputs
            )
        ],
        event_timestamp=datetime.datetime.now(),
    )
```

and then, configure for spacy endpoint miiddleware:

```python
...
app_spacy.add_middleware(
    RubrixLogHTTPMiddleware,
    api_endpoint="/spacy",
    dataset="monitoring_spacy",
    record_mapper= token_classification_mapper,
)
```
I hope this can help you

**Comment by Aymane11** [comment]
Hello @frascuchon ,
This is the updated code, but still doesn't work for both :

`helper.py`
```python
import re
import datetime

from rubrix.client.models import TokenClassificationRecord

def custom_mapper(inputs, outputs):
	spaces_regex = re.compile(r"\s+")
	text = inputs
	return TokenClassificationRecord(
		text=text,
		tokens=spaces_regex.split(text),
		prediction=[
			(entity["label"], entity["start"], entity["end"])
			for entity in (
				outputs.get("entities") if isinstance(outputs, dict) else outputs
			)
		],
		event_timestamp=datetime.datetime.now(),
	)

```

`main.py`
```python
from typing import List

import spacy
from fastapi import FastAPI
from rubrix.client.asgi import RubrixLogHTTPMiddleware
from transformers import pipeline
from helper import custom_mapper

nlp = spacy.load("en_core_web_sm")
classifier = pipeline("sentiment-analysis", return_all_scores=True)

app = FastAPI()

@app.get("/")
def root():
    return {"message": "alive"}

app_spacy = FastAPI()
app_transformers = FastAPI()

# prediction endpoint using spacy pipeline
@app_spacy.post("/spacy")
def predict_spacy(batch: List[str]):
    predictions = []
    for text in batch:
        doc = nlp(text)  # spaCy Doc creation
        # Entity annotations
        entities = [
            {"label": ent.label_, "start": ent.start_char, "end": ent.end_char}
            for ent in doc.ents
        ]

        prediction = {
            "text": text,
            "entities": entities,
        }
        predictions.append(prediction)
    return predictions

# prediction endpoint using transformers pipeline
@app_transformers.post("/transformers")
def predict_transformers(batch: List[str]):
    predictions = classifier(batch)
    return [
        {
            "labels": [p["label"] for p in prediction],
            "probabilities": [p["score"] for p in prediction],
        }
        for prediction in predictions
    ]


app_spacy.add_middleware(
    RubrixLogHTTPMiddleware,
    api_endpoint="/spacy",
    dataset="monitoring_spacy",
    records_mapper=custom_mapper
)

app_transformers.add_middleware(
    RubrixLogHTTPMiddleware,
    api_endpoint="/transformers",
    dataset="monitoring_transformers",
)


app.mount("/transformers", app_transformers)
app.mount("/spacy", app_spacy)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="127.0.0.1", port=5000)
```

Can you please take a look and tell me what's the issue?
Note: the code doesn't work even if the dataset exists.

**Comment by frascuchon** [comment]
Hi @Aymane11 

I've been checking your configuration and I see that the api_endpoint for both app middleware is wrong.

You must set the api endpoint as the complete api endpoint path. For example, your spacy app predict endpoint (`/spacy`) will be mounted under path `/spacy`, so the real api endpoint for spacy prediction will be `/spacy/spacy` instead of `/spacy`

You could change the local predict endpoints to `/` and then configure you middleware as `/spacy/` and `/transformers/`

```python
@app_spacy.post("/")
def predict_spacy(batch: List[str]):
...

@app_transformers.post("/")
...


app.mount("/transformers/", app_transformers)
app.mount("/spacy/", app_spacy)
```

Please, let me know if this works for you.

**Comment by Aymane11** [comment]
@frascuchon @dvsrepo can you please check [this PR](https://github.com/recognai/rubrix/pull/532)

**Comment by frascuchon** [comment]
Closed by #532

**Comment by dvsrepo** [comment]
Hi @Aymane11, thanks so much for your contribution! We'd like to include the author names in the tutorials, would you be ok with including your name, twitter and github handle in the tutorial? We'll include this in our docs soon.

**Comment by Aymane11** [comment]
@dvsrepo absolutely, this is my Twitter handle : [_Enamya](https://twitter.com/_Enamya)

**Comment by dvsrepo** [comment]
Great Aymane, we'll do this before the next release, thanks for your work!
