### ISSUE TITLE
[FEATURE] remove the `api_key` from the `User`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4272]
**Is your feature request related to a problem? Please describe.**
Currently we return the `User` profile with all information, including the `api_key`, but without the `password`. I do get that we might want to do this for privacy purposes but because we also return the `api_key` I would say returning the `password` should be possible for owners.

**Describe the solution you'd like**
`User.password`

**Describe alternatives you've considered**
Recreate the user after forgetting the password.

**Additional context**
N.A.

**Comment by alvarobartt** [comment]
IMO that compromises a bit user's privacy, since not even owners should have access to their users' passwords, WDYT @gabrielmbmb?

**Comment by davidberenstein1957** [comment]
I think so too, but given that we do also return the `api_key` and the owner is the only one who can create users (along with their password) it is a bit weird to not show the passwords IMO.

**Comment by davidberenstein1957** [comment]
This should align with the authentication sign-in signup.
