### ISSUE TITLE
[FEATURE] Add additional annotator agreement metrics

### ISSUE THREAD

**Issue by plaguss** [recognai/rubrix#4273]
**Is your feature request related to a problem? Please describe.**
I would like to see more agreement metrics for the `FeedbackDataset`.

**Describe the solution you'd like**
 We can add the metrics of [`nltk.metrics.agrement`](https://www.nltk.org/_modules/nltk/metrics/agreement.html) initially (the ones in [*Inter-Coder Agreement for
Computational Linguistics*](https://ict.usc.edu/pubs/Inter-Coder%20Agreement%20for%20Computational%20Linguistics.pdf)).

**Describe alternatives you've considered**
Don't add more metrics for the moment.

**Additional context**
It should be added after the metrics module is merged. More information can be found [here](https://github.com/argilla-io/argilla/pull/4175#discussion_r1398367823).

**Comment by kursathalat** [comment]
I think the basic ones to add might be: (all of which are included in nltk.metrics.agrement)
- Cohen's Kappa (for two annotators) (https://en.wikipedia.org/wiki/Cohen%27s_kappa)
    - Fleiss' Kappa (for multiple annotators) (https://en.wikipedia.org/wiki/Fleiss%27_kappa)
    - Weighted Kappa (for labels that are ordinal) (https://datatab.net/tutorial/weighted-cohens-kappa)
- Bennet, Albert and Goldstein's S (https://en.wikipedia.org/wiki/Bennett,_Alpert_and_Goldstein%27s_S)
- Scott's Pi (https://en.wikipedia.org/wiki/Scott%27s_Pi)

Also, I could not make the `KrippendorfAlpha` in the module work, it throws some error. If there is no issue yet regarding it, I can open one.

**Comment by plaguss** [comment]
Hi @kursathalat thanks for reviewing this! Please talk to @davidberenstein1957 to see the status of the metrics module.
