### ISSUE TITLE
[Server]: Limit search pagination to 10000 

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#429]
See performance issues [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html)

The idea is just set a validation rule for [`PaginationParams.from`](https://github.com/recognai/rubrix/blob/master/src/rubrix/server/tasks/commons/api/model.py#L86) attribute

**Comment by krishnajalan** [comment]
can I pick this issue?

**Comment by dvsrepo** [comment]
Definitely! Don't hesitate to ask questions!
