### ISSUE TITLE
[FEATURE] User-friendly error messages in UI

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4293]
**Is your feature request related to a problem? Please describe.**

The `error: undefined` message in the UI is not very descriptive and it is difficult to know what is the user action that triggered it. This makes it difficult to know how to solve the error and support the user.

**Describe the solution you'd like**

Avoid `error: undefined` and use more descriptive error messages in the UI.

**Describe alternatives you've considered**

**Additional context**
@damianpumar  mentioned something in a meeting about creating a dictionary of errors.

**Comment by damianpumar** [comment]
This issue was already solved here https://github.com/argilla-io/argilla/pull/4362
