### ISSUE TITLE
[FEATURE] interpret metadata entries with `None`/`nan` as non-existent instead of returning an error

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4300]
**Is your feature request related to a problem? Please describe.**
At the moment I've seen some users struggle with this because it is not very clear we should remove the entire key.

**Describe the solution you'd like**
I think we can do something like that. 
```python
filtered_dict = {key: value for key, value in my_dict.items() if value is not None and not (isinstance(value, float) and math.isnan(value))}
```

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
This is already working as confirmed in #4083

**Comment by sdiazlor** [comment]
It looks like it works for the Nan values, but not for the None values
