### ISSUE TITLE
[FEATURE] Add new dataset to help with metrics documentation

### ISSUE THREAD

**Issue by plaguss** [recognai/rubrix#4301]
**Is your feature request related to a problem? Please describe.**
The new metrics module lacks some good examples.

**Describe the solution you'd like**
Create a `FeedbakDataset` for [go_emotions](https://huggingface.co/datasets/go_emotions) so that we can use it directly from argilla to compute metrics for the annotators, and on the unified annotations.

**Describe alternatives you've considered**

**Additional context**

**Comment by kursathalat** [comment]
We already have a similar dataset in [go_emotions_raw](https://huggingface.co/datasets/argilla/go_emotions_raw). It has both the responses and suggestions for each text item. Not sure if it is the one you want, or would you like to have something not featured in this one?

**Comment by plaguss** [comment]
Sorry, this can be closed. I added the dataset but forgot to close this, thanks @kursathalat !
