### ISSUE TITLE
[BUG-python/deployment] Argilla Quickstart supports only up to 1000 datasets by default

### ISSUE THREAD

**Issue by mrshu** [recognai/rubrix#4304]
**Describe the bug**

When trying out Argilla Quickstart Docker Container (https://docs.argilla.io/en/latest/getting_started/quickstart_installation.html#%F0%9F%90%B3-Argilla-Quickstart-with-Docker), I've ran into the following issue when creating a significant number of `FeedbackDataset`s (for a significant number of annotators):

```
Exception: Failed while publishing the `FeedbackDataset` in Argilla with exception: Argilla server returned an 
error with http status: 500
Error details: [{'code': 'argilla.api.errors::GenericServerError', 'params': {'type': 
'opensearchpy.exceptions.RequestError', 'message': 'RequestError(400, 
\'{"error":{"root_cause":[{"type":"validation_exception","reason":"Validation Failed: 1: this action would add [1] 
shards, but this cluster currently has [1000]/[1000] maximum normal shards 
open;"}],"type":"validation_exception","reason":"Validation Failed: 1: this action would add [1] shards, but this 
cluster currently has [1000]/[1000] maximum normal shards open;"},"status":400}\')'}}]
```

In essence, it seems that the default settings of ElasticSearch that's used inside the container will only support up to 1000 datasets. This can then be changed by updating the `cluster.max_shards_per_node` setting (e.g. https://github.com/wazuh/wazuh-puppet/issues/222#issuecomment-594543951) from inside the container (which is a fun endeavor on its own, but it is at least somehow doable).

**Expected behavior**

It would be great to have this mentioned in the docs somewhere. Of course, having more than 1000 datasets in the "quickstart" container is certainly pushing it, but it is certainly not totally outside of the real of possibility.

**Comment by mrshu** [comment]
Note that this might be intended to work this way and I do not expect it to be changed :slightly_smiling_face:

**Comment by mrshu** [comment]
I suppose this can be closed, if this particular case ends up being an outlier.

I am also happy to prepare a quick PR that adds a note on this to the docs for sure!

**Comment by jfcalvo** [comment]
@mrshu thanks for reporting it. I think a note in the docs about this and how to change ElasticSearch/OpenSearch settings to support more datasets can be useful.

Please feel free to reopen the issue and create a PR if you feel the same.
