### ISSUE TITLE
[FEATURE] Update fields of RemoteFeedbackRecords

### ISSUE THREAD

**Issue by plaguss** [recognai/rubrix#4329]
**Is your feature request related to a problem? Please describe.**
I would like to update the `fields` of `RemoteFeedbackRecords`.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Related to #4328

**Comment by nataliaElv** [comment]
Hi @plaguss ! Is this issue related to a specific problem? What do you mean by updating fields?

**Comment by plaguss** [comment]
Hi @nataliaElv! I think this really doesn't make sense, I saw we couldn't update this from the sdk (related to the #4328), but it doesn't make sense. I'll close this

**Comment by nataliaElv** [comment]
This is definitely something that has come up in user interviews, but it has some implications in terms of dataset consistency. I'll add this to the triage so we can discuss internally.
