### ISSUE TITLE
[FEATURE] Track feedback or annotation by user and allow filtering on user level to allow for quick amendments

### ISSUE THREAD

**Issue by maxyousif15** [recognai/rubrix#4331]
**Is your feature request related to a problem? Please describe.**
Is it possible to implement a solution to allow for filtering based on the user who annotated or provided feedback? Currently, when reviewing the submitted responses, you cannot apply a filter based on the user who provided the annotation or feedback. This would be really useful for cases when a user wants to quickly review their own submissions and make amendments as necessary.
This may well be the default behaviour for obvious security reasons but it is not something I could get clarity on from the documentation. 

**Describe the solution you'd like**
Some kind of filtering functionality in the UI when you're browsing the submitted responses. Alternatively, visible submitted responses should be restricted to the user who created them, i.e. other users should not see annotations submitted by other users.

**Describe alternatives you've considered**
I have not considered any alternatives.

**Additional context**
No other context, but please let me know if you have any clarifying questions.

**Comment by davidberenstein1957** [comment]
@maxyousif15 , does the idea of using metadata to facilitate this help?

**Comment by davidberenstein1957** [comment]
Hello @maxyousif15, do you still need help with this?

**Comment by maxyousif15** [comment]
Hey. Sorry about the delay. I have not tested this implementation yet, but I will trial it. I think we can close the issue for now and I will re-open if the proposed solution does not solve the problem.
