### ISSUE TITLE
Add scikit-learn example to Rubrix cookbook

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#436]
The idea would be to add an example with scikit-learn here:

https://rubrix.readthedocs.io/en/stable/guides/cookbook.html#Rubrix-Cookbook

The steps would be:

1. Add a new section to this notebook: https://github.com/recognai/rubrix/blob/master/docs/guides/cookbook.ipynb called `scikit-learn`
2. Load a dataset, and the code to train a basic text classifier
3. Once trained log the predictions into a Rubrix dataset using rb.log()
4. (Optional) Add a training section where we load a dataset from Rubrix using rb.load(), post-process the dataset and train a text classifier with scikit-learn.

**Comment by Arvind644** [comment]
Hii @dvsrepo I want to work on this issue

**Comment by dvsrepo** [comment]
Hi @Arvind644, did you manage to take a look at this? Let us know if you need support

**Comment by Arvind644** [comment]
Hii @dvsrepo I am finding it hard to implement this. I am learning it how to do that. I think I need more knowledge.
