### ISSUE TITLE
[FEATURE] Add labels from UI for single and multi-label questions in Feedback datasets

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4364]

**Comment by davidberenstein1957** [comment]
This is also something that GSK confirmed. It might be nice to have some feedback about the implications of labels edits, like the reset of status from X records or the removal of a label from Y records when deleting. Similarly, they mentioned merging labels might be relevant, which is partially aligned with scenarios for [hierarchical labels](https://github.com/argilla-io/argilla/issues?q=is%3Aissue+is%3Aopen+hierarchical).
