### ISSUE TITLE
[FEATURE] Allow to change the order of labels once the dataset is created

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4366]
_Definition:_

Change the label order shown to users for single and multi-label questions in Feedback datasets from the UI settings section.

_User stories:_

- As an admin, I want to change the order of the labels manually in the dataset settings page, so that I can make the UI more comfortable for the annotation team.
- As an annotator, I want to tell my manager my preferred order for the labels, so they can modify it and make the task easier for me and my peers.

_Acceptance criteria:_

- [ ] In the Questions tab inside of the dataset settings page: see the labels of `Label`, `MultiLabel` and `Span` questions in the edition area (left hand side) under the description box.
- [ ] Allow users to change the order of those labels.
- [ ] When a user makes a manual change in the order of the labels, the new order should appear in the preview and the "Update" button is enabled.
- [ ] When the user clicks on the "Update" button, the order of the labels gets saved.

**Comment by nataliaElv** [comment]
Is this correcting the position in which (a) specific label(s) appear or more like changing into an alphabetic sort or other kinds of sorting?

**Comment by nataliaElv** [comment]
Let's discuss also being able to change the names and titles of labels.

**Comment by nataliaElv** [comment]
> Let's discuss also being able to change the names and titles of labels.

https://github.com/argilla-io/argilla/issues/4558

**Comment by Amelie-V** [comment]
Some additions:

Scope suggestion:
- First, reorder Single/Multi labels and Span 
- Second, title and name edition for Single/Multi labels and Span
- Third Color edition for Spans

UI:
- Compare options between visually maintaining the placeholder until the label is reordered or not showing it (could be useful when there are many labels).
- The shortcut is not visible in the labels area edition (only visible in the preview)

**Comment by Amelie-V** [comment]
![Image](https://github.com/argilla-io/argilla/assets/84135211/2b9e6b82-001b-447e-a87a-c1cd69acf847)
