### ISSUE TITLE
[BUG-UI/UX] `suggestion` filters still show without any suggestions

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4371]
**Describe the bug**
The `suggestion` filters still show without any suggestions in the dataset.

**To Reproduce**
1. add a dataset
2. don't add suggestion
3. go to the UI

**Expected behavior**
I would expect them to be hidden.

**Screenshots**
![image](https://github.com/argilla-io/argilla/assets/25269220/b22d08fa-b78b-484a-8210-add301f4e2a6)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: N.A.
 - Browser [e.g. chrome, safari]: N.A.
 - Argilla Version [e.g. 1.0.0]: 1.20
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.20

**Additional context**
This can also be a problem with the responses, whenever there aren't any yet.

**Comment by davidberenstein1957** [comment]
Related to https://github.com/argilla-io/argilla/issues/4372 and willbe tackled as part of that due to technical difficulties.

**Comment by nataliaElv** [comment]
hi @davidberenstein1957 Would you say this is a duplicate of this issue here? https://github.com/argilla-io/argilla/issues/4353

**Comment by davidberenstein1957** [comment]
Yes, closing it for that reason.
