### ISSUE TITLE
[DOCS] Hugging face space URL

### ISSUE THREAD

**Issue by pelayoarbues** [recognai/rubrix#4374]
In this page: https://docs.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html the docs say ["you can use the UI with the Direct URL you’ll find in the “Embed this Space” option (top right)."](https://docs.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html)  but this option is not available for private spaces. 
 
 As discussed with Dani in a [Slack thread](https://rubrixworkspace.slack.com/archives/C02G2TZFG3V/p1701765438934229?thread_ts=1701764819.190989&cid=C02G2TZFG3V), to write the direct URL you need to use something like: 
 
The direct url should be constructed as follows
Space url
https://huggingface.co/spaces/argilla/ultrafeedback-curator
Direct url for this dataset:
https://argilla-ultrafeedback-curator.hf.space/
So something like user (or org)-[datasetname.hf.space](http://datasetname.hf.space/)

**Comment by sdiazlor** [comment]
@pelayoarbues thanks for your feedback and we will try to improve it
