### ISSUE TITLE
[FEATURE] Add sorting by RatingQuestion value suggestion values

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#4378]
**Is your feature request related to a problem? Please describe.**
In the first iteration, we introduce sorting by suggestion scores. The reasoning is that for Label questions was not so useful to sort by label names (positive first, then negative, etc.).

For RatingQuestions, as we have numbers, it's actually useful to sort by their values: show me first the highest/lowest rated.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dvsrepo** [comment]
@nataliaElv to add and discuss in the triage

**Comment by nataliaElv** [comment]
I added this to the triage. Feel free to answer the value vs cost fields, but happy to do it myself ahead of the next roadmap meeting :)

**Comment by Amelie-V** [comment]
Create to new categories inside sort components:
- Response value
- Suggestion value
Inside each of them add "rating question name".

To discuss:
- Can we simplify "Suggestion Score" for "Score" as category name?
- Define order of categories

**Comment by nataliaElv** [comment]
I would keep "Suggestion Score" as it is now. It is more evident and contrasts with "Suggestion Value". 
Initial proposal for the order is:
1. General
2. Suggestion Score
3. Suggestion Value
4. Response Value (<- this one won't apply in the "Pending" queue)

**Comment by nataliaElv** [comment]
@damianpumar Feel free to add a tasklist to this issue with the tasks necessary to complete the feature. If anything isn't clear or needs further specification let me or @Amelie-V know ;)

**Comment by damianpumar** [comment]
- [ ] Hide responses values at pending queue. 
- [ ] Add Suggestion value category
- [ ] Show rating question name by `value`
