### ISSUE TITLE
[DOCS] review end2end tutorials: typos and outputs

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4381]
## Which page or section is this issue related to?

When working with the practical guides, I noticed some typos or some outputs that were unneeded or showing errors.
 https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/tutorials.html

**Comment by davidberenstein1957** [comment]
Sometime the references to other blogpost, next and previous, are incorrect URLs.
