### ISSUE TITLE
[BUG-python/deployment] Dependency error with matplotlib

### ISSUE THREAD

**Issue by BedirT** [recognai/rubrix#4382]
**Describe the bug**
There is a dependency issue where argilla uses `matplotlib` but doesn't specify in `pyproject.toml`. It is used in `client.py`

**Stacktrace and Code to create the bug**
Just install argilla on a fresh environment and use `assign_records` (or anything from `client.py`

**Expected behavior**
Run without `matplotlib` error.

**Environment:**
 - Argilla Version [e.g. 1.0.0]: 2.0.0
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by davidberenstein1957** [comment]
@kursathalat, we want to use a require dependency here
