### ISSUE TITLE
[BUG-UI/UX] Text search + similarity search does not work for Feedback datasets

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4387]
**Describe the bug**
When I apply a text search with the similarity search feature enabled, the text search is not applied to the result list.

**To Reproduce**
1. Open the UI and go to an already created dataset with vectors
2. Apply the "Find similar" action
3. Apply a text query in the search bar that should reduce the number of results 
4. See no text filter is applied

**Screenshots**
<img width="1068" alt="Screenshot 2023-12-11 at 10 55 45" src="https://github.com/argilla-io/argilla/assets/2518789/5de296b3-c550-403a-8c43-30a5dfa261e0">

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]: Chrome
 - Argilla Version [e.g. 1.0.0]: 1.20.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.8.2

**Comment by damianpumar** [comment]
Apparently it works, just keep in mind that this feature works only when the **use_markdown** is set to false.

![Screenshot 2023-12-12 at 07 40 12](https://github.com/argilla-io/argilla/assets/7398909/a9b71ca8-371e-43bc-aefe-9ae78136b7cd)

**Comment by damianpumar** [comment]
Consuming these endpoints the results are same:
![Screenshot 2023-12-12 at 09 56 22](https://github.com/argilla-io/argilla/assets/7398909/a560ed69-82f3-4bce-b7df-a0decfddba8d)
**(with query text)**
![Screenshot 2023-12-12 at 09 56 17](https://github.com/argilla-io/argilla/assets/7398909/7c4c5b5b-70e1-4477-91a5-95896f473096)

**(without query text)**
![Screenshot 2023-12-12 at 09 56 29](https://github.com/argilla-io/argilla/assets/7398909/b77fa74c-2922-41f0-905d-ca812610dc57)

http://localhost:3000/api/v1/me/datasets/b2effb08-e0b9-4099-911c-318485db6f86/records/search?include=responses&include=suggestions&offset=0&limit=50&response_status=missing&response_status=draft
