### ISSUE TITLE
Change dictionary key in RubrixLogHTTPMiddleware from `probabilities` into `scores`

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#439]
The idea is changing this key:

https://github.com/recognai/rubrix/blob/766a9f39cffda002f75eb3528ab040f7a8e2c46b/src/rubrix/client/asgi.py#L57

from `probabilities` to the more general `scores`

Also we'd need to update the related tests.

**Comment by iakhil** [comment]
May I work on this issue?

**Comment by dvsrepo** [comment]
Of course! Thanks so much, I assign it to you

**Comment by iakhil** [comment]
Could you please add some details in the description?

**Comment by dvsrepo** [comment]
Description added @iakhil ! Please let me know if you have questions

**Comment by iakhil** [comment]
Thank you. Where can I find the related tests?

**Comment by dvsrepo** [comment]
Hi! Tests are found in the `tests` folder, which follows the same structure of the src and contain tests for the different classes and funcions in the src .py files.

For this case: https://github.com/recognai/rubrix/blob/master/tests/client/test_asgi.py

**Comment by iakhil** [comment]
Hey! The PR I submitted for this issue has been merged. Could this issue be closed now?

**Comment by frascuchon** [comment]
thanks @iakhil
