### ISSUE TITLE
[BUG-UI/UX] Getting out of settings erases the previous filters you had selected

### ISSUE THREAD

**Issue by ignacioct** [recognai/rubrix#4390]
**Describe the bug**
While doing the Awesome Argilla datasets annotation this week, I've found that if you had some Filter or Sorting option selected, you get in the settings (in my case, to check the annotation guidelines) and you go back by pressing the "See your dataset" option, any filter or sorting option is erased, and you can loose track of the record you were annotating.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pick any filter or sorting option
2. Click the settings button
3. Click "See your dataset
4. Filters and sorting options are deselected.

**Expected behavior**
One might think that the filters and sorting options shouldn't be deselected, thus one would come back to the same record that it was before.

**Environment (please complete the following information):**
pre.argilla.io

**Comment by damianpumar** [comment]
Hi @ignacioct 👋
Your feature request is there https://github.com/argilla-io/argilla/pull/4461

Thanks to share this great idea!
