### ISSUE TITLE
[FEATURE] Order records based on user's last response

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4415]
**Is your feature request related to a problem? Please describe.**

In the Argilla UI, when I move to queues that contain records with responses (Submitted, Discarded, Draft), I would like to see first the record that I worked with last.

**Describe the solution you'd like**

Order queues based on the date and time when the last response was saved, having the most recent responses first.
Pending can stay ordered based on date of creation.

**Describe alternatives you've considered**

**Additional context**

**Comment by nataliaElv** [comment]
It seems like this is already happening for the Submitted and Draft queues but not for Discarded. Can you confirm @damianpumar ?

**Comment by damianpumar** [comment]
Hi @nataliaElv I have no idea about this feature, some days ago I detected this behavior, but I thought it was an error.
