### ISSUE TITLE
[BUG-UI/UX] Matched records number becomes incongruent when annotating a bunch of records

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4418]
**Describe the bug**
Once I start annotating records (Discard/Submit), the number of total records and the current one become incongruent, by showing an index greater than the total result.

**To Reproduce**
1. Go to the dataset annotation page
2. Start annotating records (you should annotate a decent number of them)
3. See how the total number of records (Y) becomes lower than the current record (X) in **X of Y** 

**Screenshots**
<img width="1622" alt="Screenshot 2023-12-18 at 10 58 55" src="https://github.com/argilla-io/argilla/assets/2518789/1573a9f9-23db-4ea5-822b-2b2aa51683fc">

<img width="226" alt="Screenshot 2023-12-18 at 10 58 42" src="https://github.com/argilla-io/argilla/assets/2518789/db5c49fa-d07c-401d-ae30-16e036b869ac">

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Comment by davidberenstein1957** [comment]
@damianpumar, i believe this is the same issue https://github.com/argilla-io/argilla/issues/4389

**Comment by damianpumar** [comment]
> @damianpumar, i believe this is the same issue #4389

Yes! I'll link it into my open PR. Thanks!!
