### ISSUE TITLE
[BUG-UI/UX] paginating to a new record, automatically scrolls down to selected form area

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4419]
**Describe the bug**
Not sure if this is a bug or a feature related to the usage of the auto-focus on the form area, but maybe we don't want to automatically scroll to the selected area either because it messes a bit with the annotation flow.

**To Reproduce**
1. Go to a dataset
2. Click on open screen halfway
3. Scroll down to go to the next record

**Expected behavior**
Ideally I want to stay at the top of the screen/start of the form because you are not able to annotate anything without reading the fields.

**Screenshots**
https://github.com/argilla-io/argilla/assets/25269220/feb9ea3b-847d-421a-9898-d43f37e9d269

**Environment (please complete the following information):**
 - OS [e.g. iOS]:N.A.
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.20
 - ElasticSearch Version [e.g. 7.10.2]:N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]:1.20

**Additional context**
N.A.

**Comment by damianpumar** [comment]
Thanks @davidberenstein1957 to report this. 
A few weeks ago I noticed this bug and it will be fixed in the bulk annotation here https://github.com/argilla-io/argilla/pull/4333
I'll update the change log to report this issue.
