### ISSUE TITLE
[BUG-UI/UX] no-warning of loosing information when leaving page after not saving edited `settings` as owner

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4421]
**Describe the bug**
I just updated the annotation guidelines and pressed the leave dataset button but did not get a warning about loosing information.

**To Reproduce**
1. Go to a dataset
2. Click on settings
3. Edit the setting but don't press the save button
4. Leave the page

**Expected behavior**
I would expect to get a warning

**Screenshots**
N.A.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MaxOS
 - Browser [e.g. chrome, safari]: Firefox
 - Argilla Version [e.g. 1.0.0]: 1.20
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 1.20

**Additional context**
N.A.

**Comment by damianpumar** [comment]
Hi @davidberenstein1957 🙌
I added your feature request in this PR https://github.com/argilla-io/argilla/pull/4461

If you try to close the tab with unsaved changes you can see the before unload event with default browser message.
Also if you try to go to dataset with `see your dataset` button you can see the custom notification toaster with our default behavior, and if you click on `X` button on toaster you'll move automatically unsaved data tab; if you click on 'ignore and cotinue` button you'll go to dataset with your latest filters applied.

Thanks for this great feature!!
