### ISSUE TITLE
[DOCS] align assign_records with new list aggregation for metadata

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4446]
**Is your feature request related to a problem? Please describe.**
Better align assign_records.py with new option of adding a list of metadata.

```python
from argilla.client.feedback.utils import assign_records
assignments = assign_records(
    users=[f"user_{ix}" for ix in range(0,6)],
    records=records,
    overlap=3,
    shuffle=True
)

modified_records = []
for username, records in assignments.items():
     for record in records:
        record.metadata['annotator'] = [user1, user2, user3]
        modified_records.append(record)`
```
For instance, using this, the loading time is too long
``` python
def find_users_for_record(record, assignments_dict):
    users = []
    for user, records in assignments_dict.items():
        if record in records:
            users.append(user)
    return users

modified_records = []
for record in records:
        record.metadata['annotator'] = find_users_for_record(record, assignments)
        modified_records.append(record)
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sdiazlor** [comment]
@davidberenstein1957 Regarding this issue, I've been thinking about it and the question is that, when assigning as metadata, this type of dictionary is more suitable {record : [annotators or groups]}; but when assigning using workspaces, the inverted version is the best option {annotator or group : records}. So, if we invert the current dictionary output, the problem regarding the loading time would be for those assigning using workspaces.

I don't know what solution is the most efficient and user-friendly. Some possibilities I thought about are the following:

1- To return both (but I wouldn't go for this as it is double computation)
2- Add an argument in assign_records to indicate if they are going to assign them as metadata
3- Create a different assign_records_as_metadata, as a different/parallel workflow

Let me know what you think or if you may come up with other approaches.

**Comment by davidberenstein1957** [comment]
having a shared function with a flag or argument for metadata would work
