### ISSUE TITLE
[DOCS] write a tutorial on the usage of `Metrics` to model data drift / model drift

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4448]
## Which page or section is this issue related to?
These are more high-level business topics that align with things like quality monitoring ethics etc, and might be relevant to showcase how Argilla can be used to alleviate and address those problems.

**Comment by TrineSiew** [comment]
I would love to have such documentation! 🙌

**Comment by avecillajota** [comment]
I also support the idea of providing further documentation on metrics 🙌 🙌 🙌
