### ISSUE TITLE
[FEATURE] add `last_updated_response` timestamp to records

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4452]
**Is your feature request related to a problem? Please describe.**
We only add a last updated timestamp based on record edits on a field/metadata/vector setting but don't do this for responses yet. 

**Describe the solution you'd like**
I would like to see an extra entry in the database that covers this.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by davidberenstein1957** [comment]
This was also confirmed behavior and need for GSK. They wanted to just update the x-latest responses within a [certain date time range.](https://github.com/argilla-io/argilla/issues/4365)

**Comment by nataliaElv** [comment]
This is related to https://github.com/argilla-io/argilla/issues/4415
