### ISSUE TITLE
[FEATURE] align UI warning when leaving page during record edits with leaving settings page 

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4465]
**Is your feature request related to a problem? Please describe.**
Within [this PR](https://github.com/argilla-io/argilla/pull/4461), we introduced a new behaviour to avoid losing edited information when leaving a page as described in [this issue](https://github.com/argilla-io/argilla/issues/4421). We changed this to include warnings when closing the page or navigating to another page. Currently, this is included for changes in the records with submitted status but not for other statuses.

**Describe the solution you'd like**
I would like to see this aligned with the submitted record and dataset settings warning.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by damianpumar** [comment]
@davidberenstein1957 I've been thinking about the implementation of this issue, and I've run into some UX issues. Obviously we can implement your request, but I think it would be too annoying for the user when they modify something in a certain state and can't close the window when something has been modified in the UI, as we don't have a "restore" button to undo the changes.

**Comment by davidberenstein1957** [comment]
@damianpumar, I see what you mean. For me, it made intuitive sense to align or at least evaluate if it was needed to include here too. Let's close the issue for now. Thanks for the exploration.
