### ISSUE TITLE
[FEATURE] Add support using pydantic v2 with Argilla

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4466]
**Is your feature request related to a problem? Please describe.**
Argilla users cannot work with pydantic v2, since dependency requirements are fixed by Argilla. We can adapt imports to support both, v1 and v2 versions, without a full v2 migration (proposed in https://github.com/argilla-io/argilla/issues/3369).

**Comment by frascuchon** [comment]
Fixed by #4459

**Comment by THOR300** [comment]
> Fixed by #4459

@frascuchon great news!
