### ISSUE TITLE
[FEATURE] LLM API `suggestions` from the UI

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4476]
**Is your feature request related to a problem? Please describe.**
At times, we don't want to fully rely on data scientists configuring things from their side but annotators might want to chat and interact with LLMs to get suggestions and context about their issues during annotation/ 

**Describe the solution you'd like**
A chat-like interface or potential update suggestion button to scope get input for `*Question` from within the UI.

**Describe alternatives you've considered**
This could potentially be also our self-hosted LLMs in the future as service within the cloud.

**Additional context**
As proposed by Damian Tanner.

**Comment by Piyush-Kumar-Ghosh** [comment]
Hey @davidberenstein1957, I'm ready to contribute. Can you share more details, like  any existing discussions or decisions? Also, are there specific areas that need attention?

**Comment by davidberenstein1957** [comment]
Hi @Piyush-Kumar-Ghosh this issue still needs to be triaged and evaluated internally. You would be able to handle [this distilabel issue](https://github.com/argilla-io/distilabel/issues/225) perhaps?

**Comment by Piyush-Kumar-Ghosh** [comment]
Hi @davidberenstein1957 ,

Thank you for considering me for this task. I'm confident in my ability to contribute to the `distilabel `issue. While I may require some initial guidance, I'm eager to learn and collaborate closely with the team to ensure a thorough triage and evaluation process.

I'm ready to accept the work and would appreciate access to any specific resources or documentation available.

Looking forward to contributing to the resolution of this issue.
