### ISSUE TITLE
[FEATURE] extend `multi-modality` support with `DataURL` for documents like `pdf`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4481]
**Is your feature request related to a problem? Please describe.**
We recently got a request from a user about support for PDF documents within the TextField as DataURL.
Leire found that the following worked:
`'<embed src=https://arxiv.org/pdf/2307.00808.pdf type=application/pdf width=700px height=700px/></embed>'`

**Describe the solution you'd like**
I would like to see extended support for documents like PDF, and maybe pptx, docx, xlsx and others to load them into Argilla.
`from argilla.client.feedback.utils import audio_to_html, image_to_html, video_to_html`

**Describe alternatives you've considered**
N.A.

**Additional context**
![image](https://github.com/argilla-io/argilla/assets/25269220/53204f6c-feb8-413a-9858-5c944f1376b9)

**Comment by sdiazlor** [comment]
Nice! I'll take a look, this idea is really interesting and useful!

**Comment by davidberenstein1957** [comment]
@sdiazlor add an example for the https://huggingface.co/HuggingFaceM4 dataset.
