### ISSUE TITLE
[FEATURE] Allow support for filtering by missing values 

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4486]
Since metadata accepts `None` values, it would be interesting to filter records by these missing values (find records where `metadata.environment` is missing or does not exist)

_Originally posted by @frascuchon in https://github.com/argilla-io/argilla/issues/4477#issuecomment-1887389282_

**Comment by Piyush-Kumar-Ghosh** [comment]
Hey @frascuchon! 👋 I'm diving into the task. 🚀

To ensure a seamless development process, could you provide more details or specifications on any specific requirements, considerations, or preferences you have in mind? Your insights will be invaluable in crafting a solution that aligns perfectly with the project's needs.

**Comment by frascuchon** [comment]
Thanks @Piyush-Kumar-Ghosh !!

Sure!. I will try to do my best to show how you can tackle this. The main idea would be to provide a way to query missing values, by this I mean values that do not exist in the index or that are `null/None`. 

Ideally, you should add two new filter types in the base [query dsl](https://github.com/argilla-io/argilla/blob/develop/src/argilla/server/search_engine/base.py#L116): `NotFilter` and `ExistsFilter` filters, And implement the logic in default search [engine implementation](https://github.com/argilla-io/argilla/blob/develop/src/argilla/server/search_engine/commons.py#L440), aligning those filters to the [bool query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) (`must_not` section) and the [exists query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-exists-query.html) in elasticsearch.

I would say to start implementing this functionality at the search engine level, and then integrate them in the API endpoints.

Please, do not hesitate to ask me if you need something else.

**Comment by Piyush-Kumar-Ghosh** [comment]
Hey @frascuchon! 👋 I'm excited about the new features I'm working on, and I want to ensure they meet the project's standards.

Could you please guide me on the testing approach for this contribution? Specifically:
1. Where should I write the test cases? Is there a designated directory or naming convention for them?
2. What format or structure is preferred for the test cases?

Additionally, I'm curious about integrating these it into the API endpoints. Any advice on how and where to handle this integration would be appreciated.

Your insights will help me align my work with the project's practices.🚀

**Comment by frascuchon** [comment]
Great, @Piyush-Kumar-Ghosh!

Regarding the test cases, you have the `tests/unit/server` folder where the server tests are defined. For this case, you should create new tests [here](https://github.com/argilla-io/argilla/blob/develop/tests/unit/server/search_engine/test_commons.py) (you can base on [this one](https://github.com/argilla-io/argilla/blob/develop/tests/unit/server/search_engine/test_commons.py#L706) which has a similar check behaviour)

About the API integrations, the integration must be done in those endpoints using the search engine for search. The integration should occur [here](https://github.com/argilla-io/argilla/blob/develop/src/argilla/server/apis/v1/handlers/datasets/records.py#L182), allowing to pass these new filter types in the `body.filters` section.

**Comment by Piyush-Kumar-Ghosh** [comment]
Hi @frascuchon ,

Thank you for your message regarding the test cases for the filter feature. I apologize for the delay in response.

I regret to inform you that I was unable to work on the task for the past three weeks due to unforeseen personal circumstances that required my immediate attention. Additionally, I encountered difficulty accessing the provided link, as it appears that the `develop` branch does not contain the specified path. 

Thank you for your understanding and patience in this matter. I am committed to completing the task promptly and effectively, and I'll keep you updated on my progress.

**Comment by frascuchon** [comment]
Hi @Piyush-Kumar-Ghosh

We recently separated the argilla server module into a different package (You can find it [here](https://github.com/argilla-io/argilla-server/)).

So, you should work on this issue on that repo. The updated links regarding my previous comment are:

https://github.com/argilla-io/argilla-server/blob/main/tests/unit/search_engine/test_commons.py#L704
https://github.com/argilla-io/argilla-server/blob/main/src/argilla_server/apis/v1/handlers/datasets/records.py#L108
