### ISSUE TITLE
[BUG-python/deployment] ValueError: The sum of train_size and test_size should be smaller than the number of samples

### ISSUE THREAD

**Issue by 7flash** [recognai/rubrix#4512]
Following this tutorial:

https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/training-llm-mistral-sft.html#ArgillaTrainer-&-hyperparameters

```
from argilla.feedback import ArgillaTrainer

task = TrainingTask.for_supervised_fine_tuning(formatting_func)
dataset = rg.FeedbackDataset.from_argilla("oig-30k")
formatted_dataset = dataset.prepare_for_training(framework="trl", task=task)

trainer = ArgillaTrainer(
    dataset=dataset,
    model=model,
    tokenizer=tokenizer,
    task=task,
    framework="trl",
    train_size=0.99,
)
```

It gives me an error:

```
ValueError: The sum of train_size and test_size = 30001, should be smaller than the number of samples
30000. Reduce test_size and/or train_size.
```

**Comment by 7flash** [comment]
My temporary workaround works, skipping some rows in my dataset, but I'm not sure why I'm doing that and what's correct approach if I want to use all of the rows:

```
import random
def formatting_func(sample: Dict[str, Any]) -> Iterator[str]:
    if random.random() < 0.01:
        return
```

**Comment by davidberenstein1957** [comment]
hi @7flash , I believe we are using the internal Datasets implementation of train test split to do this so it might be an internal bug. Could you check by debugging where this additional sample is coming from?

**Comment by 7flash** [comment]
> hi @7flash , I believe we are using the internal Datasets implementation of train test split to do this so it might be an internal bug. Could you check by debugging where this additional sample is coming from?

My guess it's because of train_size=0.99 if changing to smaller value it seems it works

**Comment by nataliaElv** [comment]
Hi @7flash ! Did you manage to solve this issue or do you still need help with it?
