### ISSUE TITLE
[FEATURE] See full label titles

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4528]
**Is your feature request related to a problem? Please describe.**

- When I have long labels that start in the same way it's difficult to choose one over the other because I need to look at the tooltip to see the full name / title of the label. 
- I'm always frustrated when there are some spaces to read the full label but it's cut by default.
- I want to see as much as possible my data as it is.
- I want to read sequentially my labels and even more they are numerated with the shortcut 

**Describe the solution you'd like**
- Extend the max label length to the minimum width column
- Cut the label and provide the tooltip when the label length is > to mini width column
- Consider a rule to show the label list more structured. (to avoid the case where only one label is in a second column and the rest is aligned on the left)

**Describe alternatives you've considered**

**Additional context**

**Comment by Amelie-V** [comment]
<img width="1232" alt="Screenshot 2024-01-23 at 14 12 39" src="https://github.com/argilla-io/argilla/assets/84135211/eb153c76-9263-4561-80cf-c71503217c3c">

**Comment by Amelie-V** [comment]
<img width="1232" alt="Screenshot 2024-01-23 at 14 12 39" src="https://github.com/argilla-io/argilla/assets/84135211/bf608a99-d7ad-41f4-ba27-5ab2e107c44d">

**Comment by Amelie-V** [comment]
<img width="403" alt="Screenshot 2024-01-24 at 15 37 19" src="https://github.com/argilla-io/argilla/assets/84135211/3062daca-46df-4ebd-b7af-74c45c245cfb">
