### ISSUE TITLE
[FEATURE] create `gradio` app to monitor datasets and annotations

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4543]
**Is your feature request related to a problem? Please describe.**
Not directly.

**Describe the solution you'd like**
I would like to see a `workspace`+ `dataset` overview of the annotators and their progress + input. 

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by ignacioct** [comment]
Closed in an independent repo and uploaded as a HF Space
