### ISSUE TITLE
Allow disabling ES index template creation by environment var

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#455]
Include a [API environment variable](https://github.com/recognai/rubrix/blob/master/src/rubrix/server/commons/settings.py#L25) `RUBRIX_DISABLE_ES_INDEX_TEMPLATE_CREATION` allowing advanced users create its own es [index settings and mappings](https://github.com/recognai/rubrix/blob/master/src/rubrix/server/tasks/commons/dao/dao.py#L123).

See #443

**Comment by torkashvand** [comment]
I can work on this issue. :)

**Comment by frascuchon** [comment]
Great @torkashvand !!!

Thanks. Go ahead with the solution.

**Comment by torkashvand** [comment]
check this [PR](https://github.com/recognai/rubrix/pull/469)

**Comment by frascuchon** [comment]
Thanks @torkashvand !!
