### ISSUE TITLE
[BUG-python/deployment] elasticsearch role setup

### ISSUE THREAD

**Issue by oleg-darrow** [recognai/rubrix#4554]
**Describe the bug**
The [page](https://docs.argilla.io/en/latest/getting_started/installation/configurations/elasticsearch.html#configure-roles-and-users) that contains Elasticsearch role setup isnot correct. 
After creating separate role for argilla user and using it under `ARGILLA_ELASTICSEARCH` variable - I receive 403 error
If I use `superuser` role - all works.

<img width="1414" alt="Screenshot 2024-01-31 at 10 44 33" src="https://github.com/argilla-io/argilla/assets/153456311/199ccba9-53b7-4eb2-9e74-2f5b4e6f20f6">

**Stacktrace and Code to create the bug**
```python
[01/31/24 09:53:10] WARNING  WARNING:opensearch:GET                  base.py:259
                             https://elasticsearch-es-http.eck:9200/            
                             [status:403 request:0.159s]                        
                    INFO     INFO:backoff:Backing off             _common.py:104
                             _setup_elasticsearch(...) for 11.3s                
                             (pydantic.errors.ConfigError: Your                 
                             Elasticsearch endpoint at                          
                             https://argilla:XXXX@elasticsearch-e               
                             s-http.eck:9200 is not available or                
                             not responding.                                    
                             Please make sure your Elasticsearch                
                             instance is launched and correctly                 
                             running and                                        
                             you have the necessary access                      
                             permissions.
```

**Expected behavior**
Running argilla server with connected elasticsearch engine by using custom created ES role with minimal required permissions.

**Environment:**
 - Argilla Version `1.22.0`
 - ElasticSearch Version `8.8.2`
 - Docker Image `argilla:v1.22.0`

**Comment by frascuchon** [comment]
Hi @oleg-darrow and thanks for reaching out.

Apologize for the late response. I was trying to recreate a local environment to reproduce the error. Effectively, the current documentation is a bit outdated. I'm working on that. 

Meanwhile, could you try a role setup with the following configuration?:

**Cluster privileges**
`monitor`, `manage`

**Index privileges**
*Indices*: `rg.*`, `*ar.dataset*`
*Privileges*: `all`

Please, let me know if this works for you.

Thanks!

**Comment by oleg-darrow** [comment]
hi @frascuchon 

well, i added both `rg.*` and `ar.*` and that seems to be working. thanks.

**Comment by frascuchon** [comment]
Great @oleg-darrow.

Thanks for your help
