### ISSUE TITLE
[BUG-UI/UX] navigating between views for bulk, find similar and pagination does not warn about loosing selection/progress

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4572]
**Describe the bug**
navigating between views for bulk, find similar and pagination does not warn about loosing selection/progress

**To Reproduce**
1. Go to a dataset
2. Click on bulk
3. Scroll down to label some records
4. Jump to other view
5. loose selected records

**Expected behavior**
I would expect this to warn loosing selection

**Screenshots**
N.A.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]:FireFox
 - Argilla Version [e.g. 1.0.0]: 1.23
 - ElasticSearch Version [e.g. 7.10.2]: N.A.
 - Docker Image (optional) [e.g. argilla:v1.0.0]: N.A.

**Additional context**

**Comment by damianpumar** [comment]
Hi @davidberenstein1957, this is not a bug, this is a feature. 
We show the message if you are in submitted, discarded status and you modify some questions. In pending status we'll never show this message.
