### ISSUE TITLE
[FEATURE] API Endpoint for obtaining all annotations done by all users in a workspace.

### ISSUE THREAD

**Issue by ignacioct** [recognai/rubrix#4584]
**Is your feature request related to a problem? Please describe.**
After developing the Gradio app, we realised that the only way to obtain metrics from an user was by doing the API call `/api/v1/me/datasets/{dataset_id}/metrics`, so to obtain all metrics from all users, we had to log in to each user (obtaining the keys from the workspace) and doing this call repeteadly. 

**Describe the solution you'd like**
For bulletproofing us in the future, I think it'd be cool to create an API call that returns all annotations in a dataset, alongside the username or user id that made them.

**Describe alternatives you've considered**
The current solution of log in and looping is slow and takes a lot calls, sometimes leading in timeouts or similar errors

**Additional context**
This arose in the creation of https://github.com/argilla-io/argilla-annotation-monitor

**Comment by nicolamassarenti** [comment]
I am interested in this feature - is this planned to be included? Is this in the roadmap?

@dvsrepo @frascuchon @davidberenstein1957 @ignacioct I see you were assigned to this - could you provide a feedback? It would be great for our planning
