### ISSUE TITLE
[BUG-UI/UX] Glitch on scroll in bulk view

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4592]
**Describe the bug**

When records are very long, the scroll doesn't always stop at the beginning of the record, it stops in the middle of the record. I'm not sure when this happens and when it doesn't.

**To Reproduce**
1. Go to Bulk view
2. Scroll down the records until you find one that is longer than the height in your screen.

**Expected behavior**

**Screenshots**

**Comment by nataliaElv** [comment]
@Amelie-V add any details that you can think of

**Comment by damianpumar** [comment]
@nataliaElv could you share a video or image about this issue ? 
Thanks!

**Comment by nataliaElv** [comment]
I think @Amelie-V has one, but I couldn't post it here because it was too heavy.

**Comment by damianpumar** [comment]
I can't reproduce it.
