### ISSUE TITLE
Why "pandas >=1.0.0,<2.0.0" dependency is used?

### ISSUE THREAD

**Issue by Anton-Aracor** [recognai/rubrix#4599]
We went to install Argilla as our python dependency and can't do this because it rely on the outdated version of the pandas.

> "pandas >=1.0.0,<2.0.0",

In our project we use
> pandas = "^2.1"

Because of this we can't use your tool in our project. Do you plan to change this dependency and use the latest version of Pandas?

**Comment by Anton-Aracor** [comment]
Hope this change with a newer Pandas won't break anything and will be easy switch for your project. Once done - please let me know and I will update our dependency to the latest version too. Thank you.

**Comment by davidberenstein1957** [comment]
@Anton-Constructor it will not, we'll test for both versions in the CICD pipeline so it will not break any core functionalities of Argilla.
