### ISSUE TITLE
[FEATURE] Change show/hide shortcuts help key

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4607]
**Is your feature request related to a problem? Please describe.**

Several users have expressed being confused when the shortcuts help on labels shows/hides upon pressing command in Mac for other shortcuts, for example, to make a screenshot.

**Describe alternatives you've considered**

Possible alternatives:
1. Change it to a different key, less common for other shortcut combinations.
2. Show/hide this help from a user settings page instead of a shortcut.
3. Always show the help by default, no ability to hide it.

**Additional context**

**Comment by damianpumar** [comment]
Hi @Amelie-V, I need your help to define which of the alternatives that @nataliaElv mentioned is the option we are going to implement.

Thank you for your help!

**Comment by burtenshaw** [comment]
@damianpumar This could be a useful resource for selecting available/ less used shortcuts: http://dmcritchie.mvps.org/firefox/keyboard.htm

**Comment by dvsrepo** [comment]
I have the feeling that the shortcut help should be shown always, hiding it under another keyboard key would be even more confusing and it happens to me that sometimes when I first open the dataset I see the help info, and other times not.

They're nice looking and not disturbing, I'm not sure about the value of hiding them.
