### ISSUE TITLE
[BUG-UI/UX]

### ISSUE THREAD

**Issue by chozelinek** [recognai/rubrix#4620]
**Describe the bug**
All possible values for a metadata field of type terms are not shown when trying to filter. Only up to 12. If I type a value outside this list of 12 no record is shown. I know there are several hundreds of different values for the field.
If I use the search feature and I type the value of the field, the records are found and shown.

**To Reproduce**
1. Go to Filters > Metadata > Click on a terms metadata field > you see the list of posible values (add records for more than 12 different values for the field and you will only see 12).
2. Type in the box Filter by... the value that you want to use to filter. If the value is not in the list of 12, no record is shown.
3. Type the value not shown in the dropdown in the search box, press Enter, you should see records.

**Expected behavior**
I would expect to see the full list of values, or if typing in the Filter by... box the matching values should be shown, and be selectable, so the filter is applied.

**Screenshots**
Video to show and explain the problem. https://www.loom.com/share/f689ff37ccb64f9b823e5a011e3f6fcf?sid=c599d06e-a5a3-4a77-ac1c-921daf1e5961

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: Chrome
 - Argilla Version [e.g. 1.0.0]: 1.21.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.8.0
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 

**Additional context**

**Comment by nataliaElv** [comment]
Hi @chozelinek ! My teammates tell me that this was solved in this PR that came out as part of our latest release (1.25.0): **https://github.com/argilla-io/argilla-server/pull/30**
Could you update and check if the issue was solved?

**Comment by chozelinek** [comment]
Hi @nataliaElv ! After updating to 1.25.0 the issue is solved. Thank you!

**Comment by nataliaElv** [comment]
Great! Thanks for reporting back 😄
