### ISSUE TITLE
[BUG-UI/UX]

### ISSUE THREAD

**Issue by drewskidang** [recognai/rubrix#4621]
I can't edit the models responses for the preference dataset in the UI. I can only label them.

**Comment by nataliaElv** [comment]
Hi @drewskidang ! Could you give us a bit more information about how you set up your dataset (fields, questions, etc.) and what you are trying to accomplish? Thanks!

**Comment by drewskidang** [comment]
I was just doing the standard feedback task. I was hoping to edit the models responses on the UI

**Comment by nataliaElv** [comment]
Feedback tasks are very flexible and allow users to set up datasets with multiple questions of different kinds depending on specific needs. 
If what you intend to do is simply editing your model's responses right from the UI, you can do that by creating a dataset with a `TextQuestion` and adding your model's responses as suggestions to that question. Then, you will be able to see the text right there in the text area and make any modifications you need. Here are a couple of links that I hope will help:
- https://docs.argilla.io/en/latest/practical_guides/create_update_dataset/create_dataset.html#define-questions
- https://docs.argilla.io/en/latest/practical_guides/create_update_dataset/suggestions_and_responses.html#format-suggestions
Let us know if this solved your question or if it's still not clear. You can also reach us out in [our slack community](https://join.slack.com/t/rubrixworkspace/shared_invite/zt-whigkyjn-a3IUJLD7gDbTZ0rKlvcJ5g), where you can find other users who may be also able to help 😃

**Comment by drewskidang** [comment]
Okay thank you !

**Comment by nataliaElv** [comment]
I'm closing the issue because it looks like your question was solved, but feel free to reopen it if you need to ask more 😃
