### ISSUE TITLE
[BUG-UI/UX] Keyboard shortcuts do not work in bulk mode for classification

### ISSUE THREAD

**Issue by pelayoarbues** [recognai/rubrix#4634]
**Describe the bug**
I am using a Classification dataset to annotate some texts and I am not able to use keyboard shortcuts.

**To Reproduce**
1. Bulk view
2. Select one or various observations.
3. Keyboard shortcut to classify in one of the labels do not select the label. 

**Expected behavior**
I would like to be able to use keyboard shortcuts in bulk mode similar to the single mode annotation workflow.

**Comment by nataliaElv** [comment]
Hi @pelayoarbues ! You probably need to hit `tab` after making the selection to reactivate the form and then you should be able to enter the shortcut. If this is still too cumbersome we can try to find a solution to this. 
cc @damianpumar @Amelie-V

**Comment by pelayoarbues** [comment]
It's not cumbersome, but it is not intuitive unless clearly stated to the user.
