### ISSUE TITLE
[FEATURE] Order labels by confidence score

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4647]
**Can I set the order of labels shown for examples in a FeedbackDataset with a MultiLabelQuestion for each individual example?**
In a previous question, using code in https://github.com/argilla-io/argilla/issues/4615, I am using a FeedbackDataset to label examples with quite many labels.

After creating the dataset in Argilla, I get something like the screenshot below in the front-end, and there's a couple of things I would like to improve:

- If I set the number of visible labels to (say) 10, the front-end always shows me the first elements in my list of labels (i.e. [labels[:10]]. These are (in general) irrelevant for the example to annotate, and they appear before the suggested labels, which instead are the ones likely to be fitting for my example. Is there a way to get rid of (= hide) these irrelevant labels, or at least show them after the suggested ones? At the moment it's impossible to hide them, as the minimum number of visible labels is 3.

- In the same screenshot, if I deselect a suggested variable (say "label 53") it disappears instantly if it's not in labels[:10] , and I need to go back to the search box if I want to re-select it. Ideally instead, I would like suggested labels to still stay visible, even if they are deselected. In other words, suggested labels (in my example "label 28",  "label 53",  "label 14") should have "visual priority" - should come first and should stay visible even if unselected - over the irrelevant-if-not-suggested labels[:10] . Can I set the order of labels so that suggested labels come first and not disappear if unselected?

Summarizing, I would be happy if I could allow Argilla to order visible labels in a FeedbackDataset with a MultiLabelQuestion so that they can be displayed with a custom order, depending on the example, not the one dictated by the labels argument of the MultiLabelQuestion and stay visible if unselected. Is this feasible to do?

P.S. If I am not mistaken, this is somewhat related to https://github.com/argilla-io/argilla/issues/4638, but I don't care much about displaying the score, I care about ordering the labels according to the predicted score (i.e. suggested labels, with a high score, should be shown first).

![image (1)](https://github.com/argilla-io/argilla/assets/126158523/5611aa10-1366-413a-871c-334a4a1aee5f)

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla-server/issues/132
- [ ] https://github.com/argilla-io/argilla/issues/4756
```

**Comment by nataliaElv** [comment]
Related to argilla-io/argilla#3269

**Comment by davidefiocco** [comment]
Until this implemented, a workaround (thanks @c23996 for the idea!) that allows users to access suggestions

- in the desired order
- without the risk of "losing" them in the label list 

is a bit crude, but in the end acceptable: we display suggestions (in the desired order) in a dedicated field

<img width="1591" alt="image" src="https://github.com/argilla-io/argilla/assets/4547987/1f94cbb6-34ff-460e-bda7-d83b27ded74d">

and require users to confirm suggestions one by one by copying and pasting them from the text field.

```python
import argilla as rg
api_url = "http://localhost:6900"
api_key = "<api-key>"

rg.init(api_url=api_url, api_key=api_key)

# rg.Workspace.create('argilla')

rg.set_workspace("argilla")

num_labels = 250

labels = ["label " + str(i) for i in range(0, num_labels)]

dataset = rg.FeedbackDataset(
    fields=[
        rg.TextField(name="text", required= True, use_markdown=True),
        rg.TextField(name="suggestions", required= True, use_markdown=True)
    ],
    questions=[
        rg.MultiLabelQuestion(name="question-multi", title="Which labels are correct?", labels=labels, required=True, visible_labels = 3)]
)

records = []

record = rg.FeedbackRecord(
    fields={
        "text": "tierra finamente dividida, constituida por agregados de silicatos de aluminio hidratados",
        "suggestions": "label 28, label 34, label 53, label 14, label 95"
    },
)
records.append(record)

dataset.add_records(records)

dataset.push_to_argilla(name="workaround-dataset", workspace="argilla")
```

**Comment by jfcalvo** [comment]
@nataliaElv I have two questions:
1. Does this change also apply to span questions? 
2. I understand that this change would be to change the default behavior in which the labels are showed. If that's the case, should we think about adding some configuration setting to the question so the previous behavior can be enabled? (maybe it's not useful at al, only asking in case it is).

**Comment by nataliaElv** [comment]
Hi @jfcalvo ! This won't apply for Span questions, only Label and Multilabel, and yes the idea is to make this a configuration at the question level that can be changed at any time. I'll send over more detailed specifications soon 🙂
