### ISSUE TITLE
[BUG-UI/UX] Filtering by vectors

### ISSUE THREAD

**Issue by damianpumar** [recognai/rubrix#4655]
Try to find a similar record I get this error.

https://github.com/argilla-io/argilla/assets/7398909/fc0540c1-024e-4dc0-a5e3-a486003e153e

**Comment by frascuchon** [comment]
Thanks @damianpumar!!

I need to do some tests by I think the problem is because this specific record doesn't contain a vector with that name since vector values are optional, even if vector settings are defined.

**Comment by damianpumar** [comment]
Yes! I understood, but I'm not sure if we should handle it or not, because I don't know if this is a SDK issue or we can handle it in the frontend side.

Thanks!

**Comment by nataliaElv** [comment]
Proposal for the toast message:
````
{vector_name} not found for record {id}
````

**Comment by damianpumar** [comment]
Final message: 
{vector_name} not found for the selected record.
