### ISSUE TITLE
[Suggestions - UI] Improve and align the way to show suggestions in UI for all Questions Type

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#4657]
**Is your feature request related to a problem? Please describe.**
Currently, we are presenting suggestions in two different ways in Spans and other tasks. The yellow background might cause confusion about which label is accounted for: the manually annotated one (the blue one) or the suggestion (the yellow one)? Moreover, in Span tasks, we have ceased to use yellow to indicate suggestions and are exclusively using the sparkle icon.

**Describe the solution you'd like**
For text-class (single and multi), rating, ranking, and text questions, we should remove the yellow color and use the sparkle icon to indicate suggestions.

**Describe alternatives you've considered**
An alternative solution could be to leave the system as it is and wait for a more detailed analysis of the suggestion concept.

**Additional context**
Please add any other context or screenshots about the feature request here.

**Comment by nataliaElv** [comment]
Related to #4638 . These should be released together.
