### ISSUE TITLE
Active listeners for Feedback Dataset

### ISSUE THREAD

**Issue by vmehta-cohere** [recognai/rubrix#4658]
**Is your feature request related to a problem? Please describe.**
For feedback datasets, which carry the ability to carry complex labeling tasks, manual interactions to trigger training/evaluation can be a bottleneck for high frequency models. 

**Describe the solution you'd like**
Active listeners for datasets in Argilla to trigger functions on submit, maybe an ability to ex. trigger on submitted 50/60 examples or 60/60 examples etc.

**Comment by fozziethebeat** [comment]
I also just encountered this problem and found it very surprising to find out that listeners only work with pre-built template datasets.

From what I could discover it's because `/api/datasets` endpoint only returns these pre-built template datasets and deep down listeners only check that endpoint.

**Comment by nataliaElv** [comment]
Reopening, as we might still want to tackle this one.

**Comment by frascuchon** [comment]
Fixed in https://github.com/argilla-io/argilla/pull/5467
