### ISSUE TITLE
[UI]: Deep dataset pagination is not allowed

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#466]
Since elasticsearch has some deep pagination performances limitations (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/paginate-search-results.html)), we should limit pagination limits according backend limitations.

As a simple approach, a message should be prompted from app requiring some data filtering before deep pagination.

**Comment by Amelie-V** [comment]
- Message: You have reached the current record limit (10,000). To view more records please refine your query.
- Behaviour: When user has scrolled until the last records, make appear the message with a smooth effect
- Design: text + Illustration -> Sketch
- Pagination behaviour: 9990-10,000 of 10,000
