### ISSUE TITLE
[FEATURE] Change role of user from SDK

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4681]
**Is your feature request related to a problem? Please describe.**

I have no way to change the role of an existing user without creating a new user.

**Describe the solution you'd like**

A method to change the role of an existing user from the SDK.

**Describe alternatives you've considered**

**Additional context**
 Usually the change is from a more restrictive to a less restrictive role e.g. annotator > admin or admin > owner.

**Comment by burtenshaw** [comment]
@nataliaElv The use case is clear. 

**Server side** @jfcalvo @frascuchon It seems like the user endpoints have not been carried over to `v1` and most user operations are still in the `v0` api. https://github.com/argilla-io/argilla-server/blob/main/src/argilla_server/apis/v1/handlers/users.py . We should start off by creating these server endpoints. I'm happy to take this on.

**Client side**: @frascuchon Once the the server operations exist then the SDK work is straightforward.
