### ISSUE TITLE
[BUG-python/deployment]Hugging Face Space crashing consistently in v1.25

### ISSUE THREAD

**Issue by stevengans** [recognai/rubrix#4689]
**Describe the bug**
Hugging Face Argilla Space continues to crash every few hours.

**Stacktrace and Code to create the bug**
```
Runtime error
end/generic_elastic.py", line 82, in get_instance
    client=ClientAdapterFactory.get(
  File "/opt/venv/lib/python3.10/site-packages/argilla_server/daos/backend/client_adapters/factory.py", line 46, in get
    version, distribution = cls._fetch_cluster_version_info(client_config)
  File "/opt/venv/lib/python3.10/site-packages/argilla_server/daos/backend/client_adapters/factory.py", line 82, in _fetch_cluster_version_info
    raise GenericSearchError(error)
argilla_server.daos.backend.base.GenericSearchError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fa9b06a1300>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fa9b06a1300>: Failed to establish a new connection: [Errno 111] Connection refused)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 610, in __aenter__
    await self._router.startup()
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 711, in startup
    await handler()
  File "/opt/venv/lib/python3.10/site-packages/argilla_server/_app.py", line 189, in setup_elasticsearch
    _setup_elasticsearch()
  File "/opt/venv/lib/python3.10/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/argilla_server/_app.py", line 179, in _setup_elasticsearch
    raise ConfigError(
pydantic.errors.ConfigError: Your Elasticsearch endpoint at http://localhost:9200 is not available or not responding.
Please make sure your Elasticsearch instance is launched and correctly running and
you have the necessary access permissions. Once you have verified this, restart the argilla server.


ERROR:    Application startup failed. Exiting.
```

**Expected behavior**

**Environment:**
 - Argilla Version [v1.25]

**Additional context**
It works for a few hours before crashing.

**Comment by nataliaElv** [comment]
Hi @stevengans ! So you still experience the same issue if you upgrade to 1.26.0?

**Comment by stevengans** [comment]
@nataliaElv even on 1.26.1 latest i hit this error:
pydantic.errors.ConfigError: Your Elasticsearch endpoint at http://localhost:9200 is not available or not responding.
Please make sure your Elasticsearch instance is launched and correctly running and
you have the necessary access permissions. Once you have verified this, restart the argilla server.

**Comment by nataliaElv** [comment]
Thanks for reporting back! I'll cc my colleagues @davidberenstein1957 and @frascuchon . They should be able to follow up with your case.

**Comment by davidberenstein1957** [comment]
@stevengans, @jfcalvo is working on exploration. The difficulty with HF spaces is not having access to the ES logs or being able to access the terminal so ou debugging capabilities are a bit limited.

**Comment by frascuchon** [comment]
Thanks @stevengans It would help if you could share with us some usage metrics: number of datasets, kind of datasets, records, ... All this kind of info would be great for us.

Thanks!

**Comment by jfcalvo** [comment]
Hi @stevengans, we just added two changes on the quickstart docker image, the one used for Argilla Template on Hugging Face spaces:
1. https://github.com/argilla-io/argilla-server/pull/102
  This change will allow us to see ElasticSearch logs clicking on `Logs` button so we can see what is happening with ElasticSearch on the space.
3. https://github.com/argilla-io/argilla-server/pull/109
  This change increases the memory limits for ElasticSearch from `512m` to `1g`. Be believe the crash could be related with this short restriction of memory for Elastic.

Please could you check if the problem is still happening with this new updated Argilla Template?. If that's the case and the crash is still happening it would be nice if you share the ElasticSearch logs with us.

To check this please notice that your Argilla HF space should be using `v1.27.0` in the defined Dockerfile: https://huggingface.co/spaces/argilla/argilla-template-space/blob/main/Dockerfile with a line like this:
```dockerfile
FROM argilla/argilla-quickstart:v1.27.0
```

If you duplicate the space using the current [argilla-template-space](https://huggingface.co/spaces/argilla/argilla-template-space) you will get `v1.27.0` so not additional steps are required.

Thanks.

**Comment by stevengans** [comment]
@jfcalvo Just tested it this morning - during my tests I didn't hit this issue with ElasticSearch using ```v1.27.0```

only get this warning - but the space still works so not an issue:
```[04/19/24 12:32:11] WARNING  WARNING:passlib.handlers.bcrypt:(trap bcrypt.py:622
12:32:11 argilla.1 |                              ped) error reading bcrypt version                  
12:32:11 argilla.1 |                              Traceback (most recent call last):                 
12:32:11 argilla.1 |                                File                                             
12:32:11 argilla.1 |                              "/opt/venv/lib/python3.10/site-packag              
12:32:11 argilla.1 |                              es/passlib/handlers/bcrypt.py", line               
12:32:11 argilla.1 |                              620, in _load_backend_mixin                        
12:32:11 argilla.1 |                                  version =                                      
12:32:11 argilla.1 |                              _bcrypt.__about__.__version__                      
12:32:11 argilla.1 |                              AttributeError: module 'bcrypt' has                
12:32:11 argilla.1 |                              no attribute '__about__'```

**Comment by jfcalvo** [comment]
@stevengans that it's a warning about the `bcrypt` package, it's not associated to this issue.

I will close the issue if everything is working for you. Please feel free to open it again or comment any other issue you may have.

Thanks for reporting it!
