### ISSUE TITLE
[BUG-UI/UX] No discarded in the stats progress bar

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4711]
**Describe the bug**
A clear and concise description of what the bug is. Also, draft records look overrepresented here.
The discarded records aren't represented in the progress bar inside the stats section:
<img width="348" alt="Captura de pantalla 2024-04-11 a las 11 36 51" src="https://github.com/argilla-io/argilla/assets/126158523/dcd9b97e-015d-42bf-bfc4-a4c96b237620">

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]:
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]:
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by leiyre** [comment]
It seems that the color of discard and draft is reversed, I can handle it
