### ISSUE TITLE
[DOCS] Varying Default User Credentials

### ISSUE THREAD

**Issue by MikeG112** [recognai/rubrix#4712]
## Which page or section is this issue related to?

AFAICT, the default admin account associated with the docker compose quickstart documented [here](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker_compose.html) does not have the same credentials (`username`=admin, `password`=12345678) as the default admin account that exists in the standalone docker quickstart documented [here](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker-quickstart.html).

One can instead use the docker compose quickstart out of the box by using the credentials `username`=argilla, `password`=1234. One can understand this behavior using the docs as they are (e.g. by following [this](https://github.com/argilla-io/argilla/blob/main/docker/docker-compose.yaml#L17) line to find the 1234 password), but IMO it would useful to both:

- Note those default values in the docker compose quickstart page itself, so one can compose up and log into a defaullt account without having to read anything else.
- Make default user account credentials consistent across all containerized deployment mechanisms, to avoid confusion.

**Comment by nataliaElv** [comment]
Thanks for reporting @MikeG112 ! I'm cc'ing @frascuchon so he's aware of the issue. 
If this is something you'd like to work on as a contributor let us know 😄
