### ISSUE TITLE
[BUG-UI/UX] `SpanQuestion` selections can get weirdly overwritten

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4719]
**Describe the bug**
I trtied to select some text and suddenly overwrite all my previously made annotations. Also, the previously selected tags underneath the text remain in the record.

**To Reproduce**
1. Go to a SpanQuestion without overlapping spans
2. annotate some things
3. accidentally highlight the rest.

**Expected behavior**
Provide a warning or CTRL-Z-like return to the previous state. 

**Screenshots**
https://github.com/argilla-io/argilla/assets/25269220/af76e16e-597d-48a6-b8de-c929757ee6dd

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Brave
 - Argilla Version [e.g. 1.0.0]: 1.26.1
 - ElasticSearch Version [e.g. 7.10.2]: NA
 - Docker Image (optional) [e.g. argilla:v1.0.0]: NA

**Additional context**
NA

**Comment by cceyda** [comment]
+1 for "CTRL-Z-like return to the previous state"
