### ISSUE TITLE
[FEATURE] Support for Markdown Rendering in Fields with SpanQuestion

### ISSUE THREAD

**Issue by Tomas0413** [recognai/rubrix#4722]
**Is your feature request related to a problem? Please describe.**
I've encountered an issue with markdown rendering in fields that are also configured with a SpanQuestion. Specifically, when a field is set to render as markdown (e.g., using `rg.TextField(name="response", title="Response", use_markdown=True)`), it displays correctly. However, if the same field is associated with a SpanQuestion for annotation, the markdown rendering does not work, and the text is displayed as plain text. Below is the SpanQuestion configuration used:
```code
rg.SpanQuestion(
    name="response_evaluation",
    title="Highlight the parts of the response that are correct or incorrect:",
    labels={
        "CORRECT": "Correct",
        "INCORRECT": "Incorrect"
    },
    field="response",
    required=True
)
```

**Describe the solution you'd like**
I would like the system to support markdown rendering even when the field is linked with a SpanQuestion. This would enable annotators to view and interact with formatted text, preserving the original markdown features while enabling efficient and accurate annotation.

**Describe alternatives you've considered**
An alternative could be to temporarily render the text as markdown in a separate view to assist annotators with understanding the formatting context, then switch back to plain text for the actual annotation process. However, this is not as seamless and might complicate the annotation workflow.

**Additional context**
This feature would be particularly beneficial for projects involving detailed examination of chatbot responses and document analysis where understanding the formatting is crucial. Enabling markdown in SpanQuestions would significantly enhance the usability and effectiveness of our annotation tools.

**Comment by amritap-ef** [comment]
Also interested
