### ISSUE TITLE
[BUG-UI/UX] Search queries in korean get flipped (FeedbackDataset)

### ISSUE THREAD

**Issue by cceyda** [recognai/rubrix#4733]
**Describe the bug**
On a feedback dataset (using SpanQuestion if relevant, older dataset types don't have this problem) if I type in the search bar in Korean it flips the text like:
type `한국어`-> press_enter-> `어국한`. There should be no flip. Seems to be happening on Chrome only(?), it works fine on safari. (& also doesn't happen with english)

- This doesn't happen when copy pasting text, only when typing.
- & it shows the wrong number of results compared to safari, seems to be analyzing the text differently.

**Screenshots**

https://github.com/argilla-io/argilla/assets/15624271/6ea53635-bdcb-4a2a-a5df-dbdde027acff

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: chrome
 - Argilla: 1.26 ~ 1.27

**Comment by nataliaElv** [comment]
Thanks for reporting @cceyda ! I'm cc'ing my colleague @damianpumar here. He should be able to help 🙂

**Comment by nataliaElv** [comment]
@cceyda Just a heads up so you know that @damianpumar was able to fix the issue with the korean characters flipping and it will be published in our upcoming release! It should be out by the end of next week, but you can try it out already using the `develop` branch. 😃
