### ISSUE TITLE
[FEATURE] Highlight search matches

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4747]
**Is your feature request related to a problem? Please describe.**
When I do a keyword search, I'd like to see what the search is matching in the record.

**Describe the solution you'd like**
Highlight in the record the bit of text that matched my search.

**Describe alternatives you've considered**

**Additional context**

**Comment by Amelie-V** [comment]
Full specs: https://www.notion.so/argilla/Show-highlight-search-terms-2b16e68f888c44688ac0e09ef70cbf68?pvs=4 @damianpumar @leiyre
