### ISSUE TITLE
[DOCS] Questions about installation and configuration

### ISSUE THREAD

**Issue by cufeinfor** [recognai/rubrix#4804]
## Which page or section is this issue related to?

I want to start an active learning task, so based on the documentation, I chose to use Python+Docker+Elasticsearch+Huggingface. Therefore, I chose followed the corresponding modules instruction, as shows in the figure. I did not excute the other configurations because I think I don’t need them, but I am not sure if this is correct.

![step](https://github.com/argilla-io/argilla/assets/26766616/1749f79f-0dd2-476f-b879-fe92232fe7f9)

The specific operation steps are as follows:

**Step1:  I installed the argilla package and several additional packages following the steps in the [Python environment]**(https://docs.argilla.io/en/latest/getting_started/installation/deployments/python.html). Specifically, the following commands were executed:
pip install argilla
pip install "argilla[listeners]"
pip install "argilla[server]"
pip install "argilla[postgresql]"
pip install "argilla[integrations]"
pip install "argilla[tests]"

After this, both argilla and argilla server have installed version 1.27.0, while some extra packages encountered errors due to version incompatibility during installation. However, I did not make any changes and have temporarily shelved them. Do all these packages need to be installed?

Step2:  I followed the [instructions under Docker](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker.html) to configure and successfully configured it. 

But I found that after configuring according to the instructions of Argilla Server and UI, Argilla can only continue to run when Elasticsearch for Argilla is also running, otherwise it will stop running on its own after running for a few minutes. I checked the error message and found that the Argilla server is requesting Elasticsearch for Argilla, as shown in the figure. So I am doubt about this: is the configuration of the argilla server necessary? Is it possible to use only ElasticSearch for Argilla.
![SERVER](https://github.com/argilla-io/argilla/assets/26766616/de1dab39-0251-4cf4-bfab-ef5a7b3a4b4a)

Also, due to my previous use of an old version, I encountered a[ server matching error](https://github.com/argilla-io/argilla/issues/4769) while upgrading to the latest version. Although I ultimately resolved the issue, in order to avoid other potential errors, I chose to uninstall the packages related to Argilla ( including Argilla server, datasets, Elasticsearch, and Elastic transport), and then reinstall them using pip. This allows me to follow the latest instructions for reinstallation and configuration.

Step3: Server configuration. (Not finished)
I see instructions for [server configuration](https://docs.argilla.io/en/latest/getting_started/installation/configurations/server_configuration.html), but I haven't figured out where these environment variables can be configured and what configuration files are there? I didn't see any corresponding instructions on how to find the path. Also, I'm not sure if this step is necessary?

**Comment by sdiazlor** [comment]
@jfcalvo Could you provide some guidance?

**Comment by jfcalvo** [comment]
Hi @cufeinfor ElasticSearch is a dependency of Argilla, without it Argilla can't work. You can try running the following container to run ElasticSearch:

```sh
docker run -d --name elasticsearch-for-argilla -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:8.5.3
```

Apart from mapping the ports ElasticSearch doesn't need any further configuration.

For the environment variables, if you are running Argilla with Docker you can use the `-e` argument to pass environment variables to the container ([more info about this here](https://docs.docker.com/reference/cli/docker/container/run/#env)). If you are running Argilla locally with Python you can simply defined/export the environment variables in your shell.

**Comment by cufeinfor** [comment]
> Hi @cufeinfor ElasticSearch is a dependency of Argilla, without it Argilla can't work. You can try running the following container to run ElasticSearch:
> 
> ```shell
> docker run -d --name elasticsearch-for-argilla -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:8.5.3
> ```
> 
> Apart from mapping the ports ElasticSearch doesn't need any further configuration.
> 
> For the environment variables, if you are running Argilla with Docker you can use the `-e` argument to pass environment variables to the container ([more info about this here](https://docs.docker.com/reference/cli/docker/container/run/#env)). If you are running Argilla locally with Python you can simply defined/export the environment variables in your sh

> Hi @cufeinfor ElasticSearch is a dependency of Argilla, without it Argilla can't work. You can try running the following container to run ElasticSearch:
> 
> ```shell
> docker run -d --name elasticsearch-for-argilla -p 9200:9200 -p 9300:9300 -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:8.5.3
> ```
> 
> Apart from mapping the ports ElasticSearch doesn't need any further configuration.
> 
> For the environment variables, if you are running Argilla with Docker you can use the `-e` argument to pass environment variables to the container ([more info about this here](https://docs.docker.com/reference/cli/docker/container/run/#env)). If you are running Argilla locally with Python you can simply defined/export the environment variables in your shell.

Understand! Thank you so much!
