### ISSUE TITLE
Accept flat input text for token classification in RubrixLogHTTPMiddleware ner mapper

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#482]
The default `RubrixLogHTTPMiddleware` [record mapper for token classification](https://github.com/recognai/rubrix/blob/master/src/rubrix/client/asgi.py#L35) expect a structured including a `text` field for inputs. This could make prediction model inputs a bit cumbersome. Default mapper could accepts also flat strings as inputs:

```python
def token_classification_mapper(inputs, outputs):
    if isinstance(inputs, str):
        text = inputs
     ...

**Comment by Ankush-Chander** [comment]
Hi @frascuchon 
I intend to get some clarity on this issue if it"s not already undertaken.

Thanks.

**Comment by frascuchon** [comment]
Hi @Ankush-Chander and sorry for the late response. 

Sure! You can go ahead with this issue. 

The idea is to improve [HTTP monitor middleware for token classification](https://github.com/recognai/rubrix/blob/master/src/rubrix/monitoring/asgi.py#L49) by accepting string text as inputs, instead of a dict containing the `text` key.
