### ISSUE TITLE
[BUG-UI/UX] SpanQuestion char level selection & emoji issues

### ISSUE THREAD

**Issue by cceyda** [recognai/rubrix#4834]
**Describe the bug**
@nataliaElv & @Amelie-V  here is the example code for the issues I described in the demo call & some summary of the issues:
- Char level selection works weirdly if there are no spaces and a number in the middle: "Apple10dollars"
- Shift key pressed before starting the selection is ignored (so you have to click shift after selection starts but that auto removes other spans and is hard to work quickly)
- Emoji issue from the older datasets(https://github.com/argilla-io/argilla/issues/2353) seems to still exist in SpanQuestion, i think the underlying cause is the same. If there is an emoji submit button freezes in a loop with the dev console message:
    ```
    {
        "detail": "span question response value `end` must have a value lower or equal than record field `text` length that is `18`"
    }
    ```

**To Reproduce**
```
import argilla as rg

rg.init()

labels = {
            "apple": "ABC",
            "banana": "DEF",
            "pear": "GHI",
            "strawberry": "JKL",
            "mango": "MNO",
            "orange": "PQR",
            "grape": "STU",
            "kiwi": "VWX",
            "pineapple": "YZ"
        }

dataset = rg.FeedbackDataset(
    fields= [ rg.TextField(name="text",required=True)],
    questions=[
        rg.SpanQuestion(
            name="entities",
            title="Labels:",
            labels=labels,
            field="text",
            required=True
        )],
    allow_extra_metadata=True
)
record = [
    rg.FeedbackRecord(fields={"text": "Apple 🥹 Pear 🦸🏻‍♀️"}),
    rg.FeedbackRecord(fields={"text": "Apple🥹Pear🦸🏻‍♀️banana🍌 test"}),
    rg.FeedbackRecord(fields={"text": "Apple10dollars"})
    ]
dataset.add_records(record)
dataset.push_to_argilla(name="debug_spans")
```

**Environment (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome (but also shortly tested in safari and had the same issues)
 - Docker Image: argilla: v1.28

**Comment by nataliaElv** [comment]
Thanks @cceyda ! We'll look into this 😄 cc @damianpumar

**Comment by nataliaElv** [comment]
@burtenshaw I tried to translate the script above to the new SDK and there seems to be an error when passing the dictionary of labels in the `SpanQuestion`. Is this expected?
