### ISSUE TITLE
[FEATURE] Add dependencies to support dev mode on HF Spaces

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#4867]
Hugging Face recently added support for dev mode. Enabling some features like connecting to the space through SSH or enabling a VS Code server so remote changes can be done easily.

Right now dev mode can't be enabled on Argilla because some dependencies are missing. We should modify our Argilla template to add these dependencies.

More information about the new dev mode can be found here: https://huggingface.co/dev-mode-explorers

cc @MoritzLaurer

**Comment by jfcalvo** [comment]
Some insights after a quick exploration:
* A pro account is needed on HF to enable dev mode. This means that someone with a pro account should check that everything is working as expected after the changes.
* Is not so easy as modifying the Argilla Space template `Dockerfile`. Further changes are required because the application is expected to be at `/app` (is not the case for our docker images) and the owner of the folder must be the user with uid `1000`.

With this in mind we can discuss if it's good idea to create a new Argilla `Dockerfile` specific to be used on HF.

**Comment by jfcalvo** [comment]
Another important aspect is that HF dev mode is useful to play with changes in the source code of the application. We don't have right now any Docker image including the source code of Argilla and using a dev server. Maybe we need to think about a "dev" image including the Argilla source code.

**Comment by jfcalvo** [comment]
I have defined [here](https://huggingface.co/spaces/jfcalvo/argilla-template-space-dev-mode/blob/main/Dockerfile) an Argilla space template with changes to its `Dockerfile` supporting dev mode.

I will check if it's working as expected once my user is PRO.

**Comment by MoritzLaurer** [comment]
Thanks for working on this @jfcalvo! For anyone else who wants to test this: you can request to join this HF organization to get access to dev mode without a pro account: https://huggingface.co/dev-mode-explorers
