### ISSUE TITLE
[BUG-UI/UX] records not showing up in the UI

### ISSUE THREAD

**Issue by shaikhalid** [recognai/rubrix#4877]
**Describe the bug**
I followed the quikstart guide using docker to setup Argilla and created the text classification dataset but I am not able to see the record entries in the UI. When I do dataset.records I can see the records in the jupyter notebook

**To Reproduce**
1. Go to quickstart guide
2. Run the docker command 
3. Follow the guide to create a text classification dataset
4. use the dataset.add_records api to add the records
5. No records will get reflected on the UI

**Expected behavior**
Records appear on the UI

**Screenshots**

**Environment (please complete the following information):**
─ Argilla Info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Connected to http://192.168.64.3:6900                                                                                           │
│                                                                                                                                 │
│  • Client version: 1.28.0                                                                                                       │
│  • Server version: 1.28.0                                                                                                       │
│  • ElasticSearch version: 8.8.2

 - OS: MacOS 14.4.1
 - Browser :Chrome

**Additional context**
I tried setting up argilla multiple times in MacOs and Linux VM but it never worked as expected. Not sure if I am missing something

**Comment by nataliaElv** [comment]
Hi @shaikhalid ! Can you share any code snippets or screenshots so our team can take a look at what could be happening?

**Comment by 74Mazen74** [comment]
You need to run the following two lines after pushing the dataset to argilla and defining the records:
**

> ds=rg.FeedbackDataset.from_argilla(name="<your_dataset_name>", workspace="<your_workspace>")
> ds.add_records(records)

**

**Comment by kgdrathan** [comment]
came across the same issue.
@shaikhalid were you able to resolve it?
