### ISSUE TITLE
include CI/CD for docs

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4895]

**Comment by frascuchon** [comment]
@davidberenstein1957 Almost everything is working in #4891. The only missing part is the `gh-pages` branch configuration, required by the [docs CI](https://github.com/argilla-io/argilla/pull/4891/files#diff-732aa210e47e3f8b2ad0a8dd725be661851a858dcfac6075d46bd021614cf106R48)

You can start working from #4891
