### ISSUE TITLE
[v1 DOCS] Add banner with link to the new docs

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#4920]
Let's add a banner to the Argilla v1 docs to point towards Argilla v2 docs while these two coexist.

**Comment by nataliaElv** [comment]
@davidberenstein1957 Could you share the example you mentioned? If it still exists...

**Comment by burtenshaw** [comment]
Here is an example of Haystack's current view on v1 docs:

![Screenshot from 2024-06-11 10-10-17](https://github.com/argilla-io/argilla/assets/19620375/c3877290-2f9c-4aed-b39d-3647cdb2d161)

Before this, they had a fixed banner add to the HTML template.

**Comment by burtenshaw** [comment]
@davidberenstein1957 posted this haystack image that shows the three core parts warning, welcome, and migraiton

![image](https://github.com/argilla-io/argilla/assets/19620375/cb5eba71-1c58-4780-8d48-6c92f3406d07)

**Comment by Amelie-V** [comment]
Maybe simply changing the walkthrough video for a serie of callout similar to the Haystack example. The red warning (first screenshot is similar to the one we had in the [1.29 highlights](https://github.com/argilla-io/argilla/releases/tag/v1.29.0).

Looking at these cool callouts, I'm not sure we have to created a top fixed banner to the docs pages.

**Comment by davidberenstein1957** [comment]
NEW DOCS
<img width="1728" alt="image" src="https://github.com/argilla-io/argilla/assets/25269220/24896d65-3fab-483e-8231-3a6686c89938">

**Comment by davidberenstein1957** [comment]
OLD DOCS

<img width="1728" alt="image" src="https://github.com/argilla-io/argilla/assets/25269220/7d7626d7-f1c5-4d8d-8141-20cd1649a1db">

**Comment by nataliaElv** [comment]
Looking nice!
