### ISSUE TITLE
[FEATURE] Improve settings defaults warnings when fetching from Argilla

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#4928]
**Is your feature request related to a problem? Please describe.**
When fetching a dataset from Argilla, the empty warning settings message is shown. This can be confusing to users.

![image](https://github.com/argilla-io/argilla-server/assets/2518789/fd606686-5076-477d-9568-053612c2416a)

**Describe the solution you'd like**
The default empty warning/error should be shown when creating/publishing datasets.

**Comment by burtenshaw** [comment]
@frascuchon Have you resolved this within the `Settings` refactor for update?

**Comment by frascuchon** [comment]
Not really. The confusing warning message is raised from `Dataset.__init__` method since dataset settings are loaded lazily and the default settings value is assigned when fetching datasets from Argilla.
