### ISSUE TITLE
[FEAT] Delete records

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4930]
I would like to also have the possibility of deleting records.

**Comment by burtenshaw** [comment]
@nataliaElv This is something we could feasibly fit into v2. Do you think it adds value?

**Comment by nataliaElv** [comment]
Yes it does! 😃 I'll add it to the milestone

**Comment by burtenshaw** [comment]
@sdiazlor 

How do you plan on interfacing this feature? I first expected just a record delete method, like so:

```python
for record in dataset.record:
    record.delete()
```

**Comment by burtenshaw** [comment]
@sdiazlor Are you still working on this? If not, I can take it on.

**Comment by sdiazlor** [comment]
@burtenshaw Yes, I worked on this and have the changes locally. These days I was waiting for the code migration to create the PR in the main argilla repo and no more PRs here

**Comment by nataliaElv** [comment]
I'm moving this issue to the v2.0.0 milestone in the `argilla` repo then! So @sdiazlor can link the PR
