### ISSUE TITLE
[QUESTION] Regarding password of user

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#4933]
When creating a user if you do not set a password, this one is created randomly thanks to `_generate_random_password`, what it's nice. However, how can we get that randomly generated password and share it with our annotators? As far as I know

- When retrieving a user, password is not shown for security
- A user can not be updated, so no password can be updated later to add your own

**Comment by burtenshaw** [comment]
Hey @sdiazlor 

Thanks for the feedback. A user's password can be accessed during the process when it was initialized, so if a random value was used it will need to be printed/ looged. For example:

```python
import argilla_sdk as rg

client = rg.Argilla(api_url="http://localhost:6900", api_key="argilla.apikey")

user = rg.User(username="benny")
user.password
# >> random_value
user.create()
user.password
# >> same random_value

gotten_user = client.users("benny")
assert gotten_user.password is None
```
We could warn when `_generate_random_password` that password should be logged.

**Comment by sdiazlor** [comment]
Okay, thanks @burtenshaw. I believe that providing a warning to the user can be helpful. By the moment, I'll add this to the docs too.

**Comment by frascuchon** [comment]
@burtenshaw Definitely we should show a message to users to access the password attribute

**Comment by burtenshaw** [comment]
As suggested by @jfcalvo, we could make password a required parameter for `User.create()` when the user does not exist yet. This would allow for the init of an existing `User` resource without a password, but stop this problem.

**Comment by burtenshaw** [comment]
@jfcalvo Do you think this is one you could tackle? I can help to set you up if necessary.

**Comment by jfcalvo** [comment]
Thanks @burtenshaw I will take a look and ping you in the case I need help.
