### ISSUE TITLE
[FEATURE] [SDK] Improve logging when adding and updating records

### ISSUE THREAD

**Issue by burtenshaw** [recognai/rubrix#4947]
When adding records from a notebook the logging is very minimal:

![image](https://github.com/argilla-io/argilla-python/assets/19620375/8c421f8e-6a5b-422a-9b64-8d83a0c5c6d3)

It would make sense to 
- show a status bar
- log the number of records that were added or updated
- log a link to the dataset
-  be notebook compatible. 
- consider returning the`DatasetRecords` object instead of the records themselves.

**Comment by frascuchon** [comment]
cc @burtenshaw do you think this can be relevant for v2?

**Comment by burtenshaw** [comment]
@frascuchon @nataliaElv Yes. I'd like to work on this asap. Move it to 2.0.
