### ISSUE TITLE
[DOCS] Add contributing pages

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#4952]
```[tasklist]
### Tasks
- [ ] create a page for [GitHub workflows](https://docs.argilla.io/en/latest/community/contributing.html). We can copy-paste this reasoning and page.
- [ ] create a page for the [Development environments](https://docs.argilla.io/en/latest/community/developer_docs.html). Feel free to adapt this to the current deployment of Argilla UI, docs (mkdocs now) and server (@jfcalvo), and SDK 2 (@burtenshaw )
```

**Comment by nataliaElv** [comment]
@davidberenstein1957 What's the status of this issue? Is this something still pending to do? If so, is it for 2.0 or can be left for later?

**Comment by burtenshaw** [comment]
@nataliaElv We have basic outline of these pages, but let's move it to 2.1
@davidberenstein1957 Should we expand on this issue to improve what we have?

**Comment by sdiazlor** [comment]
Added here: https://docs.argilla.io/latest/community/contributor/
