### ISSUE TITLE
[DOCS] Improvements to docker-compose getting started installation guide

### ISSUE THREAD

**Issue by giorgionicoli** [recognai/rubrix#4964]
Hey team, as discussed [on Slack](https://rubrixworkspace.slack.com/archives/C02G2TZFG3V/p1717576955218259), I'm opening this issue regarding a couple of improvements to the `docker-compose`  installation/deployment getting started [guide](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker_compose.html):

- The link to the `docker-compose.yaml` for the `wget` command seems to be outdated and should point to https://raw.githubusercontent.com/argilla-io/argilla/develop/examples/deployments/docker/docker-compose.yaml
- If one wants to run this locally, the `docker-compose.yaml` has to be amended, and in particular line 39 `#- xpack.security.enabled=false` should be uncommented, otherwise the argilla-server container can't communicate with the elasticsearch container.
- It could be worth mentioning also that, compared to the quickstart example, the default user used here is `argilla` with password `1234`, instead of `owner` and `12345678`.
- Finally, even though as per the `docker-compose.yaml` comments, one could override the password and api-key of the default used by uncommenting and setting the variables `DEFAULT_USER_PASSWORD` and `DEFAULT_USER_API_KEY`. I could not get it to work, and the default user stayed unchanged. Maybe those comments are outdated? And maybe this is not really strictly speaking related to documentation, but I thought worth mentioning anyway.

I hope this is all useful!

## Which page or section is this issue related to?

https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker_compose.html

**Comment by giorgionicoli** [comment]
I can probably look into preparing a small PR in the next few days.

**Comment by MikeG112** [comment]
For another data point, I had the same experience regarding bullet point 4, and haven't yet understood how to alter the default user credentials in the server image successfully via environment variables.

Also, if you do do this work @giorgionicoli, I think https://github.com/argilla-io/argilla/issues/4712 can be closed if you address bullet point 3.

**Comment by MikeG112** [comment]
I'm not sure what changed, but in starting to debug this further I noticed that after upgrading to a new server image

(in my case from 
`argilla/argilla-server@sha256:6d80baa6359109797c72afb316c1417234ab781a1288797043440bc9d69f75fd` -> `argilla/argilla-server@sha256:b1db6256bbc614946ec648ee19b637ea65a1152924e33d2519dc441db3f5d2c6`)

I can no longer reproduce the issue with setting the `DEFAULT_USER_PASSWORD`.

So that point may be addressed already in main, depending on how the newer image was built.

**Comment by jo-jstrm** [comment]
Thanks for providing the correct link to the docker compose here :). 

I want to highlight that the link in the [docs](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker_compose.html) is still broken. Would be an easy fix I think and might save some folks the headache of searching the compose file.

**Comment by sdiazlor** [comment]
It should be fixed in the latest documentation: https://docs.argilla.io/latest/getting_started/how-to-deploy-argilla-with-docker/. Credentials are fixed too: https://docs.argilla.io/latest/how_to_guides/user/#initial-users-and-credentials
