### ISSUE TITLE
[TASK] Avoid creating Docker images from pull request into our main Docker hub account

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#4965]
Right now we are generating Docker images for every pull request and uploading them to our main `argilla/argilla-server` and `argilla/argilla-quickstart` like `pr-1234`.

This is causing confusion to some of our users in the sense that they are using `pr-*` docker images to deploy and use Argilla.

At the end we should have only specific final versions like `1.29.0` and having other "development" images possibly in a different repository (but we can explore other ideas).

**Comment by frascuchon** [comment]
Done
