### ISSUE TITLE
[DOCS] Analyzing Annotation Metrics with FastFit Model Predictions blog post contains link to copied blog post

### ISSUE THREAD

**Issue by stephantul** [recognai/rubrix#4994]
Hi!

In [this article](https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/training-fastfit-agreement.html), you link to a blog post about FastFit and Setfit on Medium. This blog post is actually almost a direct copy of [this one](https://pub.towardsai.net/few-shot-nlp-intent-classification-d29bf85548aa) (unfortunately, this one is behind a paywall). It even copies the image, but cuts off the original author name. 

I think you should link to the original source, or at least mention that it was based on the other article. 

## Which page or section is this issue related to?

https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/training-fastfit-agreement.html

**Comment by dvsrepo** [comment]
thanks for reporting @stephantul ! @sdiazlor can take care of this

**Comment by sdiazlor** [comment]
Thanks for noticing @stephantul! I'll tackle this right away
