### ISSUE TITLE
[DOCS] pulling user by ID does not work as specified in the docs

### ISSUE THREAD

**Issue by datapumpernickel** [recognai/rubrix#5011]
Hi!

thanks for this wonderful framework for text annotation. Very easy to implement and use! 

I am trying to get a user by id and it is not working as expected. The docs [here](https://docs.argilla.io/en/latest/getting_started/installation/configurations/user_management.html#get-a-user-by-id) give the following code: 

``` python
import argilla as rg

rg.init(api_url="<ARGILLA_API_URL>", api_key="<ARGILLA_API_KEY>")

user = rg.User.from_id("00000000-0000-0000-0000-000000000000")
```

but this does not work. What does work is: 

``` python
import argilla as rg

from uuid import UUID

rg.init(api_url="<ARGILLA_API_URL>", api_key="<ARGILLA_API_KEY>")

user = rg.User.from_id(UUID("00000000-0000-0000-0000-000000000000")) ## <--- note the UUID() here


```

**Environment:**
 - Argilla Version [1.29.0]:
 - Docker Image (optional) [https://hub.docker.com/layers/argilla/argilla-quickstart/latest/images/sha256-6c33f7ce577d90cc6a1c292ff79611237da8c5e3f33d1ef7538bc05c4bc25316?context=explore]:

**Comment by sdiazlor** [comment]
@datapumpernickel Thanks for noticing, we'll update it soon or feel free to open a PR with that change :)

**Comment by datapumpernickel** [comment]
Made a PR (#5044), but I am not sure about the tests that need to be run for it to be included. :) Maybe it is helpful, otherwise feel free to close.
