### ISSUE TITLE
[ENHANCEMENT] Make mapping function in DatasetRecords.log compatible with multiple attributes

### ISSUE THREAD

**Issue by burtenshaw** [recognai/rubrix#5043]
# What
It is not possible to use the `mapping` parameter in the `log` method to assign one column of the incoming dataset to multiple Argilla attributes.

# why
This impacts text generation datasets where the annotator is given a `TextQuestion` and asked to correct one of the fields. I.e. a prompt or response.

# how
The problem is caused by the fact that we use a dictionary to define the mapping. This could be remedied by reversing the dictionary. 

# what now
You can get round this by: 1. renaming the columns in the dataset 👎  2. iterating over the dataset and defining `rg.Record`.

**Comment by davidberenstein1957** [comment]
Would it be possible to have 2 arguments too: `mapping`  and `reverse_mapping`? This might also be easier with deprecating and people can choose their preferred way of working? Not sure if this is common in other frameworks and or might complicate the process.

**Comment by burtenshaw** [comment]
> Would it be possible to have 2 arguments too: `mapping` and `reverse_mapping`? This might also be easier with deprecating and people can choose their preferred way of working? Not sure if this is common in other frameworks and or might complicate the process.

This is a friendly approach, but I think it would complicate things.

**Comment by nataliaElv** [comment]
@burtenshaw Expand documentation for 2.1.0
