### ISSUE TITLE
[TASK] Add restriction to update dataset distribution settings

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#5050]
We should add a restriction to only allow updating a dataset distribution settings when the associated records for the dataset has not responses.

As an alternative to this we could do the same but only allowing the update for datasets that have not records with `status` as `completed`.

We should do what is better from a performance point of view and return a easy to understand message to the user if there is an error.

**Comment by frascuchon** [comment]
Fixed by #5171
