### ISSUE TITLE
[DOCS] Document how to setup HF OAuth

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#5091]
We should re-introduce the guide on how to setup HF OAuth.

Initially I'd say we can add a new section here: https://argilla-io.github.io/argilla/dev/getting_started/quickstart/

Setup Hugging Face sign-in

or something like that

wdyt @sdiazlor @davidberenstein1957 ?

**Comment by dvsrepo** [comment]
we can take the opportunity to improve the previous guide!

**Comment by sdiazlor** [comment]
IMO, I would only focus on how to set it up and remove the 'create a dataset' section, as it's the same as the quickstart and can create confusion about whether they are different methods.

**Comment by dvsrepo** [comment]
> IMO, I would only focus on how to set it up and remove the 'create a dataset' section, as it's the same as the quickstart and can create confusion about whether they are different methods.

Fully agree!

**Comment by davidberenstein1957** [comment]
Perhaps related: https://github.com/argilla-io/argilla/issues/5097

**Comment by nataliaElv** [comment]
I'm closing and removing the 2.0 milestone, since this is already merged with main 🙂
