### ISSUE TITLE
[BUG-UI/UX] Issues with argilla/argilla-template-space-with-oauth space

### ISSUE THREAD

**Issue by MoritzLaurer** [recognai/rubrix#5097]
**Describe the bug**

Two issues with the [argilla/argilla-template-space-with-oauth](https://huggingface.co/spaces/argilla/argilla-template-space-with-oauth) space:

1. When I'm on the space and I click on `Sign in with Hugging Face` I get a 400 Invalid client_id error (see screenshot). 
<img width="225" alt="Screenshot 2024-06-23 at 15 01 44" src="https://github.com/argilla-io/argilla/assets/41862082/26f004e2-bd1e-41b3-8ca4-4f1184d58efc">

2. When I duplicate the space and I do not specify an owner password, I get the following error while the space container is building: 
```
Runtime error
sure this value has at least 8 characters 
13:06:21 argilla.1 | (type=value_error.any_str.min_length; limit_value=8)
13:06:21 argilla.1 | api_key
13:06:21 argilla.1 |   ensure this value has at least 8 characters 
13:06:21 argilla.1 | (type=value_error.any_str.min_length; limit_value=8)
13:06:21 system    | argilla.1 stopped (rc=1)
13:06:21 system    | sending SIGTERM to elastic.1 (pid 10)
13:06:21 elastic.1 | [2024-06-23T13:06:21,726][INFO ][o.e.n.Node               ] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] stopping ...
13:06:21 elastic.1 | [2024-06-23T13:06:21,727][INFO ][o.e.c.f.AbstractFileWatchingService] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] shutting down watcher thread
13:06:21 elastic.1 | [2024-06-23T13:06:21,728][INFO ][o.e.c.f.AbstractFileWatchingService] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] watcher service stopped
13:06:21 elastic.1 | [2024-06-23T13:06:21,733][INFO ][o.e.x.m.p.NativeController] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] Native controller process has stopped - no new native processes can be started
13:06:21 elastic.1 | [2024-06-23T13:06:21,733][INFO ][o.e.x.w.WatcherService   ] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] stopping watch service, reason [shutdown initiated]
13:06:21 elastic.1 | [2024-06-23T13:06:21,734][INFO ][o.e.x.w.WatcherLifeCycleService] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] watcher has stopped and shutdown
13:06:22 elastic.1 | [2024-06-23T13:06:22,156][INFO ][o.e.n.Node               ] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] stopped
13:06:22 elastic.1 | [2024-06-23T13:06:22,157][INFO ][o.e.n.Node               ] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] closing ...
13:06:22 elastic.1 | [2024-06-23T13:06:22,164][INFO ][o.e.n.Node               ] [r-moritzlaurer-argilla-template-space-with-oauth-xupi-f583f-w44] closed
13:06:24 system    | elastic.1 stopped (rc=-15)
```

I could fix it by providing a 8 character owner password, but this requirement should probably either be made explicit/enforced during space creation/duplication, or removed. 

**Environment (please complete the following information):**

Chrome browser with current version of the HF space.

**Comment by frascuchon** [comment]
Thanks for your feedback, @MoritzLaurer!

For the first problem, there is some missing info you should provide when setting up the space. The OAUTH app client ID (and secret) is missing. We need to improve the docs and add an HF OAuth setup. Meanwhile, you can take a look at the [old one](https://docs.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html#setting-up-hf-authentication). Basically, you should set the secrets OAUTH2_HUGGINGFACE_CLIENT_ID, and OAUTH2_HUGGINGFACE_CLIENT_SECRET with the values from your oauth application.

For the second error, those values are exposed when setting up the space, but a default value of 12345678 is provided when not defined.  In your case, the default values are overridden with empty strings.

**Comment by MoritzLaurer** [comment]
thanks @frascuchon, I confirm that following the old [oauth docs here](https://docs.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html#setting-up-hf-authentication) solved the issue for me.

**Comment by nataliaElv** [comment]
hey @MoritzLaurer ! Closing this issue in favor of #5091 if that's ok. Feel free to reopen it if necessary.
