### ISSUE TITLE
[FEATURE] relax `typer` constraints

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5104]
**Is your feature request related to a problem? Please describe.**
Currently, Argilla 1 depends on typer <0.10 but currently typer is at 0.13 so it might be worth relaxing these constraitns.

**Describe the solution you'd like**
relax the contraints

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by frascuchon** [comment]
we shouldn't change argilla-v1 setup. As far as I understand this problem exists already with `argilla<2.0.0` right?

The `argilla-v1` is a renamed package to support both SDK versions, but its behavior shouldn't be modified.

**Comment by davidberenstein1957** [comment]
Yes, it did, however, given that we do intend to dedicate to support fixes, I am not sure if we don't want to support things like this at all or just only want to do explicit bug fixes. 

I don't know what is common practice for relaxing version constraints after deprecation but it doesn't sound very weird to do this for a certain period.

**Comment by davidberenstein1957** [comment]
Partially resolved through this PR https://github.com/argilla-io/argilla/pull/5164
