### ISSUE TITLE
[FEATURE] add method to deploy on spaces through `huggingface_hub`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5108]
**Is your feature request related to a problem? Please describe.**
Argilla is cool but sometimes deployment can contain a lot of clickety steps with copy_pasting.

**Describe the solution you'd like**
Some underlying code that goes over steps on https://huggingface.co/docs/hub/en/spaces-sdks-docker-argilla but through the `huggingface_hub`SDK. 
https://huggingface.co/docs/huggingface_hub/main/en/guides/manage-spaces#manage-your-space

Also, the client might easily be initialized with the HF key headers after.

```python
rg.deploy_on_spaces(
    repo_id="user/name",
    private=True,
    admin_username=...,
    admin_password=...,
    admin_apikey=...,
) 
```

show a message:

```
Argilla has been deployed on a private HF Space with url http://hf.co/spaces/user/name. You can now connect with 
Client(etc)
```
**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
@davanstrien as hub expert, WDYT?

**Comment by davanstrien** [comment]
I think this could be very nice, especially for tutorials/demos, etc. I think one thing to consider would be persistent storage. It probably doesn't make sense to set that as default, but I think if it's not enabled, it might be nice to keep showing warnings when interacting with the client?
