### ISSUE TITLE
[DOCS]  I cannot create the space in hugging face in this multiclass doc

### ISSUE THREAD

**Issue by micuentadecasa** [recognai/rubrix#5134]
## Which page or section is this issue related to?
(https://docs.argilla.io/en/latest/tutorials/notebooks/labelling-textclassification-setfit-zeroshot.html)

the link to create the space takes me to HF, I have tried multiple combinations of the keys, and I use the free EPHEMERAL store space, but always there is an error when creating the space, is it because selecting the free space?

17:25:23 argilla.1 | ValidationError: 1 validation error for WorkspaceCreate
17:25:23 argilla.1 | name
17:25:23 argilla.1 |   string does not match regex "^(?!-|_)[a-z0-9-_]+$" 
17:25:23 argilla.1 | (type=value_error.str.regex; pattern=^(?!-|_)[a-z0-9-_]+$)
17:25:24 system    | argilla.1 stopped (rc=1)
17:25:24 system    | sending SIGTERM to elastic.1 (pid 10)

Regards.

```[tasklist]
### Tasks
```

**Comment by davidberenstein1957** [comment]
Hi @micuentadecasa. Did you manage to already create an argilla space and connect to it? I think the name of the workspace you are trying to create does not align with the workspace regex requirements, which are used as validation to allow for elastic search indexes. Did you set any of the workspace environment variables (`*_WORKSPACE`) to something that does not match `"^(?!-|)[a-z0-9-]+$"`?

Normally the ephemeral storage is fine and can be used with the risk of losing your data upon inactivity.
