### ISSUE TITLE
Not possible to set API URL in custom docker compose deployments in version `1.29.0`

### ISSUE THREAD

**Issue by stphnthiel** [recognai/rubrix#5175]
**Describe the bug**
In the above mentioned version, talking to a custom deployment (set up based on your docker compose example) from Argilla running locally will fail.

```python
rg.init(api_url="...", api_key="...")
```
will result in a `WrongResponseError` when providing the base url of the deployment.

**Expected behavior**
`rg.init..` runns successfully and I can interact with the deployment

**Analysis:**

The API seems to be namespaced to `/api/v1/...` in `argilla-server` version `v1.29.0` (currently `latest` on docker hub and pypi). But the local SDK tries to request `/api/me` to get initial confirmation of the `api_key` and thus fails. 

There is no other possible option to provide the `api_url` so it starts working, because of this.

**NOTE:** This problem does not exist in `v2.0.0rc2` (both local SDK and `argilla-server`)

**Comment by davidberenstein1957** [comment]
@nataliaElv added v1.29.1 as milestone for bug fixes

**Comment by frascuchon** [comment]
Hi @stphnthiel  and thanks for reaching out.

I'm trying to reproduce this error but I can't. The v1.29.0 server provides both API versions aligned, so `/api/v1/me` and `/api/me` are available (you can try the API docs for [v0](http://0.0.0.0:6900/api/docs) and  [v1](http://0.0.0.0:6900/api/v1/docs).

You can verify the running server version with:
```bash
curl -X 'GET' \
  'http://0.0.0.0:6900/api/v1/version' \
  -H 'accept: application/json'
```

To make sure this works, you should use the same argilla SDK. Which client version are you using?
