### ISSUE TITLE
[FEATURE] Migrate `media to html` utility methods to v2 sdk

### ISSUE THREAD

**Issue by burtenshaw** [recognai/rubrix#5177]
**Is your feature request related to a problem? Please describe.**

To annotate media other than text, users need to represent the media as HTML. In the legacy SDK, this was supported by a set of utility methods, which can still be tunneled to via the new SDK:

```python
from argilla_v1.client.feedback.utils import audio_to_html, image_to_html, video_to_html, pdf_to_html
```

**Describe the solution you'd like**

This utility methods should be migrated and addressed within the v2 SDK.

**Comment by nataliaElv** [comment]
Conversation template for HTML
