### ISSUE TITLE
[FEATURE] Support Python 3.12.x for argilla client 2.0

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#5194]
Cucu! :) First of all huge congrats on the acquirement, just amazing, really look up to you guys!! I hope you could already savor this achievement, and that you are all doing fine! Un fuerte abrazo!

**Is your feature request related to a problem? Please describe.**
I'm on Ubuntu 24.04 and mainly work with venvs. Since the system Python version is 3.12.3 I could not install the argilla2.0 client.

**Describe the solution you'd like**
Support Python versions 3.12.x by removing the upper version cap. There are arguments to be made not to use upper caps: 
- https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires
- https://discuss.python.org/t/requires-python-upper-limits/12663

**Describe alternatives you've considered**
update the version cap to `<3.13`

**Additional context**

**Comment by davidberenstein1957** [comment]
@frascuchon @burtenshaw I would consider adding this to 2.0 if the tests pass automatically.

**Comment by davidberenstein1957** [comment]
@dcfidalgo If you want, would you be able to create a PR for this?

**Comment by dcfidalgo** [comment]
@davidberenstein1957 Here you go :)
