### ISSUE TITLE
[FEATURE] show more human readable information like `url` or `name` when logging instead of `Resource.id`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5195]
**Is your feature request related to a problem? Please describe.**

Currently, the SDK logs `Resource.id` information which does not always [make sense to humans.](https://github.com/argilla-io/argilla/pull/5187#discussion_r1671867093). I propose logging something more meaningful and rich.

**Describe the solution you'd like**

For
Dataset -> dataset URL / name
Workspace -> workspace name / URL
User -> user name

**Describe alternatives you've considered**

Understanding a UUID

**Additional context**

NA

**Comment by Roy6250** [comment]
Hi @davidberenstein1957, can I work on this issue?

**Comment by Piyush-Kumar-Ghosh** [comment]
Hi @davidberenstein1957 ,

I’d like to work on this issue.

Could you provide some additional details to help guide the implementation?

- Are there any specific fields or formats you prefer for logging the dataset URL/name, workspace name/URL, and username?

- Can you point me to the specific parts of the codebase where these resources (datasets, workspaces, users) are managed?
