### ISSUE TITLE
[BUG-UI/UX] Interface gets stuck when multiple people annotate simultaneously + conflicting copies are created

### ISSUE THREAD

**Issue by MoritzLaurer** [recognai/rubrix#5196]
**Describe the bug**
I did a workshop with 15~ people where everyone annotated images in [this HF OAuth Space](https://huggingface.co/spaces/MoritzLaurer/argilla-template-space-with-oauth) (`image_eval` dataset). Most people logged in with the HF account and annotated simultaneously for a few minutes. Two users reported that, after annotating a few images, they could not click on `Submit` anymore. They reported that refreshing the page resolved the issue. But it occurred several times. 

**To Reproduce**
Maybe reproducible by logging in with a HF user account in the space linked above (possibly requires multiple users submitting things simultaneously). I'm guessing that this is linked to several people being active in Argilla/the HF Space at the same time and maybe when people clicked on submit at the same time it created conflicting copies in the database? The users also reported that the interface showed conflicting copies (screenshots below), although they logged in with separate/unique HF accounts. (I had seen this issue before when I logged in and annotated simultaneously with the same `argilla` user account in two separate browser windows. I assume it's expected when using the same user, but not with different users)

**Expected behavior**
1. User interface does not get stuck sometimes when clicking on `Submit` button. 
2. No conflicting copies created

**Screenshots**
Initial screenshot:
<img width="663" alt="Screenshot 2024-07-10 at 14 31 23" src="https://github.com/argilla-io/argilla/assets/41862082/3fb30dfc-4906-419a-b728-6534dd6590cb">
For some reason, after refreshing again a bit later by the same user, 5 conflicting showed up:  
![Screenshot 2024-07-10 at 14 42 50](https://github.com/argilla-io/argilla/assets/41862082/57e6ebe1-dab0-49e1-b135-c89533daa9d9)

**Environment (please complete the following information):**
Annotation was run in this HF Space: https://huggingface.co/spaces/MoritzLaurer/argilla-template-space-with-oauth/
 - OS [e.g. iOS]: ? 
 - Browser [e.g. chrome, safari]: ? 
 - Argilla Version [e.g. 1.0.0]: 2.0.0r2 (version of python client used to upload data into the container)
 - ElasticSearch Version [e.g. 7.10.2]: ? 
 - Docker Image (optional) [e.g. argilla:v1.0.0]:  argilla/argilla-quickstart:v2.0.0rc1

**Additional context**
@bmateusz reported the issue

**Comment by dvsrepo** [comment]
Thanks for reporting @MoritzLaurer !

> I did a workshop with 15~ people where everyone annotated images in [this HF OAuth Space](https://huggingface.co/spaces/MoritzLaurer/argilla-template-space-with-oauth) (`image_eval` dataset). Most people logged in with the HF account and annotated simultaneously for a few minutes. Two users reported that, after annotating a few images, they could not click on `Submit` anymore. They reported that refreshing the page resolved the issue. But it occurred several times.

There's been some issues these past days with Argilla Spaces running slow or hanging. We've had in the past 100s of users annotating simultaneously on the Hub so it shouldn't be an issue to have many people annotating the same records at the same time. I cc @jfcalvo and @frascuchon because they also noticed some issues these past days.

> **To Reproduce** Maybe reproducible by logging in with a HF user account in the space linked above (possibly requires multiple users submitting things simultaneously). I'm guessing that this is linked to several people being active in Argilla/the HF Space at the same time and maybe when people clicked on submit at the same time it created conflicting copies in the database? The users also reported that the interface showed conflicting copies (screenshots below), although they logged in with separate/unique HF accounts. (I had seen this issue before when I logged in and annotated simultaneously with the same `argilla` user account in two separate browser windows. I assume it's expected when using the same user, but not with different users)

We're going to get rid of this "conflicting" concept once we support a proper automatic task distribution (in the coming days)

To add some context, these bars show the global progress of all annotators, considering submitted or discarded records as completed. This was v1 of supporting a global effort of multiple annotators. `conflicting` in this context means: at least one user `submitted` and at least one user `discarded` but this is under documented and causes user confusion as above. Conflicting seems to entail that "an issue with the response or issue saving the data" so we're getting rid of this and these bars will show `completed` vs `pending` according to the task distribution (e.g., each record is completed if it has two submissions by two different users)

cc @nataliaElv @Amelie-V @burtenshaw for viz

**Comment by MoritzLaurer** [comment]
thanks for the explanation @dvsrepo!
Regarding the first point, if you noticed this systematically, maybe open a thread in #hf-spaces-support to see what can be done about spaces reliability

**Comment by bmateusz** [comment]
I'd like to share some more details. So the group was annotating 20 images together. I was doing them with my own Hugging Face user. When I reached the 15th image, I got stuck. Here’s a screenshot of the error:
<img width="725" alt="Screenshot 2024-07-15 at 13 35 58" src="https://github.com/user-attachments/assets/cdc3cd48-231d-414e-ab2e-d88730fd9895">

I kept pressing Submit, and the same error message came up: "You've reached the end of the data for the pending queue".
To get out of this, I refreshed the page, then I could continue with the queue and do the rest.
I hope this information helps with debugging the issue!

**Comment by MoritzLaurer** [comment]
An update on this by @frascuchon (copied from an internal message). The issue should be solved @bmateusz , but don't hesitate to open it again if it comes up again.
 

> The annotation workflow has been reviewed for the 2.0. The concept of "conflicting" records does not exist anymore, and the annotation progress metrics have been improved to reflect the personal and global progress when users do their annotations. The conflicting records mean that several users gave different feedback to the same record, which can be the case in your example if one user submits the response and the other discards it.
> 
> Related to the performance issues in HF, this only occurred when persistent storage was enabled, and in the later tests, we didn't experiment with the errors with concurrent users. We haven't seen performance problems since then.
> 
> Finally, regarding the Submit button, the problem is related to how the pending queue is currently managed on the front end since the real status of the queue is maintained by the backend.
