### ISSUE TITLE
[BUG-UI/UX] Latex is not rendering in markdown TextFields

### ISSUE THREAD

**Issue by Broyojo** [recognai/rubrix#5198]
**Description**
When trying to render latex in a TextField using `use_markdown=True`, the latex is not rendered.

**To Reproduce**

1. Create a dataset with a TextField that has `use_markdown=True`
2. View a record with latex content and observe that the latex is not rendered.

**Expected behavior**
The latex should be rendered using marked-katex-extension, however it is not rendering.

**Screenshots**

![image](https://github.com/argilla-io/argilla/assets/20409082/db972ea0-54e8-4d8a-bd92-6053c24f6ad8)
![image](https://github.com/argilla-io/argilla/assets/20409082/1f2cfde3-cff5-459b-bc86-fb92fc9d1ff6)

**Environment (please complete the following information):**

 - OS [e.g. iOS]: Arch Linux (Argilla server running on hf spaces from the Argilla docker template)
 - Browser [e.g. chrome, safari]: Brave and Chrome
 - Argilla Version [e.g. 1.0.0]: 1.29.0 (from hf spaces template)
 - ElasticSearch Version [e.g. 7.10.2]: 8.8.2 (from what I can guess from the spaces logs)
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by davidberenstein1957** [comment]
@sdiazlor @damianpumar recently worked on this feature, but I am not entirely sure if this was included in 1.29 or in the 2.0.0rcx?

**Comment by sdiazlor** [comment]
Hi, @Broyojo! Latex rendering in the UI was included in the [2.0.0rc2 release](https://github.com/argilla-io/argilla/releases/tag/v2.0.0rc2).

**Comment by davidberenstein1957** [comment]
@Broyojo, could you check if it works after updating? You should be able to change the tag within the Hugging Face spaces files Dockerfile :)

**Comment by Broyojo** [comment]
Thanks for help! I updated everything to v2.0.0rc2, however the latex rendering isn't quite right... It seemingly renders both the original text and latex now:
![image](https://github.com/argilla-io/argilla/assets/20409082/2754c8d8-3222-41d3-ba57-b2171bd6bfc2)

Here is my simple code for uploading the datasets:
```python
import json
import os
import argilla as rg
from pathlib import Path


def upload_datasets(path, workspace, client):
    with open("guidelines.md", "r") as f:
        guidelines = f.read()

    for file in Path(path).glob("*.json"):
        settings = rg.Settings(
            fields=[
                rg.TextField(
                    name="question",
                    title="Question",
                    required=True,
                    use_markdown=True,
                ),
                rg.TextField(
                    name="model_answer",
                    title="Model Answer",
                    required=True,
                    use_markdown=True,
                ),
                rg.TextField(
                    name="answer",
                    title="Groundtruth Answer",
                    required=True,
                    use_markdown=True,
                ),
            ],
            questions=[
                rg.SpanQuestion(
                    name="labels",
                    title="PRM Annotation",
                    description="Highlight and label each step of the model's answer",
                    labels=["Good", "Neutral", "Bad", "Error Realization"],
                    field="model_answer",
                    required=True,
                    allow_overlapping=False,
                    visible_labels=4,
                ),
            ],
            guidelines=guidelines,
        )

        dataset = rg.Dataset(name=file.stem, settings=settings, client=client)
        dataset.create()

        with open(file, "r") as f:
            data = json.load(f)

        dataset.records.log(
            [
                rg.Record(
                    fields={
                        "question": item["question"],
                        "model_answer": item["model_answer"],
                        "answer": (
                            item["answer"][0]
                            if isinstance(item["answer"], list)
                            else item["answer"]
                        ),
                    }
                )
                for item in data
            ]
        )


def main():
    client = rg.Argilla(
        api_url="https://broyojo-prm.hf.space/", api_key=os.environ["ARGILLA_API_KEY"]
    )

    # delete all datasets
    for dataset in client.datasets.list():
        dataset.delete()

    upload_datasets(
        path="../problem_selection/selected_problems",
        workspace="benchmark",
        client=client,
    )


if __name__ == "__main__":
    main()
```

Here is an example latex text that is in the dataset:
```
Define the sequence $c_{0}, c_{1}, \\ldots$ with $c_{0}=2$ and $c_{k}=8 c_{k-1}+5$ for $k>0$. Find $\\lim _{k \\rightarrow \\infty} \\frac{c_{k}}{8^{k}}$.
```

**Comment by sdiazlor** [comment]
Thank you @Broyojo! @damianpumar could you take a look at this? Ideally, if markdown is set to true, the raw input doesn't need to be added.
