### ISSUE TITLE
[FEATURE] streamline `OAuth` deployment on `Spaces`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5205]
**Is your feature request related to a problem? Please describe.**

Currently, it takes several manual steps and efforts to launch a Hugging Face `Oauth` enabled application which is difficult even if you know what you are doing.

**Describe the solution you'd like**

Ideally this should become more of a one-click/flag enabled features.

**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
@dvsrepo

**Comment by nataliaElv** [comment]
I believe we can close this one. @davidberenstein1957 feel free to reopen if  needed.

**Comment by davidberenstein1957** [comment]
@nataliaElv that is correct:) Handled here: https://github.com/argilla-io/argilla/pull/5556
