### ISSUE TITLE
[ENHANCEMENT] Show panels when the record list is empty

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#5208]
When I am in a queue that has no records, all panels are hidden. I'd like to see them so I can check the guidelines, progress and form even when the queue is empty and move the warning that the queue has no records to the records panel.

**Comment by damianpumar** [comment]
Hi @nataliaElv.
Hiding the panels was a decision I made a few weeks ago, because I didn't see the point of showing collapsible panels without information, but we can see it together. Thanks!!
