### ISSUE TITLE
[DOCS] Update flow to update settings

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#5230]
## Which page or section is this issue related to?

https://argilla-io.github.io/argilla/dev/how_to_guides/dataset/#update-a-dataset
In general, settings can be accessed by name. So settings.fields["text"] or settings.vectors["embeddings"] are valid.

**Comment by nataliaElv** [comment]
Related to #5231

**Comment by frascuchon** [comment]
Ref https://github.com/argilla-io/argilla/pull/5240
