### ISSUE TITLE
[BUG-UI/UX] Odd behaviour when deleting Spans when using multiple SpanQuestions

### ISSUE THREAD

**Issue by Cy-Fi** [recognai/rubrix#5233]
**Describe the bug**
When using FeedbackDataset with multiple SpanQuestions, if a span is deleted, all defined spans get removed.

**To Reproduce**
1. Create a feedback Dataset with a sample reccord:
dataset = rg.FeedbackDataset(
    fields=[
        rg.TextField(
            name="text_1",
        ),
        rg.TextField(
            name="text_2",
        ),
    ],
    questions=[
        rg.SpanQuestion(
            name="span_1",
            labels={"EXPLANATION": "Explanation"},
            field="text_1",
            required=False,
            allow_overlapping=False,
        ),
        rg.SpanQuestion(
            name="span_2",
            labels={"EXPLANATION": "Explanation"},
            field="text_2",
            required=False,
            allow_overlapping=False,
        )
    ],
)
record = rg.FeedbackRecord(
    fields={
        "text_1": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        "text_2": "labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
    },
    external_id=123
)

2. Upload records to argilla
3. Go to labeling tool
4. label some spans in the two documents
5. Click on the X to remove one span
-->

**Expected behavior**
Only the Span where the X was clicked is removed.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c5adfc3-6670-4136-9f5f-53a9c727a8aa)
![image](https://github.com/user-attachments/assets/d8aef6bd-448a-48ba-b487-6b694e2ebfa7)

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Microsoft Windows
 - Browser [e.g. chrome, safari]: Microsoft Edge 126.0.2592.102
 - Argilla Version [e.g. 1.0.0]: 1.28.0
 - ElasticSearch Version [e.g. 7.10.2]: elasticsearch:8.9.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla-server:v1.28.0

**Additional context**

**Comment by nataliaElv** [comment]
hi @Cy-Fi ! Have you tried upgrading Argilla to version 1.29.1 or even [v2.0.0rc2](https://github.com/argilla-io/argilla/releases/tag/v2.0.0rc2)? We are not able to reproduce it, so it might be an issue that has been already fixed in later versions. 
Try upgrading and let us know if you're still experiencing this issue.
