### ISSUE TITLE
Please add a LICENSE file at the top of the project repo

### ISSUE THREAD

**Issue by mbrukman** [recognai/rubrix#5244]
First, thank you for sharing this project with us!

The top-level README says the project is open-source:

https://github.com/argilla-io/argilla/blob/3ed58cfd742a32012fe96c32550e02bb289b8d5d/README.md?plain=1#L60

However, there's no top-level `LICENSE` file so it's unclear under what license the project is.

Some sub-directories have their own `LICENSE` file, e.g., `argilla/LICENSE`:

https://github.com/argilla-io/argilla/blob/3ed58cfd742a32012fe96c32550e02bb289b8d5d/argilla/LICENSE#L1

and `argilla-server/LICENSE`:

https://github.com/argilla-io/argilla/blob/3ed58cfd742a32012fe96c32550e02bb289b8d5d/argilla-server/LICENSE#L1

but the other directories have no license, and no information as to their license, which implies "All Rights Reserved" [^1] but you probably meant Apache 2.0 based on those 2 directories, so maybe it's worthwhile adding a top-level `LICENSE` file with the Apache 2.0 license?

[^1]: Per [GitHub docs on licensing][github-docs-licensing]: "[...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license."

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

**Comment by dvsrepo** [comment]
thanks for reporting! we'll look into this!
