### ISSUE TITLE
Single Text classifier : Remove label selections

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#526]
- [x] Permit to remove all selection
- [x] When there is no annotation and nore prediction show "Validate" button disabled

**Comment by frascuchon** [comment]
A missing task here the behavour when validate records from global actions. These kind of records should not be selectables for validate as global action. Just for annotate as..

We must discussed about that @Amelie-V @leiyre @dcfidalgo @dvsrepo
