### ISSUE TITLE
[BUG-python/deployment] Copying records with suggestions produces an `UnprocessableEntityError`  

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#5272]
**Describe the bug**

When I want to copy a dataset, copying the records throws an error when they have suggestions.
 
**Stacktrace and Code to create the bug**

```python
import argilla as rg

client = rg.Argilla(...)

dataset = client.datasets("my_dataset")
records = list(dataset.records(with_responses=False, with_suggestions=True))

new_dataset = rg.Dataset(
    name="new_ds",
    settings=dataset.settings
)
new_dataset.create()
new_dataset.records.log(records)

```

This produces the following error:
```
UnprocessableEntityError: Argilla SDK error: UnprocessableEntityError: Unprocessable entity. The server cannot process the request. Details: {"detail":"Record at position 0 does not have valid suggestions because question with question_id=f4586a82-85a5-4214-ac05-eac2bc243233 does not exist"}
```

**Expected behavior**

Since the settings are the same, the suggestions should be recognizable and copied over to the new dataset.

**Environment:**

 - Argilla Version [e.g. 1.0.0]: argilla-2.0.0.dev0
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by davidberenstein1957** [comment]
I think we should try to check with `ID`, but when `ID` is not present, fallback on the `name`, or vice versa. Also, this flow should be resolved in a similar way for metadata and vectors. Not sure about responses, since we do want to enforce the user ID based on actual users.
