### ISSUE TITLE
[TASK] Check records using `ImageField` with URLs using `HTTP` protocol serving application from `HTTPS`

### ISSUE THREAD

**Issue by jfcalvo** [recognai/rubrix#5278]

**Comment by frascuchon** [comment]
Image URLs hosted on insecure servers (http) won't be available when accessing from https argilla servers (spaces), as you can see in the following snapshot:

<img width="1512" alt="Captura de pantalla 2024-08-29 a las 13 53 22" src="https://github.com/user-attachments/assets/2ca7c339-64ef-4d0d-95cb-b65feacde5ad">


Here is the code to reproduce the error:

```python
import argilla as rg

client = rg.Argilla(...)

settings = rg.Settings(
    fields=[
        rg.ImageField("image"),
        rg.TextField("description"),
    ],
    questions=[
        rg.TextQuestion("comments"),
    ]
)

dataset = rg.Dataset(
    name="test-dataset",
    settings=settings,
).create()


record = rg.Record(
    fields={
        "image": "http://insecure/image.jpg",
        "description": "This is a description",
    }
)

dataset.records.log([record])

```
cc @damianpumar @jfcalvo @burtenshaw 

Closing as completed
