### ISSUE TITLE
[DOCS] A equal to(=) sign is missing while specifying the version for span_marker

### ISSUE THREAD

**Issue by bikash119** [recognai/rubrix#5280]
## Which page or section is this issue related to?

[token classification tutorial](https://argilla-io.github.io/argilla/latest/tutorials/token_classification/#getting-started)
```
!pip install gliner==0.2.6 transformers==4.40.2 span_marker=1.5.0
```
A ```=``` sign is missing while specifying ```span_marker``` version

**Comment by davidberenstein1957** [comment]
@bikash119 would you be able to create a PR for this?

**Comment by bikash119** [comment]
Yes, will do.

**Comment by bikash119** [comment]
@davidberenstein1957 : Can you please assign this issue to me. I am unable to see "Create Branch" button from the issue page.

**Comment by davidberenstein1957** [comment]
@bikash119 perhaps this helps too :). https://argilla-io.github.io/argilla/dev/community/contributor/
