### ISSUE TITLE
[FEATURE] Add Task Templates to v2

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#5354]
**Is your feature request related to a problem? Please describe.**

https://docs.v1.argilla.io/en/latest/practical_guides/create_update_dataset/create_dataset.html#task-templates

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davidberenstein1957** [comment]
@sdiazlor I would like to see this underneath something like.

```python
rg.Settings.from_template("task")
```

If we implement this, the tasks can be aligned with `transformers` pipeline tasks but they can also align with the previous iteration. @burtenshaw WDYT?

**Comment by sdiazlor** [comment]
Tackled here: https://github.com/argilla-io/argilla/pull/5426
