### ISSUE TITLE
[BUG-python/deployment] Response sanity check not working due to variable renaming

### ISSUE THREAD

**Issue by maxserras** [recognai/rubrix#5357]
**Describe the bug**

Already working on the fix :D 

argilla/src/argilla/records/_resource.py 
Line 373 - The response received in the function is overwritten by the response from the self.__responses_by_question_name

```
    def _check_response_already_exists(self, response: Response) -> None:
        """Checks if a response for the same question name and user id already exists"""
        for response in self.__responses_by_question_name[response.question_name]:
            if response.user_id == response.user_id:
                raise ArgillaError(
                    f"Response for question with name {response.question_name!r} and user id {response.user_id!r} "
                    f"already found. The responses for the same question name do not support more than one user"
                )
```

**Stacktrace and Code to create the bug**

Just try to add N responses for the same question to any record from the python client.

```
for user in client.users:
      record_to_add.responses.add(rg.Response("label", label, user_id=user.id))
```

**Expected behavior**
We can add responses for different users programatically

**Environment:**
Latest development branch -  argilla-sdk-2.0.0a0.dev0

**Comment by davidberenstein1957** [comment]
@maxserras did you get around to working on a fix? Otherwise, we will pick this up from our side :)
