### ISSUE TITLE
[FEATURE] do not allow passing an empty string to a required field

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5363]
**Is your feature request related to a problem? Please describe.**

Yes, as introduced https://github.com/argilla-io/argilla/pull/5362#discussion_r1698626433 #5362 

**Describe the solution you'd like**

To not allow for doing this.

**Describe alternatives you've considered**

NA

**Additional context**

NA

**Comment by Piyush-Kumar-Ghosh** [comment]
Hi @davidberenstein1957 ,

I’d like to work on it. 

Before I get started, could you please clarify a few points?

- **Confirmation of Requirements**: Should this validation apply to all required fields across the application?

- **Implementation Guidelines**: Are there specific guidelines or best practices I should follow for this change?

- **Potential Side Effects**: Are there any known concerns or potential side effects related to this validation that I should be aware of?

- **Testing Expectations**: What type of testing is expected to ensure this change is effective and doesn’t introduce new issues?
