### ISSUE TITLE
[UI/UX] Update Welcome page

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#5369]
**Describe the bug**

- Update installation code
- Indicate the usage of HF_TOKEN only if it's a private space. If it's automatically updated as api_key and api_url, then we could remove it.

![image](https://github.com/user-attachments/assets/b792dca5-78d8-4d93-8a68-c66909a37dbb)

**Comment by nataliaElv** [comment]
Let's also update the docs to guide users better in case they use OAuth and/or private spaces: https://docs.argilla.io/latest/how_to_guides/user/ @sdiazlor feel free to open a separate issue for this from this comment
