### ISSUE TITLE
[FEATURE] improve `UnprocessableEntityError` due to mis-aligned `ID` `UUID`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5381]
**Is your feature request related to a problem? Please describe.**

Sometimes the error messaging is a bit misleading in these cases.
https://discord.com/channels/879548962464493619/1262634844903440435
https://gist.github.com/strickvl/8745fba87162e65900080d1835dc8c70

**Describe the solution you'd like**

Something like shown here https://github.com/argilla-io/argilla/issues/5272

**Describe alternatives you've considered**

**Additional context**

NA

**Comment by burtenshaw** [comment]
I expect that this is introduced by lazy init of records. Where `Record` objects in ids are not aligning with the dataset's settings id's. We could resolve this by catching these errors and trying to lookup the correct settings attribute id. Ideally with a new custom exception, and better error and warning messages.
