### ISSUE TITLE
[BUG-UI/UX] record annotation progress shows `NaN%` without any record changes

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5390]
**Describe the bug**

record annotation progress shows `NaN%` without any record changes

**To Reproduce**
Create a dataset with `TaskDistribution`
login as annotator
Don't touch anything and have a look at the progress bar.

**Expected behavior**

**Screenshots**

See bottom left :) 
<img width="862" alt="image" src="https://github.com/user-attachments/assets/66581276-5dcc-4030-b7eb-372fcb540ce7">

**Environment (please complete the following information):**

 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: Chrome
 - Argilla Version [e.g. 1.0.0]: 2.0
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]: 2.0

**Additional context**

NA

**Comment by davidberenstein1957** [comment]
@damianpumar @leiyre it seems to resolve aftar waiting a bit, not sure if this is due to slow metric computation but perhaps it is best not to show `NaN` before that?

**Comment by damianpumar** [comment]
The problem comes because the backend responds very slowly, it is taking more than 4 seconds to give us that information, we are going to add a skeleton for these scenarios.
