### ISSUE TITLE
[DOCS] Add basic developer documentation

### ISSUE THREAD

**Issue by sdiazlor** [recognai/rubrix#5401]
## Which page or section is this issue related to?

Add basic developer documentations as here: https://docs.v1.argilla.io/en/latest/community/developer_docs.html
Although pointing to the READMES for most of the cases.

**Comment by davidberenstein1957** [comment]
@sdiazlor I agree. I think we can redirect users to the corresponding readmes within argila-server and argilla-frontend where needed and focus on the core Python docs.
