### ISSUE TITLE
TokenClassificationRecord.from_client uses annotation_agent for prediction_agent

### ISSUE THREAD

**Issue by nartiz** [recognai/rubrix#542]
I believe `agent=record.annotation_agent or MACHINE_NAME,` should be `agent=record.prediciton_agent or MACHINE_NAME,` instead in the `CreationTokenClassificationRecord.from_client` method:

```python
class CreationTokenClassificationRecord(BaseRecord[TokenClassificationAnnotation]):
    tokens: List[str]
    text: str = Field(alias="raw_text")

    @classmethod
    def from_client(cls, record: ClientTokenClassificationRecord):
        prediction = None
        if record.prediction is not None:
            prediction = TokenClassificationAnnotation(
                entities=[
                    EntitySpan(label=ent[0], start=ent[1], end=ent[2])
                    if len(ent) == 3
                    else EntitySpan(
                        label=ent[0], start=ent[1], end=ent[2], score=ent[3]
                    )
                    for ent in record.prediction
                ],
                agent=record.annotation_agent or MACHINE_NAME,
            )
```
Currently I cannot specify `prediction_agent` for token classification records (it falls back to hostname unless I do it via `annotation_agent`).

**Comment by dcfidalgo** [comment]
Thank you very much for reporting! This bug was recently fixed in #524, so you could already use the master version. Otherwise, we plan to make a release this week, where this fix will be included. @nartiz Let me know if you need further help.
Sorry for the inconvenience!
