### ISSUE TITLE
[BUG-python/deployment]

### ISSUE THREAD

**Issue by nicolamassarenti** [recognai/rubrix#5442]
**Describe the bug**
Using the [latest commit](https://github.com/argilla-io/argilla/commit/e28ef13caf11aa94afa7ef89957334469564259b) in develop, I am facing an issue with the server. My python version is 3.9.7

If I run:
`pdm install`

I got this error
```
add psycopg2 failed:
...
If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.
```
Which is triggered by [this](https://github.com/argilla-io/argilla/blob/develop/argilla-server/pyproject.toml#L64) dependency.

Furthermore, by commenting the line mentioned above, by locking, re-installing the dependencies again and by running pdm server-dev I get this error

```
Traceback (most recent call last):
  File "/home/nicola/Documents/..../argilla-server/.venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/nicola/Documents/BSC/argilla-bsc/argilla-server/.venv/lib/python3.9/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
...
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/python3.9/lib/python3.9/typing.py)
```

**Comment by nicolamassarenti** [comment]
FYI I checked out to the commit tagged `v2.0.1` and I had this error

```
add psycopg2 failed:
...
If you prefer to avoid building psycopg2 from source, please install the PyPI
'psycopg2-binary' package instead.
```

By commenting, locking and re-installing I was able to successfully run `pdm server-dev`

**Comment by burtenshaw** [comment]
Hi @nicolamassarenti 

Thanks for the bug report and sorry for the late reply. I can see that by checking out a release branch and installing `psycopg2-binary` you we able to resolve the problem. I would recomend using the `main` branch for any real use of argilla.

I'll close this issue.

**Comment by nicolamassarenti** [comment]
ok @burtenshaw 

As a suggestion, you can either update the default branch to the release one or write what's the stable branch, because at the beginning I didn't see it mentioned anywhere nor I was able to understand what I had to refer to

![image](https://github.com/user-attachments/assets/3f9ec652-22c0-4478-9cd8-8ded78a8b430)

**Comment by burtenshaw** [comment]
Thanks @nicolamassarenti That's a real confusion!

@frascuchon should we update our default branch to `main` and delete `master` ?
