### ISSUE TITLE
versions for stable documentation are wrong

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#549]
Stable and master versions titles in read the docs shows dirty or wrong version numbers.

Maybe this could help (from [setuptools-scm readme](https://github.com/pypa/setuptools_scm/#usage-from-sphinx))

> ## Usage from Sphinx
> It is discouraged to use setuptools_scm from Sphinx itself, instead use importlib.metadata after editable/real installation:
> 
> 
> ```python
> # contents of docs/conf.py
> from importlib.metadata import version
> release = version('myproject')
> # for example take major/minor
> version = '.'.join(release.split('.')[:2])
> ```
> 
> The underlying reason is, that services like Read the Docs sometimes change the working directory for good reasons and using the installed metadata prevents using needless volatile data there.

**Comment by dcfidalgo** [comment]
> Stable and master versions titles in read the docs shows dirty or wrong version numbers.

Could you add a screenshot or a link? I don't manage to see it

**Comment by frascuchon** [comment]
For master:
<img width="271" alt="Screenshot 2021-11-04 at 12 04 31" src="https://user-images.githubusercontent.com/2518789/140303172-323c18a9-c137-4e5d-86a0-ffdc70df3603.png">

For release:
<img width="302" alt="Screenshot 2021-11-04 at 12 03 49" src="https://user-images.githubusercontent.com/2518789/140303213-6ba289ab-b63f-47a3-82e0-78fc593b2fd6.png">
