### ISSUE TITLE
[FEATURE] See full image in `ImageField`

### ISSUE THREAD

**Issue by nataliaElv** [recognai/rubrix#5498]
**Is your feature request related to a problem? Please describe.**

Sometimes images are of a really big size and cannot be manipulated ahead of importing them to Argilla (for example when I'm using a public URL). As Argilla displays them in raw size, sometimes it's really difficult to work with them, as I cannot see the full picture. 

**Describe the solution you'd like**

I'd like to see the full image at first sight and only zoom in when needed.

**Describe alternatives you've considered**

**Additional context**

**Comment by cceyda** [comment]
having a max height/width parameter would be really useful too. My images vary a lot in size and every next record is a new surprise right now
