### ISSUE TITLE
[BUG-UI/UX] API Key copy button not working

### ISSUE THREAD

**Issue by cceyda** [recognai/rubrix#5529]
**Describe the bug**
In `my settings` page copy key for apikey is not working.
<img width="829" alt="image" src="https://github.com/user-attachments/assets/9cb922de-d5fc-4f09-b21e-59ba5e99bf14">
Console shows below error:

**Screenshots**
<img width="1127" alt="image" src="https://github.com/user-attachments/assets/fb68e1c9-ed0a-4c8b-8617-b37cd4592d99">
Due to navigator.clipboard not existing
<img width="489" alt="image" src="https://github.com/user-attachments/assets/8a1319e6-e733-472e-857d-5c7307634188">
**Environment (please complete the following information):**

 - OS [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: chrome (also tried on safari but didn't work)(cleared cache & retried same err)
 - Argilla Version [e.g. 1.0.0]: 2.2.0

**Additional context**
I copied by breakpointing and manually copying key before error

**Comment by davidberenstein1957** [comment]
Hi @cceyda, I cannot reproduce this myself but I've asked @leiyre and @damianpumar to take a look.

**Comment by jfcalvo** [comment]
@cceyda are you accessing your Argilla instance not using HTTPS? If that's the case probably the `navigator.clipboard` is not accesible because it only works with secure origins.

**Comment by damianpumar** [comment]
Hello @cceyda 
Thanks for report this issue, I changed the way to copy on clipboard supporting `no secureContext` but in the meantime, please review your permission following this guide: https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#revoking_permission

Thanks!

**Comment by cceyda** [comment]
yeah not using https at the moment, it is already in a secure network (+ some parts are not under my control)

**Comment by damianpumar** [comment]
Yes, I think that is the problem, sometimes if you are running the app with restricted permissions disabling the permissions manually or running the app on http, some JavaScript objects don't exist, for that reason I fixed our "copy to clipboard" function to support these scenarios.

Thanks!
