### ISSUE TITLE
[FEATURE] Add Python 3.13 support

### ISSUE THREAD

**Issue by oulianov** [recognai/rubrix#5627]
**Is your feature request related to a problem? Please describe.**

Hello, I'd like to upgrade my app to python 3.13 but I can't due to argilla not supporting 3.13. What's the roadmap and timeline for this ?

**Describe the solution you'd like**

Argilla supports 3.13

**Describe alternatives you've considered**

Removing argilla from my app

**Additional context**

**Comment by sdiazlor** [comment]
@frascuchon @jfcalvo Do you have any insights about this?

**Comment by frascuchon** [comment]
Thanks @oulianov 

@sdiazlor this is an SDK requirement only.  Maybe we can just remove the [`pyproject.toml`](https://github.com/argilla-io/argilla/blob/develop/argilla/pyproject.toml#L7) upper limit. cc  @burtenshaw

**Comment by oulianov** [comment]
That would be rad !

**Comment by Jeerhz** [comment]
Hello, the argilla available on pypi still doesn't support 3.13, even though the PR #5652  added the support.
What's the timeline to publish the update package to pypi ?

**Comment by sdiazlor** [comment]
Hi @Jeerhz. The 3.13 support will be added in the upcoming release (https://github.com/argilla-io/argilla/pull/5706). It will be published during the next days.
