### ISSUE TITLE
[BUG-UI/UX] When use_markdown=True, content will be displayed twice.

### ISSUE THREAD

**Issue by Ignoramus0817** [recognai/rubrix#5629]
**Describe the bug**

When set `use_markdown=True` to `rg.TextField`, corresponding records will be displayed twice on the page. The first one is rendered and the second is raw text.

**To Reproduce**

Here is a short code snippet to reproduce the bug.
```python
import argilla as rg

client = rg.Argilla(
    api_url="<api_url>", api_key="<api_key>")

settings = rg.Settings(
    guidelines="These are some guidelines.",
    fields=[
        rg.TextField(
            name="text", title="text", use_markdown=True
        ),
    ],
    questions=[
        rg.LabelQuestion(
            name="label",
            labels=["label_1", "label_2", "label_3"]
        ),
    ],
    metadata=[
        rg.TermsMetadataProperty(
            name="id",
        )
    ]
)

dataset = rg.Dataset(
    name="sample_dataset_0",
    workspace="sft",
    settings=settings,
)

dataset.create()

dataset = client.datasets(name="sample_dataset_0")
records = [
    rg.Record(
        fields={
            "text": "Do you need **oxygen** to breathe?",
        },
        metadata={"id": "0"},
    ),
    rg.Record(
        fields={
            "text": "What is the boiling point of water?",
        },
        metadata={"id": "1"},
    ),
]

dataset.records.log(records)
```

**Expected behavior**

When using markdown, content should only be displayed once, rendered.

**Screenshots**

![screenshots](https://github.com/user-attachments/assets/7cc18338-aa7c-4966-8ef1-98124d9c95fb)

**Environment (please complete the following information):**

 - OS [e.g. iOS]: Ubuntu 22.04.2 LTS
 - Browser [e.g. chrome, safari]: Chrome
 - Argilla Version [e.g. 1.0.0]: 2.3.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.12.2
 - Docker Image (optional) [e.g. argilla:v1.0.0]: argilla/argilla-server:latest

**Comment by leiyre** [comment]
Hi @Ignoramus0817! 
Thanks for reporting the bug.  It was already fixed [in this PR](https://github.com/argilla-io/argilla/pull/5592), which is going in the next release

**Comment by Ignoramus0817** [comment]
Got it. Thanks for replying so fast.
