### ISSUE TITLE
[BUG-python/deployment] Unable to retrieve records along with the filter query

### ISSUE THREAD

**Issue by Saikiranbonu1661** [recognai/rubrix#5636]
**Describe the bug**
I tried to fetch the docs from a dataset using dataset.records(with_vectors=True) and I could see the vectors. But when I tried with some query filter like dataset.records(rg.Query(filter), with_vectors=True) I could see the filtered docs without vectors.
**Stacktrace and Code to create the bug**

**WORKING CASE**

import argilla as rg
api_url = "api_url"
api_key =  "api_key"
client = rg.Argilla(api_url, api_key)
dataset = client.datasets(name='dataset', workspace="workspace")
records = dataset.records(with_vectors=True).to_list(flatten=False)

**CASE WHERE IT'S NOT WORKING**

import argilla as rg
api_url = "api_url"
api_key =  "api_key"
client = rg.Argilla(api_url, api_key)
dataset = client.datasets(name='dataset', workspace="workspace")
filter_label = rg.Filter(("metadata.activity_status", "==", "considered_al_score"))
new_records = dataset.records(rg.Query(filter=filter_label), with_vectors=True).to_list(flatten=False)

**Expected behavior**
I need the docs with the filter applied should retrieve vectors also 

**Environment:**

 - Argilla Version: Client: 2.3.0 and Server 2.0.0

**Additional context**

**Comment by sdiazlor** [comment]
Just to point out, I tried with the latest version 2.3 of the SDK and Server, and it doesn't work either.

![Screenshot 2024-10-28 at 12 21 55](https://github.com/user-attachments/assets/34f3083f-1b6d-488f-9c99-ba6556d2ed4d)
