### ISSUE TITLE
[BUG-UI/UX] Copy to clipboard not working

### ISSUE THREAD

**Issue by caiolang** [recognai/rubrix#5668]
**Describe the bug**
Various buttons that are supposed to copy content to clipboard are failing.

**To Reproduce**
Using Chrome, open the Chrome DevTools > Console to see the error showing up
- For an error when copying the API key:
  - Go to **My settings** and click on **Copy key**
- Alternatively, for any dataset on the Home page:
  - Click on the "copy name" or the "copy url" buttons

**Expected behavior**
The contents being copied to the Clipboard

**Screenshots**
- Copy API key button:
<img width="890" alt="Captura de Tela 2024-11-04 às 16 41 11" src="https://github.com/user-attachments/assets/55a80d65-5d1f-4e38-b6d3-3f3fc5a21507">
- Copy URL and copy name buttons:
<img width="887" alt="Captura de Tela 2024-11-04 às 16 41 27" src="https://github.com/user-attachments/assets/2f314f75-e975-4cf5-a2fb-fb8e1ea61d20">

**Environment (please complete the following information):**

 - OS: MacOS 14.2.1
 - Browser: Chrome v120.0.6099.62
 - Argilla Version: 2.0.1
 - ElasticSearch Version: Unkown/Not relevant

**Additional context**
Let me know if any more context is needed!

Thank you :)

**Comment by leiyre** [comment]
Hi @caiolang! Thanks for reporting. It sounds related to this other issue https://github.com/argilla-io/argilla/issues/5529, you can upgrade to a newer version and see if it works out.

**Comment by caiolang** [comment]
Hey @leiyre ! Thank you, it seems to be the same problem – I appreciate pointing me to the original issue.
All good!
