### ISSUE TITLE
[Labeling] Design/Implement cleanlab support

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#567]
The idea is to facilitate the usage of cleanlab to easily find possible labeling errors. Should be a weak dependency.

- [x] Design
- [x] Implementation

**Comment by dcfidalgo** [comment]
Here is a first simple proposal:
```python
from rubrix.labeling.text_classification import find_label_errors

recs = find_label_errors("my_dataset_name")  # returns a list of TextClassificationRecord

# if you want to inspect the results in the notebook
pd.DataFrame(map(dict, recs))
```

So `find_label_errors` would be a light wrapper around [cleanlab.pruning.get_noise_indices](https://cleanlab.readthedocs.io/en/latest/cleanlab.html#cleanlab.pruning.get_noise_indices) with following signature:
```python
def find_label_errors(dataset: str, sorted_by: str = "likelihood", **kwargs) -> List[TextClassificationRecord]:
    """Find potential annotation/label errors in your dataset.

    It will include all records in the given dataset for which a prediction AND annotation is available.
    Make sure the predictions were made in a holdout manner, that is include only records that were not used in the training of the predictor.  
    Args:
        dataset: Name of the dataset
        sort_by: One of the two options
            - "likelihood": sort the returned records by likelihood of containing a label error (most likely first)
            - "prediction": sort the returned records by the probability of the prediction (highest probability first)
        **kwargs: Passed on to `cleanlab.pruning.get_noise_indices`      

    Returns:
        A list of records containing potential annotation/label errors
    """
```
`**kwargs` include parameters like `prune_method` and other advanced parameters. 

@dvsrepo @frascuchon as always, input/suggestions more than welcome!

**Comment by frascuchon** [comment]
I don't have much to say on this matter. Go ahead with the proposal

**Comment by dcfidalgo** [comment]
discussion with dani:
- Add warning when no record has prediction nor annotation
- Add new tutorial (only code) to this PR based on the current cleanlab tutorial:
  - use agg_news dataset
  - use a small sklearn model
  - use x-validation to check training data
