### ISSUE TITLE
[bug] Prediction agent too long when using spaCy rb.monitor

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#575]
See:

<img width="1679" alt="Screenshot 2021-11-05 at 14 21 35" src="https://user-images.githubusercontent.com/1107111/140516905-cdd8ab75-642a-4f9a-b117-57c150f336e5.png">

This has two aspects:

1. Shorten prediction_agent if its too long (not sure if leaving the first and last parts adding ..., or something else you find best @leiyre )
2. Not sure @frascuchon if we could avoid such long prediction_agent on the first place.

I would tackle both aspects in any case

**Comment by frascuchon** [comment]
Yes. From my part, I'm comfortable by setting a max_length validation to prediction/annotation agent. It's 32 the magic number?

**Comment by dvsrepo** [comment]
32 sounds magical yes

**Comment by frascuchon** [comment]
Indeed, huggingface models have names greater than 32 chars. So 64 is much more magical number
