### ISSUE TITLE
Limit metadata field name pattern

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#588]
-  only lower_case alphabet  `[a-z]`
- only underscore `_` and dot `.` as special characters
- non digits allowed

These restrictions will help to dynamically tackle metadata info for example for advances queries or aggregations.

what do you think @dcfidalgo @dvsrepo ?

**Comment by dcfidalgo** [comment]
No big deal for me, I think these restrictions are fine, maybe digits would be nice to have, but not crucial.
These restrictions apply to every key in a nested dictionary (for the metadata), right?

**Comment by dvsrepo** [comment]
No big deal for me either if we get such a great benefit in return

**Comment by frascuchon** [comment]
The idea cames thinking about basic query dsl combining nested fields. These restrictions could help to design the query lang extension
