### ISSUE TITLE
Return record-level `metrics` and `mentions` from `rb.load`

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#591]
This is needed for using metrics for downstream analyses (mentions might also be useful, if not fully covered by metrics).

**Comment by dcfidalgo** [comment]
I will list some options how to include `metrics` in the output of `rb.load`, and keep the `as_pandas` switch:

**1. Include metrics only in the pandas dataframe**
- No need to modify the client models
- not very consistent that you only get the metrics info in one of the two output types

**2. Modify the client models to have some kind of "read only" attribute**
- Both output types return the same info
- When creating the client records it's a bit weird to have an argument that you cannot actually set, not sure if pydantic has something nice for this use case

**3. Introduce different read and write client models**
- Both output types return the same info
- no "read-only" arguments
- duplicates the number of client models, increases complexity

**4. Give up the `as_pandas` switch**
- only one return type
- no need to change client models
- you must use `BaseModel.parse_obj` or ignore/filter pandas columns to get rubrix client records
- no "lightweight" way to load a dataset

Given these options, I think I prefer option 2. @dvsrepo @frascuchon Maybe you have some more/better ideas?

Regarding the `mentions`, do you refer to the `mentions_metrics` in the `TokenClassificationMetrics`, or the mentions in the `TokenClassificationRecord`? I think the latter can be extracted more or less easily from the predictions/annotations + the provided text. Former would be part of the `metrics` column?

**Comment by dcfidalgo** [comment]
Summary of a quick call:

- Option 2
- include `mentions_metrics`
