### ISSUE TITLE
[question] Could we add `query` to `rb.copy()` ?

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#592]
This would greatly facilitate data slicing (for analysis, annotation, etc.)

**Comment by frascuchon** [comment]
What's the flow for this use case? For me rb.copy creates a dataset copy. IMHO filtered dataset copies should be managed out of copy method. It's a bit confusing create a copy that is not really a copy.

**Comment by dvsrepo** [comment]
The flow for this use case is to create a slice of the dataset. It's true that overloading copy is not the best idea, but having a direct way to create a slice it's a very powerful feature for many use cases: easily create subsets for annotation, evaluation, analysis, etc. Anyway, this came out during Monday's feedback session during the demo, but it's not high priority so we can move it into the discussion phase

**Comment by frascuchon** [comment]
maybe we can use stored filters for those cases and create "views" of datasets. Yes, we must discuss about that. We can design something compatible with weak label rules too.
