### ISSUE TITLE
Cannot add more than 40 records from csv file for annotation

### ISSUE THREAD

**Issue by capableguptadotcom** [recognai/rubrix#596]
```python
import rubrix as rb
import pandas as pd

#take any data with more than 40 text rows
df=pd.read_csv("../data/_data(top1000rows).csv")

for input_text in df['identified-text']:
    if not input_text:
        continue
    input_text=str(input_text)
    rb.log(
        rb.TokenClassificationRecord(
            text=input_text,
            tokens=input_text.split()),
        name='ner-label'
        )
```
![Screenshot (24)](https://user-images.githubusercontent.com/46840328/141049863-4e6f04c1-e4e3-4a72-b057-6dc2b38b0337.png)

**Comment by capableguptadotcom** [comment]
just run the same code & open rubrix UI and check the number of records after it throws the error.

**Comment by frascuchon** [comment]
Hi @Saksham1611 

Thanks for sharing the error. It seems there is something unexpected in inputs. Could you please share the text that's raise the error?. Maybe you're logging an empty string...
