### ISSUE TITLE
[bug] Sticky top-bar related Glitch with 4 records (when showing 5 records per page)

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#604]
![Kapture 2021-11-10 at 21 45 36](https://user-images.githubusercontent.com/1107111/141190686-e76cc08e-ada1-4d9b-8cc7-df9844fb40b0.gif)

The git does not show the behaviour really well, I can show you tomorrow

**Comment by frascuchon** [comment]
Could we plan to include this issue fix for next release @Amelie-V @leiyre ???

**Comment by frascuchon** [comment]
@dvsrepo Any release affected by this bug or just in master ?
