### ISSUE TITLE
[Scrolling] Expected record view state IS lost after scroll 

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#616]
![CPT2111111623-1024x598](https://user-images.githubusercontent.com/2518789/141323781-d7dca5c7-9096-4b0e-98ea-00c0cdb67238.gif)

For text2text, record view state is lost after scrolling the page. It's an expected behavior? Should we keep the same state when scrolling @Amelie-V @leiyre @dvsrepo @dcfidalgo ?

**Comment by leiyre** [comment]
I think it should be maintained after scrolling. I doubt if it should also be maintained when we switch between explore/annotate view.
