### ISSUE TITLE
[enhancement] Control tqdm for batch, single or parallel logs

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#629]
When using for example:

```python
classifier = rb.monitor(classifier, dataset="tweets_en_es_emocion", sample_rate=1.0)
dataset.map(lambda r: {"prediction": classifier(r["text"])}, batch_size=32)
```

The progress bar and message become a bit annoying when rb.log is launched. I'd suggest providing a parameter to rb.log to disable the progress bar (and maybe the {n} records logged in... message) and use it at least in the rb.monitor methods to disable this logging. Of course any other idea is more than welcome!

**Comment by dcfidalgo** [comment]
I think your proposal is sensible, see PR #632
