### ISSUE TITLE
[Metrics] Simplify the API usage for `compute_for`

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#644]
I started testing the metrics for analysing training sets and I'd like to simplify how we set it for `Annotations` or `Predictions`. Currently:

```python
from rubrix.metrics.token_classification import entity_consistency
from rubrix.metrics.token_classification.metrics import Annotations

entity_consistency(name="conll2002_es", mentions=30, threshold=4, compute_for=Annotations).visualize()
```

I'd like at least to be able to do (avoiding `rubrix.metrics.token_classification.metrics`) :
```python
from rubrix.metrics.token_classification import entity_consistency, Annotations
```

I guess that using plain strings like "Annotations" might be problematic right?

**Comment by frascuchon** [comment]
Using typed data could help autocompletion for IDEs and interactive development. Not sure if better solutions could be implemented, @dcfidalgo ?

**Comment by dvsrepo** [comment]
Yes it's true, unless David has another idea I'd be fine with at least having the typed data available in the first level module for imports

**Comment by dcfidalgo** [comment]
I would imitate HF here, like always ... :)
They allow `str` AND `Enum`, they write as @frascuchon mentions, `Enum` can be useful for IDEs. In a notebook, I much prefer strings with a useful error message.

So I would do:
```python
def entity_consistency(..., compute_for: Union[str, rubrix.metrics.token_classification.ComputeFor]):
    if isinstance(compute_for, str):
        compute_for = ComputeFor(compute_for)  # <- this should throw an error if the value is not valid and show the options
    ...

class ComputeFor(Enum):
    ANNOTATIONS = "annotations"
    PREDICTIONS = "predictions"
```
