### ISSUE TITLE
[Metrics] `compute_for` is missing in tokens_length

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#646]
I think all metrics should have this parameter.

https://github.com/recognai/rubrix/blob/415b67663c510534b6a3a7b9cd265449b1cf5e22/src/rubrix/metrics/token_classification/metrics.py#L8

I'd also change the description to (if I understand correctly what this metric does):

"" Computes the text length distribution measured in number of tokens"""

**Comment by frascuchon** [comment]
Tokens length metric is based on input tokens, so there is no sense a `compute_for` parameter for it

**Comment by dvsrepo** [comment]
Absolutely :-D
