### ISSUE TITLE
[Metrics] input text length distribution for all task

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#652]
It would be nice include a set of general metrics for every task. One of them could be the input text length distribution based on number of characters.

For text2text and token classification it's quite easy define the input target. But not sure how to define this metric over text classification inputs, since it could be a dictionary.

Make sense define a 2 level metric for text classification : 1) computing all input values (all dict values) and 2) one distribution per input key?

For example, if we have text classification records whose inputs are like:

```python
{
   "subject": "........",
   "body": "......."
}
```

The text length distribution computes the overall length  (`subject` content  + `body` content), the `subject` content length and the `body` content length separately.

@dcfidalgo @dvsrepo, any comment ???

**Comment by dcfidalgo** [comment]
+1 for trying to generalize certain "task-independent" metrics, I think this makes a lot of sense.

Regarding the text length for text classification records, for me, it would be ok to simply start with the aggregated length (that is `subject` content + `body` content`) and if we see that we need a more fine-grained metric, then add the lengths per input key.

**Comment by frascuchon** [comment]
The idea would be also include all common filter aggregations as common metrics too (annotated_by, predicted_by, status, word terms....) and include new ones ([significant terms](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-significantterms-aggregation.html), [string stats](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-string-stats-aggregation.html))
