### ISSUE TITLE
[Empty home] Create a message

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#676]
It could be great to launch workspaces with a home when there no dataset uploaded

(Copies are fake)

### Option 2 : Only message (Faster to implement)

Need help to redact the correct message, and check the best user flow (The piece of code is only an idea...)

**Comment by Amelie-V** [comment]
![Emptyhome1](https://user-images.githubusercontent.com/84135211/142857362-f3a61d07-8901-410b-b76b-fa0e5b86d52d.png)
![Emptyhome](https://user-images.githubusercontent.com/84135211/142857387-651f58ec-a388-46f1-af06-297fba575a57.png)

**Comment by dcfidalgo** [comment]
If there are no datasets in the list I would definitely show a message. I would not show a message if there are any datasets available. 
That said, I would also include some datasets by default when a user creates an account, or launches a fresh Rubrix&ES instance locally, something that we already mentioned in the past @dvsrepo @frascuchon 

I very much like your second proposal, my suggestion for the message would be something like:
```
There aren't any datasets yet.

The Rubrix web app allows you to log, explore and annotate your data.
Start logging data with our Python client, or see the docs for more information.  

`your code snippet`
```

**Comment by dvsrepo** [comment]
I agree with David. To summarize:

1. Only show the message when no datasets available.
2. The copy from David is fine I would a link to the docs.
3. We need to design the preloading of examples and generally the quick
start with a fresh installation. Let's open an issue or discussion for that.

**Comment by Amelie-V** [comment]
- Implement Opt 2. (UI : Sketch/rubrix)
- Use David copy
- link to docs : https://docs.rubrix.ml/
- Integrate piece of code as in the docu (rounded corner)https://docs.rubrix.ml/en/stable/getting_started/setup%26installation.html
