### ISSUE TITLE
[Workspace navigation] QA

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#692]
- [x] Close the menu after selecting a workspace
- [x] Add Workspace name into breadcrumb in Dataset List
- [x] Use same font color size for text and link (400) for : Text message when No Dataset (New page), No more records (end of pagination), records number selected (global action bar)
- [x] NO Dataset New page: Enlarge width to avoid scroll in the piece of code

**Comment by Amelie-V** [comment]
<img width="316" alt="Captura de pantalla 2021-11-23 a las 17 02 51" src="https://user-images.githubusercontent.com/84135211/143059651-9f0a0c1a-4633-424d-a2ec-631993d03490.png">

**Comment by Amelie-V** [comment]
@dvsrepo need a validation on breadcrumb change

**Comment by frascuchon** [comment]
> <img alt="Captura de pantalla 2021-11-23 a las 17 02 51" width="316" src="https://user-images.githubusercontent.com/84135211/143059651-9f0a0c1a-4633-424d-a2ec-631993d03490.png">

The workspace name will be included only for dataset list ? Exploring a concrete dataset will be also the workspace name in breadcrum?

I think I prefer to find another place to show current workspace, but we can test this approach.
