### ISSUE TITLE
[Tutorials] Suggestions for the Sentiment Classifier tutorial

### ISSUE THREAD

**Issue by leireropl** [recognai/rubrix#702]
There are some things to add that could be interesting:

1. TensorFlow gives some problems when running the code, so maybe we could add a warning saying that if people encounter problems when using TensorFlow, they can change to Pytorch.
2. Jupyter Notebook can encounter due to its widgets. If so, the line **!pip install ipywidgets** can solve this. This can be also added as a warning.
3. The dataset is quite big and it takes a long time to be loaded, so **"split = 'train[0:50]'"** can be added to the banking_ds variable.

**Comment by dvsrepo** [comment]
Regarding the first point, I'd say we should enforce using PyTorch. We typically add the pip install torch at the beginning and we should make sure we're loading the pt versions of transformer

**Comment by dcfidalgo** [comment]
List of actions:
- [ ] Regarding 1, with Dani's comment: Add `%pip install transformers[torch]`
- [ ] Regarding 2: Add `%pip install ipywidgets`
- Regarding 3: Not sure, the 'banking77' data set is about 1MB , which for most normal working connections should be fine in my opinion.

@leireropl If you have some spare time, could you tackle 1 and 2?
