### ISSUE TITLE
[Dataset deletion] Allow select multiple datasets for deletion

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#705]
It could be nice to select multiple datasets from UI for deletion.

**Comment by Amelie-V** [comment]
@frascuchon @dcfidalgo which priority should we give to this enhancement?

**Comment by frascuchon** [comment]
really low. Not needed for next release if not ease to resolve.

**Comment by frascuchon** [comment]
Close this issue for now. The better way from now to delete datasets should be using the clients
