### ISSUE TITLE
[Weak Supervision] Integrate labeling rules management from app

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#745]

**Comment by Amelie-V** [comment]
QA

Global

- [x] **P2** Center tooltip
- [x] Metrics: % con 3 decimales. ej: 70.566 (except record, Correct/incorrect Total correct/incorrect)

Create rule:
- [x] Change message when you just save a new rule to: Rule has been saved (mess)
- [x] Reduce empty space between labels and metrics
- [x] Search box : change "Search records" to "Introduce a query" in the third views (explore/annotate/define rules)
- [x] Show query in semi bold and color
- [x] Add edition name (Amelie)
- [x] Tooltip on each metrics 
- [x] Shadow on the WS Area when the search area is actived
- [x] Review button color on grey area (Amélie)
- [x] Add overall metrics 
- [x] Edit name : on hover: text darker, on click: cursor
- [x] When user change the query maintain the previous label selected actived

Rules setting:

- [x] Delete rule doesnt work
- [x] Integrate copy delete modal : 
Permanently delete rule
You are about to delete the rule "earth" from your dataset. This action cannot be undone.
- [x] Create Content "0 results found" (Amélie)
- [x] Create Content "0 rules" (Amélie)
- [x] Change Search dataset to "Search rule by name"
- [x] Put metrics results (ej. 0.325) in bold
- [x] change "C. Annotated" to "Cov. Annot."
- [ ] Add state to Update button
- [x] Fix Update button to the table
- [x] Active sidebar and all interaction in "No rules" page. For now nothing is clicable
- [x] Allow clic on the table when the hand is actived
- [ ] **P2** CenterAdd toast to confirm rule is deleted

**Comment by dvsrepo** [comment]
Create rule:

- [x] If I just saved a rule and I remove the query from the search input, the rule config module still shows the state of my previous saved rule. I should see the initial empty status (the same as when I access the rules definition from the first time)

Screenshot after removing the query from the search box:

<img width="1576" alt="Screenshot 2021-12-20 at 14 28 50" src="https://user-images.githubusercontent.com/1107111/146774418-7f6c29f4-e1d0-4b6b-89fa-440d3b9c4fad.png">

I expect to see: (1) no label selected, (2) stats with `-`, and (3) Save rule button disabled


- [x] When no query is defined (in the search input), I would change the message "Select a label for your query" to "Start by entering a query in the search box" (or something like that). Then, when a query is entered, show the message "Select a label for your query"

- [x] Records visualization should have the same formatting as in other views with regards to thousands, etc. e.g., Records (127600) should be Records (127,600)

- [x] Message when no created labels should be changed to: "This doesn't have any labels yet.

To create new rules you need al least two labels. It's highly recommended to also annotate some records with these labels. Go to the annotation mode to [create the labels and annotate some records](url to Annotate mode). "

- [x] "create the labels" Link  doesn't work yet. It should take to the Annotation mode of the dataset.

- [x] Rules summary view should be disabled if no rules defined yet. Or at least show a place holder with a message: on "No rules defined yet". My preferred option would be disabling it so we dont have to create a new view and maintain another message. See screenshot:

<img width="1680" alt="Screenshot 2021-12-20 at 15 53 20" src="https://user-images.githubusercontent.com/1107111/146786755-59069d06-2a95-4a91-8867-76dc094de576.png">

- [x] [dataset labels state] If I start with a dataset with no labels, then add two labels and I go to the Define rules mode, I still see the "No labels message, define labels" message. It might be related to how labels for the dataset are computed, so then I tried adding two annotations, and went back to the Define rules mode but still the same message. After reloading the page I finally got the labels in the Rules view. See


![rule_labels](https://user-images.githubusercontent.com/1107111/146787680-a3fbd416-bac0-4151-be42-9d7088634769.gif)


- [x] QUESTION: Should we make more readable the number of records matching the query? Either including that on the rule definition box, adding a clearer message Records matching the query {query} (12,000)? (to discuss)

**Comment by dcfidalgo** [comment]
- [x] correct tooltips:
```
coverage: Fraction of records labeled by the rule.
annotated coverage: Fraction of annotated records labeled by the rule.
correct: Number of records the rule labeled correctly (if annotations are available).
incorrect: Number of records the rule labeled incorrectly (if annotations are available).
precision: Fraction of correct labels given by the rule.

Precision average: Average fraction of correct labels given by the rules.
Total correct/incorrect: Total number of records the rules labeled correctly/incorrectly (if annotations are available)
Total coverage: Fraction of records labeled by any rule.
Annotated coverage: Fraction of annotated records labeled by any rule.
```
- [x] Regarding the message in "Manage rules", when no rules are defined: If "Start to define rules" does not contain a link, I would simply drop this message.
- [x] If there is no match for a query I would still show the label select/metrics card, maybe with the message that no matches were found. reasons for me:
    - less "visual changes" when trying out different queries
    - even with a non-matching query, i should be able to access the "manage rules" view
    - maybe we could even allow the user to create rules with no matching records.

**Comment by frascuchon** [comment]
## Summary
- [x] Update summary does not appear for defined rules

<img width="1920" alt="Screenshot 2021-12-21 at 17 01 30" src="https://user-images.githubusercontent.com/2518789/146961228-29b248da-b68a-434a-8968-da3272ec8440.png">

but it appear filtering with no results
<img width="1920" alt="Screenshot 2021-12-21 at 17 02 49" src="https://user-images.githubusercontent.com/2518789/146961213-194f6911-11a8-411f-817e-f7a14f048cd4.png">

You must scroll to find the button, even when scrolling is not necessary
<img width="1920" alt="Screenshot 2021-12-21 at 17 01 36" src="https://user-images.githubusercontent.com/2518789/146961224-f9972740-8cfc-4fa0-8cf6-77bffc76418d.png">

In other cases is totally misaligned: 
<img width="1920" alt="Screenshot 2021-12-21 at 17 09 39" src="https://user-images.githubusercontent.com/2518789/146962022-d2d6373c-56ae-49e0-a8f8-782612189dd6.png">


## Metrics

- [x] Very little coverages - but not zero  - shows conflicts in metrics:

<img width="1917" alt="Screenshot 2021-12-21 at 17 12 02" src="https://user-images.githubusercontent.com/2518789/146962505-d0d7824c-f629-4d07-8a0b-d4caaefd276f.png">

- [x] Include all covered records for overall metrics
<img width="1441" alt="Screenshot 2021-12-21 at 17 35 30" src="https://user-images.githubusercontent.com/2518789/146965745-8c13dc24-da4a-4190-96be-13ceb837045d.png">

- [x] Proposal: I think it should be nice include overall metrics in query view. You can have a global labeling status while
you're defining rules.

**Comment by dvsrepo** [comment]
Rule definition view:

- [x] Remove "Start by entering a query in the search box" and "Select a label for your query" messages. These messages are not neccesary.
- [x] For me it's quite confusing that label buttons don't have the same look an feel as label buttons in the annotate mode. Also the shadow effect looks a bit strange. I'd recommend to use the same look and feel for labels

Rules management view:
- [x] Change heading `Summary` to `Rules`
- [x] Include tooltips to Overall metrics (cc @dcfidalgo )

**Comment by Amelie-V** [comment]
<img width="1306" alt="Captura de pantalla 2021-12-22 a las 13 40 49" src="https://user-images.githubusercontent.com/84135211/147094683-8db482fe-1e94-4b8c-a3c5-2008f19d68ca.png">

**Comment by frascuchon** [comment]
- [x] Since we could have datasets without annotated records, partial metrics should be supported for overall metrics.

<img width="1916" alt="Screenshot 2021-12-22 at 17 02 17" src="https://user-images.githubusercontent.com/2518789/147120971-8d44b998-ca89-4348-abde-0bf29186079d.png">

Single rule metrics view is already supporting these partial metrics:

<img width="1823" alt="Screenshot 2021-12-22 at 17 04 17" src="https://user-images.githubusercontent.com/2518789/147121238-e7cecf0e-b440-4a25-ac65-bccc5f0603b3.png">

**Comment by dvsrepo** [comment]
- [x] Change message "You have already a rule saved with that label." to "This query is already saved as a rule."

**Comment by dvsrepo** [comment]
- [x] Styles for the label buttons when no query selected should be in white (same style as in Explore mode)
- [x] Save rule button should be fixed to the bottom left (same height as manage rules button).
- [x] Rule name should not be editable when there's no query see screenshot:

<img width="816" alt="Screenshot 2021-12-23 at 22 05 04" src="https://user-images.githubusercontent.com/1107111/147291403-260b0852-03a8-4da9-9cf5-71ecd17afbc0.png">

- [x] The change in the message "You have already a rule saved with that label." to "This query is already saved as a rule." doesn't seem to be applied.


<img width="606" alt="Screenshot 2021-12-23 at 22 17 27" src="https://user-images.githubusercontent.com/1107111/147292228-9212ec23-3e1d-4c71-99b2-facd0b64fb79.png">

**Comment by dvsrepo** [comment]
I'd vote for merging this PR and then do some further fine-tuning and QA before the release.
