### ISSUE TITLE
[Imports] ImportError when spay<3.0 is installed

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#748]
When one has spacy<3.0 installed, the import of Rubrix fails. Maybe it would be best to move the imports of the "optional" dependencies to local imports in the corresponding class. This would concern the `labeling`, `metrics` and `monitor` modules. @frascuchon what do you think?

```python
import rubrix as rb

# output
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2845e3dc1a19> in <module>
----> 1 import rubrix as rb

~/recognai/rubrix/src/rubrix/__init__.py in <module>
     30 from rubrix.client import RubrixClient
     31 from rubrix.client.models import *
---> 32 from rubrix.monitoring.model_monitor import monitor
     33 
     34 try:

~/recognai/rubrix/src/rubrix/monitoring/model_monitor.py in <module>
      3 from typing import Any
      4 
----> 5 from ._spacy import Language, ner_monitor
      6 from ._transformers import Pipeline, huggingface_monitor
      7 

~/recognai/rubrix/src/rubrix/monitoring/_spacy.py in <module>
      9 try:
     10     # Conditional modules
---> 11     from spacy import Language
     12     from spacy.tokens import Doc
     13 except ModuleNotFoundError:

ImportError: cannot import name 'Language' from 'spacy' (/home/david/miniconda3/envs/rubrix/lib/python3.8/site-packages/spacy/__init__.py)
```

**Comment by frascuchon** [comment]
Mmmmm this concrete error is related to spacy version changes. For monitoring all dep modules are optionals (wrapped in a `ModuleNotFoundError` catch) 

This line:
```python
from spacy.language import Language
```

should be compatible for both spacy versions.

We can just change imports `from spacy import Language` to a cross-version compatible import

**Comment by dcfidalgo** [comment]
What I meant is that if we make all imports of these "optional" dependencies compatible with all the versions of these dependencies, then there is no problem. But if this is not the case, then maybe it would be best to move these imports inside the respective classes, so this does not affect the general `import rubrix` statement.
