### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ddy-ddy** [recognai/rubrix#768]
hello authors. I have this error while running the following code. How to solve it?
I ran it using Docker, and then i imported the data using this code in PyCharm, and there was an error.
thank you so much..

**Code:**
```
import rubrix as rb

rb.init("http://localhost:6900/", api_key="<YOUR_API_KEY>")
rb.set_workspace("rubrix")

rb.log(
  rb.TextClassificationRecord(inputs="my first rubrix example"),
  name='example-dataset'
)
```

**Error:**
```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

![截屏2021-12-08 下午3 33 37](https://user-images.githubusercontent.com/58058861/145167248-fca28cb3-8313-4950-8f8a-51c77255ac87.png)

**Comment by dvsrepo** [comment]
Hi @ddy-ddy:

If you are running the default Docker install you can skip the  `rb.init("http://localhost:6900/", api_key="<YOUR_API_KEY>") and rb.set_workspace` statements.

You can do the following:

```python
import rubrix as rb
rb.log(
    rb.TextClassificationRecord(inputs="my first rubrix example"),
    name='example-dataset'
)
```
After that I recommend you to take a look at the cookbook for more examples:

https://rubrix.readthedocs.io/en/stable/guides/cookbook.html

**Comment by ddy-ddy** [comment]
```python
import rubrix as rb
rb.log(
rb.TextClassificationRecord(inputs="my first rubrix example"),
name='example-dataset'
)
```

I did what you said. but it still made the same mistake.
![截屏2021-12-08 下午3 48 33](https://user-images.githubusercontent.com/58058861/145169229-b9b4c458-e408-4550-92fc-dbde37ef516d.png)

**Comment by dvsrepo** [comment]
Thanks, are you installing with `pip install rubrix`?

**Comment by ddy-ddy** [comment]
Yes. My version of Python is 3.6

<img width="992" alt="截屏2021-12-08 下午3 58 15" src="https://user-images.githubusercontent.com/58058861/145170585-12bcb09a-0942-45fc-add3-de407234aeb3.png">

**Comment by dvsrepo** [comment]
Thanks so much @ddy-ddy , we'll look into this

**Comment by ddy-ddy** [comment]
Ok. I look forward to your solving this problem. Have a good day.

**Comment by frascuchon** [comment]
Hi @ddy-ddy , thanks for reporting the issue.

You should use at least Python 3.7. There is a compatibility problem with pydantic and python 3.6 https://github.com/samuelcolvin/pydantic/issues/1513

**Comment by ddy-ddy** [comment]
> Hi @ddy-ddy , thanks for reporting the issue.
> 
> You should use at least Python 3.7. There is a compatibility problem with pydantic and python 3.6 [samuelcolvin/pydantic#1513](https://github.com/samuelcolvin/pydantic/issues/1513)

Thank you so much! I resolve my problem. I saw in your tutorial that Rubrix can used in Python3.6. 

Maybe you should change it or add a comment. 

Finally, I want to say that Rubrix is very useful.o(￣▽￣)ｄ 


<img width="954" alt="截屏2021-12-08 下午7 31 29" src="https://user-images.githubusercontent.com/58058861/145201444-9af579bb-3896-4b0a-add6-409e1228b2eb.png">
