### ISSUE TITLE
Add conda installation option for rubrix

### ISSUE THREAD

**Issue by sugatoray** [recognai/rubrix#781]
Add a `conda` installation option for `rubrix`. I have already stared working on this one. It has passed all the CI's and will soon be merged. Once the :bulb: [**PR**][#pr-conda-forge-rubrix] gets approved/merged, `rubrix` will be available on conda-forge as:

[#pr-conda-forge-rubrix]: https://github.com/conda-forge/staged-recipes/pull/17234

```sh
conda install -c conda-forge rubix
```

:zap: Once `rubrix` is available on `conda-forge`, I will push a PR to update the readme-installation section.

**Comment by sugatoray** [comment]
cc: @dvsrepo @recognai

**Comment by dvsrepo** [comment]
Wow! Thanks so much @sugatoray , this is very appreciated. Looking forward to it. Let us know if you need support

**Comment by sugatoray** [comment]
:rocket: A screenshot says it all!

cc: @dvsrepo

![image](https://user-images.githubusercontent.com/10201242/145589616-b784197f-f00c-4716-b38c-b79256f7a4c9.png)
