### ISSUE TITLE
[Workspaces] Include current workspace as part of url

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#816]
Including workspaces as part of url in UI brings benefits like sharing datasets between workspace members or simplify user workspaces management.

my url proposal:

`/ws/<current-workspace>/` -> will show workspace datasets
`/ws/<current-workspace>/<dataset>` -> will show workspace dataset 

I've included the `ws` namespace in url path to contextualize info and regarding future features in UI (management other than workspaces, or personal settings...)

Accessing to home url `/` will automatically redirect to the main workspace url view.

What do you think @Amelie-V @leiyre @dvsrepo @dcfidalgo ?

 See also #810  and #736

**Comment by dcfidalgo** [comment]
Sounds good to me! :rocket:
