### ISSUE TITLE
[NER] Add switch Prediction/annotation

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#821]
Just like in Text2text show Prediction/annotation in 2 views

-  Prediction by default in explore
-  Annotation by default in annotate

**Comment by frascuchon** [comment]
Maybe in this task should be nice to visualize both predictions and annotations in the same view.

**Comment by dvsrepo** [comment]
> Maybe in this task should be nice to visualize both predictions and annotations in the same view.

Yes!

**Comment by Amelie-V** [comment]
Propuesta 1: la que esta diseñada en 2 declinación (toggle o checkbox)
- Poder libremente activar/desactivar Predicciones y Anotaciones en ambas vistas (Explore y Annotate)

Propuesta 2
- Mostrar un estado por defecto (Predicciones in explore) y solo permitir activar/desactivar el segundo

**Comment by Amelie-V** [comment]
![Captura de pantalla 2021-12-17 a las 12 29 28](https://user-images.githubusercontent.com/84135211/146538919-7f8b22c4-e510-4af8-b654-7c243a88e993.png)

**Comment by frascuchon** [comment]
Nice design! I am a little afraid that the area to change from prediction to annotation at the entity level is too small.

**Comment by Amelie-V** [comment]
Tras feedback de Paco:

- [ ] Discutir el interes de tener esa vista en Annotate, o si es solo para Explore
- [ ] Buscar una forma de indicar los errores de predicción (si Pred. distinto Annot. = error)

**Comment by Amelie-V** [comment]
Here is the QA

- [x] Aumentar font del tool tip (sketch)

- [x] No veo las predictions in annotation mode

- [x] Configurar los colores de los labels para que no estén tanto en tono fluorescentes, tan saturados?

**Comment by frascuchon** [comment]
Could we deactivate selection ("rine navi" in the following example) once label menu is displayed and the whole span is selected? @leiyre @Amelie-V what do you think about that?
 

![Screenshot 2022-01-26 at 18 17 21](https://user-images.githubusercontent.com/2518789/151213269-bfb86fe5-125d-4bf5-a597-63e82b2aa86f.png)

**Comment by frascuchon** [comment]
>  No veo las predictions in annotation mode

Ten en cuenta que las predicciones sólo aparecen para records que no están validados (es decir, que no tienen predicción). En el caso de tener anotación y predicción, el modo anotación sólo mostraría las anotaciones. Sin embargo, si tienes un record sin validar (status = Default), se pueden ver las predicciones antes guardar/validar.

**Comment by Amelie-V** [comment]
Is it correct to automatically turn all predictions to annotations when we annotate part of one record?

**Comment by Amelie-V** [comment]
<img width="1287" alt="Captura de pantalla 2022-01-26 a las 22 26 18" src="https://user-images.githubusercontent.com/84135211/151251616-9640bafc-247a-4fad-a2e9-3cd782c9b6d5.png">
<img width="1298" alt="Captura de pantalla 2022-01-26 a las 22 26 08" src="https://user-images.githubusercontent.com/84135211/151251619-c595642f-eb40-4a7a-9b38-6049e2b902a7.png">

**Comment by Amelie-V** [comment]
### QA 2:

- [x] Annotation mode : align record checkbox with the first record line (margin changed)
- [x] Enlarge a bit the tooltip minimum width : give some space between Annot. and X (view ss)
- [x] Stat in Metrics: To help distinguish Predicted from annotated, I would propose to show label in the same way than in records (Underline/Highlight
- [x] Add Pred.
- [x] Enlarge a bit the tooltip minimum width on Prediction inside annotation mode : give some space between Label and X (view ss)
- [x] Review colors

**Comment by Amelie-V** [comment]
<img width="163" alt="Captura de pantalla 2022-01-27 a las 21 18 08" src="https://user-images.githubusercontent.com/84135211/151438874-75b1a8d9-4ec5-4868-9fdd-b694fa2b1344.png">

**Comment by Amelie-V** [comment]
> Could we deactivate selection ("rine navi" in the following example) once label menu is displayed and the whole span is selected? @leiyre @Amelie-V what do you think about that?
> 
> ![Screenshot 2022-01-26 at 18 17 21](https://user-images.githubusercontent.com/2518789/151213269-bfb86fe5-125d-4bf5-a597-63e82b2aa86f.png)

I agree. In the same mood, could we desactivate label selector when we click inside the record without any selection? (SS)

**Comment by Amelie-V** [comment]
<img width="487" alt="Captura de pantalla 2022-01-27 a las 21 36 55" src="https://user-images.githubusercontent.com/84135211/151439990-5fc12cdc-dbc0-4067-91be-e94325a13788.png">
