### ISSUE TITLE
[Pagination] Issue with pagination and status

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#823]
Running the active learning tutorial, I've realized there's an issue in the Webapp

If I have 10 records with status default, after enabling the filter status=Default, with 1 per page, and I start labeling them one by one, there's point where I don't see more records because the pagination status gets updated with the current number of records satisfying that filter (which are less and less as I continue annotating). I prepared a video showing this:

I guess this is not an easy issue to tackle so let's discuss it for the next dev cycle.

https://user-images.githubusercontent.com/1107111/146407664-e73b82a4-f761-4bdc-b6f1-891a335e2195.mp4

**Comment by frascuchon** [comment]
Every time you validate a record in another status, you must refresh (refresh button) to see the changes. It's the common behaviour. Using the edge case with records per page == 1 and shortcut pagination, this behaviour is a consequence of how you are using filters and pagination. 

This would not happen if you filter by status validated or default

Not sure it's an issue

**Comment by dvsrepo** [comment]
That's the thing, status is filtered with default. Having status default for annotation is what we recommend very often. It happens also with any page size, just it's less noticeable, but let's discuss it.

**Comment by frascuchon** [comment]
Yes, it's why we included the refresh buttom. It's an old discussion this records filter incongruity. The main thing is that we are changing an attribute that matches with configured filter. 

We could have a similar situation with 2 users making annotations in the same dataset. 

I think we can resolve that in a more specific annotation view. Or make more accessible the "refresh" button

**Comment by dvsrepo** [comment]
Yes, let's keep this in mind for the focus mode which should replace the page size 1 and give a proper UX for sequential annotation. Closing this issue for now.
