### ISSUE TITLE
[Sort] List of records not refreshed when removing sort field

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#831]
To reproduce:
1. Sort records by a field in the Sort "filter".
2. Remove the filter by pressing the "x".
3. You have to press the "Sort" button again to remove the sorting and update the view. For the other filters, pressing the "x" automatically refreshes the view.
![bug_remove_sort](https://user-images.githubusercontent.com/15979778/146758502-03f14921-87c1-4a7a-93dd-319e788668ca.png)
)

**Comment by leiyre** [comment]
At the moment this filter is different from the rest, having to click "sort" to confirm the action. @Amelie-V, do you think we can remove the filter directly and maybe add a "remove all" like in the rest?

**Comment by Amelie-V** [comment]
El cambio mayor deseable es que no haya que clicar un button de validación (Sort) y que el reorden se haga en tiempo real.
Si se quiere esperar la revision global de los filtros que esta pendiente, de momento podemos efectivamente permitir cerrar el modal cuando se da a la cruz

**Comment by frascuchon** [comment]
The `Sort` filter has a different behaviour with `X` button. For filters, the `X` button clears **all** selected fields for that filter.  In sort component, the `X` button drops the sort field configuration, and it used for changing sort configuration before apply it (Like changing selected fields for a filter).

To apply change proposed by @Amelie-V I would like to use the X button in a same way like filters do: clear totally the sort configuration and then close modal. If we decide to close the modal every time we click the `X` button, changing configuration in a sort with multiple fields could be a bit annoying

<img width="1373" alt="Screenshot 2021-12-22 at 12 45 18" src="https://user-images.githubusercontent.com/2518789/147088042-2300e029-0db2-4c57-8dab-5fc0a8277165.png">

**Comment by Amelie-V** [comment]
Would it be possible/relevant to add this logic? @frascuchon @dcfidalgo @dvsrepo @leiyre 

-  Add a  "remove all sort" when 2 or more sort actived . On click on it, close the modal directly.
- When there is only one sort actived, click on the X button close the modal too.

**Comment by frascuchon** [comment]
> Would it be possible/relevant to add this logic? @frascuchon @dcfidalgo @dvsrepo @leiyre
> 
> * Add a  "remove all sort" when 2 or more sort actived . On click on it, close the modal directly.
> * When there is only one sort actived, click on the X button close the modal too.

I think the same button should resolve the same action for all cases (clear the Sort configuration) like filter component does. Could you provide a sketch design proposal @Amelie-V ?

Anyway, i think It should be better invest the effort to normalize the filter section
