### ISSUE TITLE
[rules] Expose load_rules at the parent module

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#854]
I'd like the import to look like this:

`from rubrix.labeling.text_classification import load_rules`

Currently is: `from rubrix.labeling.text_classification.rule import load_rules`

**Comment by frascuchon** [comment]
Now this is fixed, should we update the weak supervision guide https://rubrix.readthedocs.io/en/releases-0.x/guides/weak-supervision.html#3.-Building-and-analizing-weak-labels @dvsrepo ??

**Comment by dvsrepo** [comment]
Yes , @dcfidalgo can you update the guide and the tutorial please?
