### ISSUE TITLE
[Define Rules] Better workflow with other modes

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#868]
The new  mode "Define Rules" should be better integrate with the rest of the page/modes. Things to tackle could be:

- Does make sense the `Refresh` action in side bar for this mode?  In that case, what should be done? Does it make sense with rule management view? 
- What kind of metrics must to be accesible from rules management view? 
- Switching to another mode should keep the mode status when come back ? For example, if we are in rule management view and we move to explore mode, then come back to define rules mode, the rules management view is not shown anymore
- Does make sense to use sidebar from rules management view?

**Comment by dvsrepo** [comment]
Some comments:

* Refresh for the rule definition view: should have a similar behaviour as the explore or annotate mode, running the query again if any, updating the metrics accordingly. To be honest I don't use Refresh much, but I expect this to work as the other modes, especially the explore mode when you are logging data and want to see the results with new records. Other option is to disable it (not show it).
* Refresh for rules management view: good question. If we keep it, it should recompute the overall metrics and the summary table, but again we might decide to disable that option from the sidebar. 
* changing to another mode and coming back, should keep the Rule management mode open? If not too much work yes, and also when refreshing the page (via a query URL param)
* sidebar in the rule management view: it's true that not all options are useful. In any case Amélie had been designing improvements on the sidebar (separating metrics, etc.) which I think can tackle this standardization (enabling, disabling, etc.) in a separate task.
