### ISSUE TITLE
[Define rules] Metrics highlighting

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#873]
It could be nice to include some color schema to highlight the best rule metrics. The greater value for precision, the better, or the lower value for incorrect records, the better too. This could help to users to analyse rule

**Comment by dcfidalgo** [comment]
Just to keep in mind, that a rule with high coverage, but low precision can be more useful than a rule with high precision, but low coverage.

**Comment by dvsrepo** [comment]
This is something we have analyzed already and as David mentioned is not so straightforward to define what's a good value. I would not recommend tackling this for 0.8.0
