### ISSUE TITLE
[Rule metrics] Table summary and rule metrics formats

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#879]
Just a suggestion that can be discussed.

The precision, coverage and annotated coverage for table summary could be formatted in same way that rule metrics does:

<img width="1751" alt="Screenshot 2022-01-06 at 12 09 00" src="https://user-images.githubusercontent.com/2518789/148374016-afaafd48-704b-4887-983c-c0c21ddb5b3e.png">

<img width="1783" alt="Screenshot 2022-01-06 at 12 09 08" src="https://user-images.githubusercontent.com/2518789/148374051-c3bab70d-1450-4335-b844-4d7877de1462.png">

**Comment by dvsrepo** [comment]
Yes, they should have the same format

**Comment by Amelie-V** [comment]
Yes, formats should be the same in both views.

**Comment by dvsrepo** [comment]
This should be tackled for 0.8.0
