### ISSUE TITLE
[Rules summary] Include covered labels by rules in overall metrics

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#880]
Suggestion open to discussion.

Maybe it could be nice to include what labels are already covered by defined rules as an overall metric.

**Comment by dvsrepo** [comment]
Absolutely agree with this. I've been testing this morning and I missed this info to know if my rules where more or less balanced

**Comment by dvsrepo** [comment]
@Amelie-V will provide the visual design on Monday, then we can estimate how much implementation work it means, to decide whether to include it on 0.8
