### ISSUE TITLE
[Datasets page] Improve code snippet for empty worskpace

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#881]
The current code snippet has caused several confusions for first-time users. The main issue is that is focused on more complex installations (several workspaces, custom API keys) and that is misaligned with our docs (where we don't use the `rb.init()` method). When we start having more complex installations the docs will recommend to set ENVs for the api key and url anyway.

I'd recommend to have this code snippet instead:

```python
import rubrix as rb

# If you are using the default installation you can skip this line
rb.set_workspace("${ws}")

rb.log(
  rb.TextClassificationRecord(inputs="my first rubrix example"), 
  name='example-dataset'
)
```

Another option is to keep the rb.init but commented out with a message like this:

`# If you have configured your own API url and key, run this line`

**Comment by dcfidalgo** [comment]
I would tackle the workspace together with the init, something like this:
```python
import rubrix as rb

# If you have configured your own API url, API key or workspace, run this line
#rb.init(api_url="my_api_url", api_key="my_api_key", workspace="my_workspace")

rb.log(
  rb.TextClassificationRecord(inputs="my first rubrix example"), 
  name='example-dataset'
)
```

**Comment by dvsrepo** [comment]
The thing is that this message is contextualized for each workspace (`"${ws}"`), so if you have several workspaces and one is empty it will show `rb.set_workspace("the_workspace_where_you_are")`, which might be useful to make sure you set the workspace before sending data (without needing to do an init which you might already have setted in ENV vars).

**Comment by dcfidalgo** [comment]
ah sorry, forgot about the context. ok, never mind, the message is perfect, dropping the `rb.init` call makes totally sense.
