### ISSUE TITLE
[Rule Management] update summary action

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#891]
Does it make sense to include the `Update Summary` as rules table summary since refresh not only rules metrics, but ALL metrics (rules and overall)? 

The first versions of this page included overall metrics as a Total row, so I think is a bit outdated after revisions.

**Comment by dvsrepo** [comment]
Fully agree, I don't think it makes sense anymore

**Comment by frascuchon** [comment]
The button will be removed
