### ISSUE TITLE
[Rule Management] Rules summary should show query when description wasprovided??

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#893]

**Comment by dvsrepo** [comment]
I found this a bit confusing too when we change substantially the description with respect to the query. 

It will be a bit repetitive for those queries with no changed description but I'd suggest adding a column with the query in the summary table to solve this issue

**Comment by dcfidalgo** [comment]
Personally, I would show the name/description on the "manage rules" page, otherwise, I am not sure when to use this feature (being able to change the name). One can always check the query by clicking on the rule name. I would even go as far as not allowing rules to share the same name.

**Comment by dcfidalgo** [comment]
One more thing I just noticed, when providing two rules with the same name to the `WeakLabels` class, it will throw a `DuplicatedRuleNameError`, we should align this!

**Comment by frascuchon** [comment]
Another thing about rules and descriptions is that several rules could have the same descriptions since the rule id is the configured query. This can be even more confusing for table summary.

Maybe we can just use the rule query and introduce description later in another release?

**Comment by dvsrepo** [comment]
Yes, let's do that and take the time to define how to introduce the descriptions

**Comment by frascuchon** [comment]
Resolved in #903
