### ISSUE TITLE
[Dataset Copy] rb.copy does not work explicitly specifying my workspace 

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#906]
Cannot create a copy when specifying my workspace. 
This works:
```python
rb.copy("ds", "ds2")
```
this does not, no error is thrown, no copy is created:
```python
rb.copy("ds", "ds2", workspace="david")
# or
rb.set_workspace("recognai")
rb.copy("ds", "ds2", workspace="david")
```

**Comment by dcfidalgo** [comment]
@frascuchon any suspicions?

**Comment by frascuchon** [comment]
It's working the opposite (from `david` to `recognai`) ?

**Comment by dcfidalgo** [comment]
Yes, the other way around works fine
