### ISSUE TITLE
Web App docu Review

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#912]
- [x] Error "dataset"/dataset
* Created at: When was the *dateset* first logged by the client.  https://rubrix.readthedocs.io/en/fix-updating-reference-docs/reference/webapp/workspace.html
- [ ] Create style for Notes https://rubrix.readthedocs.io/en/fix-updating-reference-docs/reference/webapp/dataset.html
- [x] Capture error : Annotation filters is showing Prediction filters.  https://rubrix.readthedocs.io/en/fix-updating-reference-docs/reference/webapp/dataset.html
- [x] Change "Sort by" capture (see attachment) https://rubrix.readthedocs.io/en/fix-updating-reference-docs/reference/webapp/dataset.html 

- [x] / Sidebar: Show the 3 modes in screenshot (+ show tootip "Annotate") https://rubrix.readthedocs.io/en/fix-updating-reference-docs/reference/webapp/dataset.html

- [x] / Sidebar and metrics: (change first SS and show metrics expanded) https://rubrix.readthedocs.io/en/fix-updating-reference-docs/reference/webapp/annotate_records.html

- [x] / Search records: delete last ss

- [x] / Switch workspaces: Add SS https://rubrix.readthedocs.io/en/fix-updating-reference-docs/reference/webapp/switch_workspaces.html

**Comment by Amelie-V** [comment]
<img width="1192" alt="Captura de pantalla 2022-01-10 a las 15 54 18" src="https://user-images.githubusercontent.com/84135211/148786456-da659081-4316-4658-8e42-2b76b3585ef9.png">
<img width="330" alt="Captura de pantalla 2022-01-11 a las 12 25 39" src="https://user-images.githubusercontent.com/84135211/148936029-05f5e15e-cf74-4424-ad8e-8a7fd785b265.png">

**Comment by dcfidalgo** [comment]
@Amelie-V can we close this?

**Comment by dvsrepo** [comment]
yes!
