### ISSUE TITLE
[Weak supervision] Update Weasel example with new merged support for HF

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#935]
I would even recommend moving this to its own tutorial (a short one) or to the AG News tutorial (less preferred).

What do you think @dcfidalgo ?

**Comment by dcfidalgo** [comment]
Yes, the update of the guide is on my to-do list. Yes, I think turning this part of the guide into a small tutorial would be a nice addition to the docs.

**Comment by dvsrepo** [comment]
Actually, if possible I'd like to have a code snippet (or the guide updated) with the new usage to share this before the tutorial @dcfidalgo
