### ISSUE TITLE
[Search] Improve and normalizes the search data model

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#945]
Things to keep in mind:

- Normalize text inputs fields: `text`, `inputs`, `words` must be normalized and use a common pattern for all tasks
- Several es analyzers for text fields: `standard` and `whitespace`(?) for fine tuning searches. Default as `standard`
- What about text fields in metadata ? For now, only terms queries are supported. It's mean that metadata fields with large content are not enabled to be queries as full text search.
- Created indices should contain mapping info only for its fields. A text classification index should not include mapping info for tokens or text predicted (text2text).
- Review filter fields and align with UI names (if any)
- What about nested fields? like token or metrics info for token classification, or label and its score for text classification. As default, query string dsl does not support nested queries, but it could be nice include some minimal support for that kind of queries.

@dvsrepo @dcfidalgo Anything to include here?

## Tasks

To achieve to do the work, we need tackle following tasks (that will be created as separated issues and linked here)

1. [Datasets] Avoid using global template for all indices
2. [Datasets] Dataset migration mechanisms for each release
3. [Datasets] New es document model per task with backward compatibility fields
4. [Datasets] Apply migration to new es doc model 
5. [Datasets] Build searches and aggregations using new doc model

**Comment by dcfidalgo** [comment]
Looks complete to me, just to elaborate on a few things:

>     * Normalize text inputs fields: `text`, `inputs`, `words` must be normalized and use a common pattern for all tasks

The idea here is, that `TextClassification` changes from `inputs` to `text`, right? In the end, did you find a solution for having `text.context` and `text.exact`, for example, the latter being the field analyzed with the whitespace analyzer?
And `words` includes stopwords and is for the keyword list, right?

>     * Several es analyzers for text fields: `standard` and `whitespace`(?) for fine tuning searches. Default as `standard`
 
Yes, I think whitespace is good for now.

>     * What about text fields in metadata ? For now, only terms queries are supported. It's mean that metadata fields with large content are not enabled to be queries as full text search.

For me it sounds reasonable not to support full text search in metadata for now

>     * Created indices should contain mapping info only for its fields. A text classification index should not include mapping info for tokens or text predicted (text2text).
> 
>     * Review filter fields and align with UI names (if any)
> 
>     * What about nested fields? like token or metrics info for token classification, or label and its score for text classification. As default, query string dsl does not support nested queries, but it could be nice include some minimal support for that kind of queries.

For the last point, definitely agree, would be nice to have, but I would put it further down in the priority list.

**Comment by frascuchon** [comment]
> The idea here is, that TextClassification changes from inputs to text, right? In the end, did you find a solution for having text.context and text.exact, for example, the latter being the field analyzed with the whitespace analyzer?

Not clear enough. During implementation we will find a way to normalize regarding the `text` multiple nature for text classification.

> And words includes stopwords and is for the keyword list, right?

Yes. Normally we will include the `wordcloud` property to all text fields, but we will see during implementation

**Comment by frascuchon** [comment]
See also recognai/roadmap#55

**Comment by frascuchon** [comment]
We definitely can't combine the `text` field with the inputs for text classification.

What we can do is to normalize as the default search field to `text: busy` or `text.exact: busy`, for all tasks.

For text classification, use the input fields when you want to search for a specific field: `inputs.text: busy` or `inputs.text.exact: busy`

**Comment by dcfidalgo** [comment]
And could we have something like `text_context: busy` or `text_text: busy`? just to have this consistency of specifying a `rb.TextClassificationRecord(text={"context": "blablabla", "text": "blublublub})` in the client and than be able to search for `text_context: busy` or `text_text: busy` in the web app.

**Comment by frascuchon** [comment]
Mmmm I don't really agree with this solution. Regarding the search data model, it a bit weird use the `_`  nomenclature for dictionaries, that normally are accessed by `.`. Using this nomeclature for inputs, we should, for consistency, for other data dictionary, like `metadata` or metrics, what introduces a hard naming processing (`metadata_field_subfiel` or `metadata_field.subfield` ???)

Regarding the  text classification record model proposal, it not very natural use a `text` field where can include a data dictionary. I would feel more comfortable if we have a separate `text` field for when we record a single string leaving the inputs as is:

```
rb.TextClassificationRecord(text="the text")
rb.TextClassificationRecord(inputs={"context": "blablabl", "text":"blublublu"})
```
Also, this change will not break client compatibility

**Comment by dcfidalgo** [comment]
> Regarding the text classification record model proposal, it not very natural use a text field where can include a data dictionary.

I guess a similar argument could be made for an `inputs` field that can include a string, but I get your point.
I like a lot your suggestion of including a `text` field in the client model that accepts a string, I think it's a nice compromise between consistency and not breaking stuff. 

So as a summary for the text classification records, search queries would look like this:
- search for all all `inputs` or `text`: `text:blablabla`
- search only for certain `inputs`: `inputs.subject:blablabla`

**Comment by frascuchon** [comment]
For `Text2Text` task my proposal is that `annotated_as` and `predicted_as` becomes full text search fields. So you can build queries like `annotated_as: Madrid solicita` or `predicted_as.exact: serrano!`


any suggestion @dcfidalgo @dvsrepo ?

**Comment by dcfidalgo** [comment]
:+1: sounds good!! I think `predicted_as` can be a list of texts for the Text2Text task, not sure if this is an obstacle.

**Comment by frascuchon** [comment]
Not, really. The only "problem" is that you cannot select with predicted sentence you use. It will search in all of them. But i think we can assume that

**Comment by frascuchon** [comment]
Note: PR recognai/rubrix#1018 introduces breaking changes to version <0.9.0. So we cannot include those changes until v0.11.0 in order to keep compatibility at lease 2 version prior to release
