### ISSUE TITLE
[snorkel] Remove warning (or change to info)

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#949]
Having always this red message when scoring the model is not desirable:

WARNING:rubrix.labeling.text_classification.label_models:Metrics are only calculated over non-abstained predictions!
{'accuracy': 0.5953488372093023}

I'd either remove it or change to info level.

Also is it not possible to provide more detailed metrics (precision, recall, fscore)?

**Comment by dcfidalgo** [comment]
I will remove it, it's an artifact of how snorkel does it. I will move it to the docstring, should be enough.

Regarding the more detailed metrics, definitely possible, I will open a separate issue for that. It

**Comment by dvsrepo** [comment]
💯

**Comment by frascuchon** [comment]
Documentation does not show the include NOTE reference in docstring 

https://rubrix.readthedocs.io/en/master/reference/python/python_labeling.html#rubrix.labeling.text_classification.label_models.Snorkel.score

![Screenshot 2022-02-01 at 11 05 30](https://user-images.githubusercontent.com/2518789/151949105-a7bcc37b-b42b-40ce-81c5-cd2f377e0892.png)
