### ISSUE TITLE
[Labeling Rules] Filter uncovered records

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#951]
It could be nice to explore/annotate records that are not covered by any defined rule. Some kind of filter that we can leave activated while navigating between modes

**Comment by Amelie-V** [comment]
#991

**Comment by Amelie-V** [comment]
- [x] add checkbox into annotation Filter

**Comment by frascuchon** [comment]
More specific copy text for checkbox: "Show only not covered records by rules"

@dcfidalgo @dvsrepo @Amelie-V @leiyre ? Wha do you think?
