### ISSUE TITLE
[LabelModel] Add metrics to LabelModel.score methods

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#953]
Add additional metrics (recall, precision, f1) to the output of the `Snorkel.score()` and `FlyingSquid.score()` methods. Also see #949

**Comment by dvsrepo** [comment]
Hi, @dcfidalgo could you please add an issue to update the guide and the tutorial to show this feature? As a general workflow I'd recommend to update related docs when adding a new feature or improvement, otherwise we add feature that go unnoticed.

**Comment by dcfidalgo** [comment]
See #995
