### ISSUE TITLE
[SideBar] Review sidebar

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#957]
The idea should be 

- Contextualize sidebar with active view (annotation, define rule or datasets)
- Review how to present the metrics
- Contextualize actions: is not the same refresh from explore and refresh from define rules or rules management.
- Expand sidebar on a column

@Amelie-V you can include whatever you consider is missing in checklist

Related issue: #868

**Comment by Amelie-V** [comment]
- [ ] Dress a list of metrics desired by tasks and mode
- [ ] Create navigation flow
- [ ] Review UI sidebar structure
- [ ] Create metrics naming and icons
