### ISSUE TITLE
[Weak supervision] Rules numbers by label

### ISSUE THREAD

**Issue by Amelie-V** [recognai/rubrix#961]
For instance:

Sci/tech 2
Sports 1
Business 4
Politics 0
World 0

his feature could be used for two things:
- Help to know how is going the rule definition 
- See the full label list (in "define rules" we dont have this list by default)

**Comment by frascuchon** [comment]
@Amelie-V Is this issue the same that #880 ? Can we close one of them?

**Comment by Amelie-V** [comment]
Right panel

- [x] Disabel tooltip on icon after click 
- [x] Add Grey BG on hover/active states Icon mode (Explore, Annotate,Rules)
- [x] Review color progress bar (tooltip color = progress color, BG bar is a % of progress color)
- [x] Review spaces between Title and progress bar (check UI)
- [x] Add animation to labels counter to allow user see live the impact on creating rules on rule counter
- [x] Animation enhancement (WIP)
- [x] UI navigation component enhancement (open/close) (WIP)

**Comment by Amelie-V** [comment]
![Captura de pantalla 2022-04-05 a las 15 52 34](https://user-images.githubusercontent.com/84135211/161769493-bcede0b1-ba6e-40b5-ad9d-b8b5c39ea13e.png)

**Comment by Amelie-V** [comment]
### QA
- [x] user icon should be aligned with other panel icons (If necessary increase a bit the width sidebar, to avoid problem with user modal)
- [x] Move the panel 1px down (it's not aligned with blue header)
- [x] Panel sidebar should open over pagination.
- [x] Could you pliz reduce the shadow effect on the right-side panel?

### Next iteration

- [x] Add expand effect animation on panel
- [x] Add animation on "chevron" (panel closing)

**Comment by Amelie-V** [comment]
<img width="297" alt="Captura de pantalla 2022-04-06 a las 15 21 04" src="https://user-images.githubusercontent.com/84135211/161985788-b01507fd-2b55-4078-a49f-42ba192a186e.png">
<img width="62" alt="Captura de pantalla 2022-04-06 a las 15 20 31" src="https://user-images.githubusercontent.com/84135211/161985795-e2b3a249-69df-4a5a-ab14-e7596e920141.png">

**Comment by Amelie-V** [comment]
- [x] It misses the Grey BG on ***hover*** states on all sidebar icons 
- [x] Record/page selector had lost it's correct position

**Comment by Amelie-V** [comment]
<img width="299" alt="Captura de pantalla 2022-04-08 a las 11 54 01" src="https://user-images.githubusercontent.com/84135211/162412898-8968949a-94a7-4508-97bf-62cb98d859ed.png">

**Comment by Amelie-V** [comment]
(Animation review : pending)


- [x] Bring to front the right panel (view screenshot 1024) UPDATE: see #1407
- [x]  Move the panel 1px down (it's not aligned with blue header): it's better, but the panel should not have border frame, this very light but we can distinguish it on the SS. @leiyre maybe you will fix it with the animation panel enhancement

**Comment by Amelie-V** [comment]
<img width="405" alt="Captura de pantalla 2022-04-13 a las 10 16 05" src="https://user-images.githubusercontent.com/84135211/163134114-133fa925-a9d4-47ae-82d6-54eb55d148fe.png">
