### ISSUE TITLE
[Workspace] Show all available workspaces for super users

### ISSUE THREAD

**Issue by frascuchon** [recognai/rubrix#984]
![Screenshot 2022-01-17 at 12 52 10](https://user-images.githubusercontent.com/2518789/149764985-baac100e-3135-48de-b9c5-484066d4c7f4.png)

Super users have access to all workspaces datasets, but no workspaces information is stored with this kind of users.

It would be nice include accessible workspaces from User menu in UI

**Comment by Amelie-V** [comment]
![DSlist2](https://user-images.githubusercontent.com/84135211/154476007-21e9d751-e49d-4eeb-ab8b-fc08b0d9ab06.png)
![DSlist1](https://user-images.githubusercontent.com/84135211/154476021-6f512733-624b-438a-8692-6695467f7252.png)

**Comment by Amelie-V** [comment]
Specifications related to the proposal (WIP)

- If NO dataset in any workspace : show piece of code
- Workspace is filtrable 
- A workspace belongs to a User or a Group and it's attached to an email. example : Alice workspace, IBM workspace, Linguists team workspace
- A user/group can be invited to other workspaces basing threw the email adress

Doubt:
- In that version we see the workspace name only on the dataset list
