### ISSUE TITLE
[Documentation] New admonition style affects reference docs

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#988]
@Amelie-V @leiyre The new admonition styles seem very different from each other, take a look at the `Hint` and `Note` admonition [here](https://rubrix.readthedocs.io/en/master/reference/webapp/dataset.html). Also, the `Note` admonition seems a bit too subtle to me, easy to overlook when you scroll through a page.

Also, the new styles affect the reference docs of the client, you can compare [here](https://rubrix.readthedocs.io/en/stable/reference/python/python_client.html) and [here](https://rubrix.readthedocs.io/en/master/reference/python/python_client.html). Now the method/class names are hardly visible and it's difficult to see where a new method/class begins.

**Comment by Amelie-V** [comment]
Correctly: there is a real lack of contrast... @leiyre Can we change the light grey BG to a light tone of the violet? 
The idea is to apply same color for Hint and Note

**Comment by dcfidalgo** [comment]
In #1109 I increased the contrast of the background a little bit using a light tone of the violet of the header. The references were really hard to read. I **did not** touch the unification of styles for all types of admonition!

**Comment by Amelie-V** [comment]
- [x] Note header: 4C4EA3 / Light: 4C4EA31C
- [x] Hint header: 67c795 / Light: 67c7951C
- [x] Warning header:  ffba28 / Light: ffba281C
