### ISSUE TITLE
[Stats] The pie chart in the error distribution gives a wrong impression

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#989]
The pie chart of the _Error distribution_ in the _Stats_ metrics, gives a wrong impression because the records with no annotations are represented in green. 
![Screenshot from 2022-01-17 17-32-11](https://user-images.githubusercontent.com/15979778/149807934-9662ee65-2b04-4d24-ac78-318cc61a3649.png)
Looking at the pie chart in the screenshot, it looks like much more records are predicted ok than ko, which is not the case looking at the numbers.
Either we paint the percentage of not annotated/predicted records in grey, or the pie chart has a total of `predicted ok + predicted ko` (I prefer the latter).

**Comment by dcfidalgo** [comment]
@dvsrepo @frascuchon @Amelie-V

**Comment by dvsrepo** [comment]
Yes, I prefer the later too
