### ISSUE TITLE
[Install] update the installation docs recomending the python -m rubrix.server way   

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#994]
The idea is following default installation:
```bash
# install server dependencies
pip install rubrix[server]

# if no ES running
docker run ...

# run web app
python -m rubrix.server
```

advantage: 
- without docker-compose: easier to update the rubrix version
- with ES container running in the background, easier to avoid data loss
- we advocate only one way to start the web app, docker-compose is an extra that can still be used by "experts"

disadvantage:
- we include the server dependencies in the default installation, installation is not as lightweight as before

note:
- in the conda package we need to update the dependencies

**Comment by dcfidalgo** [comment]
@frascuchon @dvsrepo

**Comment by dvsrepo** [comment]
I like it a lot this way. Also, it's a good opportunity to have a very clear documentation for installation section

**Comment by frascuchon** [comment]
We can include also the basics of howto launch with [`uvicorn` directly](https://fastapi.tiangolo.com/deployment/manually/#run-the-server-program)
