### ISSUE TITLE
[LabelModel] Use classification_report for the LabelModel.score method

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/rubrix#995]
Return the str of the `sklearn.metrics.classification_report` by default, add an `output_dict` parameter to be able to output a dict instead.
Show this feature in our wl guide/tutorial.

**Comment by frascuchon** [comment]
Can we close this PR ?????

**Comment by dcfidalgo** [comment]
Naa, still pending, it's on my todo, I'll try to open a PR this week.
